In [1]:
from fastapi import APIRouter, Query, HTTPException
from typing import Optional, List, Dict, Any, Literal
from datetime import datetime, timedelta
from collections import defaultdict
import pandas as pd
import json
import re
import sys
import os
sys.path.insert(0, r"D:/A0_Project")  # 讓它優先被找到
from PI_SYSTEM.models.sql_db_connect import MySQLConnet

db = MySQLConnet('piaoi_ol_defect_map')
cim_db = MySQLConnet('cim_piaoi')
old_db = MySQLConnet('l6a01_project')

#db = MySQLConnet('piaoi_inspection_density')
#from PI_SYSTEM.models.density.cim_density_job import Config as DensityJobConfig
#from PI_SYSTEM.models.density.API_Config import API_Config

In [20]:
na_tools = []
for file in os.listdir('PI_SYSTEM\models\inspection_density\output_csv'):
    df = pd.read_csv('D:\A0_Project\PI_SYSTEM\models\inspection_density\output_csv//' + file)
    na_tools = [v for v in set(na_tools + df['TOOL_ID'].unique().tolist())]
na_tools

['CAPIC607', 'CAPIC107', 'CAPIC507', 'CAPIC407', 'CAPIC207']

In [2]:
bpi_same_db = MySQLConnet('piaoi_bpi_same_point')
inspec_db = MySQLConnet('piaoi_inspection_density')
bpi_same_tbn = 'bpi_same_point_202606'
cim_tbn = 'cim_pi_glass_202606'

inspec_df = inspec_db.get_table('inspection_api_summary_202606')
print(inspec_df.iloc[0,:].to_dict())
bpi_same_df = bpi_same_db.get_table(bpi_same_tbn)
bpi_same_df.head()

{'pi_hour': Timestamp('2026-06-01 07:00:00'), 'shift_day': Timestamp('2026-06-01 00:00:00'), 'shift_week': '2026W23', 'shift_month': '202606', 'shift_start': Timestamp('2026-06-01 07:30:00'), 'shift_end': Timestamp('2026-06-01 08:30:00'), 'line_id': 'CAPIC207', 'model': 'G215HVN01', 'glass_type': 'CF', 'maingroup_glass_count': 44, 'maingroup_defect_count': 314, 'maingroup_density': 7.136363636363637, 'defect_code_glass_count': 44, 'small_defect_count': 212, 'middle_defect_count': 71, 'large_defect_count': 24, 'over_defect_count': 7, 'glass': 'AL5H151YSP,AL5H151YSQ,AL5H151YSJ,AL5H151YY5,AL5H151YXY,AL5H151Z1R,AL5H151Z1P,AL5H151Z1N,AL5H151Z37,AL5H151Z1M,AL5H151YTN,AL5H151YVD,AL5H151YV6,AL5H151YV5,AL5H151YVB,AL5H151YZJ,AL5H151YXT,AL5H151YZH,AL5H151YY1,AL5H151YTA,AL5H151YZC,AL5H151YZK,AL5H151YZN,AL5H151YZM,AL5H151YRK,AL5H151YQW,AL5H151YQ2,AL5H151YW4,AL5H151YZP,AL5H151YT9,AL5H151YZD,AL5H151YWL,AL5H151YPA,AL5H151Z07,AL5H151YWK,AL5H151Z0G,AL5H151Z09,AL5H151Z0J,AL5H151YNK,AL5H151Z1J,AL5H151YYU,AL5H151YRE,AL5H151YXL,AL5H151YPJ', 'glass_size_detail': '[{"glass_id": "AL5H151YSP", "S": 7, "M": 1, "L": 1, "O": 0, "def_count": 9}, {"glass_id": "AL5H151YSQ", "S": 10, "M": 1, "L": 1, "O": 0, "def_count": 12}, {"glass_id": "AL5H151YSJ", "S": 3, "M": 1, "L": 0, "O": 0, "def_count": 4}, {"glass_id": "AL5H151YY5", "S": 10, "M": 2, "L": 0, "O": 0, "def_count": 12}, {"glass_id": "AL5H151YXY", "S": 7, "M": 1, "L": 4, "O": 0, "def_count": 12}, {"glass_id": "AL5H151Z1R", "S": 6, "M": 1, "L": 0, "O": 0, "def_count": 7}, {"glass_id": "AL5H151Z1P", "S": 3, "M": 0, "L": 1, "O": 1, "def_count": 5}, {"glass_id": "AL5H151Z1N", "S": 6, "M": 2, "L": 1, "O": 0, "def_count": 9}, {"glass_id": "AL5H151Z37", "S": 6, "M": 1, "L": 0, "O": 0, "def_count": 7}, {"glass_id": "AL5H151Z1M", "S": 3, "M": 5, "L": 1, "O": 2, "def_count": 11}, {"glass_id": "AL5H151YTN", "S": 5, "M": 3, "L": 0, "O": 0, "def_count": 8}, {"glass_id": "AL5H151YVD", "S": 3, "M": 1, "L": 0, "O": 0, "def_count": 4}, {"glass_id": "AL5H151YV6", "S": 8, "M": 1, "L": 0, "O": 1, "def_count": 10}, {"glass_id": "AL5H151YV5", "S": 10, "M": 2, "L": 0, "O": 0, "def_count": 12}, {"glass_id": "AL5H151YVB", "S": 6, "M": 3, "L": 0, "O": 0, "def_count": 9}, {"glass_id": "AL5H151YZJ", "S": 6, "M": 3, "L": 0, "O": 1, "def_count": 10}, {"glass_id": "AL5H151YXT", "S": 8, "M": 1, "L": 0, "O": 0, "def_count": 9}, {"glass_id": "AL5H151YZH", "S": 7, "M": 2, "L": 2, "O": 0, "def_count": 11}, {"glass_id": "AL5H151YY1", "S": 2, "M": 0, "L": 0, "O": 0, "def_count": 2}, {"glass_id": "AL5H151YTA", "S": 3, "M": 2, "L": 3, "O": 0, "def_count": 8}, {"glass_id": "AL5H151YZC", "S": 2, "M": 1, "L": 0, "O": 1, "def_count": 4}, {"glass_id": "AL5H151YZK", "S": 3, "M": 0, "L": 1, "O": 1, "def_count": 5}, {"glass_id": "AL5H151YZN", "S": 2, "M": 2, "L": 0, "O": 0, "def_count": 4}, {"glass_id": "AL5H151YZM", "S": 3, "M": 1, "L": 0, "O": 0, "def_count": 4}, {"glass_id": "AL5H151YRK", "S": 1, "M": 2, "L": 0, "O": 0, "def_count": 3}, {"glass_id": "AL5H151YQW", "S": 5, "M": 0, "L": 0, "O": 0, "def_count": 5}, {"glass_id": "AL5H151YQ2", "S": 8, "M": 1, "L": 0, "O": 0, "def_count": 9}, {"glass_id": "AL5H151YW4", "S": 3, "M": 1, "L": 0, "O": 0, "def_count": 4}, {"glass_id": "AL5H151YZP", "S": 2, "M": 1, "L": 1, "O": 0, "def_count": 4}, {"glass_id": "AL5H151YT9", "S": 5, "M": 2, "L": 1, "O": 0, "def_count": 8}, {"glass_id": "AL5H151YZD", "S": 3, "M": 2, "L": 0, "O": 0, "def_count": 5}, {"glass_id": "AL5H151YWL", "S": 1, "M": 3, "L": 0, "O": 0, "def_count": 4}, {"glass_id": "AL5H151YPA", "S": 1, "M": 0, "L": 1, "O": 0, "def_count": 2}, {"glass_id": "AL5H151Z07", "S": 7, "M": 4, "L": 0, "O": 0, "def_count": 11}, {"glass_id": "AL5H151YWK", "S": 5, "M": 2, "L": 0, "O": 0, "def_count": 7}, {"glass_id": "AL5H151Z0G", "S": 2, "M": 1, "L": 2, "O": 0, "def_count": 5}, {"glass_id": "AL5H151Z09", "S": 7, "M": 0, "L": 1, "O": 0, "def_count": 8}, {"glass_id": "AL5H151Z0J", "S": 6, "M": 4, "L": 0, "O": 0, "def_count": 10}, {"glass_id": "AL5H151YNK", "S": 5, "M": 2, "L": 0, "O": 0, "def_count": 7}, {"glass_id": "AL5H151Z1J", "S": 6, "M": 2, "L": 0, "O": 0, "def_count": 8}, {"glass_id": "AL5H151YYU", "S": 1, "M": 1, "L": 1, "O": 0, "def_count": 3}, {"glass_id": "AL5H151YRE", "S": 6, "M": 5, "L": 1, "O": 0, "def_count": 12}, {"glass_id": "AL5H151YXL", "S": 4, "M": 0, "L": 1, "O": 0, "def_count": 5}, {"glass_id": "AL5H151YPJ", "S": 5, "M": 1, "L": 0, "O": 0, "def_count": 6}]', 'comment': '', 'action': '', 'Editor': '', 'modify_time': Timestamp('2026-06-04 13:46:26')}

,id,model,glass_side,glass_id,scan_hour,run_day,tab,bpi_aoi,bpi_line_id,bpi_recipe_id,...,api_over_defect_count,pair_status,pair_message,default_offset_um,matched_points_json,comment,action,editor,modify_time,gen_time
0,123,M315TAN01,TFT,3N6A5JE4B,2026-06-03 11:00:00,2026-06-03,PISpot,aoi200,CAPIC200,4363,...,0,OK,,20,"[{""offset_um"": 20, ""distance"": 17.691806012954...",,,,NaT,2026-06-23 10:07:40
1,124,M315TAN01,TFT,3N6A5JE4B,2026-06-03 10:00:00,2026-06-03,UPI,aoi200,CAPIC200,4363,...,6,OK,,20,"[{""offset_um"": 20, ""distance"": 0.0, ""dx"": 0.0,...",,,,NaT,2026-06-23 10:07:40
2,125,M315TAN01,TFT,3N6A5JE4C,2026-06-03 10:00:00,2026-06-03,PISpot,aoi200,CAPIC200,4363,...,0,OK,,20,[],,,,NaT,2026-06-23 10:07:40
3,126,M315TAN01,TFT,3N6A5JE4C,2026-06-03 10:00:00,2026-06-03,UPI,aoi200,CAPIC200,4363,...,0,OK,,20,"[{""offset_um"": 20, ""distance"": 1.0, ""dx"": 0.0,...",,,,NaT,2026-06-23 10:07:40
4,127,M340QAR1B,TFT,VP6G4N88J,2026-06-05 14:00:00,2026-06-05,PISpot,aoi200,CAPIC400,4298,...,1,OK,,20,"[{""offset_um"": 20, ""distance"": 4.0, ""dx"": -4.0...",,,,NaT,2026-06-23 10:07:40

In [27]:
rows = cim_db.get_rows('cim_pi_glass_202605', {'pi_type':'API', 'aoi':'CAAOI202'})    
bpi_df = pd.DataFrame(rows)
print(len(bpi_df))
bpi_df

9130

,sheet_id_chip_id,test_time,model_no,op_id,abbr_cat,recipe_id,cassette_id,aoi,total_defect_qty,defect_size_o_qty,defect_size_l_qty,defect_size_m_qty,defect_size_s_qty,line_id,pi_time,pi_hour,pi_type
0,6R6A5LD2H,2026-05-01 04:17:01,M270HAN03,PCS1,TFT,2227,CA0117,CAAOI202,59,0,0,8,51,CAPIC100,2026-05-01 02:55:51,2026-05-01 02:00:00,API
1,6R6A5LD2H,2026-05-01 04:19:05,M270HAN03,PCS1,TFT,0227,CA0117,CAAOI202,169,0,0,33,136,CAPIC100,2026-05-01 02:55:51,2026-05-01 02:00:00,API
2,6R6A5LD2F,2026-05-01 04:30:04,M270HAN03,PCS1,TFT,2227,CA0117,CAAOI202,54,0,1,10,43,CAPIC100,2026-05-01 02:55:51,2026-05-01 02:00:00,API
3,6R6A5LD2G,2026-05-01 04:23:14,M270HAN03,PCS1,TFT,2227,CA0117,CAAOI202,43,0,1,8,34,CAPIC100,2026-05-01 02:55:51,2026-05-01 02:00:00,API
4,6R6A5LD2G,2026-05-01 04:25:04,M270HAN03,PCS1,TFT,0227,CA0117,CAAOI202,234,0,0,16,218,CAPIC100,2026-05-01 02:55:51,2026-05-01 02:00:00,API
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9125,5H6A5101D,2026-06-01 01:56:38,B160UAN4A,PCS1,TFT,2251,CA0315,CAAOI202,8,0,0,4,4,CAPIC600,2026-05-31 20:47:43,2026-05-31 20:00:00,API
9126,5H6A5101C,2026-06-01 02:01:55,B160UAN4A,PCS1,TFT,0251,CA0315,CAAOI202,59,0,2,18,39,CAPIC600,2026-05-31 20:47:43,2026-05-31 20:00:00,API
9127,5H6A5101B,2026-06-01 02:06:36,B160UAN4A,PCS1,TFT,0251,CA0315,CAAOI202,1,0,0,1,0,CAPIC600,2026-05-31 20:47:43,2026-05-31 20:00:00,API
9128,5H6A5101A,2026-06-01 02:10:26,B160UAN4A,PCS1,TFT,0251,CA0315,CAAOI202,15,0,0,8,7,CAPIC600,2026-05-31 20:47:43,2026-05-31 20:00:00,API
9129,5H6A5101A,2026-06-01 02:09:12,B160UAN4A,PCS1,TFT,2251,CA0315,CAAOI202,10,0,1,2,7,CAPIC600,2026-05-31 20:47:43,2026-05-31 20:00:00,API

In [3]:
df = inspec_db.get_table('inspection_summary_table_202606')
print(len(df))
df.drop_duplicates(subset=['SHEET_ID','SCAN_ENDTIME'], inplace=True)
print(len(df))
print(len(df.groupby(['SHEET_ID','SCAN_ENDTIME'])))
df.head()

148421
133681
133681

,CHIP_COUNT,CHIP_JUDGE,CHIP_OK_COUNT,DEFECT,FAB,MODEL_NO,RECIPE_NAME,RUN_ID,SCAN_ENDTIME,SCAN_STARTTIME,SHEET_ID,STAGE,TOOL_ID,TOTAL_DEFECT_COUNT,TYPE
0,18.0,OK,17.0,True,L6A,G215HVN01,G215HVN01-CF,-2116398710.0,2026-06-01 00:00:08,2026-05-31 23:59:46.000,AL5H151YP5,CELL,CAPIC207,5.0,CF
1,18.0,OK,18.0,True,L6A,G215HVN01,G215HVN01-CF,-2116398711.0,2026-06-01 00:01:02,2026-06-01 00:00:39.000,AL5H151YP4,CELL,CAPIC207,4.0,CF
2,36.0,NG,30.0,False,L6A,B140UAN08,B140UAN08-TFT,-2116398695.0,2026-06-01 00:00:15,2026-05-31 23:59:52.000,4C6A51T62,CELL,CAPIC507,8.0,TFT
3,36.0,OK,31.0,True,L6A,B140UAN08,B140UAN08-TFT,-2116398694.0,2026-06-01 00:01:13,2026-06-01 00:00:51.000,4C6A51T63,CELL,CAPIC507,9.0,TFT
4,18.0,OK,18.0,True,L6A,G215HVN01,G215HVN01-CF,-2116398682.0,2026-06-01 00:07:13,2026-06-01 00:06:51.000,AL5H151YML,CELL,CAPIC207,3.0,CF

In [9]:
glds = [v for v in df['SHEET_ID'].unique()  if v in cim_df['sheet_id_chip_id'].unique()]

In [ ]:
#pd.DataFrame(glds).to_csv('insepc_glds.csv')

In [5]:
cim_df = cim_db.get_table('cim_pi_glass_202606')
print(len(cim_df))
cim_df.drop_duplicates(subset=['sheet_id_chip_id', 'pi_type'], inplace=True)
print(len(cim_df))
print(len(cim_df.groupby(['sheet_id_chip_id', 'pi_type'])))
cim_df.head()

15992
11029
11029

,sheet_id_chip_id,test_time,model_no,op_id,abbr_cat,recipe_id,cassette_id,aoi,total_defect_qty,defect_size_o_qty,defect_size_l_qty,defect_size_m_qty,defect_size_s_qty,line_id,pi_time,pi_hour,pi_type
0,AL5H151Z3K,2026-05-31 19:09:01,G215HVN01_VG,PI AOI,CF,608,CA0376,CAPIT203,172,0,3,16,153,CAPIC200,2026-06-01 00:33:11,2026-06-01 00:00:00,BPI
1,AL5H151Z3G,2026-05-31 19:13:11,G215HVN01_VG,PI AOI,CF,608,CA0376,CAPIT203,167,0,1,8,158,CAPIC200,2026-06-01 00:33:11,2026-06-01 00:00:00,BPI
2,AL5H151Z3M,2026-05-31 19:17:19,G215HVN01_VG,PI AOI,CF,608,CA0376,CAPIT203,155,0,4,12,139,CAPIC200,2026-06-01 00:33:11,2026-06-01 00:00:00,BPI
3,AL5H151Z3A,2026-05-31 19:21:22,G215HVN01_VG,PI AOI,CF,608,CA0376,CAPIT203,181,1,11,23,146,CAPIC200,2026-06-01 00:33:11,2026-06-01 00:00:00,BPI
4,YH6A5U84G,2026-06-01 00:35:12,B160UAV01,PCS1,TFT,2283,CA0364,CAAOI202,23,0,0,7,16,CAPIC400,2026-06-01 00:13:18,2026-05-31 23:00:00,API

In [ ]:
db = MySQLConnet('piaoi_density')
for tbn in db.list_tables():
    if '202606' in tbn or '202607' in tbn:
        print(tbn)
        #db.drop_table(tbn)

2026-07-01 14:16:30,245 - INFO - [list_tables] 成功取得資料表名稱，共 23 張表。

density_code_summary_202606

2026-07-01 14:16:32,724 - INFO - [drop_table] 資料表 'density_code_summary_202606' 已刪除.

density_code_summary_202607

2026-07-01 14:16:33,735 - INFO - [drop_table] 資料表 'density_code_summary_202607' 已刪除.

density_recipe_summary_202606

2026-07-01 14:16:34,377 - INFO - [drop_table] 資料表 'density_recipe_summary_202606' 已刪除.

density_recipe_summary_202607

2026-07-01 14:16:34,814 - INFO - [drop_table] 資料表 'density_recipe_summary_202607' 已刪除.

density_tab_summary_202606

2026-07-01 14:16:35,361 - INFO - [drop_table] 資料表 'density_tab_summary_202606' 已刪除.

density_tab_summary_202607

2026-07-01 14:16:35,847 - INFO - [drop_table] 資料表 'density_tab_summary_202607' 已刪除.

In [13]:
cim_db.get_rows('cim_pi_glass_202606', {'aoi':'CAAOI300'})

[{'sheet_id_chip_id': 'ZM6A5ZW2A',
  'test_time': datetime.datetime(2026, 6, 1, 8, 16, 28),
  'model_no': 'M270QAN06_VX',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03024',
  'cassette_id': 'CA0128',
  'aoi': 'CAAOI300',
  'total_defect_qty': 640,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 640,
  'line_id': 'CAPIC700',
  'pi_time': datetime.datetime(2026, 6, 1, 5, 47, 48),
  'pi_hour': datetime.datetime(2026, 6, 1, 5, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': 'ZG6A53S2U',
  'test_time': datetime.datetime(2026, 6, 1, 9, 26, 52),
  'model_no': 'M270QAN06_VX',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03024',
  'cassette_id': 'CA0128',
  'aoi': 'CAAOI300',
  'total_defect_qty': 1772,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 1772,
  'line_id': 'CAPIC700',
  'pi_time': datetime.datetime(2026, 6, 1, 5, 47, 48),
  'pi_hour': datetime.datetime(2026, 6, 1, 5, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': 'ZG6A53S2Q',
  'test_time': datetime.datetime(2026, 6, 1, 10, 0, 14),
  'model_no': 'M270QAN06_VX',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03024',
  'cassette_id': 'CA0128',
  'aoi': 'CAAOI300',
  'total_defect_qty': 2269,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 2269,
  'line_id': 'CAPIC700',
  'pi_time': datetime.datetime(2026, 6, 1, 5, 47, 48),
  'pi_hour': datetime.datetime(2026, 6, 1, 5, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': 'ZG6A53S2N',
  'test_time': datetime.datetime(2026, 6, 1, 10, 15, 46),
  'model_no': 'M270QAN06_VX',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03024',
  'cassette_id': 'CA0128',
  'aoi': 'CAAOI300',
  'total_defect_qty': 366,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 366,
  'line_id': 'CAPIC700',
  'pi_time': datetime.datetime(2026, 6, 1, 5, 47, 48),
  'pi_hour': datetime.datetime(2026, 6, 1, 5, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': 'ZG6A53S2K',
  'test_time': datetime.datetime(2026, 6, 1, 10, 30, 28),
  'model_no': 'M270QAN06_VX',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03024',
  'cassette_id': 'CA0128',
  'aoi': 'CAAOI300',
  'total_defect_qty': 1439,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 1439,
  'line_id': 'CAPIC700',
  'pi_time': datetime.datetime(2026, 6, 1, 5, 47, 48),
  'pi_hour': datetime.datetime(2026, 6, 1, 5, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': 'ZG6A53S2J',
  'test_time': datetime.datetime(2026, 6, 1, 10, 38, 12),
  'model_no': 'M270QAN06_VX',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03024',
  'cassette_id': 'CA0128',
  'aoi': 'CAAOI300',
  'total_defect_qty': 353,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 353,
  'line_id': 'CAPIC700',
  'pi_time': datetime.datetime(2026, 6, 1, 5, 47, 48),
  'pi_hour': datetime.datetime(2026, 6, 1, 5, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': 'ZG6A5145N',
  'test_time': datetime.datetime(2026, 6, 1, 11, 42, 49),
  'model_no': 'M270QAN06_VX',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03024',
  'cassette_id': 'CA0214',
  'aoi': 'CAAOI300',
  'total_defect_qty': 1020,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 1020,
  'line_id': 'CAPIC700',
  'pi_time': datetime.datetime(2026, 6, 1, 6, 33, 18),
  'pi_hour': datetime.datetime(2026, 6, 1, 6, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50H4A',
  'test_time': datetime.datetime(2026, 6, 1, 12, 16, 7),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0216',
  'aoi': 'CAAOI300',
  'total_defect_qty': 92,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 92,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 5, 45, 56),
  'pi_hour': datetime.datetime(2026, 6, 1, 5, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A5Z464',
  'test_time': datetime.datetime(2026, 6, 1, 12, 21, 11),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0216',
  'aoi': 'CAAOI300',
  'total_defect_qty': 57,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 57,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 5, 45, 56),
  'pi_hour': datetime.datetime(2026, 6, 1, 5, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A5Z463',
  'test_time': datetime.datetime(2026, 6, 1, 12, 26, 26),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0216',
  'aoi': 'CAAOI300',
  'total_defect_qty': 74,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 74,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 5, 45, 56),
  'pi_hour': datetime.datetime(2026, 6, 1, 5, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': 'ZG6A5145M',
  'test_time': datetime.datetime(2026, 6, 1, 11, 52, 4),
  'model_no': 'M270QAN06_VX',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03024',
  'cassette_id': 'CA0214',
  'aoi': 'CAAOI300',
  'total_defect_qty': 1761,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 1761,
  'line_id': 'CAPIC700',
  'pi_time': datetime.datetime(2026, 6, 1, 6, 33, 18),
  'pi_hour': datetime.datetime(2026, 6, 1, 6, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': 'ZG6A5145L',
  'test_time': datetime.datetime(2026, 6, 1, 11, 59, 52),
  'model_no': 'M270QAN06_VX',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03024',
  'cassette_id': 'CA0214',
  'aoi': 'CAAOI300',
  'total_defect_qty': 1837,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 1837,
  'line_id': 'CAPIC700',
  'pi_time': datetime.datetime(2026, 6, 1, 6, 33, 18),
  'pi_hour': datetime.datetime(2026, 6, 1, 6, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J54',
  'test_time': datetime.datetime(2026, 6, 1, 15, 32, 41),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 198,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 198,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J53',
  'test_time': datetime.datetime(2026, 6, 1, 15, 37, 53),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 177,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 177,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J52',
  'test_time': datetime.datetime(2026, 6, 1, 15, 43, 17),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 258,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 258,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J51',
  'test_time': datetime.datetime(2026, 6, 1, 15, 48, 44),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 168,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 168,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5Z',
  'test_time': datetime.datetime(2026, 6, 1, 15, 53, 55),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 130,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 130,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5Y',
  'test_time': datetime.datetime(2026, 6, 1, 15, 59, 13),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 130,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 1,
  'defect_size_s_qty': 129,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5X',
  'test_time': datetime.datetime(2026, 6, 1, 16, 4, 19),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 136,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 136,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5W',
  'test_time': datetime.datetime(2026, 6, 1, 16, 9, 27),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 110,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 1,
  'defect_size_s_qty': 109,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5V',
  'test_time': datetime.datetime(2026, 6, 1, 16, 14, 52),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 114,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 2,
  'defect_size_s_qty': 112,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5U',
  'test_time': datetime.datetime(2026, 6, 1, 16, 20),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 94,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 1,
  'defect_size_s_qty': 93,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5T',
  'test_time': datetime.datetime(2026, 6, 1, 16, 25, 6),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 95,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 95,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5S',
  'test_time': datetime.datetime(2026, 6, 1, 16, 30, 22),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 162,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 162,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5R',
  'test_time': datetime.datetime(2026, 6, 1, 16, 35, 35),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 68,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 68,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5Q',
  'test_time': datetime.datetime(2026, 6, 1, 16, 40, 39),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 85,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 85,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5P',
  'test_time': datetime.datetime(2026, 6, 1, 16, 45, 56),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 89,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 89,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5N',
  'test_time': datetime.datetime(2026, 6, 1, 16, 51, 6),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 66,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 66,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5M',
  'test_time': datetime.datetime(2026, 6, 1, 16, 56, 10),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 62,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 62,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5L',
  'test_time': datetime.datetime(2026, 6, 1, 17, 1, 23),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 62,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 62,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5K',
  'test_time': datetime.datetime(2026, 6, 1, 17, 6, 27),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 74,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 74,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5J',
  'test_time': datetime.datetime(2026, 6, 1, 17, 11, 31),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 85,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 1,
  'defect_size_s_qty': 84,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5H',
  'test_time': datetime.datetime(2026, 6, 1, 17, 16, 49),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 67,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 67,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5G',
  'test_time': datetime.datetime(2026, 6, 1, 17, 21, 55),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 69,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 69,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5F',
  'test_time': datetime.datetime(2026, 6, 1, 17, 27),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 117,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 117,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5E',
  'test_time': datetime.datetime(2026, 6, 1, 17, 32, 21),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 87,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 1,
  'defect_size_s_qty': 86,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5D',
  'test_time': datetime.datetime(2026, 6, 1, 17, 37, 32),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 61,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 61,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5C',
  'test_time': datetime.datetime(2026, 6, 1, 17, 42, 36),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 169,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,
  'defect_size_m_qty': 0,
  'defect_size_s_qty': 169,
  'line_id': 'CAPIC300',
  'pi_time': datetime.datetime(2026, 6, 1, 7, 53, 40),
  'pi_hour': datetime.datetime(2026, 6, 1, 7, 0),
  'pi_type': 'API'},
 {'sheet_id_chip_id': '5H6A50J5B',
  'test_time': datetime.datetime(2026, 6, 1, 17, 48, 27),
  'model_no': 'B160UAN4A_VB',
  'op_id': 'PCS1',
  'abbr_cat': 'TFT',
  'recipe_id': '03093',
  'cassette_id': 'CA0184',
  'aoi': 'CAAOI300',
  'total_defect_qty': 31,
  'defect_size_o_qty': 0,
  'defect_size_l_qty': 0,

In [22]:
rows = cim_db.get_rows('cim_defect_202606_aoi100_capic200', {'sheet_id_chip_id':'AL5HZ60L39'})
print(len(rows))


rows = cim_db.get_rows('cim_defect_202606_aoi100_capic200', {'sheet_id_chip_id':'AL5HZ60L39', 'adc_def_code': 'others'})
print(len(rows))

2026-07-01 16:30:18,017 - INFO - [get_rows] 'cim_defect_202606_aoi100_capic200' 無符合條件資料.

76
0

In [ ]:
row_in={'pi_hour': '26-06-30 20', 'line_id': 'CAPIC200', 'aoi': 'aoi100', 'model': 'M215HAN01', 'glass_type': 'CF', 'recipe_id': '117', 'adc_def_code': 'others', 'glass': 'AL5HZ60L38,AL5HZ60L39,AL5HZ60L3A,AL5HZ60L3B,AL5HZ60L3C,AL5HZ60L3F,AL5HZ60L3H,AL5HZ60L3K,AL5HZ60L49,AL5HZ60LD9,AL5HZ60LDR,AL5HZ60LDT,AL5HZ60LDY,AL5HZ60LDZ,AL5HZ60LGB,AL5HZ60LGD,AL5HZ60LJF,AL5HZ60LJK,AL5HZ60LJM,AL5HZ60LJQ,AL5HZ60LJV,AL5HZ60M4G,AL5HZ60MMR,AL5HZ60MZS,AL5HZ60MZT,AL5HZ60N0T,AL5HZ60N0X,AL5HZ60N0Z', 'glass_size_detail': '{"AL5HZ60L38": {"S": 56, "M": 0, "L": 0, "O": 0, "T": 56}, "AL5HZ60L39": {"S": 30, "M": 0, "L": 0, "O": 0, "T": 30}, "AL5HZ60L3A": {"S": 55, "M": 0, "L": 0, "O": 0, "T": 55}, "AL5HZ60L3B": {"S": 57, "M": 0, "L": 0, "O": 0, "T": 57}, "AL5HZ60L3C": {"S": 39, "M": 1, "L": 0, "O": 0, "T": 40}, "AL5HZ60L3F": {"S": 42, "M": 0, "L": 0, "O": 0, "T": 42}, "AL5HZ60L3H": {"S": 34, "M": 0, "L": 0, "O": 0, "T": 34}, "AL5HZ60L3K": {"S": 52, "M": 0, "L": 0, "O": 0, "T": 52}, "AL5HZ60L49": {"S": 43, "M": 0, "L": 0, "O": 0, "T": 43}, "AL5HZ60LD9": {"S": 63, "M": 0, "L": 0, "O": 0, "T": 63}, "AL5HZ60LDR": {"S": 136, "M": 86, "L": 0, "O": 0, "T": 222}, "AL5HZ60LDT": {"S": 101, "M": 30, "L": 0, "O": 0, "T": 131}, "AL5HZ60LDY": {"S": 34, "M": 0, "L": 0, "O": 0, "T": 34}, "AL5HZ60LDZ": {"S": 20, "M": 0, "L": 0, "O": 0, "T": 20}, "AL5HZ60LGB": {"S": 41, "M": 0, "L": 0, "O": 0, "T": 41}, "AL5HZ60LGD": {"S": 20, "M": 0, "L": 0, "O": 0, "T": 20}, "AL5HZ60LJF": {"S": 48, "M": 0, "L": 0, "O": 0, "T": 48}, "AL5HZ60LJK": {"S": 20, "M": 0, "L": 0, "O": 0, "T": 20}, "AL5HZ60LJM": {"S": 58, "M": 0, "L": 0, "O": 0, "T": 58}, "AL5HZ60LJQ": {"S": 59, "M": 0, "L": 0, "O": 0, "T": 59}, "AL5HZ60LJV": {"S": 62, "M": 0, "L": 0, "O": 0, "T": 62}, "AL5HZ60M4G": {"S": 69, "M": 0, "L": 0, "O": 0, "T": 69}, "AL5HZ60MMR": {"S": 52, "M": 0, "L": 0, "O": 0, "T": 52}, "AL5HZ60MZS": {"S": 44, "M": 0, "L": 0, "O": 0, "T": 44}, "AL5HZ60MZT": {"S": 62, "M": 10, "L": 0, "O": 0, "T": 72}, "AL5HZ60N0T": {"S": 66, "M": 1, "L": 0, "O": 0, "T": 67}, "AL5HZ60N0X": {"S": 21, "M": 0, "L": 0, "O": 0, "T": 21}, "AL5HZ60N0Z": {"S": 35, "M": 0, "L": 0, "O": 0, "T": 35}}'}
#INFO - [defect_map] query pi_dt=2026-06-30 20:00:00, start_dt=2026-06-27 20:00:00, end_dt=2026-07-03 20:00:00, months=['202606', '202607'], aoi=aoi100, line_id=CAPIC200, def_code=others, glds=28

In [ ]:
base_keys={'adc_def_code': 'others', 'sheet_id_chip_id':'3D6A56S9A', 'recipe_id': '117'}
in_values=['AL5HZ60N0Z', 'AL5HZ60L38', 'AL5HZ60LDZ', 'AL5HZ60L3K', 'AL5HZ60LJF', 'AL5HZ60L49', 'AL5HZ60LJK', 'AL5HZ60L3F', 'AL5HZ60LJQ', 'AL5HZ60LDT', 'AL5HZ60LD9', 'AL5HZ60L3B', 'AL5HZ60LDR', 'AL5HZ60LJV', 'AL5HZ60LDY', 'AL5HZ60MZT', 'AL5HZ60MMR', 'AL5HZ60L3A', 'AL5HZ60LJM', 'AL5HZ60MZS', 'AL5HZ60M4G', 'AL5HZ60N0T', 'AL5HZ60L3C', 'AL5HZ60L3H', 'AL5HZ60L39', 'AL5HZ60LGB', 'AL5HZ60N0X', 'AL5HZ60LGD']

In [28]:
t = 0
for gld in in_values:
    print(gld, '----')
    rows = cim_db.get_rows('cim_defect_202606_aoi100_capic200', {'sheet_id_chip_id':gld})
    gls_df = pd.DataFrame(rows)
    print('1 total:', len(rows))
    for (tt, ), gld_rows in gls_df.groupby(['test_time']):
        print('test_time', tt)
        print('2. total:', len(gld_rows))
        t += len(rows)
        for (def_code, ), defs in gld_rows.groupby((['adc_def_code'])):
            print(def_code, len(defs))

AL5HZ60N0Z ----
1 total: 65
test_time 2026-06-30 22:57:02
2. total: 65
NPI_CF 2
NPI_OIL 1
NPI_TFT 1
Not_Found 23
OP_Defect 9
PI_Gel 2
PI_Spot_NP 1
Polymer 4
SPS 1
SSIU_Polymer 6
nan 15
AL5HZ60L38 ----
1 total: 95
test_time 2026-06-30 21:58:31
2. total: 95
NPI_CF 3
NPI_OIL 1
Not_Found 21
OP_Defect 13
PIS With Particle 1
Polymer 5
SSIU_Polymer 6
nan 45
AL5HZ60LDZ ----
1 total: 67
test_time 2026-06-30 22:30:53
2. total: 67
NPI_CF 6
Not_Found 11
OP_Defect 9
PI_Gel 4
Polymer 5
SPS 3
SSIU_Polymer 12
nan 17
AL5HZ60L3K ----
1 total: 105
test_time 2026-06-30 22:14:35
2. total: 105
NPI_CF 2
Not_Found 29
OP_Defect 6
PI_Gel 1
Polymer 2
SPS 2
SSIU_Polymer 8
nan 55
AL5HZ60LJF ----
1 total: 79
test_time 2026-06-30 21:32:16
2. total: 79
NPI_CF 2
Not_Found 27
OP_Defect 6
PI_Gel 6
SSIU_Polymer 9
nan 29
AL5HZ60L49 ----
1 total: 84
test_time 2026-06-30 22:34:10
2. total: 84
NPI_CF 3
NPI_OIL 2
Not_Found 24
OP_Defect 8
PI_Gel 2
Polymer 4
SPS 1
SSIU_Polymer 6
nan 34
AL5HZ60LJK ----
1 total: 71
test_time 2026-06-30 21:35:35
2. total: 71
NPI_CF 2
Not_Found 17
OP_Defect 4
PI_Gel 8
Polymer 3
SPS 1
SSIU_Polymer 15
nan 21
AL5HZ60L3F ----
1 total: 88
test_time 2026-06-30 22:11:25
2. total: 88
NPI_CF 3
Not_Found 21
OP_Defect 9
PI_Gel 7
PI_Spot_NP 1
SSIU_Polymer 9
nan 38
AL5HZ60LJQ ----
1 total: 93
test_time 2026-06-30 21:52:00
2. total: 93
NPI_CF 4
NPI_OIL 1
Not_Found 26
OP_Defect 7
PI_Gel 4
Polymer 1
SPS 1
SSIU_Polymer 6
nan 43
AL5HZ60LDT ----
1 total: 184
test_time 2026-06-30 22:21:12
2. total: 184
NPI_OIL 4
Not_Found 13
OP_Defect 28
PI_Gel 1
PI_Spot_NP 1
SPS 1
SSIU_Polymer 2
nan 134
AL5HZ60LD9 ----
1 total: 79
test_time 2026-06-30 21:45:24
2. total: 79
NPI_CF 3
NPI_OIL 1
Not_Found 17
OP_Defect 6
PI_Gel 6
PI_Spot_NP 3
Polymer 2
SPS 5
SSIU_Polymer 7
nan 29
AL5HZ60L3B ----
1 total: 100
test_time 2026-06-30 22:08:16
2. total: 100
Fiber 1
NPI_CF 4
NPI_OIL 1
Not_Found 20
OP_Defect 14
PI_Gel 2
Polymer 4
SSIU_Polymer 4
nan 50
AL5HZ60LDR ----
1 total: 258
test_time 2026-06-30 22:24:25
2. total: 258
NPI_CF 7
NPI_OIL 1
Not_Found 6
OP_Defect 34
SPS 1
SSIU_Polymer 1
nan 208
AL5HZ60LJV ----
1 total: 97
test_time 2026-06-30 21:48:42
2. total: 97
Fiber 1
NPI_CF 5
NPI_OIL 1
Not_Found 19
OP_Defect 13
PI_Gel 2
Polymer 1
SSIU_Polymer 8
nan 47
AL5HZ60LDY ----
1 total: 76
test_time 2026-06-30 22:27:35
2. total: 76
NPI_CF 6
NPI_TFT 1
Not_Found 20
OP_Defect 7
PI_Gel 3
PI_Spot_NP 1
Polymer 4
SSIU_Polymer 8
nan 26
AL5HZ60MZT ----
1 total: 101
test_time 2026-06-30 22:50:43
2. total: 101
NPI_CF 3
Not_Found 32
OP_Defect 6
PI_Gel 2
Polymer 3
SPS 1
SSIU_Polymer 3
nan 51
AL5HZ60MMR ----
1 total: 91
test_time 2026-06-30 21:38:53
2. total: 91
NPI_CF 3
Not_Found 37
OP_Defect 6
PI_Gel 1
SSIU_Polymer 3
nan 41
AL5HZ60L3A ----
1 total: 87
test_time 2026-06-30 22:01:49
2. total: 87
NPI_CF 3
Not_Found 20
OP_Defect 11
PI_Gel 2
Polymer 1
SPS 1
SSIU_Polymer 12
nan 37
AL5HZ60LJM ----
1 total: 84
test_time 2026-06-30 21:29:03
2. total: 84
Fiber 2
NPI_CF 2
Not_Found 17
OP_Defect 19
PI_Gel 5
SSIU_Polymer 5
nan 34
AL5HZ60MZS ----
1 total: 78
test_time 2026-06-30 22:47:26
2. total: 78
NPI_CF 5
Not_Found 15
OP_Defect 8
PI_Gel 2
Polymer 3
SPS 2
SSIU_Polymer 15
nan 28
AL5HZ60M4G ----
1 total: 124
test_time 2026-06-30 21:42:03
2. total: 124
Fiber 1
NPI_CF 3
Not_Found 30
OP_Defect 6
PI_Gel 5
SPS 2
SSIU_Polymer 2
nan 75
AL5HZ60N0T ----
1 total: 111
test_time 2026-06-30 22:44:08
2. total: 111
NPI_CF 3
Not_Found 30
OP_Defect 12
PI_Gel 1
PI_Spot_NP 1
Polymer 1
SPS 1
SSIU_Polymer 1
nan 61
AL5HZ60L3C ----
1 total: 78
test_time 2026-06-30 22:05:06
2. total: 78
NPI_CF 6
Not_Found 18
OP_Defect 7
PI_Gel 3
PI_Spot_NP 2
Polymer 2
SPS 1
SSIU_Polymer 11
nan 28
AL5HZ60L3H ----
1 total: 60
test_time 2026-06-30 22:17:52
2. total: 60
NPI_CF 2
NPI_OIL 2
Not_Found 14
OP_Defect 12
PI_Gel 1
Polymer 5
SSIU_Polymer 14
nan 10
AL5HZ60L39 ----
1 total: 76
test_time 2026-06-30 21:55:15
2. total: 76
NPI_CF 6
Not_Found 18
OP_Defect 6
PI_Gel 2
PI_Spot_NP 1
Polymer 5
SSIU_Polymer 12
nan 26
AL5HZ60LGB ----
1 total: 82
test_time 2026-06-30 22:40:50
2. total: 82
NPI_CF 3
Not_Found 13
OP_Defect 5
PI_Gel 2
Polymer 6
SSIU_Polymer 21
nan 32
AL5HZ60N0X ----
1 total: 65
test_time 2026-06-30 22:53:52
2. total: 65
NPI_CF 1
NPI_OIL 1
Not_Found 18
OP_Defect 5
PI_Gel 3
Polymer 1
SPS 1
SSIU_Polymer 20
nan 15
AL5HZ60LGD ----
1 total: 74
test_time 2026-06-30 22:37:33
2. total: 74
Fiber 1
NPI_CF 4
Not_Found 16
OP_Defect 14
PI_Gel 3
Polymer 2
SPS 1
SSIU_Polymer 9
nan 24

In [26]:
t

2652

In [4]:


for (gld, ) ,bs_rows in bpi_same_cf_df.groupby(['glass_id']):
    print('search gld: ', gld, len(bs_rows))
    print(bs_rows[['bpi_pi_time', 'bpi_scan_time','bpi_defect_count',  'api_scan_time', 'api_defect_count', 'glass_side']].drop_duplicates())
    cim_rows = cim_db.get_rows(cim_tbn, {'sheet_id_chip_id':gld})
    cim_df = pd.DataFrame(cim_rows)
    print('aoi cim_db pi_glass: ', len(cim_df))
    print(cim_df[['test_time', 'model_no', 'abbr_cat', 'aoi', 'total_defect_qty', 'line_id', 'pi_time',  'pi_type']].drop_duplicates())

    inspec_gld_df = inspec_df[inspec_df['glass'].str.contains(gld)][['pi_hour',  'line_id', 'model', 'glass_type','glass']]
    print('insepction api raws:', len(inspec_gld_df))
    print(inspec_gld_df.drop_duplicates())
    
    inspec_rows = inspec_db.get_rows('inspection_summary_table_202606', {'SHEET_ID':gld})
    inspec_rows_df = pd.DataFrame(inspec_rows)
    print('insepction defect raws:', len(inspec_rows_df))
    if not inspec_rows_df.empty:
        print(inspec_rows_df)
#

search gld:  AH0EQ604SA 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
769 2026-06-29 18:12:33 2026-06-29 07:32:14              1523

          api_scan_time  api_defect_count glass_side
769 2026-06-29 21:59:09                22         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-29 07:32:14     M170ETN1A       CF  CAAOI202              1523
1 2026-06-29 21:59:09  M170ETN1A_VG       CF  CAPIT203                22

    line_id             pi_time pi_type
0  CAPIC700 2026-06-29 18:12:33     BPI
1  CAPIC700 2026-06-29 18:12:33     API
insepction api raws: 0
Empty DataFrame
Columns: [pi_hour, line_id, model, glass_type, glass]
Index: []

2026-06-30 15:57:09,954 - INFO - [get_rows] 'inspection_summary_table_202606' 無符合條件資料.

insepction defect raws: 0
search gld:  AH0EQ604SC 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
770 2026-06-29 18:12:33 2026-06-29 06:53:29              1417

          api_scan_time  api_defect_count glass_side
770 2026-06-29 22:08:09                29         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-29 06:53:29     M170ETN1A       CF  CAAOI202              1417
1 2026-06-29 22:08:09  M170ETN1A_VG       CF  CAPIT203                29

    line_id             pi_time pi_type
0  CAPIC700 2026-06-29 18:12:33     BPI
1  CAPIC700 2026-06-29 18:12:33     API
insepction api raws: 0
Empty DataFrame
Columns: [pi_hour, line_id, model, glass_type, glass]
Index: []

2026-06-30 15:57:34,211 - INFO - [get_rows] 'inspection_summary_table_202606' 無符合條件資料.

insepction defect raws: 0
search gld:  AH0EQ604TG 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
771 2026-06-29 18:12:33 2026-06-29 07:45:11              1480

          api_scan_time  api_defect_count glass_side
771 2026-06-29 21:56:08                27         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-29 07:45:11     M170ETN1A       CF  CAAOI202              1480
1 2026-06-29 21:56:08  M170ETN1A_VG       CF  CAPIT203                27

    line_id             pi_time pi_type
0  CAPIC700 2026-06-29 18:12:33     BPI
1  CAPIC700 2026-06-29 18:12:33     API
insepction api raws: 0
Empty DataFrame
Columns: [pi_hour, line_id, model, glass_type, glass]
Index: []

2026-06-30 15:58:04,850 - INFO - [get_rows] 'inspection_summary_table_202606' 無符合條件資料.

insepction defect raws: 0
search gld:  AH0EQ604Z3 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
772 2026-06-29 18:12:33 2026-06-29 08:24:02              2026

          api_scan_time  api_defect_count glass_side
772 2026-06-29 21:47:04                42         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-29 08:24:02     M170ETN1A       CF  CAAOI202              2026
1 2026-06-29 21:47:04  M170ETN1A_VG       CF  CAPIT203                42

    line_id             pi_time pi_type
0  CAPIC700 2026-06-29 18:12:33     BPI
1  CAPIC700 2026-06-29 18:12:33     API
insepction api raws: 0
Empty DataFrame
Columns: [pi_hour, line_id, model, glass_type, glass]
Index: []

2026-06-30 15:58:13,126 - INFO - [get_rows] 'inspection_summary_table_202606' 無符合條件資料.

insepction defect raws: 0
search gld:  AH0EQ604ZG 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
773 2026-06-29 18:12:33 2026-06-29 08:11:03              2506

          api_scan_time  api_defect_count glass_side
773 2026-06-29 21:50:11                21         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-29 08:11:03     M170ETN1A       CF  CAAOI202              2506
1 2026-06-29 21:50:11  M170ETN1A_VG       CF  CAPIT203                21

    line_id             pi_time pi_type
0  CAPIC700 2026-06-29 18:12:33     BPI
1  CAPIC700 2026-06-29 18:12:33     API
insepction api raws: 0
Empty DataFrame
Columns: [pi_hour, line_id, model, glass_type, glass]
Index: []

2026-06-30 15:58:20,447 - INFO - [get_rows] 'inspection_summary_table_202606' 無符合條件資料.

insepction defect raws: 0
search gld:  AR0HG61GL9 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
191 2026-06-13 13:50:32 2026-06-13 10:53:52               223

          api_scan_time  api_defect_count glass_side
191 2026-06-13 17:26:40                79         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 10:53:52  M270HVN0G_VX       CF  CAPIT203               223
1 2026-06-13 17:26:40  M270HVN0G_VX       CF  CAPIT203                79

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1849 2026-06-13 13:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1849  AR0HG61HN7,AR0HG61HNA,AR0HG61HLY,AR0HG61HN8,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           2.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339453.0 2026-06-13 13:42:38  2026-06-13 13:42:13.000  AR0HG61GL9

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               33.0   CF
search gld:  AR0HG61GLA 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
192 2026-06-13 13:50:32 2026-06-13 11:20:32               201

          api_scan_time  api_defect_count glass_side
192 2026-06-13 15:53:22               109         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 11:20:32  M270HVN0G_VX       CF  CAPIT203               201
1 2026-06-13 15:53:22  M270HVN0G_VX       CF  CAPIT203               109

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1849 2026-06-13 13:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1849  AR0HG61HN7,AR0HG61HNA,AR0HG61HLY,AR0HG61HN8,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           2.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339447.0 2026-06-13 13:48:02  2026-06-13 13:47:37.000  AR0HG61GLA

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               40.0   CF
search gld:  AR0HG61GLB 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
193 2026-06-13 13:50:32 2026-06-13 11:03:06               184

          api_scan_time  api_defect_count glass_side
193 2026-06-13 17:19:37                90         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 11:03:06  M270HVN0G_VX       CF  CAPIT203               184
1 2026-06-13 17:19:37  M270HVN0G_VX       CF  CAPIT203                90

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1849 2026-06-13 13:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1849  AR0HG61HN7,AR0HG61HNA,AR0HG61HLY,AR0HG61HN8,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           3.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339451.0 2026-06-13 13:44:28  2026-06-13 13:44:03.000  AR0HG61GLB

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               27.0   CF
search gld:  AR0HG61GLC 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
194 2026-06-13 13:50:32 2026-06-13 10:58:27               242

          api_scan_time  api_defect_count glass_side
194 2026-06-13 17:23:08                89         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 10:58:27  M270HVN0G_VX       CF  CAPIT203               242
1 2026-06-13 17:23:08  M270HVN0G_VX       CF  CAPIT203                89

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API

2026-06-30 15:58:21,291 - INFO - [get_rows] 'inspection_summary_table_202606' 無符合條件資料.

insepction api raws: 0
Empty DataFrame
Columns: [pi_hour, line_id, model, glass_type, glass]
Index: []
insepction defect raws: 0
search gld:  AR0HG61GLD 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
195 2026-06-13 13:50:32 2026-06-13 11:11:35               193

          api_scan_time  api_defect_count glass_side
195 2026-06-13 16:00:46               103         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 11:11:35  M270HVN0G_VX       CF  CAPIT203               193
1 2026-06-13 16:00:46  M270HVN0G_VX       CF  CAPIT203               103

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1849 2026-06-13 13:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1849  AR0HG61HN7,AR0HG61HNA,AR0HG61HLY,AR0HG61HN8,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           5.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339449.0 2026-06-13 13:46:11  2026-06-13 13:45:46.000  AR0HG61GLD

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               28.0   CF
search gld:  AR0HG61GLE 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
196 2026-06-13 13:50:32 2026-06-13 11:07:25               168

          api_scan_time  api_defect_count glass_side
196 2026-06-13 17:14:28               273         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 11:07:25  M270HVN0G_VX       CF  CAPIT203               168
1 2026-06-13 17:14:28  M270HVN0G_VX       CF  CAPIT203               273

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1849 2026-06-13 13:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1849  AR0HG61HN7,AR0HG61HNA,AR0HG61HLY,AR0HG61HN8,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           3.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339450.0 2026-06-13 13:45:16  2026-06-13 13:44:51.000  AR0HG61GLE

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               34.0   CF
search gld:  AR0HG61GLF 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
197 2026-06-13 13:50:32 2026-06-13 11:24:57               232

          api_scan_time  api_defect_count glass_side
197 2026-06-13 15:49:45               100         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 11:24:57  M270HVN0G_VX       CF  CAPIT203               232
1 2026-06-13 15:49:45  M270HVN0G_VX       CF  CAPIT203               100

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1849 2026-06-13 13:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1849  AR0HG61HN7,AR0HG61HNA,AR0HG61HLY,AR0HG61HN8,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           4.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339446.0 2026-06-13 13:48:49  2026-06-13 13:48:23.000  AR0HG61GLF

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               41.0   CF
search gld:  AR0HG61GLG 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
198 2026-06-13 13:50:32 2026-06-13 11:15:59               211

          api_scan_time  api_defect_count glass_side
198 2026-06-13 15:57:07               100         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 11:15:59  M270HVN0G_VX       CF  CAPIT203               211
1 2026-06-13 15:57:07  M270HVN0G_VX       CF  CAPIT203               100

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1849 2026-06-13 13:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1849  AR0HG61HN7,AR0HG61HNA,AR0HG61HLY,AR0HG61HN8,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           4.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339448.0 2026-06-13 13:47:05  2026-06-13 13:46:39.000  AR0HG61GLG

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               28.0   CF
search gld:  AR0HG61GNY 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
199 2026-06-13 13:50:32 2026-06-13 10:27:44               193

          api_scan_time  api_defect_count glass_side
199 2026-06-13 17:48:14                92         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 10:27:44  M270HVN0G_VX       CF  CAPIT203               193
1 2026-06-13 17:48:14  M270HVN0G_VX       CF  CAPIT203                92

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1849 2026-06-13 13:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1849  AR0HG61HN7,AR0HG61HNA,AR0HG61HLY,AR0HG61HN8,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           2.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339482.0 2026-06-13 13:37:23  2026-06-13 13:36:58.000  AR0HG61GNY

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               21.0   CF
search gld:  AR0HG61GNZ 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
200 2026-06-13 13:50:32 2026-06-13 10:49:44               164

          api_scan_time  api_defect_count glass_side
200 2026-06-13 17:30:08                79         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 10:49:44  M270HVN0G_VX       CF  CAPIT203               164
1 2026-06-13 17:30:08  M270HVN0G_VX       CF  CAPIT203                79

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1849 2026-06-13 13:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1849  AR0HG61HN7,AR0HG61HNA,AR0HG61HLY,AR0HG61HN8,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           4.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339454.0 2026-06-13 13:41:42  2026-06-13 13:41:16.000  AR0HG61GNZ

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               30.0   CF
search gld:  AR0HG61GQ7 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
201 2026-06-13 13:50:32 2026-06-13 10:32:06               201

          api_scan_time  api_defect_count glass_side
201 2026-06-13 17:44:32               111         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 10:32:06  M270HVN0G_VX       CF  CAPIT203               201
1 2026-06-13 17:44:32  M270HVN0G_VX       CF  CAPIT203               111

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1849 2026-06-13 13:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1849  AR0HG61HN7,AR0HG61HNA,AR0HG61HLY,AR0HG61HN8,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           3.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339481.0 2026-06-13 13:38:10  2026-06-13 13:37:44.000  AR0HG61GQ7

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               29.0   CF
search gld:  AR0HG61GQ8 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
202 2026-06-13 13:50:32 2026-06-13 10:23:03               230

          api_scan_time  api_defect_count glass_side
202 2026-06-13 17:51:50               100         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 10:23:03  M270HVN0G_VX       CF  CAPIT203               230
1 2026-06-13 17:51:50  M270HVN0G_VX       CF  CAPIT203               100

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1849 2026-06-13 13:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1849  AR0HG61HN7,AR0HG61HNA,AR0HG61HLY,AR0HG61HN8,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           1.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339483.0 2026-06-13 13:36:27  2026-06-13 13:36:01.000  AR0HG61GQ8

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               45.0   CF
search gld:  AR0HG61GQ9 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
203 2026-06-13 13:50:32 2026-06-13 10:36:32               183

          api_scan_time  api_defect_count glass_side
203 2026-06-13 17:40:59                91         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 10:36:32  M270HVN0G_VX       CF  CAPIT203               183
1 2026-06-13 17:40:59  M270HVN0G_VX       CF  CAPIT203                91

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1849 2026-06-13 13:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1849  AR0HG61HN7,AR0HG61HNA,AR0HG61HLY,AR0HG61HN8,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           4.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339457.0 2026-06-13 13:39:03  2026-06-13 13:38:38.000  AR0HG61GQ9

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               35.0   CF
search gld:  AR0HG61GQB 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
204 2026-06-13 13:50:32 2026-06-13 10:45:14               211

          api_scan_time  api_defect_count glass_side
204 2026-06-13 17:33:35               107         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 10:45:14  M270HVN0G_VX       CF  CAPIT203               211
1 2026-06-13 17:33:35  M270HVN0G_VX       CF  CAPIT203               107

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1849 2026-06-13 13:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1849  AR0HG61HN7,AR0HG61HNA,AR0HG61HLY,AR0HG61HN8,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           2.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339455.0 2026-06-13 13:40:56  2026-06-13 13:40:31.000  AR0HG61GQB

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               45.0   CF
search gld:  AR0HG61GQC 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
205 2026-06-13 13:50:32 2026-06-13 10:40:53               192

          api_scan_time  api_defect_count glass_side
205 2026-06-13 17:37:22                95         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 10:40:53  M270HVN0G_VX       CF  CAPIT203               192
1 2026-06-13 17:37:22  M270HVN0G_VX       CF  CAPIT203                95

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1849 2026-06-13 13:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1849  AR0HG61HN7,AR0HG61HNA,AR0HG61HLY,AR0HG61HN8,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           5.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339456.0 2026-06-13 13:40:04  2026-06-13 13:39:39.000  AR0HG61GQC

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               30.0   CF
search gld:  AR0HG61GT1 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
206 2026-06-13 13:50:32 2026-06-13 10:18:29               216

          api_scan_time  api_defect_count glass_side
206 2026-06-13 17:55:28                85         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 10:18:29  M270HVN0G_VX       CF  CAPIT203               216
1 2026-06-13 17:55:28  M270HVN0G_VX       CF  CAPIT203                85

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 0
Empty DataFrame
Columns: [pi_hour, line_id, model, glass_type, glass]
Index: []

2026-06-30 15:58:24,257 - INFO - [get_rows] 'inspection_summary_table_202606' 無符合條件資料.

insepction defect raws: 0
search gld:  AR0HG61GT5 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
207 2026-06-13 13:50:32 2026-06-13 09:33:37               187

          api_scan_time  api_defect_count glass_side
207 2026-06-13 18:34:52                82         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 09:33:37  M270HVN0G_VX       CF  CAPIT203               187
1 2026-06-13 18:34:52  M270HVN0G_VX       CF  CAPIT203                82

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1840 2026-06-13 12:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1840  AR0HG61JHL,AR0HG61JHK,AR0HG61JHJ,AR0HG61JHF,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           3.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339516.0 2026-06-13 13:26:47  2026-06-13 13:26:21.000  AR0HG61GT5

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               38.0   CF
search gld:  AR0HG61GT7 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
208 2026-06-13 13:50:32 2026-06-13 09:46:36               193

          api_scan_time  api_defect_count glass_side
208 2026-06-13 18:23:59               114         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 09:46:36  M270HVN0G_VX       CF  CAPIT203               193
1 2026-06-13 18:23:59  M270HVN0G_VX       CF  CAPIT203               114

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1840 2026-06-13 12:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1840  AR0HG61JHL,AR0HG61JHK,AR0HG61JHJ,AR0HG61JHF,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           5.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339491.0 2026-06-13 13:29:22  2026-06-13 13:28:57.000  AR0HG61GT7

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               38.0   CF
search gld:  AR0HG61HLW 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
209 2026-06-13 13:50:32 2026-06-13 10:09:18               215

          api_scan_time  api_defect_count glass_side
209 2026-06-13 18:05:46               121         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 10:09:18  M270HVN0G_VX       CF  CAPIT203               215
1 2026-06-13 18:05:46  M270HVN0G_VX       CF  CAPIT203               121

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1849 2026-06-13 13:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1849  AR0HG61HN7,AR0HG61HNA,AR0HG61HLY,AR0HG61HN8,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           2.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339486.0 2026-06-13 13:33:50  2026-06-13 13:33:25.000  AR0HG61HLW

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               51.0   CF
search gld:  AR0HG61HLY 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
210 2026-06-13 13:50:32 2026-06-13 10:00:27               187

          api_scan_time  api_defect_count glass_side
210 2026-06-13 18:13:03                90         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 10:00:27  M270HVN0G_VX       CF  CAPIT203               187
1 2026-06-13 18:13:03  M270HVN0G_VX       CF  CAPIT203                90

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1849 2026-06-13 13:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1849  AR0HG61HN7,AR0HG61HNA,AR0HG61HLY,AR0HG61HN8,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           3.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339488.0 2026-06-13 13:32:03  2026-06-13 13:31:35.000  AR0HG61HLY

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               34.0   CF
search gld:  AR0HG61HMG 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
211 2026-06-13 13:50:32 2026-06-13 10:13:50               227

          api_scan_time  api_defect_count glass_side
211 2026-06-13 17:58:54                95         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 10:13:50  M270HVN0G_VX       CF  CAPIT203               227
1 2026-06-13 17:58:54  M270HVN0G_VX       CF  CAPIT203                95

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1849 2026-06-13 13:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1849  AR0HG61HN7,AR0HG61HNA,AR0HG61HLY,AR0HG61HN8,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           2.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339485.0 2026-06-13 13:34:34  2026-06-13 13:34:08.000  AR0HG61HMG

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               44.0   CF
search gld:  AR0HG61HMP 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
212 2026-06-13 13:50:32 2026-06-13 09:41:59               215

          api_scan_time  api_defect_count glass_side
212 2026-06-13 18:27:39               108         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 09:41:59  M270HVN0G_VX       CF  CAPIT203               215
1 2026-06-13 18:27:39  M270HVN0G_VX       CF  CAPIT203               108

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1840 2026-06-13 12:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1840  AR0HG61JHL,AR0HG61JHK,AR0HG61JHJ,AR0HG61JHF,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           1.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339514.0 2026-06-13 13:28:26  2026-06-13 13:28:00.000  AR0HG61HMP

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507              166.0   CF
search gld:  AR0HG61HN7 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
213 2026-06-13 13:50:32 2026-06-13 09:51:00               240

          api_scan_time  api_defect_count glass_side
213 2026-06-13 18:20:16               108         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 09:51:00  M270HVN0G_VX       CF  CAPIT203               240
1 2026-06-13 18:20:16  M270HVN0G_VX       CF  CAPIT203               108

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1849 2026-06-13 13:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1849  AR0HG61HN7,AR0HG61HNA,AR0HG61HLY,AR0HG61HN8,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           1.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339490.0 2026-06-13 13:30:18  2026-06-13 13:29:53.000  AR0HG61HN7

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               46.0   CF
search gld:  AR0HG61HN8 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
214 2026-06-13 13:50:32 2026-06-13 10:04:47               203

          api_scan_time  api_defect_count glass_side
214 2026-06-13 18:09:33                84         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 10:04:47  M270HVN0G_VX       CF  CAPIT203               203
1 2026-06-13 18:09:33  M270HVN0G_VX       CF  CAPIT203                84

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1849 2026-06-13 13:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1849  AR0HG61HN7,AR0HG61HNA,AR0HG61HLY,AR0HG61HN8,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           0.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339487.0 2026-06-13 13:32:56  2026-06-13 13:32:31.000  AR0HG61HN8

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               45.0   CF
search gld:  AR0HG61HNA 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
215 2026-06-13 13:50:32 2026-06-13 09:55:38               258

          api_scan_time  api_defect_count glass_side
215 2026-06-13 18:16:37               106         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 09:55:38  M270HVN0G_VX       CF  CAPIT203               258
1 2026-06-13 18:16:37  M270HVN0G_VX       CF  CAPIT203               106

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1849 2026-06-13 13:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1849  AR0HG61HN7,AR0HG61HNA,AR0HG61HLY,AR0HG61HN8,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           1.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339489.0 2026-06-13 13:31:03  2026-06-13 13:30:38.000  AR0HG61HNA

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               52.0   CF
search gld:  AR0HG61HNB 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
216 2026-06-13 13:50:32 2026-06-13 09:37:59               146

          api_scan_time  api_defect_count glass_side
216 2026-06-13 18:31:22                84         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 09:37:59  M270HVN0G_VX       CF  CAPIT203               146
1 2026-06-13 18:31:22  M270HVN0G_VX       CF  CAPIT203                84

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1840 2026-06-13 12:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1840  AR0HG61JHL,AR0HG61JHK,AR0HG61JHJ,AR0HG61JHF,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           3.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339515.0 2026-06-13 13:27:30  2026-06-13 13:27:05.000  AR0HG61HNB

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               43.0   CF
search gld:  AR0HG61J04 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
217 2026-06-13 13:50:32 2026-06-13 11:29:36               250

          api_scan_time  api_defect_count glass_side
217 2026-06-13 15:45:20               202         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 11:29:36  M270HVN0G_VX       CF  CAPIT203               250
1 2026-06-13 15:45:20  M270HVN0G_VX       CF  CAPIT203               202

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1849 2026-06-13 13:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1849  AR0HG61HN7,AR0HG61HNA,AR0HG61HLY,AR0HG61HN8,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           0.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339422.0 2026-06-13 13:49:43  2026-06-13 13:49:18.000  AR0HG61J04

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               93.0   CF
search gld:  AR0HG61J06 1
            bpi_pi_time       bpi_scan_time  bpi_defect_count  \
218 2026-06-13 13:50:32 2026-06-13 11:34:27               234

          api_scan_time  api_defect_count glass_side
218 2026-06-13 15:41:28               133         CF
aoi cim_db pi_glass:  2
            test_time      model_no abbr_cat       aoi  total_defect_qty  \
0 2026-06-13 11:34:27  M270HVN0G_VX       CF  CAPIT203               234
1 2026-06-13 15:41:28  M270HVN0G_VX       CF  CAPIT203               133

    line_id             pi_time pi_type
0  CAPIC500 2026-06-13 13:50:32     BPI
1  CAPIC500 2026-06-13 13:50:32     API
insepction api raws: 1
                 pi_hour   line_id      model glass_type  \
1849 2026-06-13 13:00:00  CAPIC507  M270HVN0G         CF

                                                  glass
1849  AR0HG61HN7,AR0HG61HNA,AR0HG61HLY,AR0HG61HN8,AR...
insepction defect raws: 1
  CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO   RECIPE_NAME  \
0       12.0         NG           0.0  False  L6A  M270HVN0G  M270HVN0G-CF

          RUN_ID        SCAN_ENDTIME           SCAN_STARTTIME    SHEET_ID  \
0  -2116339421.0 2026-06-13 13:50:39  2026-06-13 13:50:13.000  AR0HG61J06

  STAGE   TOOL_ID TOTAL_DEFECT_COUNT TYPE
0  CELL  CAPIC507               61.0   CF

In [27]:
gld = 'YH6A56B4D'
db = MySQLConnet('piaoi_inspection_density')
tbn = 'inspection_summary_table_202606'
#tbn = 'inspection_raw_table_202606'
#tbn = 'incoming_glass_summary_202606'
#rows = db.get_rows(tbn, {'TOOL_ID':'CAPIC407'})
#rows
df = db.get_table('inspection_api_summary_202606')
df[df['glass'].str.contains(gld)]

,pi_hour,shift_day,shift_week,shift_month,shift_start,shift_end,line_id,model,glass_type,maingroup_glass_count,...,small_defect_count,middle_defect_count,large_defect_count,over_defect_count,glass,glass_size_detail,comment,action,Editor,modify_time
3322,2026-06-23 04:00:00,2026-06-22,2026W26,202606,2026-06-23 04:30:00,2026-06-23 05:30:00,CAPIC407,B160UAV01,TFT,28,...,9,18,26,6,"YH6A56B4A,YH6A56B4B,YH6A56B4C,YH6A56B4D,YH6A56...","[{""glass_id"": ""YH6A56B4A"", ""S"": 0, ""M"": 1, ""L""...",,,,2026-06-23 08:27:26

In [28]:
df.columns

Index(['pi_hour', 'shift_day', 'shift_week', 'shift_month', 'shift_start',
       'shift_end', 'line_id', 'model', 'glass_type', 'maingroup_glass_count',
       'maingroup_defect_count', 'maingroup_density',
       'defect_code_glass_count', 'small_defect_count', 'middle_defect_count',
       'large_defect_count', 'over_defect_count', 'glass', 'glass_size_detail',
       'comment', 'action', 'Editor', 'modify_time'],
      dtype='object')

In [30]:

tbn = 'inspection_summary_table_202606'
tbn = 'inspection_raw_table_202606'
rows = db.get_rows(tbn, {'SHEET_ID':gld})
df = pd.DataFrame(rows)
print(len(rows))
df.iloc[0,:].to_dict()

3

{'COORD_X': '-846.8',
 'COORD_Y': '-174.7967',
 'DEFECT': 'False',
 'DEFECT_AREA': '',
 'DEFECT_ID': '1.0',
 'DEFECT_SIZE_TYPE': 'M',
 'FAB': 'L6A',
 'FRONT_REVERSE': '1P',
 'IMG_URL': '',
 'RECIPE_NAME': 'B160UAV01-TFT',
 'RUN_ID': '-2116295107.0',
 'SCAN_ENDTIME': Timestamp('2026-06-23 04:46:42'),
 'SCAN_STARTTIME': '2026-06-23T04:46:19',
 'SHEET_ID': 'YH6A56B4D',
 'SP': 'N',
 'STAGE': 'CELL',
 'TOOL_ID': 'CAPIC407',
 'TOTAL_DEFECT_COUNT': '3.0'}

In [25]:
#db = MySQLConnet('piaoi_density')
aoi_rows = cim_db.get_rows('cim_pi_glass_202606', {'sheet_id_chip_id':gld})
aoi_df=  pd.DataFrame(aoi_rows)
print(len(aoi_df))
aoi_df

3

,sheet_id_chip_id,test_time,model_no,op_id,abbr_cat,recipe_id,cassette_id,aoi,total_defect_qty,defect_size_o_qty,defect_size_l_qty,defect_size_m_qty,defect_size_s_qty,line_id,pi_time,pi_hour,pi_type
0,YH6A56B4D,2026-06-22 23:30:39,B160UAV01,PCS1,TFT,4283,AA0268,CAAOI202,157,0,0,74,83,CAPIC400,2026-06-23 05:59:05,2026-06-23 05:00:00,BPI
1,YH6A56B4D,2026-06-23 07:45:21,B160UAV01,PCS1,TFT,0283,CA0315,CAAOI202,312,0,0,110,202,CAPIC400,2026-06-23 05:59:05,2026-06-23 05:00:00,API
2,YH6A56B4D,2026-06-23 07:43:33,B160UAV01,PCS1,TFT,2283,CA0315,CAAOI202,20,0,0,11,9,CAPIC400,2026-06-23 05:59:05,2026-06-23 05:00:00,API

In [26]:
aoi_df.columns

Index(['sheet_id_chip_id', 'test_time', 'model_no', 'op_id', 'abbr_cat',
       'recipe_id', 'cassette_id', 'aoi', 'total_defect_qty',
       'defect_size_o_qty', 'defect_size_l_qty', 'defect_size_m_qty',
       'defect_size_s_qty', 'line_id', 'pi_time', 'pi_hour', 'pi_type'],
      dtype='object')

In [6]:
db = MySQLConnet('cim_cell_aoi_to_array')
tbn = 'inspection_summary_table_202606'
tbn = 'inspection_raw_table_202606'
#tbn = 'incoming_glass_summary_202606'
df = db.get_table(tbn)
#print(df['judge'].unique())
df.head()

ValueError: Table inspection_raw_table_202606 not found

In [2]:
db = MySQLConnet('piaoi_inspection_density')
tbn = 'inspection_summary_table_202606'
tbn = 'inspection_raw_table_202606'
df = db.get_table(tbn)
df.head()

,COORD_X,COORD_Y,DEFECT,DEFECT_AREA,DEFECT_ID,DEFECT_SIZE_TYPE,FAB,FRONT_REVERSE,IMG_URL,RECIPE_NAME,RUN_ID,SCAN_ENDTIME,SCAN_STARTTIME,SHEET_ID,SP,STAGE,TOOL_ID,TOTAL_DEFECT_COUNT
0,-55.645,-1327.566,True,,1.0,S,L6A,1P,http://10.97.138.179/20260601/AL5H151YP4/1.jpg,G215HVN01-CF,-2116398711.0,2026-06-01 00:01:02,2026-06-01T00:00:39,AL5H151YP4,N,CELL,CAPIC207,4.0
1,-1391.611,-352.24,True,,2.0,S,L6A,1N,http://10.97.138.179/20260601/AL5H151YP4/2.jpg,G215HVN01-CF,-2116398711.0,2026-06-01 00:01:02,2026-06-01T00:00:39,AL5H151YP4,N,CELL,CAPIC207,4.0
2,-310.482,-1053.6,True,,3.0,S,L6A,1P,http://10.97.138.179/20260601/AL5H151YP4/3.jpg,G215HVN01-CF,-2116398711.0,2026-06-01 00:01:02,2026-06-01T00:00:39,AL5H151YP4,N,CELL,CAPIC207,4.0
3,-422.042,-1298.244,True,,4.0,S,L6A,1N,http://10.97.138.179/20260601/AL5H151YP4/4.jpg,G215HVN01-CF,-2116398711.0,2026-06-01 00:01:02,2026-06-01T00:00:39,AL5H151YP4,N,CELL,CAPIC207,4.0
4,-1188.963,-892.938,True,,1.0,S,L6A,1P,http://10.97.138.179/20260601/AL5H151YP5/1.jpg,G215HVN01-CF,-2116398710.0,2026-06-01 00:00:08,2026-05-31T23:59:46,AL5H151YP5,N,CELL,CAPIC207,5.0

In [ ]:
['COORD_X', 'COORD_Y','DEFECT_SIZE_TYPE','IMG_URL', 'RECIPE_NAME',
       'RUN_ID', 'SCAN_ENDTIME','SHEET_ID', 'SP', 'STAGE',
       'TOOL_ID', 'TOTAL_DEFECT_COUNT']

Index(['COORD_X', 'COORD_Y', 'DEFECT', 'DEFECT_AREA', 'DEFECT_ID',
       'DEFECT_SIZE_TYPE', 'FAB', 'FRONT_REVERSE', 'IMG_URL', 'RECIPE_NAME',
       'RUN_ID', 'SCAN_ENDTIME', 'SCAN_STARTTIME', 'SHEET_ID', 'SP', 'STAGE',
       'TOOL_ID', 'TOTAL_DEFECT_COUNT'],
      dtype='object')

In [3]:
df.iloc[0,:].to_dict()

{'COORD_X': '-55.645',
 'COORD_Y': '-1327.566',
 'DEFECT': 'True',
 'DEFECT_AREA': '',
 'DEFECT_ID': '1.0',
 'DEFECT_SIZE_TYPE': 'S',
 'FAB': 'L6A',
 'FRONT_REVERSE': '1P',
 'IMG_URL': 'http://10.97.138.179/20260601/AL5H151YP4/1.jpg',
 'RECIPE_NAME': 'G215HVN01-CF',
 'RUN_ID': '-2116398711.0',
 'SCAN_ENDTIME': Timestamp('2026-06-01 00:01:02'),
 'SCAN_STARTTIME': '2026-06-01T00:00:39',
 'SHEET_ID': 'AL5H151YP4',
 'SP': 'N',
 'STAGE': 'CELL',
 'TOOL_ID': 'CAPIC207',
 'TOTAL_DEFECT_COUNT': '4.0'}

In [ ]:
{'CHIP_COUNT': '18.0',
 
 'MODEL_NO': 'G215HVN01',
 'RECIPE_NAME': 'G215HVN01-CF',
 'RUN_ID': '-2116398710.0',
 'SCAN_ENDTIME': Timestamp('2026-06-01 00:00:08'),
 'SCAN_STARTTIME': '2026-05-31 23:59:46.000',
 'SHEET_ID': 'AL5H151YP5',
 'STAGE': 'CELL',
 'TOOL_ID': 'CAPIC207',
 'TOTAL_DEFECT_COUNT': '5.0',
 'TYPE': 'CF'}

In [6]:
for (gld, glass_type, ),rows in  df.groupby(['SHEET_ID', 'TYPE']):
    if len(rows['TOOL_ID'].unique())>1:
        print(gld, glass_type, rows['TOOL_ID'].unique())

20260604221728 TFT ['CAPIC507' 'CAPIC407']
4C6A62G21 TFT ['CAPIC507' 'CAPIC107']
4C6A62G22 TFT ['CAPIC507' 'CAPIC107']
4C6A62G23 TFT ['CAPIC507' 'CAPIC107']
4C6A62G24 TFT ['CAPIC507' 'CAPIC107']
4C6A62G2A TFT ['CAPIC507' 'CAPIC107']
4C6A62G2B TFT ['CAPIC507' 'CAPIC107']
4C6A62G2D TFT ['CAPIC507' 'CAPIC107']
4C6A62G2E TFT ['CAPIC507' 'CAPIC107']
4C6A62G2G TFT ['CAPIC507' 'CAPIC107']
4C6A62G2J TFT ['CAPIC507' 'CAPIC107']
4C6A62G2K TFT ['CAPIC507' 'CAPIC107']
4C6A62G2M TFT ['CAPIC507' 'CAPIC107']
4C6A62G2N TFT ['CAPIC507' 'CAPIC107']
4C6A62G2P TFT ['CAPIC507' 'CAPIC107']
4C6A62G2T TFT ['CAPIC507' 'CAPIC107']
4C6A62G2U TFT ['CAPIC507' 'CAPIC107']
4C6A62G2V TFT ['CAPIC507' 'CAPIC107']
4C6A62G2W TFT ['CAPIC507' 'CAPIC107']
4C6A62G2X TFT ['CAPIC507' 'CAPIC107']
4C6A62H71 TFT ['CAPIC507' 'CAPIC107']
4C6A62H72 TFT ['CAPIC507' 'CAPIC107']
4C6A62H73 TFT ['CAPIC507' 'CAPIC107']
4C6A62H74 TFT ['CAPIC507' 'CAPIC107']
4C6A62H7A TFT ['CAPIC507' 'CAPIC107']
4C6A62H7B TFT ['CAPIC507' 'CAPIC107']
4C6A62H7C TFT ['CAPIC507' 'CAPIC107']
4C6A62H7D TFT ['CAPIC507' 'CAPIC107']
4C6A62H7E TFT ['CAPIC507' 'CAPIC107']
4C6A62H7G TFT ['CAPIC507' 'CAPIC107']
4C6A62H7J TFT ['CAPIC507' 'CAPIC107']
4C6A62H7L TFT ['CAPIC507' 'CAPIC107']
4C6A62H7N TFT ['CAPIC507' 'CAPIC107']
4C6A62H7Q TFT ['CAPIC507' 'CAPIC107']
4C6A62H7R TFT ['CAPIC507' 'CAPIC107']
4C6A62H7S TFT ['CAPIC507' 'CAPIC107']
4C6A62H7T TFT ['CAPIC507' 'CAPIC107']
4C6A62H7U TFT ['CAPIC507' 'CAPIC107']
4C6A62H7V TFT ['CAPIC507' 'CAPIC107']
4C6A62H7W TFT ['CAPIC507' 'CAPIC107']
4C6A62H7X TFT ['CAPIC507' 'CAPIC107']
4C6A62H7Y TFT ['CAPIC507' 'CAPIC107']
4C6A62H7Z TFT ['CAPIC507' 'CAPIC107']
AG0UA50N14 CF ['CAPIC607' 'CAPIC107']
AG0UA50N17 CF ['CAPIC607' 'CAPIC107']
AG0UA50N18 CF ['CAPIC607' 'CAPIC107']
AG0UA50N1A CF ['CAPIC607' 'CAPIC107']
AG0UH60107 CF ['CAPIC607' 'CAPIC307']
AG0UH6011L CF ['CAPIC607' 'CAPIC307']
AG0UH6011P CF ['CAPIC607' 'CAPIC307']
AG0UH6014U CF ['CAPIC607' 'CAPIC307']
AG0UH60170 CF ['CAPIC607' 'CAPIC307']
AG0UH601DN CF ['CAPIC607' 'CAPIC307']
AG0UH601DU CF ['CAPIC607' 'CAPIC307']
AG0UH601P8 CF ['CAPIC607' 'CAPIC307']
AL5HG601FH CF ['CAPIC307' 'CAPIC207']
AL5HG601FJ CF ['CAPIC307' 'CAPIC207']
AL5HG601FL CF ['CAPIC307' 'CAPIC207']
AL5HG601FM CF ['CAPIC307' 'CAPIC207']
AL5HG601JJ CF ['CAPIC307' 'CAPIC207']
JF6A56Y0C TFT ['CAPIC507' 'CAPIC307']
VP6G4GY6B TFT ['CAPIC607' 'CAPIC407']
VP6G4GY6R TFT ['CAPIC607' 'CAPIC407']
VP6G4HL3E TFT ['CAPIC607' 'CAPIC407']
VP6G4HL3L TFT ['CAPIC607' 'CAPIC407']
VP6G4HL3P TFT ['CAPIC507' 'CAPIC407']
VP6G4HL3S TFT ['CAPIC507' 'CAPIC407']
VP6G4HL46 TFT ['CAPIC507' 'CAPIC407']
VP6G4HL4M TFT ['CAPIC607' 'CAPIC407']
VP6G4HL4Q TFT ['CAPIC607' 'CAPIC407']
VP6G4HL4Z TFT ['CAPIC507' 'CAPIC407']
VP6G4HL55 TFT ['CAPIC607' 'CAPIC407']
VP6G4HX2X TFT ['CAPIC607' 'CAPIC407']
VP6G4HX3W TFT ['CAPIC507' 'CAPIC407']
VP6G4HX52 TFT ['CAPIC607' 'CAPIC407']
VP6G4HX56 TFT ['CAPIC507' 'CAPIC407']
VP6G4HX57 TFT ['CAPIC507' 'CAPIC407']
VP6G4HX5E TFT ['CAPIC607' 'CAPIC407']
VP6G4HX5U TFT ['CAPIC507' 'CAPIC407']
VP6G4HX7H TFT ['CAPIC507' 'CAPIC407']
VP6G4HX7S TFT ['CAPIC607' 'CAPIC407']
VP6G4JA6B TFT ['CAPIC607' 'CAPIC407']
VP6G4JA6R TFT ['CAPIC607' 'CAPIC407']
VP6G4JA6T TFT ['CAPIC607' 'CAPIC407']
VP6G4JA81 TFT ['CAPIC507' 'CAPIC407']
VP6G4JA8H TFT ['CAPIC607' 'CAPIC407']
VP6G4JZ1T TFT ['CAPIC607' 'CAPIC407']
VP6G4JZ2M TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G4JZ31 TFT ['CAPIC607' 'CAPIC407']
VP6G4JZ3H TFT ['CAPIC607' 'CAPIC407']
VP6G4JZ6K TFT ['CAPIC607' 'CAPIC407']
VP6G4KB12 TFT ['CAPIC607' 'CAPIC407']
VP6G4KB14 TFT ['CAPIC607' 'CAPIC407']
VP6G4KB16 TFT ['CAPIC607' 'CAPIC407']
VP6G4KB1J TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G4KB3J TFT ['CAPIC607' 'CAPIC407']
VP6G4KB3T TFT ['CAPIC507' 'CAPIC407']
VP6G4KB5B TFT ['CAPIC607' 'CAPIC407']
VP6G4KS6D TFT ['CAPIC607' 'CAPIC407']
VP6G4KS6R TFT ['CAPIC607' 'CAPIC407']
VP6G4KS6T TFT ['CAPIC607' 'CAPIC407']
VP6G4KS6W TFT ['CAPIC607' 'CAPIC407']
VP6G4KS9C TFT ['CAPIC507' 'CAPIC407']
VP6G4KS9P TFT ['CAPIC507' 'CAPIC407']
VP6G4L533 TFT ['CAPIC607' 'CAPIC407']
VP6G4L53M TFT ['CAPIC607' 'CAPIC407']
VP6G4L53U TFT ['CAPIC507' 'CAPIC407']
VP6G4L542 TFT ['CAPIC607' 'CAPIC407']
VP6G4L54U TFT ['CAPIC607' 'CAPIC407']
VP6G4L551 TFT ['CAPIC607' 'CAPIC407']
VP6G4L552 TFT ['CAPIC607' 'CAPIC407']
VP6G4L553 TFT ['CAPIC507' 'CAPIC407']
VP6G4L554 TFT ['CAPIC607' 'CAPIC407']
VP6G4L572 TFT ['CAPIC507' 'CAPIC407']
VP6G4L57A TFT ['CAPIC507' 'CAPIC407']
VP6G4L57G TFT ['CAPIC607' 'CAPIC407']
VP6G4LG1E TFT ['CAPIC607' 'CAPIC407']
VP6G4LG1L TFT ['CAPIC607' 'CAPIC407']
VP6G4LG2S TFT ['CAPIC607' 'CAPIC407']
VP6G4LG2U TFT ['CAPIC607' 'CAPIC407']
VP6G4LG35 TFT ['CAPIC607' 'CAPIC407']
VP6G4LG3C TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G4LG4B TFT ['CAPIC607' 'CAPIC407']
VP6G4LG4R TFT ['CAPIC607' 'CAPIC407']
VP6G4LG6Q TFT ['CAPIC507' 'CAPIC407']
VP6G4LV02 TFT ['CAPIC607' 'CAPIC407']
VP6G4LV04 TFT ['CAPIC607' 'CAPIC407']
VP6G4LV0Z TFT ['CAPIC507' 'CAPIC407']
VP6G4LV14 TFT ['CAPIC607' 'CAPIC407']
VP6G4LV27 TFT ['CAPIC607' 'CAPIC407']
VP6G4LV2T TFT ['CAPIC607' 'CAPIC407']
VP6G4M042 TFT ['CAPIC607' 'CAPIC407']
VP6G4M04A TFT ['CAPIC607' 'CAPIC407']
VP6G4M04H TFT ['CAPIC607' 'CAPIC407']
VP6G4M051 TFT ['CAPIC607' 'CAPIC407']
VP6G4M05X TFT ['CAPIC507' 'CAPIC407']
VP6G4M05Y TFT ['CAPIC607' 'CAPIC407']
VP6G4MB32 TFT ['CAPIC607' 'CAPIC407']
VP6G4MB3X TFT ['CAPIC607' 'CAPIC407']
VP6G4N883 TFT ['CAPIC607' 'CAPIC407']
VP6G4N884 TFT ['CAPIC507' 'CAPIC407']
VP6G4N88D TFT ['CAPIC507' 'CAPIC407']
VP6G4N88K TFT ['CAPIC607' 'CAPIC407']
VP6G4N88L TFT ['CAPIC607' 'CAPIC407']
VP6G4N88M TFT ['CAPIC607' 'CAPIC407']
VP6G4NP02 TFT ['CAPIC607' 'CAPIC407']
VP6G4NP04 TFT ['CAPIC507' 'CAPIC407']
VP6G4NP0B TFT ['CAPIC607' 'CAPIC407']
VP6G4NP0E TFT ['CAPIC607' 'CAPIC407']
VP6G4NP0G TFT ['CAPIC607' 'CAPIC407']
VP6G4NP0P TFT ['CAPIC507' 'CAPIC407']
VP6G4NP0S TFT ['CAPIC607' 'CAPIC407']
VP6G4NP0V TFT ['CAPIC107' 'CAPIC407']
VP6G4NP0X TFT ['CAPIC607' 'CAPIC407']
VP6G4NY96 TFT ['CAPIC507' 'CAPIC407']
VP6G4NY9A TFT ['CAPIC607' 'CAPIC407']
VP6G4NY9D TFT ['CAPIC507' 'CAPIC407']
VP6G4NY9E TFT ['CAPIC607' 'CAPIC407']
VP6G4NY9G TFT ['CAPIC507' 'CAPIC407']
VP6G4NY9P TFT ['CAPIC607' 'CAPIC407']
VP6G4NY9R TFT ['CAPIC507' 'CAPIC407']
VP6G4NZ01 TFT ['CAPIC607' 'CAPIC407']
VP6G4NZ03 TFT ['CAPIC507' 'CAPIC607']
VP6G4NZ04 TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G4NZ0A TFT ['CAPIC507' 'CAPIC407']
VP6G4NZ0D TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G4NZ0F TFT ['CAPIC507' 'CAPIC407']
VP6G4NZ0H TFT ['CAPIC507' 'CAPIC407']
VP6G4NZ0J TFT ['CAPIC607' 'CAPIC407']
VP6G4NZ0P TFT ['CAPIC507' 'CAPIC407']
VP6G4NZ0Q TFT ['CAPIC607' 'CAPIC407']
VP6G4NZ0Y TFT ['CAPIC507' 'CAPIC607']
VP6G4NZ0Z TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G4NZ11 TFT ['CAPIC607' 'CAPIC407']
VP6G4NZ12 TFT ['CAPIC607' 'CAPIC407']
VP6G4NZ1A TFT ['CAPIC507' 'CAPIC407']
VP6G4NZ1C TFT ['CAPIC607' 'CAPIC407']
VP6G4NZ1Q TFT ['CAPIC607' 'CAPIC407']
VP6G4NZ1S TFT ['CAPIC607' 'CAPIC407']
VP6G4NZ1U TFT ['CAPIC607' 'CAPIC407']
VP6G4NZ2Q TFT ['CAPIC607' 'CAPIC407']
VP6G4NZ2T TFT ['CAPIC507' 'CAPIC607']
VP6G4NZ2Z TFT ['CAPIC507' 'CAPIC407']
VP6G4NZ3E TFT ['CAPIC607' 'CAPIC407']
VP6G4NZ3F TFT ['CAPIC607' 'CAPIC407']
VP6G4NZ3G TFT ['CAPIC607' 'CAPIC407']
VP6G4NZ3J TFT ['CAPIC607' 'CAPIC407']
VP6G4NZ3M TFT ['CAPIC207' 'CAPIC407']
VP6G4NZ3P TFT ['CAPIC507' 'CAPIC407']
VP6G4NZ3Q TFT ['CAPIC207' 'CAPIC407']
VP6G4NZ3R TFT ['CAPIC507' 'CAPIC407']
VP6G4NZ43 TFT ['CAPIC507' 'CAPIC407']
VP6G4NZ44 TFT ['CAPIC507' 'CAPIC407']
VP6G4NZ47 TFT ['CAPIC607' 'CAPIC407']
VP6G4NZ4B TFT ['CAPIC607' 'CAPIC407']
VP6G4NZ4F TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G4NZ4H TFT ['CAPIC507' 'CAPIC407']
VP6G4NZ4N TFT ['CAPIC507' 'CAPIC407']
VP6G4NZ4S TFT ['CAPIC507' 'CAPIC407']
VP6G4NZ4T TFT ['CAPIC507' 'CAPIC407']
VP6G4NZ4V TFT ['CAPIC607' 'CAPIC407']
VP6G4NZ4W TFT ['CAPIC507' 'CAPIC407']
VP6G4NZ4X TFT ['CAPIC507' 'CAPIC407']
VP6G4NZ4Y TFT ['CAPIC507' 'CAPIC407']
VP6G4NZ4Z TFT ['CAPIC507' 'CAPIC407']
VP6G4NZ5A TFT ['CAPIC507' 'CAPIC407']
VP6G4NZ5B TFT ['CAPIC607' 'CAPIC407']
VP6G4NZ5D TFT ['CAPIC507' 'CAPIC407']
VP6G4NZ5G TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G4NZ5V TFT ['CAPIC507' 'CAPIC407']
VP6G4NZ5W TFT ['CAPIC607' 'CAPIC407']
VP6G4NZ5X TFT ['CAPIC607' 'CAPIC407']
VP6G4P605 TFT ['CAPIC107' 'CAPIC407']
VP6G4P607 TFT ['CAPIC207' 'CAPIC407']
VP6G4P60D TFT ['CAPIC607' 'CAPIC407']
VP6G4P60J TFT ['CAPIC607' 'CAPIC407']
VP6G4P60M TFT ['CAPIC607' 'CAPIC407']
VP6G4P60N TFT ['CAPIC607' 'CAPIC407']
VP6G4P60T TFT ['CAPIC607' 'CAPIC407']
VP6G4P613 TFT ['CAPIC507' 'CAPIC407']
VP6G4P61A TFT ['CAPIC607' 'CAPIC407']
VP6G4P61C TFT ['CAPIC607' 'CAPIC407']
VP6G4P61D TFT ['CAPIC607' 'CAPIC407']
VP6G4P61E TFT ['CAPIC607' 'CAPIC407']
VP6G4P61F TFT ['CAPIC607' 'CAPIC407']
VP6G4P61G TFT ['CAPIC607' 'CAPIC407']
VP6G4P61J TFT ['CAPIC607' 'CAPIC407']
VP6G4P61K TFT ['CAPIC607' 'CAPIC407']
VP6G4P61L TFT ['CAPIC607' 'CAPIC407']
VP6G4P61M TFT ['CAPIC507' 'CAPIC407']
VP6G4P61P TFT ['CAPIC507' 'CAPIC407']
VP6G4P61Q TFT ['CAPIC507' 'CAPIC607']
VP6G4P61R TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G4P61U TFT ['CAPIC607' 'CAPIC407']
VP6G4P61V TFT ['CAPIC607' 'CAPIC407']
VP6G4P61W TFT ['CAPIC607' 'CAPIC407']
VP6G4P61X TFT ['CAPIC507' 'CAPIC407']
VP6G4P61Z TFT ['CAPIC607' 'CAPIC407']
VP6G4PB85 TFT ['CAPIC507' 'CAPIC407']
VP6G4PB86 TFT ['CAPIC607' 'CAPIC407']
VP6G4PB8E TFT ['CAPIC507' 'CAPIC407']
VP6G4PB8J TFT ['CAPIC607' 'CAPIC407']
VP6G4PB8P TFT ['CAPIC607' 'CAPIC407']
VP6G4PB8S TFT ['CAPIC607' 'CAPIC407']
VP6G4PB8T TFT ['CAPIC607' 'CAPIC407']
VP6G4PB8W TFT ['CAPIC607' 'CAPIC407']
VP6G4PB8X TFT ['CAPIC607' 'CAPIC407']
VP6G4PB8Y TFT ['CAPIC607' 'CAPIC407']
VP6G4PB8Z TFT ['CAPIC607' 'CAPIC407']
VP6G4PR4K TFT ['CAPIC507' 'CAPIC407']
VP6G4PR4P TFT ['CAPIC507' 'CAPIC407']
VP6G4PR4R TFT ['CAPIC607' 'CAPIC407']
VP6G4PR4S TFT ['CAPIC607' 'CAPIC407']
VP6G4PR4V TFT ['CAPIC607' 'CAPIC407']
VP6G4PR4W TFT ['CAPIC607' 'CAPIC407']
VP6G4PR4X TFT ['CAPIC607' 'CAPIC407']
VP6G4PR4Z TFT ['CAPIC607' 'CAPIC407']
VP6G4PR51 TFT ['CAPIC607' 'CAPIC407']
VP6G4PR55 TFT ['CAPIC507' 'CAPIC407']
VP6G4PR5D TFT ['CAPIC607' 'CAPIC407']
VP6G4PR5S TFT ['CAPIC607' 'CAPIC407']
VP6G4PR5W TFT ['CAPIC607' 'CAPIC407']
VP6G4PR6C TFT ['CAPIC607' 'CAPIC407']
VP6G4PR6E TFT ['CAPIC507' 'CAPIC407']
VP6G4PR6F TFT ['CAPIC607' 'CAPIC407']
VP6G4PR6P TFT ['CAPIC607' 'CAPIC407']
VP6G4PR6T TFT ['CAPIC607' 'CAPIC407']
VP6G4PR6V TFT ['CAPIC607' 'CAPIC407']
VP6G4PR74 TFT ['CAPIC107' 'CAPIC407']
VP6G4PR75 TFT ['CAPIC607' 'CAPIC407']
VP6G4PR7G TFT ['CAPIC507' 'CAPIC407']
VP6G4PR7J TFT ['CAPIC507' 'CAPIC407']
VP6G4PR7V TFT ['CAPIC607' 'CAPIC407']
VP6G4PR7Z TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G4PR83 TFT ['CAPIC607' 'CAPIC407']
VP6G4PR8B TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G4PR8J TFT ['CAPIC607' 'CAPIC407']
VP6G4PR8K TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G4PR8P TFT ['CAPIC607' 'CAPIC407']
VP6G4PR8R TFT ['CAPIC607' 'CAPIC407']
VP6G4PR8S TFT ['CAPIC507' 'CAPIC607']
VP6G4PR8W TFT ['CAPIC607' 'CAPIC407']
VP6G4PR8X TFT ['CAPIC607' 'CAPIC407']
VP6G4PR8Y TFT ['CAPIC207' 'CAPIC407']
VP6G4PR91 TFT ['CAPIC507' 'CAPIC407']
VP6G4PR94 TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G4PR95 TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G4PR96 TFT ['CAPIC607' 'CAPIC407']
VP6G4PR9A TFT ['CAPIC507' 'CAPIC407']
VP6G4PR9B TFT ['CAPIC507' 'CAPIC407']
VP6G4PR9E TFT ['CAPIC507' 'CAPIC607']
VP6G4PR9F TFT ['CAPIC607' 'CAPIC407']
VP6G4PR9M TFT ['CAPIC607' 'CAPIC407']
VP6G4PR9N TFT ['CAPIC507' 'CAPIC407']
VP6G4PS01 TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G4PS02 TFT ['CAPIC607' 'CAPIC407']
VP6G4PS04 TFT ['CAPIC507' 'CAPIC407']
VP6G4PS06 TFT ['CAPIC607' 'CAPIC407']
VP6G4PS07 TFT ['CAPIC507' 'CAPIC607']
VP6G4PS0D TFT ['CAPIC607' 'CAPIC407']
VP6G4PS0E TFT ['CAPIC607' 'CAPIC407']
VP6G4PS0V TFT ['CAPIC607' 'CAPIC407']
VP6G4PS0Y TFT ['CAPIC507' 'CAPIC407']
VP6G4PS0Z TFT ['CAPIC507' 'CAPIC407']
VP6G4PS1F TFT ['CAPIC607' 'CAPIC407']
VP6G4PS1G TFT ['CAPIC607' 'CAPIC407']
VP6G4PS1K TFT ['CAPIC607' 'CAPIC407']
VP6G4PS1L TFT ['CAPIC507' 'CAPIC407']
VP6G4PS1N TFT ['CAPIC607' 'CAPIC407']
VP6G4Q255 TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G4Q25B TFT ['CAPIC507' 'CAPIC407']
VP6G4Q25C TFT ['CAPIC507' 'CAPIC407']
VP6G4Q25E TFT ['CAPIC507' 'CAPIC407']
VP6G4Q25H TFT ['CAPIC507' 'CAPIC407']
VP6G4Q25Q TFT ['CAPIC507' 'CAPIC407']
VP6G4Q25T TFT ['CAPIC507' 'CAPIC407']
VP6G4Q25Z TFT ['CAPIC507' 'CAPIC407']
VP6G4Q265 TFT ['CAPIC607' 'CAPIC407']
VP6G4Q266 TFT ['CAPIC507' 'CAPIC607']
VP6G4Q26D TFT ['CAPIC507' 'CAPIC407']
VP6G4Q26G TFT ['CAPIC507' 'CAPIC607']
VP6G4Q26N TFT ['CAPIC507' 'CAPIC407']
VP6G4Q26Q TFT ['CAPIC607' 'CAPIC407']
VP6G4Q26R TFT ['CAPIC607' 'CAPIC407']
VP6G4Q26T TFT ['CAPIC607' 'CAPIC407']
VP6G4Q26Z TFT ['CAPIC607' 'CAPIC407']
VP6G4Q272 TFT ['CAPIC507' 'CAPIC407']
VP6G4Q276 TFT ['CAPIC607' 'CAPIC407']
VP6G4Q277 TFT ['CAPIC607' 'CAPIC407']
VP6G4Q27A TFT ['CAPIC607' 'CAPIC407']
VP6G4Q27D TFT ['CAPIC507' 'CAPIC407']
VP6G4Q27M TFT ['CAPIC607' 'CAPIC407']
VP6G4Q27U TFT ['CAPIC607' 'CAPIC407']
VP6G4Q27X TFT ['CAPIC107' 'CAPIC407']
VP6G4Q27Z TFT ['CAPIC607' 'CAPIC407']
VP6G4Q281 TFT ['CAPIC507' 'CAPIC407']
VP6G4Q284 TFT ['CAPIC607' 'CAPIC407']
VP6G4Q285 TFT ['CAPIC607' 'CAPIC407']
VP6G4Q28A TFT ['CAPIC507' 'CAPIC607']
VP6G4Q28M TFT ['CAPIC607' 'CAPIC407']
VP6G4Q28T TFT ['CAPIC507' 'CAPIC407']
VP6G4Q28Y TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G4Q28Z TFT ['CAPIC507' 'CAPIC407']
VP6G4Q291 TFT ['CAPIC607' 'CAPIC407']
VP6G4Q29G TFT ['CAPIC607' 'CAPIC407']
VP6G4Q29W TFT ['CAPIC607' 'CAPIC407']
VP6G4Q29Y TFT ['CAPIC507' 'CAPIC407']
VP6G4Q302 TFT ['CAPIC107' 'CAPIC407']
VP6G4Q305 TFT ['CAPIC507' 'CAPIC407']
VP6G4Q306 TFT ['CAPIC607' 'CAPIC407']
VP6G4Q30A TFT ['CAPIC607' 'CAPIC407']
VP6G4Q30E TFT ['CAPIC607' 'CAPIC407']
VP6G4Q30F TFT ['CAPIC607' 'CAPIC407']
VP6G4Q30R TFT ['CAPIC607' 'CAPIC407']
VP6G4Q30T TFT ['CAPIC507' 'CAPIC407']
VP6G4Q30V TFT ['CAPIC607' 'CAPIC407']
VP6G4Q30W TFT ['CAPIC607' 'CAPIC407']
VP6G4Q313 TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G4Q315 TFT ['CAPIC607' 'CAPIC407']
VP6G4Q317 TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G4Q31C TFT ['CAPIC507' 'CAPIC407']
VP6G4Q31E TFT ['CAPIC607' 'CAPIC407']
VP6G4Q31F TFT ['CAPIC607' 'CAPIC407']
VP6G4Q31G TFT ['CAPIC607' 'CAPIC407']
VP6G4Q31J TFT ['CAPIC507' 'CAPIC607']
VP6G4Q31N TFT ['CAPIC607' 'CAPIC407']
VP6G4Q31V TFT ['CAPIC607' 'CAPIC407']
VP6G4Q31X TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G4Q321 TFT ['CAPIC507' 'CAPIC407']
VP6G4Q324 TFT ['CAPIC607' 'CAPIC407']
VP6G4Q326 TFT ['CAPIC507' 'CAPIC407']
VP6G4Q327 TFT ['CAPIC507' 'CAPIC407']
VP6G4Q32A TFT ['CAPIC607' 'CAPIC407']
VP6G4Q32C TFT ['CAPIC607' 'CAPIC407']
VP6G4Q32D TFT ['CAPIC607' 'CAPIC407']
VP6G4Q32F TFT ['CAPIC607' 'CAPIC407']
VP6G4Q32G TFT ['CAPIC507' 'CAPIC407']
VP6G4Q32L TFT ['CAPIC607' 'CAPIC407']
VP6G4Q32N TFT ['CAPIC607' 'CAPIC407']
VP6G4Q32W TFT ['CAPIC607' 'CAPIC407']
VP6G4Q32Z TFT ['CAPIC607' 'CAPIC407']
VP6G4Q333 TFT ['CAPIC607' 'CAPIC407']
VP6G4Q334 TFT ['CAPIC607' 'CAPIC407']
VP6G4Q335 TFT ['CAPIC607' 'CAPIC407']
VP6G4Q336 TFT ['CAPIC607' 'CAPIC407']
VP6G4Q337 TFT ['CAPIC607' 'CAPIC407']
VP6G4Q33B TFT ['CAPIC607' 'CAPIC407']
VP6G4Q33G TFT ['CAPIC607' 'CAPIC407']
VP6G4Q33H TFT ['CAPIC607' 'CAPIC407']
VP6G4Q33J TFT ['CAPIC507' 'CAPIC407']
VP6G4Q33M TFT ['CAPIC507' 'CAPIC407']
VP6G4Q33V TFT ['CAPIC607' 'CAPIC407']
VP6G4Q33X TFT ['CAPIC507' 'CAPIC407']
VP6G5ER51 TFT ['CAPIC607' 'CAPIC407']
VP6G5ER54 TFT ['CAPIC607' 'CAPIC407']
VP6G5ER57 TFT ['CAPIC607' 'CAPIC407']
VP6G5ER5B TFT ['CAPIC607' 'CAPIC407']
VP6G5ER5G TFT ['CAPIC607' 'CAPIC407']
VP6G5ER5J TFT ['CAPIC507' 'CAPIC607']
VP6G5ER5K TFT ['CAPIC607' 'CAPIC407']
VP6G5ER5P TFT ['CAPIC607' 'CAPIC407']
VP6G5ER5R TFT ['CAPIC607' 'CAPIC407']
VP6G5ER5T TFT ['CAPIC607' 'CAPIC407']
VP6G5ER5W TFT ['CAPIC607' 'CAPIC407']
VP6G5ER67 TFT ['CAPIC507' 'CAPIC407']
VP6G5ER6C TFT ['CAPIC607' 'CAPIC407']
VP6G5ER6E TFT ['CAPIC507' 'CAPIC407']
VP6G5ER6H TFT ['CAPIC507' 'CAPIC407']
VP6G5ER6J TFT ['CAPIC607' 'CAPIC407']
VP6G5ER6P TFT ['CAPIC607' 'CAPIC407']
VP6G5ER6S TFT ['CAPIC507' 'CAPIC407']
VP6G5ER6X TFT ['CAPIC607' 'CAPIC407']
VP6G5ER6Z TFT ['CAPIC607' 'CAPIC407']
VP6G5ER7B TFT ['CAPIC607' 'CAPIC407']
VP6G5ER7E TFT ['CAPIC207' 'CAPIC407']
VP6G5ER7M TFT ['CAPIC607' 'CAPIC407']
VP6G5ER7Q TFT ['CAPIC607' 'CAPIC407']
VP6G5ER7U TFT ['CAPIC607' 'CAPIC407']
VP6G5ER7V TFT ['CAPIC607' 'CAPIC407']
VP6G5ER7X TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G5ER7Y TFT ['CAPIC607' 'CAPIC407']
VP6G5FV91 TFT ['CAPIC607' 'CAPIC407']
VP6G5FV93 TFT ['CAPIC507' 'CAPIC407']
VP6G5FV94 TFT ['CAPIC507' 'CAPIC407']
VP6G5FV95 TFT ['CAPIC507' 'CAPIC407']
VP6G5FV97 TFT ['CAPIC507' 'CAPIC407']
VP6G5FV9H TFT ['CAPIC607' 'CAPIC407']
VP6G5FV9L TFT ['CAPIC607' 'CAPIC407']
VP6G5FV9M TFT ['CAPIC607' 'CAPIC407']
VP6G5FV9R TFT ['CAPIC507' 'CAPIC407']
VP6G5FV9T TFT ['CAPIC607' 'CAPIC407']
VP6G5FV9U TFT ['CAPIC607' 'CAPIC407']
VP6G5FV9X TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G5FW06 TFT ['CAPIC607' 'CAPIC407']
VP6G5FW0C TFT ['CAPIC607' 'CAPIC407']
VP6G5FW0L TFT ['CAPIC507' 'CAPIC407']
VP6G5FW1E TFT ['CAPIC607' 'CAPIC407']
VP6G5FW25 TFT ['CAPIC507' 'CAPIC407']
VP6G5FW27 TFT ['CAPIC507' 'CAPIC407']
VP6G5FW2B TFT ['CAPIC607' 'CAPIC407']
VP6G5FW2C TFT ['CAPIC607' 'CAPIC407']
VP6G5FW2E TFT ['CAPIC607' 'CAPIC407']
VP6G5FW2H TFT ['CAPIC607' 'CAPIC407']
VP6G5FW2K TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G5FW2M TFT ['CAPIC507' 'CAPIC607']
VP6G5FW2S TFT ['CAPIC507' 'CAPIC407']
VP6G5FW42 TFT ['CAPIC507' 'CAPIC407']
VP6G5FW4N TFT ['CAPIC507' 'CAPIC407']
VP6G5FW4Q TFT ['CAPIC607' 'CAPIC407']
VP6G5FW4R TFT ['CAPIC607' 'CAPIC407']
VP6G5FW4T TFT ['CAPIC607' 'CAPIC407']
VP6G5FW5N TFT ['CAPIC507' 'CAPIC407']
VP6G5FW5P TFT ['CAPIC507' 'CAPIC407']
VP6G5FW5R TFT ['CAPIC507' 'CAPIC407']
VP6G5FW5S TFT ['CAPIC507' 'CAPIC407']
VP6G5FW5T TFT ['CAPIC607' 'CAPIC407']
VP6G5FW5U TFT ['CAPIC507' 'CAPIC407']
VP6G5FW61 TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G5FW66 TFT ['CAPIC607' 'CAPIC407']
VP6G5FW6A TFT ['CAPIC607' 'CAPIC407']
VP6G5FW6B TFT ['CAPIC607' 'CAPIC407']
VP6G5FW6C TFT ['CAPIC607' 'CAPIC407']
VP6G5FW6D TFT ['CAPIC607' 'CAPIC407']
VP6G5FW6F TFT ['CAPIC607' 'CAPIC407']
VP6G5FW6Q TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G5FW6S TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G5FW6T TFT ['CAPIC507' 'CAPIC407']
VP6G5G10D TFT ['CAPIC507' 'CAPIC407']
VP6G5G10E TFT ['CAPIC507' 'CAPIC407']
VP6G5G10F TFT ['CAPIC507' 'CAPIC407']
VP6G5G10H TFT ['CAPIC507' 'CAPIC407']
VP6G5G10K TFT ['CAPIC507' 'CAPIC407']
VP6G5G10M TFT ['CAPIC607' 'CAPIC407']
VP6G5G10T TFT ['CAPIC507' 'CAPIC407']
VP6G5G10U TFT ['CAPIC507' 'CAPIC407']
VP6G5G10Z TFT ['CAPIC507' 'CAPIC407']
VP6G5G115 TFT ['CAPIC507' 'CAPIC407']
VP6G5G11D TFT ['CAPIC507' 'CAPIC407']
VP6G5G11G TFT ['CAPIC507' 'CAPIC407']
VP6G5G11J TFT ['CAPIC507' 'CAPIC407']
VP6G5G11L TFT ['CAPIC607' 'CAPIC407']
VP6G5G11P TFT ['CAPIC607' 'CAPIC407']
VP6G5G11S TFT ['CAPIC507' 'CAPIC407']
VP6G5G11T TFT ['CAPIC607' 'CAPIC407']
VP6G5G11U TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G5G11V TFT ['CAPIC507' 'CAPIC407']
VP6G5G11W TFT ['CAPIC507' 'CAPIC407']
VP6G5G124 TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G5G12E TFT ['CAPIC507' 'CAPIC407']
VP6G5G12G TFT ['CAPIC507' 'CAPIC407']
VP6G5G12J TFT ['CAPIC507' 'CAPIC407']
VP6G5G12M TFT ['CAPIC507' 'CAPIC407']
VP6G5G12N TFT ['CAPIC507' 'CAPIC407']
VP6G5G12P TFT ['CAPIC507' 'CAPIC407']
VP6G5G12R TFT ['CAPIC507' 'CAPIC407']
VP6G5G12U TFT ['CAPIC507' 'CAPIC407']
VP6G5G12Y TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G5G13A TFT ['CAPIC607' 'CAPIC407']
VP6G5G13D TFT ['CAPIC607' 'CAPIC407']
VP6G5G13F TFT ['CAPIC607' 'CAPIC407']
VP6G5G13J TFT ['CAPIC607' 'CAPIC407']
VP6G5G13K TFT ['CAPIC507' 'CAPIC407']
VP6G5G13L TFT ['CAPIC607' 'CAPIC407']
VP6G5G13M TFT ['CAPIC607' 'CAPIC407']
VP6G5G13N TFT ['CAPIC607' 'CAPIC407']
VP6G5G13R TFT ['CAPIC607' 'CAPIC407']
VP6G5G13V TFT ['CAPIC507' 'CAPIC407']
VP6G5G13X TFT ['CAPIC607' 'CAPIC407']
VP6G5G13Y TFT ['CAPIC507' 'CAPIC407']
VP6G5G141 TFT ['CAPIC607' 'CAPIC407']
VP6G5G142 TFT ['CAPIC507' 'CAPIC607']
VP6G5G145 TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G5G146 TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G5G147 TFT ['CAPIC507' 'CAPIC607' 'CAPIC407']
VP6G5G14G TFT ['CAPIC507' 'CAPIC607']
VP6G5G14R TFT ['CAPIC607' 'CAPIC407']

In [ ]:
df = cim_db.get_runs_delta_days('cim_defect_202606_aoi200_capic600', 2, 'test_time')
df.head()

,sheet_id_chip_id,chip_id,test_time,defect_size,pox_x1,pox_y1,image_file_path,image_file_name,img_file_url_path,retype_def_code,adc_def_code,pi_time,pi_hour
0,5T6A60Y0D,A,2026-06-18 06:20:37,M,379368,576681,Image/CA036602/5T6A60Y0D/,RV1_379368_576681_0.jpg,PIT/2606/18/CAAOI202/5T6A60Y0D/0620/,nan,PI_Spot_NP,2026-06-18 03:45:20,2026-06-18 03:00:00
1,5T6A60Y0D,A,2026-06-18 06:20:37,S,1111430,1444051,Image/CA036602/5T6A60Y0D/,RV1_1111430_1444051_1.jpg,PIT/2606/18/CAAOI202/5T6A60Y0D/0620/,nan,PI_Spot_NP,2026-06-18 03:45:20,2026-06-18 03:00:00
2,5T6A60Y0D,A,2026-06-18 06:20:37,S,1466114,994383,Image/CA036602/5T6A60Y0D/,RV1_1466114_994383_2.jpg,PIT/2606/18/CAAOI202/5T6A60Y0D/0620/,nan,PI_Spot_NP,2026-06-18 03:45:20,2026-06-18 03:00:00
3,5T6A60Y0D,A,2026-06-18 06:20:37,S,386825,649628,Image/CA036602/5T6A60Y0D/,RV1_386825_649628_3.jpg,PIT/2606/18/CAAOI202/5T6A60Y0D/0620/,nan,PI_Spot_NP,2026-06-18 03:45:20,2026-06-18 03:00:00
4,5T6A60Y0D,A,2026-06-18 06:20:37,S,319425,560372,Image/CA036602/5T6A60Y0D/,RV1_319425_560372_4.jpg,PIT/2606/18/CAAOI202/5T6A60Y0D/0620/,nan,PI_Spot_NP,2026-06-18 03:45:20,2026-06-18 03:00:00

In [4]:
#df = cim_db.get_runs_delta_days('cim_defect_202606_aoi200_capic600', 7, 'test_time')
#df['defect_size'].unique()
db = MySQLConnet('piaoi_bpi_same_point')
#df = db.get_table('bpi_api_summary_202604')
#df.iloc[0,:].to_dict()

In [ ]:
datetime.datetime(2026, 6, 20, 15, 0)

In [10]:
row_in={'pi_hour': '26-06-20 15', 'line_id': 'CAPIC700', 'aoi': 'aoi200', 'model': 'M270QAN06', 'glass_type': 'TFT', 'recipe_id': '2234', 'adc_def_code': 'SSIU_Polymer', 'glass': 'ZG6A64H1C,ZG6A64H1D,ZG6A64H1E,ZG6A64H1F,ZG6A64H1G', 'glass_size_detail': '{"ZG6A64H1C": {"S": 6, "M": 0, "L": 0, "O": 0, "T": 6}, "ZG6A64H1D": {"S": 15, "M": 0, "L": 0, "O": 0, "T": 15}, "ZG6A64H1E": {"S": 9, "M": 0, "L": 0, "O": 0, "T": 9}, "ZG6A64H1F": {"S": 13, "M": 0, "L": 0, "O": 0, "T": 13}, "ZG6A64H1G": {"S": 2, "M": 21, "L": 14, "O": 10, "T": 47}}'}
base_keys={'adc_def_code': 'SSIU_Polymer', 'pi_hour': "2026-06-20 15:00:00"}
tbn = 'cim_defect_202606_aoi200_capic700'
glds = {'ZG6A64H1D', 'ZG6A64H1E', 'ZG6A64H1C', 'ZG6A64H1G', 'ZG6A64H1F'}

In [13]:
cols = [ 'sheet_id_chip_id', 'adc_def_code','defect_size', 'pi_time', 'pox_x1',
       'pox_y1', 'test_time']

In [4]:
[v for v in cim_db.list_tables() if 'cim_defect' in v and '202606' in v]

2026-06-23 14:27:20,380 - INFO - [list_tables] 成功取得資料表名稱，共 179 張表。

['__stg_cim_defect_202606_aoi300_capic700_1782172498',
 'cim_defect_202606_aoi100_capic100',
 'cim_defect_202606_aoi100_capic200',
 'cim_defect_202606_aoi100_capic300',
 'cim_defect_202606_aoi100_capic400',
 'cim_defect_202606_aoi100_capic500',
 'cim_defect_202606_aoi100_capic600',
 'cim_defect_202606_aoi100_capic700',
 'cim_defect_202606_aoi100_pi000',
 'cim_defect_202606_aoi200_capic100',
 'cim_defect_202606_aoi200_capic200',
 'cim_defect_202606_aoi200_capic300',
 'cim_defect_202606_aoi200_capic400',
 'cim_defect_202606_aoi200_capic500',
 'cim_defect_202606_aoi200_capic600',
 'cim_defect_202606_aoi200_capic700',
 'cim_defect_202606_aoi200_pi000',
 'cim_defect_202606_aoi300_capic100',
 'cim_defect_202606_aoi300_capic200',
 'cim_defect_202606_aoi300_capic300',
 'cim_defect_202606_aoi300_capic400',
 'cim_defect_202606_aoi300_capic500',
 'cim_defect_202606_aoi300_capic600',
 'cim_defect_202606_aoi300_capic700',
 'cim_defect_202606_aoi300_pi000']

In [3]:
db = MySQLConnet('piaoi_density')
df = db.get_table('default_spec_table')
df[df['model'].str.contains('test')]

,line_id,model,glass_type,adc_def_code,defect_size,OOC,OOS,Editor,modify_time,drop,MODEL_TYPE,PROCESS_TYPE
7422,CAPIC100,test_0317_2,TFT,PI_Spot_NP,S,0,5,預設,2026-03-17 15:58:57,T,高階,BIG
7434,CAPIC100,test_0429,TFT,PI_Spot_NP,S,1,2,預設,2026-04-29 10:39:59,T,Normal,1
7603,CAPIC700,test_0623,TFT,NPI_CF,OLM,5,10,預設,2026-06-23 13:52:53,F,Normal,BIG

In [ ]:

tbn = 'density_code_summary_202606'
base_keys={'adc_def_code': 'SSIU_Polymer', 'pi_hour': "2026-06-20 15:00:00", 'aoi':'aoi200', 'line_id':'CAPIC700', 'model':'M270QAN06'}
"""
df_all = cim_db.get_rows_df_in(
    table_name=tbn,
    base_keys=base_keys,
    in_key="sheet_id_chip_id",
    in_values=list(glds),
)
"""
df = db.get_rows(tbn,base_keys )
df

[{'line_id': 'CAPIC700',
  'aoi': 'aoi200',
  'model': 'M270QAN06',
  'glass_type': 'TFT',
  'pi_hour': datetime.datetime(2026, 6, 20, 15, 0),
  'recipe_id': '0234',
  'adc_def_code': 'SSIU_Polymer',
  'recipe_total_glass_cnt': 5,
  'recipe_total_defect_cnt': 1651,
  'recipe_total_density': 330.2,
  'defect_cnt': 5,
  'def_glass_cnt': 1,
  'glass_cnt': 5,
  'recipe_code_density': 1.0,
  'density': 1.0,
  'small_defect_count': 3,
  'middle_defect_count': 2,
  'large_defect_count': 0,
  'over_defect_count': 0,
  'glass': 'ZG6A64H1C,ZG6A64H1D,ZG6A64H1E,ZG6A64H1F,ZG6A64H1G',
  'glass_size_detail': '{"ZG6A64H1C": {"S": 0, "M": 0, "L": 0, "O": 0, "T": 0}, "ZG6A64H1D": {"S": 0, "M": 0, "L": 0, "O": 0, "T": 0}, "ZG6A64H1E": {"S": 0, "M": 0, "L": 0, "O": 0, "T": 0}, "ZG6A64H1F": {"S": 0, "M": 0, "L": 0, "O": 0, "T": 0}, "ZG6A64H1G": {"S": 3, "M": 2, "L": 0, "O": 0, "T": 5}}',
  'comment': '',
  'action': '',
  'Editor': '',
  'modify_time': '2026-06-23 10:10:32'},
 {'line_id': 'CAPIC700',
  'aoi': 'aoi200',
  'model': 'M270QAN06',
  'glass_type': 'TFT',
  'pi_hour': datetime.datetime(2026, 6, 20, 15, 0),
  'recipe_id': '2234',
  'adc_def_code': 'SSIU_Polymer',
  'recipe_total_glass_cnt': 5,
  'recipe_total_defect_cnt': 1301,
  'recipe_total_density': 260.2,
  'defect_cnt': 90,
  'def_glass_cnt': 5,
  'glass_cnt': 5,
  'recipe_code_density': 18.0,
  'density': 18.0,
  'small_defect_count': 45,
  'middle_defect_count': 21,
  'large_defect_count': 14,
  'over_defect_count': 10,
  'glass': 'ZG6A64H1C,ZG6A64H1D,ZG6A64H1E,ZG6A64H1F,ZG6A64H1G',
  'glass_size_detail': '{"ZG6A64H1C": {"S": 6, "M": 0, "L": 0, "O": 0, "T": 6}, "ZG6A64H1D": {"S": 15, "M": 0, "L": 0, "O": 0, "T": 15}, "ZG6A64H1E": {"S": 9, "M": 0, "L": 0, "O": 0, "T": 9}, "ZG6A64H1F": {"S": 13, "M": 0, "L": 0, "O": 0, "T": 13}, "ZG6A64H1G": {"S": 2, "M": 21, "L": 14, "O": 10, "T": 47}}',
  'comment': '',
  'action': '',
  'Editor': '',
  'modify_time': '2026-06-23 10:10:32'}]

In [18]:
tbn = 'cim_defect_202606_aoi200_capic700'
df_all = cim_db.get_rows_df_in(
    table_name=tbn,
    base_keys=base_keys,
    in_key="sheet_id_chip_id",
    in_values=list(glds),
)
for (gld, tt), rows in df_all[cols].groupby(['sheet_id_chip_id', "test_time"]):
    print(gld, tt, len(rows))
    if gld !='ZG6A64H1G':continue
    print(rows)

2026-06-23 11:12:30,816 - INFO - [get_rows_df_in] 成功取得 'cim_defect_202606_aoi200_capic700' 共 108 筆符合條件資料.

ZG6A64H1C 2026-06-20 17:58:02 6
ZG6A64H1D 2026-06-20 17:48:48 15
ZG6A64H1E 2026-06-20 17:24:24 9
ZG6A64H1F 2026-06-20 17:13:55 13
ZG6A64H1G 2026-06-20 16:47:27 13
   sheet_id_chip_id  adc_def_code defect_size             pi_time   pox_x1  \
0         ZG6A64H1G  SSIU_Polymer           S 2026-06-20 15:43:21  1796313
1         ZG6A64H1G  SSIU_Polymer           S 2026-06-20 15:43:21  1412045
2         ZG6A64H1G  SSIU_Polymer           S 2026-06-20 15:43:21  1574059
3         ZG6A64H1G  SSIU_Polymer           S 2026-06-20 15:43:21  1803645
4         ZG6A64H1G  SSIU_Polymer           S 2026-06-20 15:43:21  1818081
5         ZG6A64H1G  SSIU_Polymer           S 2026-06-20 15:43:21  1309441
6         ZG6A64H1G  SSIU_Polymer           S 2026-06-20 15:43:21  1452014
7         ZG6A64H1G  SSIU_Polymer           S 2026-06-20 15:43:21  1614355
8         ZG6A64H1G  SSIU_Polymer           S 2026-06-20 15:43:21  1584014
9         ZG6A64H1G  SSIU_Polymer           S 2026-06-20 15:43:21   504272
10        ZG6A64H1G  SSIU_Polymer           S 2026-06-20 15:43:21   804728
11        ZG6A64H1G  SSIU_Polymer           S 2026-06-20 15:43:21  1066203
12        ZG6A64H1G  SSIU_Polymer           S 2026-06-20 15:43:21  1221055

     pox_y1           test_time
0    413357 2026-06-20 16:47:27
1    401306 2026-06-20 16:47:27
2    692882 2026-06-20 16:47:27
3    598578 2026-06-20 16:47:27
4    504798 2026-06-20 16:47:27
5    552088 2026-06-20 16:47:27
6    170840 2026-06-20 16:47:27
7    965846 2026-06-20 16:47:27
8    881724 2026-06-20 16:47:27
9    855519 2026-06-20 16:47:27
10  1339528 2026-06-20 16:47:27
11   528126 2026-06-20 16:47:27
12   478587 2026-06-20 16:47:27
ZG6A64H1G 2026-06-20 16:58:22 47
    sheet_id_chip_id  adc_def_code defect_size             pi_time   pox_x1  \
25         ZG6A64H1G  SSIU_Polymer           S 2026-06-20 15:43:21   551277
44         ZG6A64H1G  SSIU_Polymer           S 2026-06-20 15:43:21  1628571
53         ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21  1770148
54         ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21  1800903
55         ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21  1806395
56         ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21  1798315
57         ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21  1803387
67         ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21  1702337
68         ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21  1460859
69         ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21  1540823
70         ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21  1501457
71         ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21  1455263
72         ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21  1455883
73         ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21  1448631
74         ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21  1449871
75         ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21  1451739
76         ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21  1540407
77         ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21  1496485
78         ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21  1464583
79         ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21  1452979
80         ZG6A64H1G  SSIU_Polymer         nan 2026-06-20 15:43:21  1825071
81         ZG6A64H1G  SSIU_Polymer         nan 2026-06-20 15:43:21  1747187
82         ZG6A64H1G  SSIU_Polymer         nan 2026-06-20 15:43:21  1713429
83         ZG6A64H1G  SSIU_Polymer         nan 2026-06-20 15:43:21  1793013
84         ZG6A64H1G  SSIU_Polymer         nan 2026-06-20 15:43:21  1781062
85         ZG6A64H1G  SSIU_Polymer         nan 2026-06-20 15:43:21  1746571
86         ZG6A64H1G  SSIU_Polymer           L 2026-06-20 15:43:21  1727764
88         ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21  1500032
89         ZG6A64H1G  SSIU_Polymer         nan 2026-06-20 15:43:21  1817452
90         ZG6A64H1G  SSIU_Polymer         nan 2026-06-20 15:43:21  1804648
91         ZG6A64H1G  SSIU_Polymer         nan 2026-06-20 15:43:21  1827432
92         ZG6A64H1G  SSIU_Polymer         nan 2026-06-20 15:43:21  1824848
93         ZG6A64H1G  SSIU_Polymer           L 2026-06-20 15:43:21  1671280
94         ZG6A64H1G  SSIU_Polymer           L 2026-06-20 15:43:21  1674180
95         ZG6A64H1G  SSIU_Polymer           L 2026-06-20 15:43:21  1672628
96         ZG6A64H1G  SSIU_Polymer           L 2026-06-20 15:43:21  1673352
97         ZG6A64H1G  SSIU_Polymer           L 2026-06-20 15:43:21  1667864
98         ZG6A64H1G  SSIU_Polymer           L 2026-06-20 15:43:21  1669728
99         ZG6A64H1G  SSIU_Polymer           L 2026-06-20 15:43:21  1667240
100        ZG6A64H1G  SSIU_Polymer           L 2026-06-20 15:43:21  1664756
101        ZG6A64H1G  SSIU_Polymer           L 2026-06-20 15:43:21  1675424
102        ZG6A64H1G  SSIU_Polymer           L 2026-06-20 15:43:21  1655432
103        ZG6A64H1G  SSIU_Polymer           L 2026-06-20 15:43:21  1643828
104        ZG6A64H1G  SSIU_Polymer           L 2026-06-20 15:43:21  1653980
105        ZG6A64H1G  SSIU_Polymer           L 2026-06-20 15:43:21  1645072
106        ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21  1492056
107        ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21  1492780

      pox_y1           test_time
25   1179111 2026-06-20 16:58:22
44   1322223 2026-06-20 16:58:22
53    387898 2026-06-20 16:58:22
54    387909 2026-06-20 16:58:22
55    387913 2026-06-20 16:58:22
56    387909 2026-06-20 16:58:22
57    387909 2026-06-20 16:58:22
67    778890 2026-06-20 16:58:22
68    778663 2026-06-20 16:58:22
69    778730 2026-06-20 16:58:22
70    778678 2026-06-20 16:58:22
71    778650 2026-06-20 16:58:22
72    778654 2026-06-20 16:58:22
73    778649 2026-06-20 16:58:22
74    778650 2026-06-20 16:58:22
75    778650 2026-06-20 16:58:22
76    778726 2026-06-20 16:58:22
77    778682 2026-06-20 16:58:22
78    778655 2026-06-20 16:58:22
79    778650 2026-06-20 16:58:22
80    778901 2026-06-20 16:58:22
81    778810 2026-06-20 16:58:22
82    778791 2026-06-20 16:58:22
83    778874 2026-06-20 16:58:22
84    778849 2026-06-20 16:58:22
85    778810 2026-06-20 16:58:22
86    778804 2026-06-20 16:58:22
88     29735 2026-06-20 16:58:22
89     29918 2026-06-20 16:58:22
90     29925 2026-06-20 16:58:22
91     29820 2026-06-20 16:58:22
92     29820 2026-06-20 16:58:22
93     29842 2026-06-20 16:58:22
94     29843 2026-06-20 16:58:22
95     29843 2026-06-20 16:58:22
96     29843 2026-06-20 16:58:22
97     29842 2026-06-20 16:58:22
98     29842 2026-06-20 16:58:22
99     29842 2026-06-20 16:58:22
100    29842 2026-06-20 16:58:22
101    29859 2026-06-20 16:58:22
102    29841 2026-06-20 16:58:22
103    29828 2026-06-20 16:58:22
104    29841 2026-06-20 16:58:22
105    29832 2026-06-20 16:58:22
106    29738 2026-06-20 16:58:22
107    29738 2026-06-20 16:58:22
ZG6A64H1G 2026-06-20 17:04:19 5
   sheet_id_chip_id  adc_def_code defect_size             pi_time  pox_x1  \
14        ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21  124654
15        ZG6A64H1G  SSIU_Polymer           S 2026-06-20 15:43:21   54961
16        ZG6A64H1G  SSIU_Polymer           S 2026-06-20 15:43:21   90662
38        ZG6A64H1G  SSIU_Polymer           M 2026-06-20 15:43:21   33975
39        ZG6A64H1G  SSIU_Polymer           S 2026-06-20 15:43:21   36183

     pox_y1           test_time
14   606356 2026-06-20 17:04:19
15   471748 2026-06-20 17:04:19
16   638958 2026-06-20 17:04:19
38  1208157 2026-06-20 17:04:19
39  1269522 2026-06-20 17:04:19

In [ ]:
glds = []
tb_data = {}
for tbn in db.list_tables():
    print(tbn)
    
    if '_202606' not in tbn:continue
    #tb_data[tbn] = db.get_table(tbn)
    #db.drop_table(tbn)
    """
    df = db.get_table(tbn)
    tb_data[tbn] = df.copy()
    for v in df[df['aoi'] =='aoi200']['glass_list']:
        glds = glds + v.split(",")
    """

2026-06-23 08:49:27,518 - INFO - [list_tables] 成功取得資料表名稱，共 7 張表。

bpi_same_point_202605
bpi_same_point_202606

2026-06-23 08:49:30,533 - INFO - [drop_table] 資料表 'bpi_same_point_202606' 已刪除.

bpi_same_point_match_detail_202605
bpi_same_point_match_detail_202606

2026-06-23 08:49:40,883 - INFO - [drop_table] 資料表 'bpi_same_point_match_detail_202606' 已刪除.

bpi_same_point_offset_summary_202605
bpi_same_point_offset_summary_202606

2026-06-23 08:49:42,079 - INFO - [drop_table] 資料表 'bpi_same_point_offset_summary_202606' 已刪除.

default_spec_table

In [5]:
glds = [v for v in set(glds)]
len(glds)

1061

In [15]:
cim_db.get_rows_df_in('cim_pi_glass_202605', {}, 'sheet_id_chip_id', ['LF6A5NW3H']).to_dict(orient='index')

2026-06-18 15:38:05,096 - INFO - [get_rows_df_in] 成功取得 'cim_pi_glass_202605' 共 1 筆符合條件資料.

{0: {'abbr_cat': 'TFT',
  'aoi': 'CAAOI202',
  'cassette_id': 'AA0500',
  'defect_size_l_qty': 85,
  'defect_size_m_qty': 95,
  'defect_size_o_qty': 0,
  'defect_size_s_qty': 19,
  'line_id': 'CAPIC100',
  'model_no': 'M215HAN01',
  'op_id': 'PCS1',
  'pi_hour': Timestamp('2026-05-04 03:00:00'),
  'pi_time': Timestamp('2026-05-04 03:31:28'),
  'pi_type': 'BPI',
  'recipe_id': '4231',
  'sheet_id_chip_id': 'LF6A5NW3H',
  'test_time': Timestamp('2026-05-03 17:24:08'),
  'total_defect_qty': 468}}

In [17]:
85+95+19+269

468

In [11]:
tbns = ['cim_defect_202605_aoi200_capic100',
            'cim_defect_202605_aoi200_capic200',
            'cim_defect_202605_aoi200_capic300',
            'cim_defect_202605_aoi200_capic400',
            'cim_defect_202605_aoi200_capic500',
            'cim_defect_202605_aoi200_capic600',
            'cim_defect_202605_aoi200_capic700',
            'cim_defect_202605_aoi200_pi000']
for tbn in tbns:
    df = cim_db.get_rows_df_in(tbn, base_keys={},in_key = 'sheet_id_chip_id',in_values=glds,empty_cols=['defect_size'])
    if df.empty:continue
    print(tbn)
    for (gld, tt, ), rows in df.groupby(['sheet_id_chip_id', 'pi_time']):
        print(gld, tt, len(rows))

2026-06-18 15:01:57,068 - INFO - [get_rows_df_in] 成功取得 'cim_defect_202605_aoi200_capic100' 共 2448 筆符合條件資料.

cim_defect_202605_aoi200_capic100
8A6A5VW1A 2026-05-30 18:13:52 1
8A6A5VW1B 2026-05-30 18:13:52 3
8A6A5VW1C 2026-05-30 18:13:52 3
LF6A5NW3G 2026-05-04 03:31:28 1
LF6A5NW3H 2026-05-04 03:31:28 269
LF6A5NW3L 2026-05-04 03:31:28 1
Y26A5RV7A 2026-05-14 13:02:28 3
Y26A5RV7B 2026-05-14 13:02:28 15
Y26A5RV7C 2026-05-14 13:02:28 1
Y26A5RV7F 2026-05-14 22:21:05 3
Y26A5RV7G 2026-05-14 22:21:05 2093
Y26A5RV7H 2026-05-14 22:21:05 1
Y26A5RV7X 2026-05-14 23:16:21 1
YL6A5059E 2026-05-27 16:01:50 17
YL6A5059F 2026-05-27 16:01:50 17
YL6A5059G 2026-05-27 16:01:50 8
YL6A5059H 2026-05-27 16:01:50 10
YL6A5ZD2E 2026-05-26 20:45:13 1

2026-06-18 15:01:57,696 - INFO - [get_rows_df_in] 'cim_defect_202605_aoi200_capic200' 無符合條件資料.
2026-06-18 15:01:58,892 - INFO - [get_rows_df_in] 成功取得 'cim_defect_202605_aoi200_capic300' 共 5 筆符合條件資料.

cim_defect_202605_aoi200_capic300
HJ6A5KT9A 2026-05-13 22:53:59 1
HJ6A5KT9J 2026-05-13 22:53:59 1
YD6A5PY0B 2026-05-04 00:39:49 1
YD6A5PY0E 2026-05-04 00:39:49 1
YD6A5PY0F 2026-05-04 00:39:49 1

2026-06-18 15:02:00,408 - INFO - [get_rows_df_in] 成功取得 'cim_defect_202605_aoi200_capic400' 共 9 筆符合條件資料.

cim_defect_202605_aoi200_capic400
VP6G3RX94 2026-05-09 18:41:26 1
VP6G4E16J 2026-05-02 07:41:38 1
VP6G4F40G 2026-05-10 01:04:54 1
VP6G4FH24 2026-05-10 01:04:54 2
VP6G4FH5W 2026-05-08 16:49:22 1
VP6G4JA84 2026-05-15 23:32:56 1
VP6G4PR7T 2026-06-04 20:50:43 1
YH6A5U88C 2026-05-31 13:35:37 1

2026-06-18 15:02:01,101 - INFO - [get_rows_df_in] 'cim_defect_202605_aoi200_capic500' 無符合條件資料.
2026-06-18 15:02:01,565 - INFO - [get_rows_df_in] 成功取得 'cim_defect_202605_aoi200_capic600' 共 1 筆符合條件資料.

cim_defect_202605_aoi200_capic600
5H6A5YR5E 2026-05-30 21:25:20 1

2026-06-18 15:02:03,517 - INFO - [get_rows_df_in] 'cim_defect_202605_aoi200_capic700' 無符合條件資料.
2026-06-18 15:02:04,174 - INFO - [get_rows_df_in] 成功取得 'cim_defect_202605_aoi200_pi000' 共 10 筆符合條件資料.

cim_defect_202605_aoi200_pi000

8A6A5VW1A 2026-05-30 18:55:15 1
8A6A5VW1B 2026-05-30 18:50:21 3
8A6A5VW1C 2026-05-30 18:46:01 3
LF6A5NW3G 2026-05-03 17:19:44 1
LF6A5NW3H 2026-05-03 17:24:08 269
LF6A5NW3L 2026-05-03 17:37:33 1
Y26A5RV7A 2026-05-12 12:08:06 1
Y26A5RV7A 2026-05-14 19:08:51 1
Y26A5RV7A 2026-05-14 19:13:06 1
Y26A5RV7B 2026-05-14 18:48:07 14
Y26A5RV7B 2026-05-14 19:00:05 1
Y26A5RV7C 2026-05-14 19:06:28 1
Y26A5RV7F 2026-05-12 12:23:43 1
Y26A5RV7F 2026-05-14 23:55:02 1
Y26A5RV7F 2026-05-14 23:58:07 1
Y26A5RV7G 2026-05-12 12:27:14 966
Y26A5RV7G 2026-05-14 23:43:14 1127
Y26A5RV7H 2026-05-14 23:37:06 1
Y26A5RV7X 2026-05-15 01:15:42 1
YL6A5059E 2026-05-27 10:44:26 16
YL6A5059E 2026-05-27 18:10:51 1
YL6A5059F 2026-05-27 10:47:34 16
YL6A5059F 2026-05-27 18:06:42 1
YL6A5059G 2026-05-27 10:50:30 8
YL6A5059H 2026-05-27 10:53:16 10
YL6A5ZD2E 2026-05-26 23:58:46 1

In [18]:
[v for v in cim_db.list_tables() if '202605_aoi200' in v]

2026-06-18 14:44:43,876 - INFO - [list_tables] 成功取得資料表名稱，共 178 張表。

['cim_defect_202605_aoi200_capic100',
 'cim_defect_202605_aoi200_capic200',
 'cim_defect_202605_aoi200_capic300',
 'cim_defect_202605_aoi200_capic400',
 'cim_defect_202605_aoi200_capic500',
 'cim_defect_202605_aoi200_capic600',
 'cim_defect_202605_aoi200_capic700',
 'cim_defect_202605_aoi200_pi000']

In [24]:
db = MySQLConnet('piaoi_inspection_density')
#rows = db.get_rows('inspection_raw_table_202606', {'TOOL_ID':'CAPIC207'})
rows = db.get_runs_delta_days('inspection_raw_table_202606', 9,'SCAN_ENDTIME')
df = rows[rows['SHEET_ID'] .isin(['AL5H151Z1P','L66A5181F','AL5HC500PC','3N6A5JD9A'])]

In [26]:
df[['SHEET_ID','COORD_X', 'COORD_Y',  'DEFECT_SIZE_TYPE', 'RECIPE_NAME', 'SCAN_ENDTIME', 'TOTAL_DEFECT_COUNT']].to_csv('inspection_data2.csv')

for (scan_time, gld, ), rows in df.groupby(['SCAN_ENDTIME', 'SHEET_ID']):
    print(scan_time, gld)
    print(rows.loc[rows.index[:3],rows.columns])

2026-06-01 07:46:56 AL5H151Z1P
         COORD_X    COORD_Y DEFECT DEFECT_AREA DEFECT_ID DEFECT_SIZE_TYPE  \
176080  -573.089  -1535.837   True                   1.0                S
176081   -197.59    -888.72   True                   2.0                O
176082  -462.718  -1083.322   True                   3.0                S

        FAB FRONT_REVERSE                                         IMG_URL  \
176080  L6A            1N  http://10.97.138.179/20260601/AL5H151Z1P/1.jpg
176081  L6A            1N  http://10.97.138.179/20260601/AL5H151Z1P/2.jpg
176082  L6A            1N  http://10.97.138.179/20260601/AL5H151Z1P/3.jpg

         RECIPE_NAME         RUN_ID        SCAN_ENDTIME       SCAN_STARTTIME  \
176080  G215HVN01-CF  -2116396399.0 2026-06-01 07:46:56  2026-06-01T07:46:33
176081  G215HVN01-CF  -2116396399.0 2026-06-01 07:46:56  2026-06-01T07:46:33
176082  G215HVN01-CF  -2116396399.0 2026-06-01 07:46:56  2026-06-01T07:46:33

          SHEET_ID SP STAGE   TOOL_ID TOTAL_DEFECT_COUNT
176080  AL5H151Z1P  N  CELL  CAPIC207                5.0
176081  AL5H151Z1P  N  CELL  CAPIC207                5.0
176082  AL5H151Z1P  N  CELL  CAPIC207                5.0
2026-06-01 13:19:40 L66A5181F
          COORD_X    COORD_Y DEFECT DEFECT_AREA DEFECT_ID DEFECT_SIZE_TYPE  \
158715  -1073.065  -1922.858  False                   1.0                O
158716   -723.705  -1785.636  False                   2.0                L
158717   -709.826   -1807.91  False                   3.0                L

        FAB FRONT_REVERSE                                        IMG_URL  \
158715  L6A            1N  http://10.97.138.179/20260601/L66A5181F/1.jpg
158716  L6A            1P  http://10.97.138.179/20260601/L66A5181F/2.jpg
158717  L6A            1P  http://10.97.138.179/20260601/L66A5181F/3.jpg

          RECIPE_NAME         RUN_ID        SCAN_ENDTIME       SCAN_STARTTIME  \
158715  G215HVN01-TFT  -2116395579.0 2026-06-01 13:19:40  2026-06-01T13:19:19
158716  G215HVN01-TFT  -2116395579.0 2026-06-01 13:19:40  2026-06-01T13:19:19
158717  G215HVN01-TFT  -2116395579.0 2026-06-01 13:19:40  2026-06-01T13:19:19

         SHEET_ID SP STAGE   TOOL_ID TOTAL_DEFECT_COUNT
158715  L66A5181F  N  CELL  CAPIC207                8.0
158716  L66A5181F  N  CELL  CAPIC207                8.0
158717  L66A5181F  N  CELL  CAPIC207                8.0
2026-06-01 21:43:53 AL5HC500PC
         COORD_X    COORD_Y DEFECT DEFECT_AREA DEFECT_ID DEFECT_SIZE_TYPE  \
146064   -41.987  -1814.475   True                   1.0                O
146065   -69.584  -1907.431   True                   2.0                O
146066  -705.982    -609.38   True                   3.0                S

        FAB FRONT_REVERSE                                         IMG_URL  \
146064  L6A            1N  http://10.97.138.179/20260601/AL5HC500PC/1.jpg
146065  L6A            1N  http://10.97.138.179/20260601/AL5HC500PC/2.jpg
146066  L6A            1P  http://10.97.138.179/20260601/AL5HC500PC/3.jpg

         RECIPE_NAME         RUN_ID        SCAN_ENDTIME       SCAN_STARTTIME  \
146064  G215HVN1C-CF  -2116394545.0 2026-06-01 21:43:53  2026-06-01T21:43:31
146065  G215HVN1C-CF  -2116394545.0 2026-06-01 21:43:53  2026-06-01T21:43:31
146066  G215HVN1C-CF  -2116394545.0 2026-06-01 21:43:53  2026-06-01T21:43:31

          SHEET_ID SP STAGE   TOOL_ID TOTAL_DEFECT_COUNT
146064  AL5HC500PC  N  CELL  CAPIC207                5.0
146065  AL5HC500PC  N  CELL  CAPIC207                5.0
146066  AL5HC500PC  N  CELL  CAPIC207                5.0
2026-06-03 19:07:48 3N6A5JD9A
         COORD_X    COORD_Y DEFECT DEFECT_AREA DEFECT_ID DEFECT_SIZE_TYPE  \
85040  -1041.281  -1812.612   True                   1.0                S
85041  -1364.473   -1985.02   True                   2.0                L

       FAB FRONT_REVERSE                                        IMG_URL  \
85040  L6A            1P  http://10.97.138.179/20260603/3N6A5JD9A/1.jpg
85041  L6A            1P  http://10.97.138.179/20260603/3N6A5JD9A/2.jpg

         RECIPE_NAME         RUN_ID        SCAN_ENDTIME       SCAN_STARTTIME  \
85040  M315TAN01-TFT  -2116385215.0 2026-06-03 19:07:48  2026-06-03T19:07:25
85041  M315TAN01-TFT  -2116385215.0 2026-06-03 19:07:48  2026-06-03T19:07:25

        SHEET_ID SP STAGE   TOOL_ID TOTAL_DEFECT_COUNT
85040  3N6A5JD9A  N  CELL  CAPIC207                2.0
85041  3N6A5JD9A  N  CELL  CAPIC207                2.0
2026-06-04 17:39:06 3N6A5JD9A
        COORD_X    COORD_Y DEFECT DEFECT_AREA DEFECT_ID DEFECT_SIZE_TYPE  FAB  \
73519  -598.266  -1902.605   True                   1.0                S  L6A
73520  -598.266  -1902.605   True                   1.0                S  L6A

      FRONT_REVERSE                                        IMG_URL  \
73519            1P  http://10.97.138.179/20260603/3N6A5JD9A/1.jpg
73520            1P  http://10.97.138.179/20260604/3N6A5JD9A/1.jpg

         RECIPE_NAME         RUN_ID        SCAN_ENDTIME       SCAN_STARTTIME  \
73519  M315TAN01-TFT  -2116381295.0 2026-06-04 17:39:06  2026-06-04T17:38:43
73520  M315TAN01-TFT  -2116381295.0 2026-06-04 17:39:06  2026-06-04T17:38:43

        SHEET_ID SP STAGE   TOOL_ID TOTAL_DEFECT_COUNT
73519  3N6A5JD9A  N  CELL  CAPIC207                1.0
73520  3N6A5JD9A  N  CELL  CAPIC207                1.0

In [ ]:
{"OC": "testing_date",  #"scan_time"
 "PS": "testing_date",  #"scan_time"
 "PX1=MOR": "test_time", #"scan_time"
 "TAR":"ddate_ttime",    #"repair time",
 "TOS": "ddate_ttime"    #"repair time",
 }

In [ ]:
"same_point_offset"
"same_point_defect_cnt "
"same_point_rate "

In [ ]:
{
    "glass_id": "sheet_id",
    "chip_id":"chip_id",
    "model_no": "model_no",
    "testing_date":"scan_time",
    "eqp_id":"eqp_id",
    "op":"op",
    "defect_no":"defect_no",
    "defect_code":"defect_code",
    "defect_size_type":"defect_size",
    "coord_x": "ori_x",
    "coord_y": "ori_y",
    "repair_op":"repair_op",
    }

{
    "tft_lot_id": "lot_id",
    "test_time":"scan_time",
    "tft_sheet_id":"sheet_id",
    "tft_chip_id":"chip_id",
    "signal_no":"signal",
    "gate_no":"gate",
    "pox_x": "ori_x",
    "pox_y": "ori_y",
    "defect_size":"defect_size",
    "image_file_name":"image_name",
    "op_key":"op_id",
    "recipe_id":"recipe_id",
    "eqp_id":"eqp_id",
    "adc_repair_answers":"defect_code",
}


{
    "lot_id": "lot_id",
    "board_id":"sheet_id",
    "chip_id":"chip_id",
    "data_ax":"signal",
    "gate_ax":"gate",
    "dft_mode":"signal_gate_defect_code",
    "route":"route",
    "ddate_ttime":"repair time",
    "retype":"defect_code",
    "tar_judge":"defect_size",
    "x_cord": "ori_x",
    "y_cord": "ori_y",
    "tester_tool": "tester_tool",
    "image_name": "image_name"

}

{'sheet_id_chip_id': 'sheet_id',
 'test_time': "scan_time",
 'model_no': 'G215HVN01_VG',
 'abbr_cat': 'CF',
 'recipe_id': 'recipe_id',
 'cassette_id': 'cassette_id',
 'aoi': 'cell_aoi',
 'total_defect_qty': 'cell_total_defect_cnt',
 'line_id': 'cell_line_id',
 'pi_time': 'pi_time',
 'pi_type': 'cell_op'
}


"""

"""

In [4]:
{
'sheet_id_chip_id': 'sheet_id', 
'line_id': 'line_id', 
'test_time': 'test_time',  
'model_no': 'model_no',  
'abbr_cat': 'abbr_cat', 
'recipe_id': 'recipe_id', 
'cassette_id': 'cassette_id', 
'aoi': 'aoi',  
'total_defect_qty': 'total_defect_qty', 
'pi_time': 'pi_time',  
'pi_type': 'pi_type', 

}.keys()

dict_keys(['sheet_id_chip_id', 'line_id', 'test_time', 'model_no', 'abbr_cat', 'recipe_id', 'cassette_id', 'aoi', 'total_defect_qty', 'pi_time', 'pi_type'])

In [3]:
df.columns

Index(['sheet_id_chip_id', 'test_time', 'model_no', 'op_id', 'abbr_cat',
       'recipe_id', 'cassette_id', 'aoi', 'total_defect_qty',
       'defect_size_o_qty', 'defect_size_l_qty', 'defect_size_m_qty',
       'defect_size_s_qty', 'line_id', 'pi_time', 'pi_hour', 'pi_type'],
      dtype='object')

In [2]:
db = MySQLConnet('cim_piaoi')
#db.list_tables()
df = db.get_table('cim_pi_glass_202606')
df.head()

,sheet_id_chip_id,test_time,model_no,op_id,abbr_cat,recipe_id,cassette_id,aoi,total_defect_qty,defect_size_o_qty,defect_size_l_qty,defect_size_m_qty,defect_size_s_qty,line_id,pi_time,pi_hour,pi_type
0,AL5H151Z3K,2026-05-31 19:09:01,G215HVN01_VG,PI AOI,CF,608,CA0376,CAPIT203,172,0,3,16,153,CAPIC200,2026-06-01 00:33:11,2026-06-01 00:00:00,BPI
1,AL5H151Z3G,2026-05-31 19:13:11,G215HVN01_VG,PI AOI,CF,608,CA0376,CAPIT203,167,0,1,8,158,CAPIC200,2026-06-01 00:33:11,2026-06-01 00:00:00,BPI
2,AL5H151Z3M,2026-05-31 19:17:19,G215HVN01_VG,PI AOI,CF,608,CA0376,CAPIT203,155,0,4,12,139,CAPIC200,2026-06-01 00:33:11,2026-06-01 00:00:00,BPI
3,AL5H151Z3A,2026-05-31 19:21:22,G215HVN01_VG,PI AOI,CF,608,CA0376,CAPIT203,181,1,11,23,146,CAPIC200,2026-06-01 00:33:11,2026-06-01 00:00:00,BPI
4,YH6A5U84G,2026-06-01 00:35:12,B160UAV01,PCS1,TFT,2283,CA0364,CAAOI202,23,0,0,7,16,CAPIC400,2026-06-01 00:13:18,2026-05-31 23:00:00,API

In [15]:
from .. density.API_Config import API_Config
def _recipe_family(recipe_id: object) -> str:
    """
    依 recipe_id 粗分頁籤用途。
    """
    s = "" if recipe_id is None else str(recipe_id).strip()

    if len(s) == 4:
        if s.startswith("2"):
            return "UPI"
        if s.startswith("0"):
            return "PISpot_SPS"

    if len(s) == 3:
        return "ALL"

    return ""


def _add_router_total_density(clean_df: pd.DataFrame, api_cfg: API_Config) -> pd.DataFrame:
    """
    在 router 端重算 Total defect count / Total glass count / Total density。

    計算語意：
      1. 後端 density_summary 是 per recipe_id + per adc_def_code。
      2. 先在 recipe 粒度上去除同 recipe 多 defect code 造成的 glass_cnt 重複。
      3. 再依 tab family 聚合 total。
      4. merge 回原本每一列，讓前端直接取用。
    """
    if clean_df is None or clean_df.empty:
        clean_df = clean_df.copy()
        clean_df["total_defect_cnt"] = 0
        clean_df["total_glass_cnt"] = 0
        clean_df["total_density"] = 0.0
        return clean_df

    df = clean_df.copy()

    base_keys = ["pi_hour", "line_id", "aoi", "model", "glass_type"]
    recipe_keys = base_keys + ["recipe_id"]

    need_cols = set(base_keys + ["recipe_id", "adc_def_code", "glass_cnt", "defect_cnt"])
    miss = [c for c in need_cols if c not in df.columns]
    if miss:
        df["total_defect_cnt"] = 0
        df["total_glass_cnt"] = 0
        df["total_density"] = 0.0
        return df

    df["recipe_family"] = df["recipe_id"].apply(_recipe_family)

    df["glass_cnt"] = pd.to_numeric(df["glass_cnt"], errors="coerce").fillna(0)
    df["defect_cnt"] = pd.to_numeric(df["defect_cnt"], errors="coerce").fillna(0)

    # per recipe 去重 glass_cnt，避免同一 recipe 下多 defect code 重複加總 glass_cnt
    recipe_base = (
        df.groupby(recipe_keys + ["recipe_family"], dropna=False)
          .agg(
              recipe_total_glass_cnt=("glass_cnt", "max"),
              recipe_total_defect_cnt=("defect_cnt", "sum"),
          )
          .reset_index()
    )

    # UPI
    upi_base = recipe_base[recipe_base["recipe_family"].isin(["UPI", "ALL"])].copy()
    upi_total = (
        upi_base.groupby(base_keys, dropna=False)
                .agg(
                    total_glass_cnt=("recipe_total_glass_cnt", "sum"),
                    total_defect_cnt=("recipe_total_defect_cnt", "sum"),
                )
                .reset_index()
    )
    upi_total["recipe_family"] = "UPI"

    # PISpot / SPS：目前你的 recipe 規則兩者共用 0xxx + 3碼
    pis_sps_base = recipe_base[recipe_base["recipe_family"].isin(["PISpot_SPS", "ALL"])].copy()
    pis_sps_total = (
        pis_sps_base.groupby(base_keys, dropna=False)
                    .agg(
                        total_glass_cnt=("recipe_total_glass_cnt", "sum"),
                        total_defect_cnt=("recipe_total_defect_cnt", "sum"),
                    )
                    .reset_index()
    )
    pis_sps_total["recipe_family"] = "PISpot_SPS"

    total_df = pd.concat([upi_total, pis_sps_total], ignore_index=True)

    if total_df.empty:
        df["total_defect_cnt"] = 0
        df["total_glass_cnt"] = 0
        df["total_density"] = 0.0
        return df.drop(columns=["recipe_family"], errors="ignore")

    total_df["total_density"] = (
        total_df["total_defect_cnt"] /
        total_df["total_glass_cnt"].replace(0, pd.NA)
    ).fillna(0).round(3)

    df = df.merge(
        total_df,
        on=base_keys + ["recipe_family"],
        how="left"
    )

    df["total_defect_cnt"] = df["total_defect_cnt"].fillna(0)
    df["total_glass_cnt"] = df["total_glass_cnt"].fillna(0)
    df["total_density"] = df["total_density"].fillna(0.0)

    return df.drop(columns=["recipe_family"], errors="ignore")

ImportError: attempted relative import with no known parent package

In [ ]:
db = MySQLConnet('piaoi_density')
#db.list_tables()
#df = db.get_table('rtms_aoi300_raw_202605')
tbn = 'density_code_summary_202605'
#df = db.get_runs_between(tbn,  '2026-05-02', '2026-05-05', time_col="pi_hour")
df = db.get_rows(tbn, {'line_id': 'CAPIC400',  'model': 'B160UAV01', 'adc_def_code':'NPI_TFT'})
pd.DataFrame(df)#['adc_def_code'].unique()

,line_id,aoi,model,glass_type,pi_hour,recipe_id,adc_def_code,recipe_total_glass_cnt,recipe_total_defect_cnt,recipe_total_density,...,small_defect_count,middle_defect_count,large_defect_count,over_defect_count,glass,glass_size_detail,comment,action,Editor,modify_time
0,CAPIC400,aoi200,B160UAV01,TFT,2026-05-31 06:00:00,2283,NPI_TFT,3,92,30.667,...,1,4,0,0,"YH6A5VF1G,YH6A5VF1H,YH6A5VF1J","{""YH6A5VF1G"": {""S"": 0, ""M"": 1, ""L"": 0, ""O"": 0,...",,,,2026-06-01 07:05:17
1,CAPIC400,aoi200,B160UAV01,TFT,2026-05-31 06:00:00,0283,NPI_TFT,3,608,202.667,...,20,0,0,0,"YH6A5VF1G,YH6A5VF1H,YH6A5VF1J","{""YH6A5VF1G"": {""S"": 13, ""M"": 0, ""L"": 0, ""O"": 0...",,,,2026-06-01 07:05:17
2,CAPIC400,aoi200,B160UAV01,TFT,2026-05-31 13:00:00,4283,NPI_TFT,7,1614,230.571,...,46,21,3,0,"YH6A5U88A,YH6A5U88B,YH6A5U88C,YH6A5U88D,YH6A5U...","{""YH6A5U88A"": {""S"": 3, ""M"": 7, ""L"": 0, ""O"": 0,...",,,,2026-06-01 13:35:13
3,CAPIC400,aoi200,B160UAV01,TFT,2026-05-31 16:00:00,2283,NPI_TFT,7,209,29.857,...,10,11,0,0,"YH6A5VF7A,YH6A5VF7B,YH6A5VF7C,YH6A5VF7D,YH6A5V...","{""YH6A5VF7A"": {""S"": 1, ""M"": 1, ""L"": 0, ""O"": 0,...",,,,2026-06-01 16:45:17
4,CAPIC400,aoi200,B160UAV01,TFT,2026-05-31 16:00:00,0283,NPI_TFT,7,902,128.857,...,59,4,0,0,"YH6A5VF7A,YH6A5VF7B,YH6A5VF7C,YH6A5VF7D,YH6A5V...","{""YH6A5VF7A"": {""S"": 7, ""M"": 0, ""L"": 0, ""O"": 0,...",,,,2026-06-01 16:45:17
5,CAPIC400,aoi200,B160UAV01,TFT,2026-05-31 20:00:00,2283,NPI_TFT,7,162,23.143,...,11,4,0,0,"YH6A5UA1A,YH6A5UA1B,YH6A5UA1C,YH6A5UA1D,YH6A5U...","{""YH6A5UA1A"": {""S"": 0, ""M"": 0, ""L"": 0, ""O"": 0,...",,,,2026-06-01 20:45:09
6,CAPIC400,aoi200,B160UAV01,TFT,2026-05-31 20:00:00,0283,NPI_TFT,7,1169,167.000,...,76,5,0,0,"YH6A5UA1A,YH6A5UA1B,YH6A5UA1C,YH6A5UA1D,YH6A5U...","{""YH6A5UA1A"": {""S"": 0, ""M"": 0, ""L"": 0, ""O"": 0,...",,,,2026-06-01 20:45:09

In [ ]:
df[(df['aoi'] =='aoi100' )& (df['model'] == 'G215HVN01') ] # & (df['pi_hour'] == '2026-05-05 10:00:00')

Empty DataFrame
Columns: [line_id, aoi, model, glass_type, recipe_id, pi_hour, adc_def_code, defect_cnt, glass_cnt, density, def_glass_cnt, small_defect_count, middle_defect_count, large_defect_count, over_defect_count, glass, glass_size_detail, shift, comment, action, Editor, modify_time]
Index: []

[0 rows x 22 columns]

In [ ]:
db = MySQLConnet('rtms_piaoi_other')
db.list_tables()
df = db.get_table('rtms_aoi300_raw_202605')

#df['defect_size'].unique()

2026-05-05 11:46:03,167 - INFO - [list_tables] 成功取得資料表名稱，共 4 張表。

In [ ]:
rows = df[df['sheet_id_chip_id'] =='ZG6A5N17C']
print(len(rows))
rows['test_time'].unique()
rows.iloc[0].to_dict()

191

{'id': 4964,
 'sheet_id_chip_id': 'ZG6A5N17C',
 'chip_id': 'ZG6A5N17C2',
 'test_time': Timestamp('2026-05-04 16:21:16'),
 'defect_size': 'S',
 'size_class': '6',
 'pox_x1': 310572,
 'pox_y1': 1035260,
 'adc_def_code': '',
 'retype_def_code': '',
 'image_file_name': 'CAAOI300.M270QAN06.M270QAN06-T-API-260225.CA020601.ZG6A5N17C.1.bt5.1777882876.jpg',
 'img_file_url_path': 'PIT/2605/04/CAAOI300/ZG6A5N17C/1621/',
 'pic_path': 'http://10.97.139.98:1454/CAAOI300/CA020601/ZG6A5N17C/PCS1/58703/CaptureImage/small/CAAOI300.M270QAN06.M270QAN06-T-API-260225.CA020601.ZG6A5N17C.1.bt5.1777882876.jpg',
 'recipe_id': 'M270QAN06-T-API-260225',
 'line_id': 'Null',
 'aoi': 'aoi300',
 'model': 'M270QAN06',
 'glass_type': 'TFT',
 'pi_time': NaT,
 'pi_type': 'API',
 'cst_id': 'CA020601',
 'defect_count': 190,
 'defect_id': '1',
 'source_file': 'CAAOI300.M270QAN06.M270QAN06-T-API-260225.CA020601.ZG6A5N17C.58703.defect',
 'source_mtime': Timestamp('2026-05-04 16:23:27'),
 'update_time': Timestamp('2026-05-05 08:03:49')}

In [ ]:
df['recipe_id'].unique()

array(['M270DAN7F-T-API', 'M270QAN06-T-API-260225',
       'B160UAN4A-T-API-20260203', 'B180UAN01-T-API-260405',
       'M270QAN07-T-API_260410', 'M340QAR1B-T-API-060206',
       'M270TAN2Z-T-API-260416', 'M270HAN03-T-API', 'M270HAN1C-T-API',
       'B140UAN04-T-API', 'CELL-ITO', 'M215HAN01-T-API-060204',
       'B160UAN4A-T-BPI'], dtype=object)

In [ ]:
cols = ['aoi', 'test_time', 'glass_type', 'glass_type', 'defect_count'] #same gld
for (gld,  ) , rows in df.groupby(['sheet_id_chip_id']):
    print(gld, len(rows))
    print(rows[cols])

MQ6A5TK12 4
        aoi           test_time glass_type glass_type  defect_count
368  aoi300 2026-05-02 08:30:45        ITO        ITO             0
369  aoi300 2026-05-02 08:30:45        ITO        ITO             0
370  aoi300 2026-05-02 08:30:45        ITO        ITO             0
371  aoi300 2026-05-02 08:30:45        ITO        ITO             0
MQ6A5TK13 4
        aoi           test_time glass_type glass_type  defect_count
372  aoi300 2026-05-02 08:26:03        ITO        ITO             0
373  aoi300 2026-05-02 08:26:03        ITO        ITO             0
374  aoi300 2026-05-02 08:26:03        ITO        ITO             0
375  aoi300 2026-05-02 08:26:03        ITO        ITO             0
MQ6A5TK14 4
        aoi           test_time glass_type glass_type  defect_count
376  aoi300 2026-05-02 08:21:10        ITO        ITO             0
377  aoi300 2026-05-02 08:21:10        ITO        ITO             0
378  aoi300 2026-05-02 08:21:10        ITO        ITO             0
379  aoi300 2026-05-02 08:21:10        ITO        ITO             0
MQ6A5U901 4
        aoi           test_time glass_type glass_type  defect_count
236  aoi300 2026-05-03 19:37:04        ITO        ITO             0
237  aoi300 2026-05-03 19:37:04        ITO        ITO             0
238  aoi300 2026-05-03 19:37:04        ITO        ITO             0
239  aoi300 2026-05-03 19:37:04        ITO        ITO             0
MQ6A5U902 4
        aoi           test_time glass_type glass_type  defect_count
240  aoi300 2026-05-03 19:32:22        ITO        ITO             0
241  aoi300 2026-05-03 19:32:22        ITO        ITO             0
242  aoi300 2026-05-03 19:32:22        ITO        ITO             0
243  aoi300 2026-05-03 19:32:22        ITO        ITO             0
MQ6A5U903 4
        aoi           test_time glass_type glass_type  defect_count
244  aoi300 2026-05-03 19:27:30        ITO        ITO             0
245  aoi300 2026-05-03 19:27:30        ITO        ITO             0
246  aoi300 2026-05-03 19:27:30        ITO        ITO             0
247  aoi300 2026-05-03 19:27:30        ITO        ITO             0
MQ6A5U904 4
        aoi           test_time glass_type glass_type  defect_count
248  aoi300 2026-05-03 19:22:45        ITO        ITO             0
249  aoi300 2026-05-03 19:22:45        ITO        ITO             0
250  aoi300 2026-05-03 19:22:45        ITO        ITO             0
251  aoi300 2026-05-03 19:22:45        ITO        ITO             0
MQ6A5U90L 4
       aoi           test_time glass_type glass_type  defect_count
88  aoi300 2026-05-02 10:37:32        ITO        ITO             0
89  aoi300 2026-05-02 10:37:32        ITO        ITO             0
90  aoi300 2026-05-02 10:37:32        ITO        ITO             0
91  aoi300 2026-05-02 10:37:32        ITO        ITO             0
MQ6A5U90M 4
       aoi           test_time glass_type glass_type  defect_count
92  aoi300 2026-05-02 10:32:48        ITO        ITO             0
93  aoi300 2026-05-02 10:32:48        ITO        ITO             0
94  aoi300 2026-05-02 10:32:48        ITO        ITO             0
95  aoi300 2026-05-02 10:32:48        ITO        ITO             0
MQ6A5U90N 4
       aoi           test_time glass_type glass_type  defect_count
64  aoi300 2026-05-02 17:30:02        ITO        ITO             0
65  aoi300 2026-05-02 17:30:02        ITO        ITO             0
66  aoi300 2026-05-02 17:30:02        ITO        ITO             0
67  aoi300 2026-05-02 17:30:02        ITO        ITO             0
MQ6A5U90P 4
       aoi           test_time glass_type glass_type  defect_count
68  aoi300 2026-05-02 17:25:11        ITO        ITO             0
69  aoi300 2026-05-02 17:25:11        ITO        ITO             0
70  aoi300 2026-05-02 17:25:11        ITO        ITO             0
71  aoi300 2026-05-02 17:25:11        ITO        ITO             0
MQ6A5U90Q 4
        aoi           test_time glass_type glass_type  defect_count
404  aoi300 2026-05-02 21:05:11        ITO        ITO             0
405  aoi300 2026-05-02 21:05:11        ITO        ITO             0
406  aoi300 2026-05-02 21:05:11        ITO        ITO             0
407  aoi300 2026-05-02 21:05:11        ITO        ITO             0
MQ6A5U90R 4
        aoi           test_time glass_type glass_type  defect_count
408  aoi300 2026-05-02 21:00:21        ITO        ITO             0
409  aoi300 2026-05-02 21:00:21        ITO        ITO             0
410  aoi300 2026-05-02 21:00:21        ITO        ITO             0
411  aoi300 2026-05-02 21:00:21        ITO        ITO             0
MQ6A5U90S 4
        aoi           test_time glass_type glass_type  defect_count
412  aoi300 2026-05-02 20:50:47        ITO        ITO             0
413  aoi300 2026-05-02 20:50:47        ITO        ITO             0
414  aoi300 2026-05-02 20:50:47        ITO        ITO             0
415  aoi300 2026-05-02 20:50:47        ITO        ITO             0
MQ6A5U90T 4
        aoi           test_time glass_type glass_type  defect_count
416  aoi300 2026-05-02 20:55:39        ITO        ITO             0
417  aoi300 2026-05-02 20:55:39        ITO        ITO             0
418  aoi300 2026-05-02 20:55:39        ITO        ITO             0
419  aoi300 2026-05-02 20:55:39        ITO        ITO             0
MQ6A5U90U 4
        aoi           test_time glass_type glass_type  defect_count
476  aoi300 2026-05-02 21:14:46        ITO        ITO             0
477  aoi300 2026-05-02 21:14:46        ITO        ITO             0
478  aoi300 2026-05-02 21:14:46        ITO        ITO             0
479  aoi300 2026-05-02 21:14:46        ITO        ITO             0
MQ6A5U90V 4
        aoi           test_time glass_type glass_type  defect_count
480  aoi300 2026-05-02 21:10:03        ITO        ITO             0
481  aoi300 2026-05-02 21:10:03        ITO        ITO             0
482  aoi300 2026-05-02 21:10:03        ITO        ITO             0
483  aoi300 2026-05-02 21:10:03        ITO        ITO             0
MQ6A5U90W 4
        aoi           test_time glass_type glass_type  defect_count
344  aoi300 2026-05-03 05:29:10        ITO        ITO             0
345  aoi300 2026-05-03 05:29:10        ITO        ITO             0
346  aoi300 2026-05-03 05:29:10        ITO        ITO             0
347  aoi300 2026-05-03 05:29:10        ITO        ITO             0
MQ6A5U90X 4
        aoi           test_time glass_type glass_type  defect_count
348  aoi300 2026-05-03 05:24:27        ITO        ITO             0
349  aoi300 2026-05-03 05:24:27        ITO        ITO             0
350  aoi300 2026-05-03 05:24:27        ITO        ITO             0
351  aoi300 2026-05-03 05:24:27        ITO        ITO             0
MQ6A5U90Y 4
        aoi           test_time glass_type glass_type  defect_count
204  aoi300 2026-05-03 13:00:12        ITO        ITO             0
205  aoi300 2026-05-03 13:00:12        ITO        ITO             0
206  aoi300 2026-05-03 13:00:12        ITO        ITO             0
207  aoi300 2026-05-03 13:00:12        ITO        ITO             0
MQ6A5U90Z 4
        aoi           test_time glass_type glass_type  defect_count
208  aoi300 2026-05-03 12:55:29        ITO        ITO             0
209  aoi300 2026-05-03 12:55:29        ITO        ITO             0
210  aoi300 2026-05-03 12:55:29        ITO        ITO             0
211  aoi300 2026-05-03 12:55:29        ITO        ITO             0
MQ6A5U911 4
        aoi           test_time glass_type glass_type  defect_count
296  aoi300 2026-05-03 08:01:37        ITO        ITO             0
297  aoi300 2026-05-03 08:01:37        ITO        ITO             0
298  aoi300 2026-05-03 08:01:37        ITO        ITO             0
299  aoi300 2026-05-03 08:01:37        ITO        ITO             0
MQ6A5U912 4
        aoi           test_time glass_type glass_type  defect_count
448  aoi300 2026-05-03 12:37:01        ITO        ITO             0
449  aoi300 2026-05-03 12:37:01        ITO        ITO             0
450  aoi300 2026-05-03 12:37:01        ITO        ITO             0
451  aoi300 2026-05-03 12:37:01        ITO        ITO             0
MQ6A5U913 4
        aoi           test_time glass_type glass_type  defect_count
452  aoi300 2026-05-03 12:32:17        ITO        ITO             0
453  aoi300 2026-05-03 12:32:17        ITO        ITO             0
454  aoi300 2026-05-03 12:32:17        ITO        ITO             0
455  aoi300 2026-05-03 12:32:17        ITO        ITO             0
MQ6A5U914 4
        aoi           test_time glass_type glass_type  defect_count
456  aoi300 2026-05-03 12:27:35        ITO        ITO             0
457  aoi300 2026-05-03 12:27:35        ITO        ITO             0
458  aoi300 2026-05-03 12:27:35        ITO        ITO             0
459  aoi300 2026-05-03 12:27:35        ITO        ITO             0
MQ6A5U91E 4
        aoi           test_time glass_type glass_type  defect_count
328  aoi300 2026-05-02 08:49:52        ITO        ITO             0
329  aoi300 2026-05-02 08:49:52        ITO        ITO             0
330  aoi300 2026-05-02 08:49:52        ITO        ITO             0
331  aoi300 2026-05-02 08:49:52        ITO        ITO             0
MQ6A5U91F 4
        aoi           test_time glass_type glass_type  defect_count
332  aoi300 2026-05-02 08:45:06        ITO        ITO             0
333  aoi300 2026-05-02 08:45:06        ITO        ITO             0
334  aoi300 2026-05-02 08:45:06        ITO        ITO             0
335  aoi300 2026-05-02 08:45:06        ITO        ITO             0
MQ6A5U91G 4
        aoi           test_time glass_type glass_type  defect_count
336  aoi300 2026-05-02 08:40:22        ITO        ITO             0
337  aoi300 2026-05-02 08:40:22        ITO        ITO             0
338  aoi300 2026-05-02 08:40:22        ITO        ITO             0
339  aoi300 2026-05-02 08:40:22        ITO        ITO             0
MQ6A5U91H 4
        aoi           test_time glass_type glass_type  defect_count
340  aoi300 2026-05-02 08:35:31        ITO        ITO             0
341  aoi300 2026-05-02 08:35:31        ITO        ITO             0
342  aoi300 2026-05-02 08:35:31        ITO        ITO             0
343  aoi300 2026-05-02 08:35:31        ITO        ITO             0
MQ6A5U91J 4
        aoi           test_time glass_type glass_type  defect_count
352  aoi300 2026-05-02 17:39:12        ITO        ITO             0
353  aoi300 2026-05-02 17:39:12        ITO        ITO             0
354  aoi300 2026-05-02 17:39:12        ITO        ITO             0
355  aoi300 2026-05-02 17:39:12        ITO        ITO             0
MQ6A5U91K 4
        aoi           test_time glass_type glass_type  defect_count
356  aoi300 2026-05-02 17:34:45        ITO        ITO             0
357  aoi300 2026-05-02 17:34:45        ITO        ITO             0
358  aoi300 2026-05-02 17:34:45        ITO        ITO             0
359  aoi300 2026-05-02 17:34:45        ITO        ITO             0
MQ6A5U91L 4
        aoi           test_time glass_type glass_type  defect_count
104  aoi300 2026-05-02 18:57:45        ITO        ITO             0
105  aoi300 2026-05-02 18:57:45        ITO        ITO             0
106  aoi300 2026-05-02 18:57:45        ITO        ITO             0
107  aoi300 2026-05-02 18:57:45        ITO        ITO             0
MQ6A5U91M 4
        aoi           test_time glass_type glass_type  defect_count
108  aoi300 2026-05-02 18:53:02        ITO        ITO             0
109  aoi300 2026-05-02 18:53:02        ITO        ITO             0
110  aoi300 2026-05-02 18:53:02        ITO        ITO             0
111  aoi300 2026-05-02 18:53:02        ITO        ITO             0
MQ6A5U91N 4
        aoi           test_time glass_type glass_type  defect_count
196  aoi300 2026-05-02 22:08:59        ITO        ITO             0
197  aoi300 2026-05-02 22:08:59        ITO        ITO             0
198  aoi300 2026-05-02 22:08:59        ITO        ITO             0
199  aoi300 2026-05-02 22:08:59        ITO        ITO             0
MQ6A5U91P 4
        aoi           test_time glass_type glass_type  defect_count
200  aoi300 2026-05-02 22:04:07        ITO        ITO             0
201  aoi300 2026-05-02 22:04:07        ITO        ITO             0
202  aoi300 2026-05-02 22:04:07        ITO        ITO             0
203  aoi300 2026-05-02 22:04:07        ITO        ITO             0
MQ6A5U91Q 4
        aoi           test_time glass_type glass_type  defect_count
268  aoi300 2026-05-03 02:34:27        ITO        ITO             0
269  aoi300 2026-05-03 02:34:27        ITO        ITO             0
270  aoi300 2026-05-03 02:34:27        ITO        ITO             0
271  aoi300 2026-05-03 02:34:27        ITO        ITO             0
MQ6A5U91R 4
        aoi           test_time glass_type glass_type  defect_count
272  aoi300 2026-05-03 02:29:26        ITO        ITO             0
273  aoi300 2026-05-03 02:29:26        ITO        ITO             0
274  aoi300 2026-05-03 02:29:26        ITO        ITO             0
275  aoi300 2026-05-03 02:29:26        ITO        ITO             0
MQ6A5U91S 4
        aoi           test_time glass_type glass_type  defect_count
276  aoi300 2026-05-03 02:25:00        ITO        ITO             0
277  aoi300 2026-05-03 02:25:00        ITO        ITO             0
278  aoi300 2026-05-03 02:25:00        ITO        ITO             0
279  aoi300 2026-05-03 02:25:00        ITO        ITO             0
MQ6A5U91T 4
       aoi           test_time glass_type glass_type  defect_count
80  aoi300 2026-05-03 02:20:09        ITO        ITO             0
81  aoi300 2026-05-03 02:20:09        ITO        ITO             0
82  aoi300 2026-05-03 02:20:09        ITO        ITO             0
83  aoi300 2026-05-03 02:20:09        ITO        ITO             0
MQ6A5U91U 4
       aoi           test_time glass_type glass_type  defect_count
84  aoi300 2026-05-03 02:15:24        ITO        ITO             0
85  aoi300 2026-05-03 02:15:24        ITO        ITO             0
86  aoi300 2026-05-03 02:15:24        ITO        ITO             0
87  aoi300 2026-05-03 02:15:24        ITO        ITO             0
MQ6A5U91V 4
        aoi           test_time glass_type glass_type  defect_count
220  aoi300 2026-05-03 07:36:11        ITO        ITO             0
221  aoi300 2026-05-03 07:36:11        ITO        ITO             0
222  aoi300 2026-05-03 07:36:11        ITO        ITO             0
223  aoi300 2026-05-03 07:36:11        ITO        ITO             0
MQ6A5U91W 4
        aoi           test_time glass_type glass_type  defect_count
224  aoi300 2026-05-03 07:31:27        ITO        ITO             0
225  aoi300 2026-05-03 07:31:27        ITO        ITO             0
226  aoi300 2026-05-03 07:31:27        ITO        ITO             0
227  aoi300 2026-05-03 07:31:27        ITO        ITO             0
MQ6A5U91X 4
        aoi           test_time glass_type glass_type  defect_count
228  aoi300 2026-05-03 07:26:44        ITO        ITO             0
229  aoi300 2026-05-03 07:26:44        ITO        ITO             0
230  aoi300 2026-05-03 07:26:44        ITO        ITO             0
231  aoi300 2026-05-03 07:26:44        ITO        ITO             0
MQ6A5U91Y 4
        aoi           test_time glass_type glass_type  defect_count
232  aoi300 2026-05-03 07:21:52        ITO        ITO             0
233  aoi300 2026-05-03 07:21:52        ITO        ITO             0
234  aoi300 2026-05-03 07:21:52        ITO        ITO             0
235  aoi300 2026-05-03 07:21:52        ITO        ITO             0
MQ6A5U91Z 4
        aoi           test_time glass_type glass_type  defect_count
300  aoi300 2026-05-03 08:06:20        ITO        ITO             0
301  aoi300 2026-05-03 08:06:20        ITO        ITO             0
302  aoi300 2026-05-03 08:06:20        ITO        ITO             0
303  aoi300 2026-05-03 08:06:20        ITO        ITO             0
MQ6A5UC2A 4
        aoi           test_time glass_type glass_type  defect_count
360  aoi300 2026-05-03 17:54:24        ITO        ITO             0
361  aoi300 2026-05-03 17:54:24        ITO        ITO             0
362  aoi300 2026-05-03 17:54:24        ITO        ITO             0
363  aoi300 2026-05-03 17:54:24        ITO        ITO             0
MQ6A5UC2B 4
        aoi           test_time glass_type glass_type  defect_count
364  aoi300 2026-05-03 17:49:40        ITO        ITO             0
365  aoi300 2026-05-03 17:49:40        ITO        ITO             0
366  aoi300 2026-05-03 17:49:40        ITO        ITO             0
367  aoi300 2026-05-03 17:49:40        ITO        ITO             0
MQ6A5UC2C 4
        aoi           test_time glass_type glass_type  defect_count
440  aoi300 2026-05-03 23:39:27        ITO        ITO             0
441  aoi300 2026-05-03 23:39:27        ITO        ITO             0
442  aoi300 2026-05-03 23:39:27        ITO        ITO             0
443  aoi300 2026-05-03 23:39:27        ITO        ITO             0
MQ6A5UC2D 4
        aoi           test_time glass_type glass_type  defect_count
444  aoi300 2026-05-03 23:35:00        ITO        ITO             0
445  aoi300 2026-05-03 23:35:00        ITO        ITO             0
446  aoi300 2026-05-03 23:35:00        ITO        ITO             0
447  aoi300 2026-05-03 23:35:00        ITO        ITO             0
MQ6A5UC2E 4
        aoi           test_time glass_type glass_type  defect_count
420  aoi300 2026-05-03 23:56:57        ITO        ITO             0
421  aoi300 2026-05-03 23:56:57        ITO        ITO             0
422  aoi300 2026-05-03 23:56:57        ITO        ITO             0
423  aoi300 2026-05-03 23:56:57        ITO        ITO             0
MQ6A5UC2F 4
        aoi           test_time glass_type glass_type  defect_count
424  aoi300 2026-05-03 23:52:15        ITO        ITO             0
425  aoi300 2026-05-03 23:52:15        ITO        ITO             0
426  aoi300 2026-05-03 23:52:15        ITO        ITO             0
427  aoi300 2026-05-03 23:52:15        ITO        ITO             0
MQ6A5UC2G 4
        aoi           test_time glass_type glass_type  defect_count
428  aoi300 2026-05-03 23:47:23        ITO        ITO             0
429  aoi300 2026-05-03 23:47:23        ITO        ITO             0
430  aoi300 2026-05-03 23:47:23        ITO        ITO             0
431  aoi300 2026-05-03 23:47:23        ITO        ITO             0
MQ6A5UC2H 4
        aoi           test_time glass_type glass_type  defect_count
460  aoi300 2026-05-04 01:30:50        ITO        ITO             0
461  aoi300 2026-05-04 01:30:50        ITO        ITO             0
462  aoi300 2026-05-04 01:30:50        ITO        ITO             0
463  aoi300 2026-05-04 01:30:50        ITO        ITO             0
MQ6A5UC2J 4
        aoi           test_time glass_type glass_type  defect_count
464  aoi300 2026-05-04 01:25:58        ITO        ITO             0
465  aoi300 2026-05-04 01:25:58        ITO        ITO             0
466  aoi300 2026-05-04 01:25:58        ITO        ITO             0
467  aoi300 2026-05-04 01:25:58        ITO        ITO             0
MQ6A5UC2K 4
        aoi           test_time glass_type glass_type  defect_count
212  aoi300 2026-05-04 02:54:46        ITO        ITO             0
213  aoi300 2026-05-04 02:54:46        ITO        ITO             0
214  aoi300 2026-05-04 02:54:46        ITO        ITO             0
215  aoi300 2026-05-04 02:54:46        ITO        ITO             0
MQ6A5UC2L 4
        aoi           test_time glass_type glass_type  defect_count
216  aoi300 2026-05-04 02:49:53        ITO        ITO             0
217  aoi300 2026-05-04 02:49:53        ITO        ITO             0
218  aoi300 2026-05-04 02:49:53        ITO        ITO             0
219  aoi300 2026-05-04 02:49:53        ITO        ITO             0
MQ6A5UC2M 4
        aoi           test_time glass_type glass_type  defect_count
312  aoi300 2026-05-04 04:41:40        ITO        ITO             0
313  aoi300 2026-05-04 04:41:40        ITO        ITO             0
314  aoi300 2026-05-04 04:41:40        ITO        ITO             0

In [ ]:
db.get_rows('rtms_aoi300_raw_202604',{'defect_size': 'OK'})

[{'id': 17860074,
  'sheet_id_chip_id': 'MQ6A5PN71',
  'chip_id': 'MQ6A5PN710',
  'test_time': datetime.datetime(2026, 4, 24, 13, 7, 26),
  'defect_size': 'OK',
  'size_class': '0',
  'pox_x1': 0,
  'pox_y1': 0,
  'adc_def_code': '',
  'retype_def_code': '',
  'image_file_name': 'CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN71.GlassImage_modality5.bm.1777007246.jpg',
  'img_file_url_path': 'PIT/2604/24/CAAOI300/MQ6A5PN71/1307/Map/',
  'pic_path': 'http://10.97.139.98:1454/CAAOI300/CA002001/MQ6A5PN71/PCS1/47086/Map/CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN71.GlassImage_modality5.bm.1777007246.jpg',
  'recipe_id': 'CELL-ITO',
  'line_id': 'Null',
  'aoi': 'aoi300',
  'model': 'CELL-ITO',
  'glass_type': 'ITO',
  'pi_time': None,
  'pi_type': 'CELL-ITO',
  'cst_id': 'CA002001',
  'defect_count': 0,
  'defect_id': 'MACRO_1',
  'source_file': 'CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN71.47086.defect',
  'source_mtime': datetime.datetime(2026, 4, 24, 13, 9, 27),
  'update_time': datetime.datetime(2026, 4, 27, 9, 0, 49)},
 {'id': 17860075,
  'sheet_id_chip_id': 'MQ6A5PN71',
  'chip_id': 'MQ6A5PN710',
  'test_time': datetime.datetime(2026, 4, 24, 13, 7, 26),
  'defect_size': 'OK',
  'size_class': '0',
  'pox_x1': 0,
  'pox_y1': 0,
  'adc_def_code': '',
  'retype_def_code': '',
  'image_file_name': 'CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN71.GlassImage_modality6.bm.1777007246.jpg',
  'img_file_url_path': 'PIT/2604/24/CAAOI300/MQ6A5PN71/1307/Map/',
  'pic_path': 'http://10.97.139.98:1454/CAAOI300/CA002001/MQ6A5PN71/PCS1/47086/Map/CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN71.GlassImage_modality6.bm.1777007246.jpg',
  'recipe_id': 'CELL-ITO',
  'line_id': 'Null',
  'aoi': 'aoi300',
  'model': 'CELL-ITO',
  'glass_type': 'ITO',
  'pi_time': None,
  'pi_type': 'CELL-ITO',
  'cst_id': 'CA002001',
  'defect_count': 0,
  'defect_id': 'MACRO_2',
  'source_file': 'CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN71.47086.defect',
  'source_mtime': datetime.datetime(2026, 4, 24, 13, 9, 27),
  'update_time': datetime.datetime(2026, 4, 27, 9, 0, 49)},
 {'id': 17860076,
  'sheet_id_chip_id': 'MQ6A5PN71',
  'chip_id': 'MQ6A5PN710',
  'test_time': datetime.datetime(2026, 4, 24, 13, 7, 26),
  'defect_size': 'OK',
  'size_class': '0',
  'pox_x1': 0,
  'pox_y1': 0,
  'adc_def_code': '',
  'retype_def_code': '',
  'image_file_name': 'CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN71.GlassImage_modality7.bm.1777007246.jpg',
  'img_file_url_path': 'PIT/2604/24/CAAOI300/MQ6A5PN71/1307/Map/',
  'pic_path': 'http://10.97.139.98:1454/CAAOI300/CA002001/MQ6A5PN71/PCS1/47086/Map/CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN71.GlassImage_modality7.bm.1777007246.jpg',
  'recipe_id': 'CELL-ITO',
  'line_id': 'Null',
  'aoi': 'aoi300',
  'model': 'CELL-ITO',
  'glass_type': 'ITO',
  'pi_time': None,
  'pi_type': 'CELL-ITO',
  'cst_id': 'CA002001',
  'defect_count': 0,
  'defect_id': 'MACRO_3',
  'source_file': 'CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN71.47086.defect',
  'source_mtime': datetime.datetime(2026, 4, 24, 13, 9, 27),
  'update_time': datetime.datetime(2026, 4, 27, 9, 0, 49)},
 {'id': 17860077,
  'sheet_id_chip_id': 'MQ6A5PN71',
  'chip_id': 'MQ6A5PN710',
  'test_time': datetime.datetime(2026, 4, 24, 13, 7, 26),
  'defect_size': 'OK',
  'size_class': '0',
  'pox_x1': 0,
  'pox_y1': 0,
  'adc_def_code': '',
  'retype_def_code': '',
  'image_file_name': 'CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN71.GlassImage_Color.bm.1777007246.jpg',
  'img_file_url_path': 'PIT/2604/24/CAAOI300/MQ6A5PN71/1307/Map/',
  'pic_path': 'http://10.97.139.98:1454/CAAOI300/CA002001/MQ6A5PN71/PCS1/47086/Map/CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN71.GlassImage_Color.bm.1777007246.jpg',
  'recipe_id': 'CELL-ITO',
  'line_id': 'Null',
  'aoi': 'aoi300',
  'model': 'CELL-ITO',
  'glass_type': 'ITO',
  'pi_time': None,
  'pi_type': 'CELL-ITO',
  'cst_id': 'CA002001',
  'defect_count': 0,
  'defect_id': 'MACRO_4',
  'source_file': 'CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN71.47086.defect',
  'source_mtime': datetime.datetime(2026, 4, 24, 13, 9, 27),
  'update_time': datetime.datetime(2026, 4, 27, 9, 0, 49)},
 {'id': 17860078,
  'sheet_id_chip_id': 'MQ6A5PN72',
  'chip_id': 'MQ6A5PN720',
  'test_time': datetime.datetime(2026, 4, 24, 13, 2, 34),
  'defect_size': 'OK',
  'size_class': '0',
  'pox_x1': 0,
  'pox_y1': 0,
  'adc_def_code': '',
  'retype_def_code': '',
  'image_file_name': 'CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN72.GlassImage_modality5.bm.1777006954.jpg',
  'img_file_url_path': 'PIT/2604/24/CAAOI300/MQ6A5PN72/1302/Map/',
  'pic_path': 'http://10.97.139.98:1454/CAAOI300/CA002001/MQ6A5PN72/PCS1/46809/Map/CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN72.GlassImage_modality5.bm.1777006954.jpg',
  'recipe_id': 'CELL-ITO',
  'line_id': 'Null',
  'aoi': 'aoi300',
  'model': 'CELL-ITO',
  'glass_type': 'ITO',
  'pi_time': None,
  'pi_type': 'CELL-ITO',
  'cst_id': 'CA002001',
  'defect_count': 0,
  'defect_id': 'MACRO_1',
  'source_file': 'CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN72.46809.defect',
  'source_mtime': datetime.datetime(2026, 4, 24, 13, 4, 45),
  'update_time': datetime.datetime(2026, 4, 27, 9, 0, 49)},
 {'id': 17860079,
  'sheet_id_chip_id': 'MQ6A5PN72',
  'chip_id': 'MQ6A5PN720',
  'test_time': datetime.datetime(2026, 4, 24, 13, 2, 34),
  'defect_size': 'OK',
  'size_class': '0',
  'pox_x1': 0,
  'pox_y1': 0,
  'adc_def_code': '',
  'retype_def_code': '',
  'image_file_name': 'CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN72.GlassImage_modality6.bm.1777006954.jpg',
  'img_file_url_path': 'PIT/2604/24/CAAOI300/MQ6A5PN72/1302/Map/',
  'pic_path': 'http://10.97.139.98:1454/CAAOI300/CA002001/MQ6A5PN72/PCS1/46809/Map/CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN72.GlassImage_modality6.bm.1777006954.jpg',
  'recipe_id': 'CELL-ITO',
  'line_id': 'Null',
  'aoi': 'aoi300',
  'model': 'CELL-ITO',
  'glass_type': 'ITO',
  'pi_time': None,
  'pi_type': 'CELL-ITO',
  'cst_id': 'CA002001',
  'defect_count': 0,
  'defect_id': 'MACRO_2',
  'source_file': 'CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN72.46809.defect',
  'source_mtime': datetime.datetime(2026, 4, 24, 13, 4, 45),
  'update_time': datetime.datetime(2026, 4, 27, 9, 0, 49)},
 {'id': 17860080,
  'sheet_id_chip_id': 'MQ6A5PN72',
  'chip_id': 'MQ6A5PN720',
  'test_time': datetime.datetime(2026, 4, 24, 13, 2, 34),
  'defect_size': 'OK',
  'size_class': '0',
  'pox_x1': 0,
  'pox_y1': 0,
  'adc_def_code': '',
  'retype_def_code': '',
  'image_file_name': 'CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN72.GlassImage_modality7.bm.1777006954.jpg',
  'img_file_url_path': 'PIT/2604/24/CAAOI300/MQ6A5PN72/1302/Map/',
  'pic_path': 'http://10.97.139.98:1454/CAAOI300/CA002001/MQ6A5PN72/PCS1/46809/Map/CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN72.GlassImage_modality7.bm.1777006954.jpg',
  'recipe_id': 'CELL-ITO',
  'line_id': 'Null',
  'aoi': 'aoi300',
  'model': 'CELL-ITO',
  'glass_type': 'ITO',
  'pi_time': None,
  'pi_type': 'CELL-ITO',
  'cst_id': 'CA002001',
  'defect_count': 0,
  'defect_id': 'MACRO_3',
  'source_file': 'CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN72.46809.defect',
  'source_mtime': datetime.datetime(2026, 4, 24, 13, 4, 45),
  'update_time': datetime.datetime(2026, 4, 27, 9, 0, 49)},
 {'id': 17860081,
  'sheet_id_chip_id': 'MQ6A5PN72',
  'chip_id': 'MQ6A5PN720',
  'test_time': datetime.datetime(2026, 4, 24, 13, 2, 34),
  'defect_size': 'OK',
  'size_class': '0',
  'pox_x1': 0,
  'pox_y1': 0,
  'adc_def_code': '',
  'retype_def_code': '',
  'image_file_name': 'CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN72.GlassImage_Color.bm.1777006954.jpg',
  'img_file_url_path': 'PIT/2604/24/CAAOI300/MQ6A5PN72/1302/Map/',
  'pic_path': 'http://10.97.139.98:1454/CAAOI300/CA002001/MQ6A5PN72/PCS1/46809/Map/CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN72.GlassImage_Color.bm.1777006954.jpg',
  'recipe_id': 'CELL-ITO',
  'line_id': 'Null',
  'aoi': 'aoi300',
  'model': 'CELL-ITO',
  'glass_type': 'ITO',
  'pi_time': None,
  'pi_type': 'CELL-ITO',
  'cst_id': 'CA002001',
  'defect_count': 0,
  'defect_id': 'MACRO_4',
  'source_file': 'CAAOI300.CELL-ITO.CELL-ITO.CA002001.MQ6A5PN72.46809.defect',
  'source_mtime': datetime.datetime(2026, 4, 24, 13, 4, 45),
  'update_time': datetime.datetime(2026, 4, 27, 9, 0, 49)},
 {'id': 17860082,
  'sheet_id_chip_id': 'MQ6A5Q86L',
  'chip_id': 'MQ6A5Q86L0',
  'test_time': datetime.datetime(2026, 4, 24, 19, 53, 29),
  'defect_size': 'OK',
  'size_class': '0',
  'pox_x1': 0,
  'pox_y1': 0,
  'adc_def_code': '',
  'retype_def_code': '',
  'image_file_name': 'CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86L.GlassImage_modality5.bm.1777031609.jpg',
  'img_file_url_path': 'PIT/2604/24/CAAOI300/MQ6A5Q86L/1953/Map/',
  'pic_path': 'http://10.97.139.98:1454/CAAOI300/CA002202/MQ6A5Q86L/PCS1/71448/Map/CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86L.GlassImage_modality5.bm.1777031609.jpg',
  'recipe_id': 'CELL-ITO',
  'line_id': 'Null',
  'aoi': 'aoi300',
  'model': 'CELL-ITO',
  'glass_type': 'ITO',
  'pi_time': None,
  'pi_type': 'CELL-ITO',
  'cst_id': 'CA002202',
  'defect_count': 0,
  'defect_id': 'MACRO_1',
  'source_file': 'CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86L.71448.defect',
  'source_mtime': datetime.datetime(2026, 4, 24, 19, 55, 31),
  'update_time': datetime.datetime(2026, 4, 27, 9, 0, 49)},
 {'id': 17860083,
  'sheet_id_chip_id': 'MQ6A5Q86L',
  'chip_id': 'MQ6A5Q86L0',
  'test_time': datetime.datetime(2026, 4, 24, 19, 53, 29),
  'defect_size': 'OK',
  'size_class': '0',
  'pox_x1': 0,
  'pox_y1': 0,
  'adc_def_code': '',
  'retype_def_code': '',
  'image_file_name': 'CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86L.GlassImage_modality6.bm.1777031609.jpg',
  'img_file_url_path': 'PIT/2604/24/CAAOI300/MQ6A5Q86L/1953/Map/',
  'pic_path': 'http://10.97.139.98:1454/CAAOI300/CA002202/MQ6A5Q86L/PCS1/71448/Map/CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86L.GlassImage_modality6.bm.1777031609.jpg',
  'recipe_id': 'CELL-ITO',
  'line_id': 'Null',
  'aoi': 'aoi300',
  'model': 'CELL-ITO',
  'glass_type': 'ITO',
  'pi_time': None,
  'pi_type': 'CELL-ITO',
  'cst_id': 'CA002202',
  'defect_count': 0,
  'defect_id': 'MACRO_2',
  'source_file': 'CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86L.71448.defect',
  'source_mtime': datetime.datetime(2026, 4, 24, 19, 55, 31),
  'update_time': datetime.datetime(2026, 4, 27, 9, 0, 49)},
 {'id': 17860084,
  'sheet_id_chip_id': 'MQ6A5Q86L',
  'chip_id': 'MQ6A5Q86L0',
  'test_time': datetime.datetime(2026, 4, 24, 19, 53, 29),
  'defect_size': 'OK',
  'size_class': '0',
  'pox_x1': 0,
  'pox_y1': 0,
  'adc_def_code': '',
  'retype_def_code': '',
  'image_file_name': 'CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86L.GlassImage_modality7.bm.1777031609.jpg',
  'img_file_url_path': 'PIT/2604/24/CAAOI300/MQ6A5Q86L/1953/Map/',
  'pic_path': 'http://10.97.139.98:1454/CAAOI300/CA002202/MQ6A5Q86L/PCS1/71448/Map/CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86L.GlassImage_modality7.bm.1777031609.jpg',
  'recipe_id': 'CELL-ITO',
  'line_id': 'Null',
  'aoi': 'aoi300',
  'model': 'CELL-ITO',
  'glass_type': 'ITO',
  'pi_time': None,
  'pi_type': 'CELL-ITO',
  'cst_id': 'CA002202',
  'defect_count': 0,
  'defect_id': 'MACRO_3',
  'source_file': 'CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86L.71448.defect',
  'source_mtime': datetime.datetime(2026, 4, 24, 19, 55, 31),
  'update_time': datetime.datetime(2026, 4, 27, 9, 0, 49)},
 {'id': 17860085,
  'sheet_id_chip_id': 'MQ6A5Q86L',
  'chip_id': 'MQ6A5Q86L0',
  'test_time': datetime.datetime(2026, 4, 24, 19, 53, 29),
  'defect_size': 'OK',
  'size_class': '0',
  'pox_x1': 0,
  'pox_y1': 0,
  'adc_def_code': '',
  'retype_def_code': '',
  'image_file_name': 'CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86L.GlassImage_Color.bm.1777031609.jpg',
  'img_file_url_path': 'PIT/2604/24/CAAOI300/MQ6A5Q86L/1953/Map/',
  'pic_path': 'http://10.97.139.98:1454/CAAOI300/CA002202/MQ6A5Q86L/PCS1/71448/Map/CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86L.GlassImage_Color.bm.1777031609.jpg',
  'recipe_id': 'CELL-ITO',
  'line_id': 'Null',
  'aoi': 'aoi300',
  'model': 'CELL-ITO',
  'glass_type': 'ITO',
  'pi_time': None,
  'pi_type': 'CELL-ITO',
  'cst_id': 'CA002202',
  'defect_count': 0,
  'defect_id': 'MACRO_4',
  'source_file': 'CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86L.71448.defect',
  'source_mtime': datetime.datetime(2026, 4, 24, 19, 55, 31),
  'update_time': datetime.datetime(2026, 4, 27, 9, 0, 49)},
 {'id': 17860086,
  'sheet_id_chip_id': 'MQ6A5Q86M',
  'chip_id': 'MQ6A5Q86M0',
  'test_time': datetime.datetime(2026, 4, 24, 19, 48, 35),
  'defect_size': 'OK',
  'size_class': '0',
  'pox_x1': 0,
  'pox_y1': 0,
  'adc_def_code': '',
  'retype_def_code': '',
  'image_file_name': 'CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86M.GlassImage_modality5.bm.1777031315.jpg',
  'img_file_url_path': 'PIT/2604/24/CAAOI300/MQ6A5Q86M/1948/Map/',
  'pic_path': 'http://10.97.139.98:1454/CAAOI300/CA002202/MQ6A5Q86M/PCS1/71171/Map/CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86M.GlassImage_modality5.bm.1777031315.jpg',
  'recipe_id': 'CELL-ITO',
  'line_id': 'Null',
  'aoi': 'aoi300',
  'model': 'CELL-ITO',
  'glass_type': 'ITO',
  'pi_time': None,
  'pi_type': 'CELL-ITO',
  'cst_id': 'CA002202',
  'defect_count': 0,
  'defect_id': 'MACRO_1',
  'source_file': 'CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86M.71171.defect',
  'source_mtime': datetime.datetime(2026, 4, 24, 19, 50, 48),
  'update_time': datetime.datetime(2026, 4, 27, 9, 0, 49)},
 {'id': 17860087,
  'sheet_id_chip_id': 'MQ6A5Q86M',
  'chip_id': 'MQ6A5Q86M0',
  'test_time': datetime.datetime(2026, 4, 24, 19, 48, 35),
  'defect_size': 'OK',
  'size_class': '0',
  'pox_x1': 0,
  'pox_y1': 0,
  'adc_def_code': '',
  'retype_def_code': '',
  'image_file_name': 'CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86M.GlassImage_modality6.bm.1777031315.jpg',
  'img_file_url_path': 'PIT/2604/24/CAAOI300/MQ6A5Q86M/1948/Map/',
  'pic_path': 'http://10.97.139.98:1454/CAAOI300/CA002202/MQ6A5Q86M/PCS1/71171/Map/CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86M.GlassImage_modality6.bm.1777031315.jpg',
  'recipe_id': 'CELL-ITO',
  'line_id': 'Null',
  'aoi': 'aoi300',
  'model': 'CELL-ITO',
  'glass_type': 'ITO',
  'pi_time': None,
  'pi_type': 'CELL-ITO',
  'cst_id': 'CA002202',
  'defect_count': 0,
  'defect_id': 'MACRO_2',
  'source_file': 'CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86M.71171.defect',
  'source_mtime': datetime.datetime(2026, 4, 24, 19, 50, 48),
  'update_time': datetime.datetime(2026, 4, 27, 9, 0, 49)},
 {'id': 17860088,
  'sheet_id_chip_id': 'MQ6A5Q86M',
  'chip_id': 'MQ6A5Q86M0',
  'test_time': datetime.datetime(2026, 4, 24, 19, 48, 35),
  'defect_size': 'OK',
  'size_class': '0',
  'pox_x1': 0,
  'pox_y1': 0,
  'adc_def_code': '',
  'retype_def_code': '',
  'image_file_name': 'CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86M.GlassImage_modality7.bm.1777031315.jpg',
  'img_file_url_path': 'PIT/2604/24/CAAOI300/MQ6A5Q86M/1948/Map/',
  'pic_path': 'http://10.97.139.98:1454/CAAOI300/CA002202/MQ6A5Q86M/PCS1/71171/Map/CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86M.GlassImage_modality7.bm.1777031315.jpg',
  'recipe_id': 'CELL-ITO',
  'line_id': 'Null',
  'aoi': 'aoi300',
  'model': 'CELL-ITO',
  'glass_type': 'ITO',
  'pi_time': None,
  'pi_type': 'CELL-ITO',
  'cst_id': 'CA002202',
  'defect_count': 0,
  'defect_id': 'MACRO_3',
  'source_file': 'CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86M.71171.defect',
  'source_mtime': datetime.datetime(2026, 4, 24, 19, 50, 48),
  'update_time': datetime.datetime(2026, 4, 27, 9, 0, 49)},
 {'id': 17860089,
  'sheet_id_chip_id': 'MQ6A5Q86M',
  'chip_id': 'MQ6A5Q86M0',
  'test_time': datetime.datetime(2026, 4, 24, 19, 48, 35),
  'defect_size': 'OK',
  'size_class': '0',
  'pox_x1': 0,
  'pox_y1': 0,
  'adc_def_code': '',
  'retype_def_code': '',
  'image_file_name': 'CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86M.GlassImage_Color.bm.1777031315.jpg',
  'img_file_url_path': 'PIT/2604/24/CAAOI300/MQ6A5Q86M/1948/Map/',
  'pic_path': 'http://10.97.139.98:1454/CAAOI300/CA002202/MQ6A5Q86M/PCS1/71171/Map/CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86M.GlassImage_Color.bm.1777031315.jpg',
  'recipe_id': 'CELL-ITO',
  'line_id': 'Null',
  'aoi': 'aoi300',
  'model': 'CELL-ITO',
  'glass_type': 'ITO',
  'pi_time': None,
  'pi_type': 'CELL-ITO',
  'cst_id': 'CA002202',
  'defect_count': 0,
  'defect_id': 'MACRO_4',
  'source_file': 'CAAOI300.CELL-ITO.CELL-ITO.CA002202.MQ6A5Q86M.71171.defect',
  'source_mtime': datetime.datetime(2026, 4, 24, 19, 50, 48),
  'update_time': datetime.datetime(2026, 4, 27, 9, 0, 49)},
 {'id': 17860090,
  'sheet_id_chip_id': 'MQ6A5Q87J',
  'chip_id': 'MQ6A5Q87J0',
  'test_time': datetime.datetime(2026, 4, 25, 0, 25, 35),
  'defect_size': 'OK',
  'size_class': '0',
  'pox_x1': 0,
  'pox_y1': 0,
  'adc_def_code': '',
  'retype_def_code': '',
  'image_file_name': 'CAAOI300.CELL-ITO.CELL-ITO.CA003302.MQ6A5Q87J.GlassImage_modality5.bm.1777047935.jpg',
  'img_file_url_path': 'PIT/2604/25/CAAOI300/MQ6A5Q87J/0025/Map/',
  'pic_path': 'http://10.97.139.98:1454/CAAOI300/CA003302/MQ6A5Q87J/PCS1/1374/Map/CAAOI300.CELL-ITO.CELL-ITO.CA003302.MQ6A5Q87J.GlassImage_modality5.bm.1777047935.jpg',
  'recipe_id': 'CELL-ITO',
  'line_id': 'Null',
  'aoi': 'aoi300',
  'model': 'CELL-ITO',
  'glass_type': 'ITO',
  'pi_time': None,
  'pi_type': 'CELL-ITO',
  'cst_id': 'CA003302',
  'defect_count': 0,
  'defect_id': 'MACRO_1',
  'source_file': 'CAAOI300.CELL-ITO.CELL-ITO.CA003302.MQ6A5Q87J.1374.defect',
  'source_mtime': datetime.datetime(2026, 4, 25, 0, 27, 39),
  'update_time': datetime.datetime(2026, 4, 27, 9, 0, 49)},
 {'id': 17860091,
  'sheet_id_chip_id': 'MQ6A5Q87J',
  'chip_id': 'MQ6A5Q87J0',
  'test_time': datetime.datetime(2026, 4, 25, 0, 25, 35),
  'defect_size': 'OK',
  'size_class': '0',
  'pox_x1': 0,
  'pox_y1': 0,
  'adc_def_code': '',
  'retype_def_code': '',
  'image_file_name': 'CAAOI300.CELL-ITO.CELL-ITO.CA003302.MQ6A5Q87J.GlassImage_modality6.bm.1777047935.jpg',
  'img_file_url_path': 'PIT/2604/25/CAAOI300/MQ6A5Q87J/0025/Map/',
  'pic_path': 'http://10.97.139.98:1454/CAAOI300/CA003302/MQ6A5Q87J/PCS1/1374/Map/CAAOI300.CELL-ITO.CELL-ITO.CA003302.MQ6A5Q87J.GlassImage_modality6.bm.1777047935.jpg',
  'recipe_id': 'CELL-ITO',
  'line_id': 'Null',
  'aoi': 'aoi300',
  'model': 'CELL-ITO',
  'glass_type': 'ITO',
  'pi_time': None,
  'pi_type': 'CELL-ITO',
  'cst_id': 'CA003302',
  'defect_count': 0,
  'defect_id': 'MACRO_2',
  'source_file': 'CAAOI300.CELL-ITO.CELL-ITO.CA003302.MQ6A5Q87J.1374.defect',
  'source_mtime': datetime.datetime(2026, 4, 25, 0, 27, 39),
  'update_time': datetime.datetime(2026, 4, 27, 9, 0, 49)},
 {'id': 17860092,
  'sheet_id_chip_id': 'MQ6A5Q87J',
  'chip_id': 'MQ6A5Q87J0',
  'test_time': datetime.datetime(2026, 4, 25, 0, 25, 35),
  'defect_size': 'OK',
  'size_class': '0',
  'pox_x1': 0,
  'pox_y1': 0,
  'adc_def_code': '',
  'retype_def_code': '',
  'image_file_name': 'CAAOI300.CELL-ITO.CELL-ITO.CA003302.MQ6A5Q87J.GlassImage_modality7.bm.1777047935.jpg',
  'img_file_url_path': 'PIT/2604/25/CAAOI300/MQ6A5Q87J/0025/Map/',
  'pic_path': 'http://10.97.139.98:1454/CAAOI300/CA003302/MQ6A5Q87J/PCS1/1374/Map/CAAOI300.CELL-ITO.CELL-ITO.CA003302.MQ6A5Q87J.GlassImage_modality7.bm.1777047935.jpg',
  'recipe_id': 'CELL-ITO',
  'line_id': 'Null',
  'aoi': 'aoi300',
  'model': 'CELL-ITO',
  'glass_type': 'ITO',
  'pi_time': None,
  'pi_type': 'CELL-ITO',
  'cst_id': 'CA003302',
  'defect_count': 0,
  'defect_id': 'MACRO_3',
  'source_file': 'CAAOI300.CELL-ITO.CELL-ITO.CA003302.MQ6A5Q87J.1374.defect',
  'source_mtime': datetime.datetime(2026, 4, 25, 0, 27, 39),
  'update_time': datetime.datetime(2026, 4, 27, 9, 0, 49)},
 {'id': 17860093,
  'sheet_id_chip_id': 'MQ6A5Q87J',
  'chip_id': 'MQ6A5Q87J0',
  'test_time': datetime.datetime(2026, 4, 25, 0, 25, 35),
  'defect_size': 'OK',
  'size_class': '0',
  'pox_x1': 0,
  'pox_y1': 0,
  'adc_def_code': '',
  'retype_def_code': '',
  'image_file_name': 'CAAOI300.CELL-ITO.CELL-ITO.CA003302.MQ6A5Q87J.GlassImage_Color.bm.1777047935.jpg',

In [17]:
import csv
df = pd.read_csv('D:/A0_Project/PI_SYSTEM/models/density/AOI_Spec2.csv',encoding='cp950')
df

      序號      Model     產品別 Defect Type Item1 Defect Size  OOC   OOS
0      1  B070AAN01  Normal     Polymer   BIG        OLMS  5.0  10.0
1      2  B070AAN1Y  Normal     Polymer   BIG        OLMS  5.0  10.0
2      3  B070VTN01  Normal     Polymer   BIG        OLMS  5.0  10.0
3      4  B080EAN05  Normal     Polymer   BIG        OLMS  5.0  10.0
4      5  B101EAN2A  Normal     Polymer   BIG        OLMS  5.0  10.0
..   ...        ...     ...         ...   ...         ...  ...   ...
945  159  P270QAN01  Normal     NPI_TFT   BIG        OLMS  8.0  10.0
946  160  P270QAN02  Normal     NPI_TFT   BIG        OLMS  8.0  10.0
947  161  P281SAN01  Normal     NPI_TFT   BIG        OLMS  8.0  10.0
948  162  Y160UAN03  Normal     NPI_TFT   BIG        OLMS  8.0  10.0
949  163  Z335XAN01  Normal     NPI_TFT   BIG        OLMS  8.0  10.0

[950 rows x 8 columns]

In [22]:
df.rename({
    'Model':'model',
    '產品別':'MODEL_TYPE',
    'Defect Type':'adc_def_code',
    'Item1':'PROCESS_TYPE',
    'Defect Size':'defect_size',
    'OOC':'OOC',
    'OOS':'OOS'

},axis=1, inplace=True)

df.loc[df.index, ['line_id', 'glass_type', 'Editor', 'modify_time']] = ''
df.loc[df.index, ['drop']] = 'F'
df = df[[cl for cl in df.columns if cl in spec_df.columns]]
df.head()

,model,MODEL_TYPE,adc_def_code,PROCESS_TYPE,defect_size,OOC,OOS,line_id,glass_type,Editor,modify_time,drop
0,B070AAN01,Normal,Polymer,BIG,OLMS,5.0,10.0,,,,,F
1,B070AAN1Y,Normal,Polymer,BIG,OLMS,5.0,10.0,,,,,F
2,B070VTN01,Normal,Polymer,BIG,OLMS,5.0,10.0,,,,,F
3,B080EAN05,Normal,Polymer,BIG,OLMS,5.0,10.0,,,,,F
4,B101EAN2A,Normal,Polymer,BIG,OLMS,5.0,10.0,,,,,F

In [25]:
type(df['OOC'][0])

numpy.float64

In [28]:
new = pd.DataFrame()

for line_id in spec_df['line_id'].unique():
    print(line_id)
    df['line_id'] = line_id
    new = pd.concat([new, df.copy()])
    print(len(new))

spec2 = pd.DataFrame()
for t in spec_df['glass_type'].unique():
    new['glass_type'] = t
    spec2 = pd.concat([spec2, new.copy()])

CAPIC100
950
CAPIC200
1900
CAPIC300
2850
CAPIC400
3800
CAPIC500
4750
CAPIC600
5700
CAPIC700
6650

C:\Users\Ray\AppData\Local\Temp\ipykernel_16356\1485156070.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['line_id'] = line_id

In [29]:
db.save_table('default_spec_table', spec2)

2026-06-23 14:58:41,564 - INFO - [save_table] piaoi_density.default_spec_table 已寫入 13300 列（去除 0 重複）

13300

In [ ]:
http://tcweb002.corpnet.auo.com/fafle001/image/PS/4/AR0DJ600R4/RAR0DJ600R4_0038_001_1011544_1567595.jpg
http://tcweb002.corpnet.auo.com/fafle001/image/PS/4/AR0DJ600R4/RAR0DJ600R4_0010_001_1341804_1290293.jpg

In [21]:
[cl for cl in spec_df.columns if cl not in df.columns]

['line_id', 'glass_type', 'Editor', 'modify_time', 'drop']

In [6]:
db = MySQLConnet('piaoi_density')
spec_df = db.get_table('default_spec_table')
#cols = ['model']
print(len(spec_df))
spec_df

7604

,line_id,model,glass_type,adc_def_code,defect_size,OOC,OOS,Editor,modify_time,drop,MODEL_TYPE,PROCESS_TYPE
0,CAPIC100,B070AAN01,TFT,PIS With Particle,OL,0.28,0.33,預設,2025-12-24 15:56:23,F,Normal,BIG
1,CAPIC100,B070AAN01,TFT,PIS With Particle,OLMS,2,3,預設,2026-06-18 10:46:24,T,Normal,BIG
2,CAPIC100,B070AAN01,TFT,PI_Spot_NP,OL,0.33,0.57,預設,2025-12-09 08:00:00,F,Normal,BIG
3,CAPIC100,B070AAN01,TFT,PI_Spot_NP,OLMS,300,300,預設,2026-06-18 10:55:43,T,Normal,BIG
4,CAPIC100,B070AAN01,TFT,Polymer,OLMS,5,10,預設,2025-12-09 08:00:00,F,Normal,BIG
...,...,...,...,...,...,...,...,...,...,...,...,...
7599,CAPIC700,M270QAN06,TFT,NPI_TFT,OLMS,8,10,預設,2026-06-18 15:53:22,F,Normal,BIG
7600,CAPIC100,TEST,TFT,NPI_TFT,OLMS,0.5,0.6,預設,2026-06-22 08:41:35,F,Normal,BIG
7601,CAPIC400,B160UAV01,TFT,Polymer,OLMS,5,10,預設,2026-06-23 07:48:29,F,高階,BIG
7602,CAPIC400,B160UAV01,TFT,SSIU_Polymer,OLMS,40,80,預設,2026-06-23 07:49:03,F,高階,BIG
7603,CAPIC700,test_0623,TFT,NPI_CF,OLM,5,10,預設,2026-06-23 14:22:25,T,Normal,BIG

In [27]:
spec_df['glass_type'].unique()

array(['TFT', 'CF'], dtype=object)

In [ ]:
import pandas as pd


def build_expand_spec_df(
    model_list,
    line_id_list=None,
    glass_type_list=None,
    size_group_list=None,
    default_ooc=150,
    default_oos=200,
    editor="預設",
    modify_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
):
    #if line_id_list is None:
    #    line_id_list = ["ALL"]

    if glass_type_list is None:
        glass_type_list = ["TFT", "CF"]

    if size_group_list is None:
        size_group_list = ["S", "MS", "LMS", "O", "OL", "OLM", "OLMS"]

    def clean_list(values):
        out = []
        for v in values or []:
            if v is None:
                continue
            s = str(v).strip()
            if not s:
                continue
            if s.lower() in {"nan", "none", "null", "<na>", "nat"}:
                continue
            out.append(s)
        return sorted(set(out))

    models = clean_list(model_list)
    #lines = clean_list(line_id_list)
    glass_types = clean_list(glass_type_list)
    size_groups = clean_list(size_group_list)

    rows = []

    #for line_id in lines:
    for model in models:
        for glass_type in glass_types:
            for size_group in size_groups:
                rows.append({
                    "model": model,
                    "glass_type": glass_type,
                    "defect_size": size_group,
                    "OOC": default_ooc,
                    "OOS": default_oos,
                    "Editor": editor,
                    "modify_time": modify_time ,
                    "drop" : 'F'
                })

    return pd.DataFrame(rows)

spec_df = build_expand_spec_df([v for v in models if 'test' not in v])
spec_df

,model,glass_type,defect_size,OOC,OOS,Editor,modify_time,drop
0,B070AAN01,CF,LMS,150,200,預設,2026-04-28 13:57:13,F
1,B070AAN01,CF,MS,150,200,預設,2026-04-28 13:57:13,F
2,B070AAN01,CF,O,150,200,預設,2026-04-28 13:57:13,F
3,B070AAN01,CF,OL,150,200,預設,2026-04-28 13:57:13,F
4,B070AAN01,CF,OLM,150,200,預設,2026-04-28 13:57:13,F
...,...,...,...,...,...,...,...,...
2585,Z335XAN01_TEST,TFT,O,150,200,預設,2026-04-28 13:57:13,F
2586,Z335XAN01_TEST,TFT,OL,150,200,預設,2026-04-28 13:57:13,F
2587,Z335XAN01_TEST,TFT,OLM,150,200,預設,2026-04-28 13:57:13,F
2588,Z335XAN01_TEST,TFT,OLMS,150,200,預設,2026-04-28 13:57:13,F
2589,Z335XAN01_TEST,TFT,S,150,200,預設,2026-04-28 13:57:13,F

In [ ]:
spec_df.columns

Index(['model', 'glass_type', 'defect_size', 'OOC', 'OOS', 'Editor',
       'modify_time', 'drop'],
      dtype='object')

In [ ]:
db = MySQLConnet('piaoi_bpi_density')
#db.list_tables()
#db.save_table('default_spec_table', spec_df)
db.get_rows('default_spec_table', {'model': 'test_0429'})

[{'model': 'test_0429',
  'glass_type': 'TFT',
  'defect_size': 'MS',
  'OOC': 111,
  'OOS': 222,
  'Editor': '預設',
  'modify_time': '2026-04-29 10:33:03',
  'drop': 'F'}]

In [ ]:
df = db.get_runs_between('bpi_api_summary_202604', '2026-04-26', '2026-04-28', 'scan_hour')
df.iloc[-1,:].to_dict()

{'id': 3,
 'aoi': 'aoi200',
 'model': 'B160UAN05',
 'scan_hour': Timestamp('2026-04-26 11:00:00'),
 'cassette_id': 'AA1659',
 'glass_side': 'TFT',
 'recipe_id': '4258',
 'pi_type': 'BPI',
 'run_day': datetime.date(2026, 4, 26),
 'glass_count': 1,
 'total_defect_count': 4851,
 'small_defect_count': 473,
 'middle_defect_count': 1563,
 'large_defect_count': 1359,
 'over_defect_count': 0,
 'density': 4851.0,
 'glass_list': 'VN6A3VE6A',
 'glass_size_detail': '{"VN6A3VE6A": {"S": 473, "M": 1563, "L": 1359, "O": 0, "T": 3395, "line_id": "CAPIC200", "test_time": "2026-04-26 12:09:45"}}',
 'source_db': 'cim_piaoi',
 'source_table': 'cim_pi_glass_202604',
 'comment': '',
 'action': '',
 'editor': '',
 'modify_time': None,
 'update_time': Timestamp('2026-04-28 11:08:34')}

In [ ]:
db = MySQLConnet('cim_piaoi')
df = db.get_runs_between('cim_pi_glass_202604', '2026-04-26', '2026-04-27', 'pi_hour')
df.columns

Index(['sheet_id_chip_id', 'test_time', 'model_no', 'op_id', 'abbr_cat',
       'recipe_id', 'cassette_id', 'aoi', 'total_defect_qty',
       'defect_size_o_qty', 'defect_size_l_qty', 'defect_size_m_qty',
       'defect_size_s_qty', 'line_id', 'pi_time', 'pi_hour', 'pi_type'],
      dtype='object')

In [ ]:
rdf = df[(df['cassette_id'] == 'AA1659') & (df['model_no'] == 'B160UAN05') ] #(df['model'] == 'B160UAN05') & (df['scan_hour'] == "2026-04-26 11:00:00") 
rdf

,sheet_id_chip_id,test_time,model_no,op_id,abbr_cat,recipe_id,cassette_id,aoi,total_defect_qty,defect_size_o_qty,defect_size_l_qty,defect_size_m_qty,defect_size_s_qty,line_id,pi_time,pi_hour,pi_type
89,VN6A3VE6A,2026-04-26 12:09:45,B160UAN05,PCS1,TFT,4258,AA1659,CAAOI202,4851,0,1359,1563,473,CAPIC200,2026-04-26 18:21:21,2026-04-26 17:00:00,BPI

In [ ]:
730*0.65-(120+22+13)
#100-3-(4*1.5)

319.5

In [ ]:
rdf = df[(df['cassette_id'] == "AA1659") ] #(df['model'] == 'B160UAN05') & (df['scan_hour'] == "2026-04-26 11:00:00") 

for (recipe, glass_type, code, ), rows in rdf.groupby(['cassette_id','recipe_id',  'glass_side']):
    print(recipe, glass_type,  code, len(rows))
    print(rows[['glass_count', 'total_defect_count',
       'small_defect_count', 'middle_defect_count', 'large_defect_count',
       'over_defect_count', 'density']])

KeyError: 'glass_side'

In [ ]:
473+1563+1359

3395

In [ ]:
#db = MySQLConnet('piaoi_capa')
db = MySQLConnet('piaoi_bpi_same_point')
#for tbn in db.list_tables():#[v for v in db.list_tables() if 'aoi300' not in v]:
    #db.drop_table(tbn)

"""
db.save_table("default_spec_table", pd.DataFrame(columns=[
            "model",
            "glass_side",
            "defect_size",
            "OOC",
            "OOS",
            "editor",
            "modify_time",
            "drop",
        ]))
"""
df = db.get_table("bpi_same_point_offset_summary_202605")
df.iloc[0,:].to_dict()

{'id': 281,
 'model': 'B153UAN03',
 'glass_side': 'TFT',
 'glass_id': 'Y26A5RV7A',
 'scan_hour': Timestamp('2026-05-14 18:00:00'),
 'run_day': Timestamp('2026-05-14 00:00:00'),
 'tab': 'PISpot',
 'bpi_aoi': 'aoi200',
 'bpi_scan_time': Timestamp('2026-05-12 12:08:06'),
 'bpi_recipe_id': '4295',
 'api_aoi': 'aoi200',
 'api_scan_time': Timestamp('2026-05-14 19:13:06'),
 'api_recipe_id': '0295',
 'offset_um': 5,
 'bpi_defect_count': 70,
 'api_defect_count': 246,
 'matched_pair_count': 0,
 'matched_bpi_defect_count': 0,
 'matched_api_defect_count': 0,
 'unmatched_bpi_defect_count': 70,
 'unmatched_api_defect_count': 246,
 'matched_bpi_s_count': 0,
 'matched_bpi_m_count': 0,
 'matched_bpi_l_count': 0,
 'matched_bpi_o_count': 0,
 'matched_api_s_count': 0,
 'matched_api_m_count': 0,
 'matched_api_l_count': 0,
 'matched_api_o_count': 0,
 'matched_size_transition_json': '{}',
 'gen_time': Timestamp('2026-05-26 11:25:41')}

In [ ]:
df = db.get_table("bpi_same_point_202605")
df[df['model'] == "G215HVN01"]

,id,model,glass_side,glass_id,scan_hour,run_day,tab,bpi_aoi,bpi_line_id,bpi_recipe_id,...,api_over_defect_count,pair_status,pair_message,default_offset_um,matched_points_json,comment,action,editor,modify_time,gen_time
26,69,G215HVN01,CF,AL5H151YDN,2026-05-05 23:00:00,2026-05-05,aoi100,aoi200,CAPIC200,5243,...,0,OK,,20,[],,,,NaT,2026-05-26 11:25:30
27,70,G215HVN01,CF,AL5H151YEA,2026-05-05 23:00:00,2026-05-05,aoi100,aoi200,CAPIC200,5243,...,0,OK,,20,[],,,,NaT,2026-05-26 11:25:30
28,71,G215HVN01,CF,AL5H151YEK,2026-05-05 23:00:00,2026-05-05,aoi100,aoi200,CAPIC200,5243,...,0,OK,,20,[],,,,NaT,2026-05-26 11:25:30
29,72,G215HVN01,CF,AL5H151YEP,2026-05-05 23:00:00,2026-05-05,aoi100,aoi200,CAPIC200,5243,...,0,OK,,20,[],,,,NaT,2026-05-26 11:25:30
30,73,G215HVN01,CF,AL5H151YEQ,2026-05-05 23:00:00,2026-05-05,aoi100,aoi200,CAPIC200,5243,...,0,OK,,20,[],,,,NaT,2026-05-26 11:25:30
31,74,G215HVN01,CF,AL5H151YES,2026-05-05 23:00:00,2026-05-05,aoi100,aoi200,CAPIC200,5243,...,0,OK,,20,[],,,,NaT,2026-05-26 11:25:30
32,75,G215HVN01,CF,AL5H151YEU,2026-05-05 23:00:00,2026-05-05,aoi100,aoi200,CAPIC200,5243,...,0,OK,,20,"[{""offset_um"": 20, ""distance"": 19.849433241279...",,,,NaT,2026-05-26 11:25:30
33,76,G215HVN01,CF,AL5H151YK5,2026-05-05 23:00:00,2026-05-05,aoi100,aoi200,CAPIC200,5243,...,0,OK,,20,"[{""offset_um"": 20, ""distance"": 16.278820596099...",,,,NaT,2026-05-26 11:25:30

In [ ]:
df = db.get_table("default_spec_table")
df.iloc[-1,:].to_dict()

{'model': 'nan',
 'glass_side': 'nan',
 'defect_size': 'nan',
 'OOC': '5',
 'OOS': '10',
 'editor': '預設',
 'modify_time': '2026-05-27 15:52:23',
 'drop': 'F'}

In [ ]:
[{"offset_um": 20, 
  "distance": 2.0, 
  "dx": -2.0, "dy": 0.0, 
  "match_rank": 1, 
  "bpi_defect_uid": "RTMS|47373", 
  "bpi_chip_id": "YL6A5MX7D26", 
  "bpi_x": 1425267.0, "bpi_y": 940299.0,
  "bpi_defect_size": "S", 
  "bpi_adc_def_code": "", 
  "bpi_retype_code": "", 
  "bpi_pic_path": "http://10.97.139.98:1454/CAAOI300/AA001901/YL6A5MX7D/PCS1/61210/CaptureImage/small/CAAOI300.B156HAN2U.B156HAN2U-T-BPI.AA001901.YL6A5MX7D.61.bt5.1777971783.jpg", "bpi_pic_name": "CAAOI300.B156HAN2U.B156HAN2U-T-BPI.AA001901.YL6A5MX7D.61.bt5.1777971783.jpg", 
  "api_defect_uid": "CIM|YL6A5MX7D|2026-05-25 08:30:57|1|1425269|940299|RV1_1425269_940299_19.jpg", 
  "api_chip_id": "1", 
  "api_x": 1425269.0, "api_y": 940299.0, 
  "api_defect_size": "M", 
  "api_adc_def_code": "NPI_OIL", 
  "api_retype_code": "", 
  "api_pic_path": "http://l6apaimg103/dms/CELAIDI_L6A/PIT/2605/25/CAAOI202/YL6A5MX7D/0830/", 
  "api_pic_name": "RV1_1425269_940299_19.jpg"},
    {"offset_um": 20, "distance": 18.439088914585774, "dx": -12.0, "dy": 14.0, "match_rank": 2, "bpi_defect_uid": "RTMS|47371", "bpi_chip_id": "YL6A5MX7D24", "bpi_x": 1374237.0, "bpi_y": 248056.0, "bpi_defect_size": "S", "bpi_adc_def_code": "", "bpi_retype_code": "", "bpi_pic_path": "http://10.97.139.98:1454/CAAOI300/AA001901/YL6A5MX7D/PCS1/61210/CaptureImage/small/CAAOI300.B156HAN2U.B156HAN2U-T-BPI.AA001901.YL6A5MX7D.59.bt5.1777971783.jpg", "bpi_pic_name": "CAAOI300.B156HAN2U.B156HAN2U-T-BPI.AA001901.YL6A5MX7D.59.bt5.1777971783.jpg", "api_defect_uid": "CIM|YL6A5MX7D|2026-05-25 08:30:57|Z|1374249|248042|RV1_1374249_248042_44.jpg", "api_chip_id": "Z", "api_x": 1374249.0, "api_y": 248042.0, "api_defect_size": "L", "api_adc_def_code": "OP_Defect", "api_retype_code": "", "api_pic_path": "http://l6apaimg103/dms/CELAIDI_L6A/PIT/2605/25/CAAOI202/YL6A5MX7D/0830/",
      "api_pic_name": "RV1_1374249_248042_44.jpg"}]

In [4]:
7.8*1.25

9.75

In [7]:
db = MySQLConnet('cim_cell_aoi_to_array')
tbns = db.list_tables()
tbns

2026-06-26 15:12:27,766 - INFO - [list_tables] 成功取得資料表名稱，共 12 張表。

['api_aoi_summary_202606',
 'incoming_glass_summary_202606',
 'incoming_governance_state',
 'incoming_same_point_detail_202606',
 'incoming_source_array_mor_defect_raw_202606',
 'incoming_source_array_tar_defect_raw_202605',
 'incoming_source_array_tar_defect_raw_202606',
 'incoming_source_array_tos_defect_raw_202604',
 'incoming_source_array_tos_defect_raw_202605',
 'incoming_source_array_tos_defect_raw_202606',
 'incoming_source_cf_oc_defect_raw_202606',
 'incoming_source_cf_ps_defect_raw_202606']

In [37]:
rows = db.get_rows('incoming_source_cf_ps_defect_raw_202606', {'sheet_id':'AR0DJ600R4'})
#rows.sort_values(by='scan_time', ascending=True, inplace=True)
rows

[{'id': 5,
  'sheet_id': 'AR0DJ600R4',
  'chip_id': 'AR0DJ600R4E',
  'model_no': 'M270DAN7J-VC51MP000',
  'scan_time': datetime.datetime(2026, 6, 22, 4, 50, 33),
  'eqp_id': 'FASAOI30',
  'op': 'PS',
  'repair_time': datetime.datetime(2026, 6, 22, 9, 31, 36),
  'repair_code': 'nan',
  'repair_eqp_id': 'FAAREP42',
  'repair_op': 'REPAIR-PS',
  'op_id': 'PS',
  'defect_no': '0005',
  'defect_code': 'RB',
  'defect_size': 'M',
  'defect_size_raw': 'M',
  'ori_x': 1430703.0,
  'ori_y': 1190736.0,
  'trans_x': 1190736.0,
  'trans_y': 69297.0,
  'image_name': 'RAR0DJ600R4_0005_001_1430703_1190736.jpg',
  'img_url_path': 'http://tcweb002.corpnet.auo.com/fafle001/image/PS/4/AR0DJ600R4/RAR0DJ600R4_0005_001_1430703_1190736.jpg',
  'source_group_key': 'CF|AR0DJ600R4|PS|2026-06-22 04:50:33',
  'source_defect_uid': 'CF|AR0DJ600R4|PS|2026-06-22 04:50:33|AR0DJ600R4E|0005|RB|M|1430703|1190736|RAR0DJ600R4_0005_001_1430703_1190736.jpg',
  'raw_json': '{"glass_id": "AR0DJ600R4", "chip_id": "AR0DJ600R4E", "model_no": "M270DAN7J-VC51MP000", "testing_date": "2026-06-22 04:50:33", "eqp_id": "FASAOI30", "op": "PS", "defect_no": "0005", "defect_code": "RB", "defect_size_type": "M", "coord_x": "1430703", "coord_y": "1190736", "repair_date": "2026-06-22 09:31:36", "repair_code": null, "repair_eqp_id": "FAAREP42", "repair_op": "REPAIR-PS", "op_norm": "PS", "eqp_id_norm": "FASAOI30", "op_id": "PS", "source_rule": "OP_PS", "op_id_anchor": "PS", "latest_scan_time": "2026-06-22 04:50:33", "op_id_final": "PS"}',
  'create_time': datetime.datetime(2026, 6, 23, 16, 18, 51),
  'update_time': datetime.datetime(2026, 6, 23, 16, 18, 51)},
 {'id': 6,
  'sheet_id': 'AR0DJ600R4',
  'chip_id': 'AR0DJ600R4E',
  'model_no': 'M270DAN7J-VC51MP000',
  'scan_time': datetime.datetime(2026, 6, 22, 4, 50, 33),
  'eqp_id': 'FASAOI30',
  'op': 'PS',
  'repair_time': datetime.datetime(2026, 6, 22, 9, 31, 36),
  'repair_code': 'nan',
  'repair_eqp_id': 'FAAREP42',
  'repair_op': 'REPAIR-PS',
  'op_id': 'PS',
  'defect_no': '0006',
  'defect_code': 'RB',
  'defect_size': 'M',
  'defect_size_raw': 'M',
  'ori_x': 1422091.0,
  'ori_y': 1118859.0,
  'trans_x': 1118859.0,
  'trans_y': 77909.0,
  'image_name': 'RAR0DJ600R4_0006_001_1422091_1118859.jpg',
  'img_url_path': 'http://tcweb002.corpnet.auo.com/fafle001/image/PS/4/AR0DJ600R4/RAR0DJ600R4_0006_001_1422091_1118859.jpg',
  'source_group_key': 'CF|AR0DJ600R4|PS|2026-06-22 04:50:33',
  'source_defect_uid': 'CF|AR0DJ600R4|PS|2026-06-22 04:50:33|AR0DJ600R4E|0006|RB|M|1422091|1118859|RAR0DJ600R4_0006_001_1422091_1118859.jpg',
  'raw_json': '{"glass_id": "AR0DJ600R4", "chip_id": "AR0DJ600R4E", "model_no": "M270DAN7J-VC51MP000", "testing_date": "2026-06-22 04:50:33", "eqp_id": "FASAOI30", "op": "PS", "defect_no": "0006", "defect_code": "RB", "defect_size_type": "M", "coord_x": "1422091", "coord_y": "1118859", "repair_date": "2026-06-22 09:31:36", "repair_code": null, "repair_eqp_id": "FAAREP42", "repair_op": "REPAIR-PS", "op_norm": "PS", "eqp_id_norm": "FASAOI30", "op_id": "PS", "source_rule": "OP_PS", "op_id_anchor": "PS", "latest_scan_time": "2026-06-22 04:50:33", "op_id_final": "PS"}',
  'create_time': datetime.datetime(2026, 6, 23, 16, 18, 51),
  'update_time': datetime.datetime(2026, 6, 23, 16, 18, 51)},
 {'id': 7,
  'sheet_id': 'AR0DJ600R4',
  'chip_id': 'AR0DJ600R4J',
  'model_no': 'M270DAN7J-VC51MP000',
  'scan_time': datetime.datetime(2026, 6, 22, 4, 50, 33),
  'eqp_id': 'FASAOI30',
  'op': 'PS',
  'repair_time': None,
  'repair_code': 'nan',
  'repair_eqp_id': 'nan',
  'repair_op': 'nan',
  'op_id': 'PS',
  'defect_no': '0011',
  'defect_code': 'TB',
  'defect_size': 'L',
  'defect_size_raw': 'L',
  'ori_x': 1341691.0,
  'ori_y': 1290545.0,
  'trans_x': 1290545.0,
  'trans_y': 158309.0,
  'image_name': 'RAR0DJ600R4_0011_001_1341691_1290545.jpg',
  'img_url_path': 'http://tcweb002.corpnet.auo.com/fafle001/image/PS/4/AR0DJ600R4/RAR0DJ600R4_0011_001_1341691_1290545.jpg',
  'source_group_key': 'CF|AR0DJ600R4|PS|2026-06-22 04:50:33',
  'source_defect_uid': 'CF|AR0DJ600R4|PS|2026-06-22 04:50:33|AR0DJ600R4J|0011|TB|L|1341691|1290545|RAR0DJ600R4_0011_001_1341691_1290545.jpg',
  'raw_json': '{"glass_id": "AR0DJ600R4", "chip_id": "AR0DJ600R4J", "model_no": "M270DAN7J-VC51MP000", "testing_date": "2026-06-22 04:50:33", "eqp_id": "FASAOI30", "op": "PS", "defect_no": "0011", "defect_code": "TB", "defect_size_type": "L", "coord_x": "1341691", "coord_y": "1290545", "repair_date": null, "repair_code": null, "repair_eqp_id": null, "repair_op": null, "op_norm": "PS", "eqp_id_norm": "FASAOI30", "op_id": "PS", "source_rule": "OP_PS", "op_id_anchor": "PS", "latest_scan_time": "2026-06-22 04:50:33", "op_id_final": "PS"}',
  'create_time': datetime.datetime(2026, 6, 23, 16, 18, 51),
  'update_time': datetime.datetime(2026, 6, 23, 16, 18, 51)},
 {'id': 8,
  'sheet_id': 'AR0DJ600R4',
  'chip_id': 'AR0DJ600R4J',
  'model_no': 'M270DAN7J-VC51MP000',
  'scan_time': datetime.datetime(2026, 6, 22, 4, 50, 33),
  'eqp_id': 'FASAOI30',
  'op': 'PS',
  'repair_time': datetime.datetime(2026, 6, 22, 9, 31, 36),
  'repair_code': 'nan',
  'repair_eqp_id': 'FAAREP42',
  'repair_op': 'REPAIR-PS',
  'op_id': 'PS',
  'defect_no': '0010',
  'defect_code': 'TW',
  'defect_size': 'M',
  'defect_size_raw': 'M',
  'ori_x': 1341804.0,
  'ori_y': 1290293.0,
  'trans_x': 1290293.0,
  'trans_y': 158196.0,
  'image_name': 'RAR0DJ600R4_0010_001_1341804_1290293.jpg',
  'img_url_path': 'http://tcweb002.corpnet.auo.com/fafle001/image/PS/4/AR0DJ600R4/RAR0DJ600R4_0010_001_1341804_1290293.jpg',
  'source_group_key': 'CF|AR0DJ600R4|PS|2026-06-22 04:50:33',
  'source_defect_uid': 'CF|AR0DJ600R4|PS|2026-06-22 04:50:33|AR0DJ600R4J|0010|TW|M|1341804|1290293|RAR0DJ600R4_0010_001_1341804_1290293.jpg',
  'raw_json': '{"glass_id": "AR0DJ600R4", "chip_id": "AR0DJ600R4J", "model_no": "M270DAN7J-VC51MP000", "testing_date": "2026-06-22 04:50:33", "eqp_id": "FASAOI30", "op": "PS", "defect_no": "0010", "defect_code": "TW", "defect_size_type": "M", "coord_x": "1341804", "coord_y": "1290293", "repair_date": "2026-06-22 09:31:36", "repair_code": null, "repair_eqp_id": "FAAREP42", "repair_op": "REPAIR-PS", "op_norm": "PS", "eqp_id_norm": "FASAOI30", "op_id": "PS", "source_rule": "OP_PS", "op_id_anchor": "PS", "latest_scan_time": "2026-06-22 04:50:33", "op_id_final": "PS"}',
  'create_time': datetime.datetime(2026, 6, 23, 16, 18, 51),
  'update_time': datetime.datetime(2026, 6, 23, 16, 18, 51)},
 {'id': 9,
  'sheet_id': 'AR0DJ600R4',
  'chip_id': 'AR0DJ600R4K',
  'model_no': 'M270DAN7J-VC51MP000',
  'scan_time': datetime.datetime(2026, 6, 22, 4, 50, 33),
  'eqp_id': 'FASAOI30',
  'op': 'PS',
  'repair_time': None,
  'repair_code': 'nan',
  'repair_eqp_id': 'nan',
  'repair_op': 'nan',
  'op_id': 'PS',
  'defect_no': '0009',
  'defect_code': 'TB',
  'defect_size': 'M',
  'defect_size_raw': 'M',
  'ori_x': 945887.0,
  'ori_y': 1603906.0,
  'trans_x': 1603906.0,
  'trans_y': 554113.0,
  'image_name': 'RAR0DJ600R4_0009_001_0945887_1603906.jpg',
  'img_url_path': 'http://tcweb002.corpnet.auo.com/fafle001/image/PS/4/AR0DJ600R4/RAR0DJ600R4_0009_001_0945887_1603906.jpg',
  'source_group_key': 'CF|AR0DJ600R4|PS|2026-06-22 04:50:33',
  'source_defect_uid': 'CF|AR0DJ600R4|PS|2026-06-22 04:50:33|AR0DJ600R4K|0009|TB|M|0945887|1603906|RAR0DJ600R4_0009_001_0945887_1603906.jpg',
  'raw_json': '{"glass_id": "AR0DJ600R4", "chip_id": "AR0DJ600R4K", "model_no": "M270DAN7J-VC51MP000", "testing_date": "2026-06-22 04:50:33", "eqp_id": "FASAOI30", "op": "PS", "defect_no": "0009", "defect_code": "TB", "defect_size_type": "M", "coord_x": "0945887", "coord_y": "1603906", "repair_date": null, "repair_code": null, "repair_eqp_id": null, "repair_op": null, "op_norm": "PS", "eqp_id_norm": "FASAOI30", "op_id": "PS", "source_rule": "OP_PS", "op_id_anchor": "PS", "latest_scan_time": "2026-06-22 04:50:33", "op_id_final": "PS"}',
  'create_time': datetime.datetime(2026, 6, 23, 16, 18, 51),
  'update_time': datetime.datetime(2026, 6, 23, 16, 18, 51)}]

In [21]:
#rows = db.get_runs_delta_days('incoming_glass_summary_202606', 3, 'scan_time')
rows['sheet_id'].iloc[0:50].to_csv('test_sheet.csv', index=False, header=False)

In [8]:

for tbn in db.list_tables():
    db.drop_table(tbn)

2026-06-26 15:12:31,387 - INFO - [list_tables] 成功取得資料表名稱，共 12 張表。

2026-06-26 15:12:32,830 - INFO - [drop_table] 資料表 'api_aoi_summary_202606' 已刪除.
2026-06-26 15:12:33,285 - INFO - [drop_table] 資料表 'incoming_glass_summary_202606' 已刪除.
2026-06-26 15:12:33,657 - INFO - [drop_table] 資料表 'incoming_governance_state' 已刪除.
2026-06-26 15:12:34,317 - INFO - [drop_table] 資料表 'incoming_same_point_detail_202606' 已刪除.
2026-06-26 15:12:34,643 - INFO - [drop_table] 資料表 'incoming_source_array_mor_defect_raw_202606' 已刪除.
2026-06-26 15:12:35,181 - INFO - [drop_table] 資料表 'incoming_source_array_tar_defect_raw_202605' 已刪除.
2026-06-26 15:12:35,614 - INFO - [drop_table] 資料表 'incoming_source_array_tar_defect_raw_202606' 已刪除.
2026-06-26 15:12:36,222 - INFO - [drop_table] 資料表 'incoming_source_array_tos_defect_raw_202604' 已刪除.
2026-06-26 15:12:36,539 - INFO - [drop_table] 資料表 'incoming_source_array_tos_defect_raw_202605' 已刪除.
2026-06-26 15:12:37,127 - INFO - [drop_table] 資料表 'incoming_source_array_tos_defect_raw_202606' 已刪除.
2026-06-26 15:12:37,457 - INFO - [drop_table] 資料表 'incoming_source_cf_oc_defect_raw_202606' 已刪除.
2026-06-26 15:12:37,821 - INFO - [drop_table] 資料表 'incoming_source_cf_ps_defect_raw_202606' 已刪除.

In [9]:
rows = db.get_rows('incoming_same_point_detail_202606', {'cell_aoi':'CAAOI202'})
df = pd.DataFrame(rows)
df['match_status'].unique()

array(['NO_SAME_POINT', 'SOURCE_NOT_FOUND'], dtype=object)

In [5]:
df = db.get_table('incoming_same_point_detail_202606')
df

,id,sheet_id,scan_time,model_no,abbr_cat,process,recipe_id,cassette_id,cell_aoi,cell_line_id,...,source_scan_time,source_defect_cnt,same_point_offset,same_point_defect_cnt,same_point_rate,point_detail,match_status,match_status_detail,create_time,update_time
0,1,5T6A5604A,2026-06-10 08:14:44,B160UAN5L,TFT,ARRAY,0335,CA0175,CAAOI202,CAPIC100,...,2026-06-05 16:49:03,152.0,1000.0,0.0,0.000000,[],NO_SAME_POINT,source found but no same point; source_defect_...,2026-06-11 16:22:45,2026-06-11 16:22:45
1,2,5T6A5604A,2026-06-10 08:14:44,B160UAN5L,TFT,ARRAY,0335,CA0175,CAAOI202,CAPIC100,...,NaT,NaN,1000.0,NaN,NaN,[],SOURCE_NOT_FOUND,no source defect group for TAR,2026-06-11 16:22:45,2026-06-11 16:22:45
2,3,5T6A5604A,2026-06-10 08:14:44,B160UAN5L,TFT,ARRAY,0335,CA0175,CAAOI202,CAPIC100,...,2026-06-06 15:51:56,1.0,1000.0,0.0,0.000000,[],NO_SAME_POINT,source found but no same point; source_defect_...,2026-06-11 16:22:45,2026-06-11 16:22:45
3,4,5T6A5604B,2026-06-10 08:10:47,B160UAN5L,TFT,ARRAY,0335,CA0175,CAAOI202,CAPIC100,...,2026-06-05 16:49:03,177.0,1000.0,0.0,0.000000,[],NO_SAME_POINT,source found but no same point; source_defect_...,2026-06-11 16:22:45,2026-06-11 16:22:45
4,5,5T6A5604B,2026-06-10 08:10:47,B160UAN5L,TFT,ARRAY,0335,CA0175,CAAOI202,CAPIC100,...,NaT,NaN,1000.0,NaN,NaN,[],SOURCE_NOT_FOUND,no source defect group for TAR,2026-06-11 16:22:45,2026-06-11 16:22:45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,330,YL6A5643V,2026-06-10 11:50:58,B156HAN2U_VB,TFT,ARRAY,01145,AA1774,CAAOI300,CAPIC600,...,2026-06-08 23:19:07,2.0,1000.0,0.0,0.000000,[],NO_SAME_POINT,source found but no same point; source_defect_...,2026-06-11 16:22:45,2026-06-11 16:22:45
330,331,YL6A5643V,2026-06-10 11:50:58,B156HAN2U_VB,TFT,ARRAY,01145,AA1774,CAAOI300,CAPIC600,...,2026-06-07 10:25:37,1.0,1000.0,1.0,1.000000,"[{""cell"": {""cell_defect_uid"": ""YL6A5643V|2026-...",MATCHED,source_same_point_cnt=1; cell_same_point_cnt=2...,2026-06-11 16:22:45,2026-06-11 16:22:45
331,332,YL6A5643W,2026-06-10 11:56:07,B156HAN2U_VB,TFT,ARRAY,01145,AA1774,CAAOI300,CAPIC600,...,2026-06-06 15:27:00,260.0,1000.0,4.0,0.015385,"[{""cell"": {""cell_defect_uid"": ""YL6A5643W|2026-...",MATCHED,source_same_point_cnt=4; cell_same_point_cnt=4...,2026-06-11 16:22:45,2026-06-11 16:22:45
332,333,YL6A5643W,2026-06-10 11:56:07,B156HAN2U_VB,TFT,ARRAY,01145,AA1774,CAAOI300,CAPIC600,...,2026-06-08 23:19:07,5.0,1000.0,2.0,0.400000,"[{""cell"": {""cell_defect_uid"": ""YL6A5643W|2026-...",MATCHED,source_same_point_cnt=2; cell_same_point_cnt=2...,2026-06-11 16:22:45,2026-06-11 16:22:45
333,334,YL6A5643W,2026-06-10 11:56:07,B156HAN2U_VB,TFT,ARRAY,01145,AA1774,CAAOI300,CAPIC600,...,2026-06-07 08:27:32,4.0,1000.0,3.0,0.750000,"[{""cell"": {""cell_defect_uid"": ""YL6A5643W|2026-...",MATCHED,source_same_point_cnt=3; cell_same_point_cnt=3...,2026-06-11 16:22:45,2026-06-11 16:22:45

In [4]:
df = db.get_rows('incoming_glass_summary_202606', {'sheet_id': 'L86A5246J'})
df

[{'id': 211,
  'sheet_id': 'L86A5246J',
  'scan_time': datetime.datetime(2026, 6, 9, 16, 46, 3),
  'model_no': 'M215HAN1G_VB',
  'abbr_cat': 'TFT',
  'process': 'ARRAY',
  'recipe_id': '07086',
  'cassette_id': 'CA0335',
  'cell_aoi': 'CAAOI300',
  'cell_line_id': 'CAPIC200',
  'pi_time': datetime.datetime(2026, 6, 8, 5, 53, 9),
  'cell_op': 'API',
  'cell_defect_cnt': 210,
  'source_station_cnt': 3,
  'source_found_station_cnt': 1,
  'total_source_defect_cnt': 2,
  'total_same_point_defect_cnt': 36,
  'total_same_point_rate': 0.17142857142857143,
  'cf_oc_source_defect_cnt': 0,
  'cf_ps_source_defect_cnt': 0,
  'array_mor_source_defect_cnt': 0,
  'array_tar_source_defect_cnt': 0,
  'array_tos_source_defect_cnt': 2,
  'cf_oc_same_point_cnt': 0,
  'cf_ps_same_point_cnt': 0,
  'array_mor_same_point_cnt': 0,
  'array_tar_same_point_cnt': 0,
  'array_tos_same_point_cnt': 36,
  'judge': 'MATCHED',
  'judge_detail': 'cell_defect_cnt=210; source_found_station_cnt=1; total_source_defect_cnt=2; total_same_point_defect_cnt=36',
  'create_time': datetime.datetime(2026, 6, 11, 10, 14, 59),
  'update_time': datetime.datetime(2026, 6, 11, 10, 14, 59)}]

In [ ]:
[{
    "cell": {
        "cell_defect_uid": "AE1UA600E0|2026-06-08 10:27:24|1123",
        "chip_id": "", 
        "defect_code": "", 
        "retype_def_code": "", 
        "defect_size": "S", 
        "ori_x": 592905.0,
        "ori_y": 899232.0, 
        "trans_x": 592905.0, 
        "trans_y": 600768.0, 
        "image_name": "", 
        "img_url_path": "http://l6apaimg103/dms/CELAIDI_L6A/PIT/2606/08/CAPIT203/AE1UA600E0/1027/"
        }, 
    "source": {
        "process": "CF", 
        "source_op_id": "OC", 
        "scan_time": "2026-06-07 01:52:29", 
        "chip_id": "AE1UA600E0K",
        "defect_no": "0007", 
        "defect_code": "TB", 
        "defect_size": "M", 
        "ori_x": 898215.0, 
        "ori_y": 591007.0, 
        "trans_x": 591007.0, 
        "trans_y": 601785.0, 
        "image_name": "RAE1UA600E0_0007_001_898215_591007.jpg", 
        "img_url_path": "http://tcweb002.corpnet.auo.com/fafle001/image/OC/0/AE1UA600E0/RAE1UA600E0_0007_001_898215_591007.jpg", 
        "source_group_key": "CF|AE1UA600E0|OC|2026-06-07 01:52:29"
        }, 
    "match": {
        "offset": 3000.0, 
        "dx": 1898.0, 
        "dy": 1017.0, 
        "distance": 2153.2981679275167, 
        "rank": 1, 
        "is_nearest": 1
        }
    }]