In [1]:
import requests
import time
import pandas as pd
from models.sql_db_connect import MySQLConnet
from datetime import datetime, timedelta
from routers.inspection.aoi_inspection import Config
dbhandler = MySQLConnet('l6a01_project')
tbns = dbhandler.list_tables()
cfg = Config()

2026-01-08 14:38:37,527 - INFO - [list_tables] 成功取得資料表名稱，共 165 張表。

INSPECTION連線時間: 2026-01-08 14:38:37.527682(202601)

In [ ]:
details = {[19000, 4519, 0, (14481)]
            [5943, 10092, 4000, (-192)]
            [10864, 92573, 0+0+0+45589, (-26608)] 
            #8784+1499+3502+69276; (870+2780+2438+10000+2200+646+10395+7760+8500)
            [0, 8803, 7702, (-279)],
            [304, 3419, 942, (-2173)]} #-(145+29+105)
total = -14771 #
other_total = 58233 #4000+45589+7702+942

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\Ray\AppData\Local\Temp\ipykernel_17224\3674646339.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  details = {[19000, 4519, 0, (14481)]
C:\Users\Ray\AppData\Local\Temp\ipykernel_17224\3674646339.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  details = {[19000, 4519, 0, (14481)]
C:\Users\Ray\AppData\Local\Temp\ipykernel_17224\3674646339.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  details = {[19000, 4519, 0, (14481)]
C:\Users\Ray\AppData\Local\Temp\ipykernel_17224\3674646339.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  details = {[19000, 4519, 0, (14481)]
C:\Users\Ray\AppData\Local\Temp\ipykernel_17224\3674646339.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  details = {[19000, 4519, 0, (14481)]

TypeError: list indices must be integers or slices, not tuple

In [ ]:
payload = {'mode': 'comment', 
           'tabKey': None, 
           'changes': None, 
           'row': {'pi_hour': '25-12-31 23', 'line_id': 'CAPIC107', 'model': 'B116XAN06', 'glass_type': 'TFT'}, 
           'system': 'inspection', 
           'comment': '123', 
           'editor': '', 
            'modify_time': '2026-01-02T14:19:44+08:00'} #2026-01-02 09:09:12

In [2]:
now = datetime.now()
ym = now.strftime("%Y%m")
print(f"連線時間: {now}({ym})")
one_mon_ago = now - timedelta(days=30)

連線時間: 2026-01-08 14:38:43.752559(202601)

In [ ]:
path = "D:\A0_Project\AOI_Inspection\other\TFT_SPEC.csv"
df = pd.read_csv(path)
df.columns = ['pi', 'model', 'glass_type', 'line_id', 'OOC', 'OOS']#.iloc[:,1:]


df['line_id'] = df['line_id'].apply(lambda x: f'{x[:-1]}7')
#dbhandler.save_df(df, 'aoi_inspection_default_spectable')
df.head()

2025-11-26 08:50:22,941 - INFO - [save_df] 資料表 'aoi_inspection_default_spectable' 已覆蓋儲存 (721 rows).

      pi      model glass_type   line_id  OOC  OOS
0  PI100  A101EAN01        TFT  CAPIC107  0.5  0.8
1  PI100  B070AAN01        TFT  CAPIC107  0.5  0.8
2  PI100  B070AAN1Y        TFT  CAPIC107  0.5  0.8
3  PI100  B080EAN05        TFT  CAPIC107  0.5  0.8
4  PI100  B101EAN02        TFT  CAPIC107  0.5  0.8

In [14]:

tbn = 'aoi_density_spec_for_aoimonitor'
#spec_df = dbhandler.get_table(tbn)
spec_df2 = dbhandler.get_table(tbn)
spec_df2.head()

,line_id,MODEL_ID,MODEL_TYPE,DEFECT_CODE,PROCESS_TYPE,SIZE_TYPE,OOC,OOS,Editor,modify_time,drop
0,CAPIC100,B070AAN01,Normal,PIS With Particle,BIG,OL,0.28,0.33,預設,2025-12-24 15:56:23,F
1,CAPIC100,B070AAN01,Normal,PIS With Particle,BIG,OLMS,2,3,預設,2025-12-09 08:00:00,F
2,CAPIC100,B070AAN01,Normal,PI_Spot_NP,BIG,OL,0.33,0.57,預設,2025-12-09 08:00:00,F
3,CAPIC100,B070AAN01,Normal,PI_Spot_NP,BIG,OLMS,300,300,預設,2025-12-09 08:00:00,F
4,CAPIC100,B070AAN01,Normal,Polymer,BIG,OLMS,5,10,預設,2025-12-09 08:00:00,F

In [9]:
print(len(spec_df))
key_cols = ['MODEL_ID', 'MODEL_TYPE', 'DEFECT_CODE','SIZE_TYPE']

default_df = spec_df.copy()
default_df = default_df[default_df['drop'] == 'F']
default_df = default_df.drop_duplicates(subset=key_cols, keep='last')
default_df = default_df.sort_values(key_cols)
default_df.reset_index(drop = True, inplace = True)
print(len(default_df))
default_df.head()

1064
1060

,MODEL_ID,MODEL_TYPE,DEFECT_CODE,PROCESS_TYPE,SIZE_TYPE,OOC,OOS,Editor,modify_time,drop
0,B070AAN01,Normal,PIS With Particle,BIG,OL,0.28,0.33,預設,2025-12-24 15:56:23,F
1,B070AAN01,Normal,PIS With Particle,BIG,OLMS,2,3,預設,2025-12-09 08:00:00,F
2,B070AAN01,Normal,PI_Spot_NP,BIG,OL,0.33,0.57,預設,2025-12-09 08:00:00,F
3,B070AAN01,Normal,PI_Spot_NP,BIG,OLMS,300,300,預設,2025-12-09 08:00:00,F
4,B070AAN01,Normal,Polymer,BIG,OLMS,5,10,預設,2025-12-09 08:00:00,F

In [10]:
old_rows = default_df.copy()
default_spec_table_cols = ['line_id', 'MODEL_ID', 'MODEL_TYPE', 'DEFECT_CODE', 'PROCESS_TYPE', 'SIZE_TYPE',
       'OOC', 'OOS', 'Editor', 'modify_time', 'drop']
all_rows = pd.DataFrame(columns = default_spec_table_cols)
for line in [f'CAPIC{i}00' for i in range(1,8,1)]:
    print(line)
    old_rows['line_id'] = line
    old_rows = old_rows[default_spec_table_cols]
    all_rows = pd.concat([all_rows, old_rows ])

print(len(all_rows))

CAPIC100
CAPIC200
CAPIC300
CAPIC400
CAPIC500
CAPIC600
CAPIC700
7420

In [13]:
dbhandler.save_table(tbn,all_rows)

2026-01-08 14:46:59,145 - INFO - [save_table] l6a01_project.aoi_density_spec_for_aoimonitor 已寫入 7420 列（去除 0 重複）

7420

In [12]:
all_rows.head()

,line_id,MODEL_ID,MODEL_TYPE,DEFECT_CODE,PROCESS_TYPE,SIZE_TYPE,OOC,OOS,Editor,modify_time,drop
0,CAPIC100,B070AAN01,Normal,PIS With Particle,BIG,OL,0.28,0.33,預設,2025-12-24 15:56:23,F
1,CAPIC100,B070AAN01,Normal,PIS With Particle,BIG,OLMS,2,3,預設,2025-12-09 08:00:00,F
2,CAPIC100,B070AAN01,Normal,PI_Spot_NP,BIG,OL,0.33,0.57,預設,2025-12-09 08:00:00,F
3,CAPIC100,B070AAN01,Normal,PI_Spot_NP,BIG,OLMS,300,300,預設,2025-12-09 08:00:00,F
4,CAPIC100,B070AAN01,Normal,Polymer,BIG,OLMS,5,10,預設,2025-12-09 08:00:00,F

In [11]:
[v for v in tbns if 'density_' in v]

['aoi100_pidensity_202509_pi000',
 'aoi100_pidensity_202509_pi100',
 'aoi100_pidensity_202509_pi200',
 'aoi100_pidensity_202509_pi300',
 'aoi100_pidensity_202509_pi400',
 'aoi100_pidensity_202509_pi500',
 'aoi100_pidensity_202509_pi600',
 'aoi100_pidensity_202509_pi700',
 'aoi100_pidensity_202510_pi000',
 'aoi100_pidensity_202510_pi100',
 'aoi100_pidensity_202510_pi200',
 'aoi100_pidensity_202510_pi300',
 'aoi100_pidensity_202510_pi400',
 'aoi100_pidensity_202510_pi500',
 'aoi100_pidensity_202510_pi600',
 'aoi100_pidensity_202510_pi700',
 'aoi100_pidensity_202511_pi000',
 'aoi100_pidensity_202511_pi100',
 'aoi100_pidensity_202511_pi200',
 'aoi100_pidensity_202511_pi300',
 'aoi100_pidensity_202511_pi400',
 'aoi100_pidensity_202511_pi500',
 'aoi100_pidensity_202511_pi600',
 'aoi100_pidensity_202511_pi700',
 'aoi100_pidensity_202512_pi000',
 'aoi100_pidensity_202512_pi100',
 'aoi100_pidensity_202512_pi200',
 'aoi100_pidensity_202512_pi300',
 'aoi100_pidensity_202512_pi400',
 'aoi100_pidensity_202512_pi500',
 'aoi100_pidensity_202512_pi600',
 'aoi100_pidensity_202512_pi700',
 'aoi100_pidensity_202601_pi000',
 'aoi100_pidensity_202601_pi100',
 'aoi100_pidensity_202601_pi200',
 'aoi100_pidensity_202601_pi300',
 'aoi100_pidensity_202601_pi400',
 'aoi100_pidensity_202601_pi500',
 'aoi100_pidensity_202601_pi600',
 'aoi100_pidensity_202601_pi700',
 'aoi200_pidensity_202509_pi000',
 'aoi200_pidensity_202509_pi100',
 'aoi200_pidensity_202509_pi200',
 'aoi200_pidensity_202509_pi300',
 'aoi200_pidensity_202509_pi400',
 'aoi200_pidensity_202509_pi500',
 'aoi200_pidensity_202509_pi600',
 'aoi200_pidensity_202509_pi700',
 'aoi200_pidensity_202510_pi000',
 'aoi200_pidensity_202510_pi100',
 'aoi200_pidensity_202510_pi200',
 'aoi200_pidensity_202510_pi300',
 'aoi200_pidensity_202510_pi400',
 'aoi200_pidensity_202510_pi500',
 'aoi200_pidensity_202510_pi600',
 'aoi200_pidensity_202510_pi700',
 'aoi200_pidensity_202511_pi000',
 'aoi200_pidensity_202511_pi100',
 'aoi200_pidensity_202511_pi200',
 'aoi200_pidensity_202511_pi300',
 'aoi200_pidensity_202511_pi400',
 'aoi200_pidensity_202511_pi500',
 'aoi200_pidensity_202511_pi600',
 'aoi200_pidensity_202511_pi700',
 'aoi200_pidensity_202512_pi000',
 'aoi200_pidensity_202512_pi100',
 'aoi200_pidensity_202512_pi200',
 'aoi200_pidensity_202512_pi300',
 'aoi200_pidensity_202512_pi400',
 'aoi200_pidensity_202512_pi500',
 'aoi200_pidensity_202512_pi600',
 'aoi200_pidensity_202512_pi700',
 'aoi200_pidensity_202601_pi000',
 'aoi200_pidensity_202601_pi100',
 'aoi200_pidensity_202601_pi200',
 'aoi200_pidensity_202601_pi300',
 'aoi200_pidensity_202601_pi400',
 'aoi200_pidensity_202601_pi500',
 'aoi200_pidensity_202601_pi600',
 'aoi200_pidensity_202601_pi700',
 'aoi300_pidensity_202511_pi000',
 'aoi300_pidensity_202511_pi100',
 'aoi300_pidensity_202511_pi200',
 'aoi300_pidensity_202511_pi300',
 'aoi300_pidensity_202511_pi400',
 'aoi300_pidensity_202511_pi500',
 'aoi300_pidensity_202511_pi600',
 'aoi300_pidensity_202511_pi700',
 'aoi300_pidensity_202512_pi000',
 'aoi300_pidensity_202512_pi100',
 'aoi300_pidensity_202512_pi200',
 'aoi300_pidensity_202512_pi300',
 'aoi300_pidensity_202512_pi400',
 'aoi300_pidensity_202512_pi500',
 'aoi300_pidensity_202512_pi600',
 'aoi300_pidensity_202512_pi700',
 'aoi300_pidensity_202601_pi000',
 'aoi300_pidensity_202601_pi100',
 'aoi300_pidensity_202601_pi200',
 'aoi300_pidensity_202601_pi300',
 'aoi300_pidensity_202601_pi400',
 'aoi300_pidensity_202601_pi500',
 'aoi300_pidensity_202601_pi600',
 'aoi300_pidensity_202601_pi700',
 'aoi_density_fixed_spec_table',
 'aoi_density_for_aoimonitor',
 'aoi_density_spec_for_aoimonitor',
 'pidensity_202509',
 'pidensity_202510',
 'pidensity_202511',
 'pidensity_202512',
 'pidensity_202601']

In [51]:
tb = dbhandler.get_table('pidensity_202512')
tb.head()
#

,pi_hour,aoi,pi,line_id,model,glass_type,recipe_id,defect_type,ai_code_1,n_rows,n_glasses,small_defect_count,middle_defect_count,large_defect_count,over_defect_count,unknown_defect_count,glass,comment
0,2025-11-30 07:00:00,AOI200,PI200,CAPIC200,M270DANA0,TFT,2236,,Not_Found,1,1,1,0,0,0,0,VN5AAXQ3C,
1,2025-11-30 07:00:00,AOI200,PI200,CAPIC200,M270DANA0,TFT,2236,,NPI_TFT,5,1,5,0,0,0,0,VN5AAXQ3C,
2,2025-11-30 07:00:00,AOI200,PI200,CAPIC200,M270DANA0,TFT,2236,,OP_Defect,51,1,39,12,0,0,0,VN5AAXQ3C,
3,2025-11-30 07:00:00,AOI200,PI200,CAPIC200,M270DANA0,TFT,2236,,PI_Gel,1,1,1,0,0,0,0,VN5AAXQ3C,
4,2025-11-30 07:00:00,AOI200,PI200,CAPIC200,M270DANA0,TFT,2236,Particle,Polymer,1,1,0,1,0,0,0,VN5AAXQ3C,

In [55]:
#for tbn in ['pidensity_202511','pidensity_202512','pidensity_202601']:
#    tb = dbhandler.get_table(tbn)
#    print(tbn)
for key, rows in tb.groupby(['glass', 'pi_hour']):
    
    if len(rows)>1:
        print(key, len(rows))
        print(rows[[
            'pi_hour', 'aoi', 'line_id', 'model',
            'glass_type', 'recipe_id', 'ai_code_1', 'pic_paths',
            'maingroup_glass_count', 'maingroup_defect_count',
            'defect_code_glass_count', 'defect_code_count',
            'small_defect_count', 'middle_defect_count', 'large_defect_count', 'over_defect_count',
            'glass', 'comment'
        ]])

('2N5ABLS71', Timestamp('2025-12-18 08:00:00')) 1456

KeyError: "['pic_paths', 'maingroup_glass_count', 'maingroup_defect_count', 'defect_code_glass_count', 'defect_code_count'] not in index"

In [ ]:
def process1_(x):
    vals = []
    if ':' in x:
        print('ok', x)
        return x
    for gld in x.split(","):
        vals.append(f'{gld}:S=0;M=0;L=0;O=0')
    val = ",".join(vals)  # 建議這裡用逗號分隔每片 glass
    #print(val)
    return val

tb['glass_size_detail'] = tb.apply(
    lambda row: process1_(row['glass']) if row['glass_size_detail'] == '' else row['glass_size_detail'],
    axis=1  )

A25ACPC54:S=0;M=0;L=0;O=0,A25ACPC0A:S=0;M=0;L=0;O=0,A25ACPC0B:S=0;M=0;L=0;O=0
AG0UAC0E78:S=0;M=0;L=0;O=0,AG0UAC0E5U:S=0;M=0;L=0;O=0,AG0UAC0EFG:S=0;M=0;L=0;O=0,AG0UAC0E5W:S=0;M=0;L=0;O=0,AG0UAC0EFJ:S=0;M=0;L=0;O=0,AG0UAC0E5Y:S=0;M=0;L=0;O=0,AG0UAC0EJR:S=0;M=0;L=0;O=0,AG0UAC0EJS:S=0;M=0;L=0;O=0,AG0UAC0EJT:S=0;M=0;L=0;O=0,AG0UAC0EN5:S=0;M=0;L=0;O=0,AG0UAC0ENA:S=0;M=0;L=0;O=0,AG0UAC0EJU:S=0;M=0;L=0;O=0,AG0UAC0EH4:S=0;M=0;L=0;O=0,AG0UAC0EFU:S=0;M=0;L=0;O=0,AG0UAC0EH2:S=0;M=0;L=0;O=0
AA1X6C06LF:S=0;M=0;L=0;O=0
AG0UAC0EHC:S=0;M=0;L=0;O=0,AG0UAC0EHD:S=0;M=0;L=0;O=0,AG0UAC0EH5:S=0;M=0;L=0;O=0,AG0UAC0EH8:S=0;M=0;L=0;O=0,AG0UAC0EJW:S=0;M=0;L=0;O=0,AG0UAC0EH9:S=0;M=0;L=0;O=0,AG0UAC0ENS:S=0;M=0;L=0;O=0,AG0UAC0ENJ:S=0;M=0;L=0;O=0,AG0UAC0ENG:S=0;M=0;L=0;O=0,AG0UAC0ENH:S=0;M=0;L=0;O=0,AG0UAC0ENK:S=0;M=0;L=0;O=0,AG0UAC0ENL:S=0;M=0;L=0;O=0,AG0UAC0EPQ:S=0;M=0;L=0;O=0,AG0UAC0ENP:S=0;M=0;L=0;O=0,AG0UAC0EPR:S=0;M=0;L=0;O=0,AG0UAC0ENR:S=0;M=0;L=0;O=0,AG0UAC0EPN:S=0;M=0;L=0;O=0,AG0UAC0EPP:S=0;M=0;L=0;O=0,AG0UAC0EG8:S=0;M=0;L=0;O=0,AG0UAC0E7J:S=0;M=0;L=0;O=0,AG0UAC0E8R:S=0;M=0;L=0;O=0,AG0UAC0E8S:S=0;M=0;L=0;O=0,AG0UAC0E8P:S=0;M=0;L=0;O=0,AG0UAC0E8Q:S=0;M=0;L=0;O=0,AG0UAC0E8M:S=0;M=0;L=0;O=0,AG0UAC0ECT:S=0;M=0;L=0;O=0,AG0UAC0ELS:S=0;M=0;L=0;O=0,AG0UAC0ELU:S=0;M=0;L=0;O=0,AG0UAC0ELT:S=0;M=0;L=0;O=0,AG0UAC0ELW:S=0;M=0;L=0;O=0,AG0UAC0ELV:S=0;M=0;L=0;O=0,AG0UAC0ELX:S=0;M=0;L=0;O=0,AG0UAC0ELY:S=0;M=0;L=0;O=0,AG0UAC0EN8:S=0;M=0;L=0;O=0,AG0UAC0ELZ:S=0;M=0;L=0;O=0,AG0UAC0EM2:S=0;M=0;L=0;O=0,AG0UAC0EH7:S=0;M=0;L=0;O=0,AG0UAC0EHB:S=0;M=0;L=0;O=0,AG0UAC0EF8:S=0;M=0;L=0;O=0,AG0UAC0EDR:S=0;M=0;L=0;O=0,AG0UAC0ER8:S=0;M=0;L=0;O=0,AG0UAC0EFA:S=0;M=0;L=0;O=0,AG0UAC0EJQ:S=0;M=0;L=0;O=0,AG0UAC0EDT:S=0;M=0;L=0;O=0,AG0UAC0EPH:S=0;M=0;L=0;O=0,AG0UAC0EN7:S=0;M=0;L=0;O=0,AG0UAC0EPJ:S=0;M=0;L=0;O=0,AG0UAC0EHT:S=0;M=0;L=0;O=0,AG0UAC0EHS:S=0;M=0;L=0;O=0,AG0UAC0EHN:S=0;M=0;L=0;O=0,AG0UAC0EHP:S=0;M=0;L=0;O=0,AG0UAC0EHM:S=0;M=0;L=0;O=0,AG0UAC0EHL:S=0;M=0;L=0;O=0,AG0UAC0EHJ:S=0;M=0;L=0;O=0,AG0UAC0EHA:S=0;M=0;L=0;O=0,AG0UAC0EHF:S=0;M=0;L=0;O=0,AG0UAC0EHG:S=0;M=0;L=0;O=0,AG0UAC0E6Y:S=0;M=0;L=0;O=0,AG0UAC0E75:S=0;M=0;L=0;O=0,AG0UAC0E76:S=0;M=0;L=0;O=0,AG0UAC0EHY:S=0;M=0;L=0;O=0,AG0UAC0EJ0:S=0;M=0;L=0;O=0,AG0UAC0F3M:S=0;M=0;L=0;O=0,AG0UAC0F3P:S=0;M=0;L=0;O=0,AG0UAC0F3R:S=0;M=0;L=0;O=0,AG0UAC0F3S:S=0;M=0;L=0;O=0,AG0UAC0EN3:S=0;M=0;L=0;O=0
A25ACPC3Y:S=0;M=0;L=0;O=0,A25ACPC3Z:S=0;M=0;L=0;O=0,A25ACPC31:S=0;M=0;L=0;O=0,A25ACPC32:S=0;M=0;L=0;O=0,A25ACPC33:S=0;M=0;L=0;O=0,A25ACPC34:S=0;M=0;L=0;O=0
AL5HZC08NZ:S=0;M=0;L=0;O=0,AL5HZC092Y:S=0;M=0;L=0;O=0,AL5HZC08QB:S=0;M=0;L=0;O=0,AL5HZC08P0:S=0;M=0;L=0;O=0,MQ5ACWS5U:S=0;M=0;L=0;O=0,MQ5ACWR94:S=0;M=0;L=0;O=0,AL5HZC08W3:S=0;M=0;L=0;O=0
Y25ACQS24:S=0;M=0;L=0;O=0,AF0U3C03BR:S=0;M=0;L=0;O=0
AF0U3C04Y1:S=0;M=0;L=0;O=0,AF0U3C04Y5:S=0;M=0;L=0;O=0,AF0U3C04W9:S=0;M=0;L=0;O=0,AF0U3C04Y9:S=0;M=0;L=0;O=0,AF0U3C04Y3:S=0;M=0;L=0;O=0,AF0U3C04Y7:S=0;M=0;L=0;O=0,AF0U3C04XZ:S=0;M=0;L=0;O=0,AF0U3C03PK:S=0;M=0;L=0;O=0,AF0U3C03QG:S=0;M=0;L=0;O=0,AF0U3C03QB:S=0;M=0;L=0;O=0,AF0U3C03PL:S=0;M=0;L=0;O=0,AF0U3C03PJ:S=0;M=0;L=0;O=0,AF0U3C051P:S=0;M=0;L=0;O=0,AF0U3C04EW:S=0;M=0;L=0;O=0,AF0U3C051E:S=0;M=0;L=0;O=0,AF0U3C051K:S=0;M=0;L=0;O=0,AF0U3C04F1:S=0;M=0;L=0;O=0,AF0U3C04DW:S=0;M=0;L=0;O=0,AF0U3C04FS:S=0;M=0;L=0;O=0,AF0U3C04FR:S=0;M=0;L=0;O=0,AF0U3C04FL:S=0;M=0;L=0;O=0,AF0U3C04F8:S=0;M=0;L=0;O=0,AF0U3C04FK:S=0;M=0;L=0;O=0,AF0U3C04FF:S=0;M=0;L=0;O=0,AF0U3C04F9:S=0;M=0;L=0;O=0,AF0U3C04FC:S=0;M=0;L=0;O=0,AF0U3C04FB:S=0;M=0;L=0;O=0,AF0U3C04FG:S=0;M=0;L=0;O=0,AF0U3C04FA:S=0;M=0;L=0;O=0,AF0U3C04FD:S=0;M=0;L=0;O=0,AF0U3C04FE:S=0;M=0;L=0;O=0,AF0U3C04EZ:S=0;M=0;L=0;O=0,AF0U3C04FH:S=0;M=0;L=0;O=0,AF0U3C04FJ:S=0;M=0;L=0;O=0,AF0U3C04F4:S=0;M=0;L=0;O=0,AF0U3C04MB:S=0;M=0;L=0;O=0,AF0U3C04ER:S=0;M=0;L=0;O=0,AF0U3C04QF:S=0;M=0;L=0;O=0,AF0U3C04ET:S=0;M=0;L=0;O=0,AF0U3C04EQ:S=0;M=0;L=0;O=0
Y25ACQR2A:S=0;M=0;L=0;O=0,Y25ACQR2B:S=0;M=0;L=0;O=0,Y25ACQR2C:S=0;M=0;L=0;O=0,Y25ACQR2D:S=0;M=0;L=0;O=0,Y25ACQR2E:S=0;M=0;L=0;O=0,Y25ACQR2F:S=0;M=0;L=0;O=0,Y25ACQR2G:S=0;M=0;L=0;O=0,Y25ACQR2H:S=0;M=0;L=0;O=0,Y25ACQR2J:S=0;M=0;L=0;O=0,Y25ACQR2K:S=0;M=0;L=0;O=0,Y25ACQR2L:S=0;M=0;L=0;O=0,Y25ACQR2M:S=0;M=0;L=0;O=0
AF0U3C04JD:S=0;M=0;L=0;O=0,AF0U3C04J7:S=0;M=0;L=0;O=0,AF0U3C04J8:S=0;M=0;L=0;O=0,AF0U3C04JA:S=0;M=0;L=0;O=0,AF0U3C04SG:S=0;M=0;L=0;O=0,AF0U3C04SD:S=0;M=0;L=0;O=0,AF0U3C04S7:S=0;M=0;L=0;O=0,AF0U3C03G6:S=0;M=0;L=0;O=0,AF0U3C03EW:S=0;M=0;L=0;O=0,AF0U3C03F0:S=0;M=0;L=0;O=0,AF0U3C03E9:S=0;M=0;L=0;O=0,AF0U3C03F3:S=0;M=0;L=0;O=0,AF0U3C03FA:S=0;M=0;L=0;O=0,AF0U3C03BX:S=0;M=0;L=0;O=0,AF0U3C03BW:S=0;M=0;L=0;O=0,AF0U3C04UX:S=0;M=0;L=0;O=0,AF0U3C03BU:S=0;M=0;L=0;O=0,AF0U3C04HT:S=0;M=0;L=0;O=0,AF0U3C04HS:S=0;M=0;L=0;O=0,AF0U3C04JZ:S=0;M=0;L=0;O=0,AF0U3C04HR:S=0;M=0;L=0;O=0,AF0U3C04HV:S=0;M=0;L=0;O=0,AF0U3C04HX:S=0;M=0;L=0;O=0,AF0U3C04HY:S=0;M=0;L=0;O=0,AF0U3C04JT:S=0;M=0;L=0;O=0,AF0U3C04HZ:S=0;M=0;L=0;O=0,AF0U3C04HN:S=0;M=0;L=0;O=0,AF0U3C04K8:S=0;M=0;L=0;O=0,AF0U3C04JN:S=0;M=0;L=0;O=0,AF0U3C04K7:S=0;M=0;L=0;O=0,AF0U3C04K5:S=0;M=0;L=0;O=0,AF0U3C04K2:S=0;M=0;L=0;O=0,AF0U3C04K3:S=0;M=0;L=0;O=0,AF0U3C04JV:S=0;M=0;L=0;O=0,AF0U3C04K0:S=0;M=0;L=0;O=0,AF0U3C04JY:S=0;M=0;L=0;O=0
AF0U3C04JU:S=0;M=0;L=0;O=0,AF0U3C04JX:S=0;M=0;L=0;O=0,AF0U3C04JQ:S=0;M=0;L=0;O=0,AF0U3C04JR:S=0;M=0;L=0;O=0
Y25ACRB6A:S=0;M=0;L=0;O=0,Y25ACRB6B:S=0;M=0;L=0;O=0,Y25ACRB6C:S=0;M=0;L=0;O=0,Y25ACRB6D:S=0;M=0;L=0;O=0
AF0U3C03BY:S=0;M=0;L=0;O=0
LV5ACLH9A:S=0;M=0;L=0;O=0,LV5ACLH9B:S=0;M=0;L=0;O=0,LV5ACLH9C:S=0;M=0;L=0;O=0
AL5HZC08X2:S=0;M=0;L=0;O=0,AL5HZC08X3:S=0;M=0;L=0;O=0,AL5HZC08VY:S=0;M=0;L=0;O=0,AL5HZC08X0:S=0;M=0;L=0;O=0,AL5HZC08X1:S=0;M=0;L=0;O=0,AL5HZC08WZ:S=0;M=0;L=0;O=0,AL5HZC08WY:S=0;M=0;L=0;O=0,AL5HZC08W2:S=0;M=0;L=0;O=0,AL5HZC08VZ:S=0;M=0;L=0;O=0
Q65ABLS34:S=0;M=0;L=0;O=0,LV5ACLH9E:S=0;M=0;L=0;O=0,LV5ACLH9F:S=0;M=0;L=0;O=0
LV5ACRE1A:S=0;M=0;L=0;O=0,LV5ACRE1B:S=0;M=0;L=0;O=0,LV5ACRE1C:S=0;M=0;L=0;O=0,LV5ACRE1D:S=0;M=0;L=0;O=0,LV5ACRE1E:S=0;M=0;L=0;O=0,LV5ACRE1F:S=0;M=0;L=0;O=0,LV5ACRE1G:S=0;M=0;L=0;O=0,LV5ACRE1H:S=0;M=0;L=0;O=0,LV5ACRE1J:S=0;M=0;L=0;O=0,LV5ACRE1K:S=0;M=0;L=0;O=0,LV5ACRE1L:S=0;M=0;L=0;O=0,LV5ACRE1M:S=0;M=0;L=0;O=0,LV5ACRE1N:S=0;M=0;L=0;O=0,LV5ACRE1P:S=0;M=0;L=0;O=0,LV5ACRE1Q:S=0;M=0;L=0;O=0,LV5ACRE1R:S=0;M=0;L=0;O=0,LV5ACRE1S:S=0;M=0;L=0;O=0,LV5ACRE1T:S=0;M=0;L=0;O=0,LV5ACRE1U:S=0;M=0;L=0;O=0,LV5ACRE1V:S=0;M=0;L=0;O=0,LV5ACRE1W:S=0;M=0;L=0;O=0,LV5ACRE1X:S=0;M=0;L=0;O=0,LV5ACRE1Y:S=0;M=0;L=0;O=0
AL5HZC094X:S=0;M=0;L=0;O=0,AL5HZC094U:S=0;M=0;L=0;O=0,AL5HZC094V:S=0;M=0;L=0;O=0,AL5HZC094S:S=0;M=0;L=0;O=0,AL5HZC094T:S=0;M=0;L=0;O=0,AL5HZC094Q:S=0;M=0;L=0;O=0,AL5HZC094R:S=0;M=0;L=0;O=0,AL5HZC094N:S=0;M=0;L=0;O=0,AL5HZC094K:S=0;M=0;L=0;O=0,AL5HZC094P:S=0;M=0;L=0;O=0,AL5HZC094L:S=0;M=0;L=0;O=0,AL5HZC095V:S=0;M=0;L=0;O=0,AL5HZC095S:S=0;M=0;L=0;O=0,AL5HZC095T:S=0;M=0;L=0;O=0,AL5HZC092H:S=0;M=0;L=0;O=0,AL5HZC08M0:S=0;M=0;L=0;O=0,AL5HZC095Q:S=0;M=0;L=0;O=0,AL5HZC092F:S=0;M=0;L=0;O=0,AL5HZC092E:S=0;M=0;L=0;O=0,AL5HZC092C:S=0;M=0;L=0;O=0,AL5HZC08WC:S=0;M=0;L=0;O=0
AF0U3C03RE:S=0;M=0;L=0;O=0,AF0U3C03FK:S=0;M=0;L=0;O=0,AF0U3C03FM:S=0;M=0;L=0;O=0,AF0U3C03FP:S=0;M=0;L=0;O=0,AF0U3C04LU:S=0;M=0;L=0;O=0,AF0U3C04KA:S=0;M=0;L=0;O=0,AF0U3C04LT:S=0;M=0;L=0;O=0,AF0U3C04LW:S=0;M=0;L=0;O=0,AF0U3C04LS:S=0;M=0;L=0;O=0,AF0U3C03TQ:S=0;M=0;L=0;O=0,AF0U3C03FF:S=0;M=0;L=0;O=0,AF0U3C03GD:S=0;M=0;L=0;O=0,AF0U3C04QL:S=0;M=0;L=0;O=0
AL5HZC08FH:S=0;M=0;L=0;O=0,AL5HZC08FF:S=0;M=0;L=0;O=0,AL5HZC08FG:S=0;M=0;L=0;O=0,AL5HZC08LV:S=0;M=0;L=0;O=0,AL5HZC08LU:S=0;M=0;L=0;O=0,AL5HZC08LT:S=0;M=0;L=0;O=0,AL5HZC08LS:S=0;M=0;L=0;O=0,AL5HZC08LR:S=0;M=0;L=0;O=0,AL5HZC08FX:S=0;M=0;L=0;O=0,AL5HZC08JT:S=0;M=0;L=0;O=0,AL5HZC08HB:S=0;M=0;L=0;O=0,AL5HZC08S1:S=0;M=0;L=0;O=0,AL5HZC08S4:S=0;M=0;L=0;O=0,AL5HZC08S6:S=0;M=0;L=0;O=0,AL5HZC093G:S=0;M=0;L=0;O=0,AL5HZC0933:S=0;M=0;L=0;O=0,AL5HZC0934:S=0;M=0;L=0;O=0,AL5HZC096C:S=0;M=0;L=0;O=0
AF6H6C05YA:S=0;M=0;L=0;O=0,AF6H6C05Y9:S=0;M=0;L=0;O=0,AF6H6C05VW:S=0;M=0;L=0;O=0,AF6H6C05Y8:S=0;M=0;L=0;O=0,AF6H6C05UM:S=0;M=0;L=0;O=0,AF6H6C05JW:S=0;M=0;L=0;O=0,AF6H6C06RT:S=0;M=0;L=0;O=0,AF6H6C06RW:S=0;M=0;L=0;O=0,AF6H6C06T9:S=0;M=0;L=0;O=0,AF6H6C06KK:S=0;M=0;L=0;O=0,AF6H6C06KF:S=0;M=0;L=0;O=0
AF0U3C03R5:S=0;M=0;L=0;O=0,AF0U3C03R4:S=0;M=0;L=0;O=0,AF0U3C03QY:S=0;M=0;L=0;O=0,AF0U3C03QZ:S=0;M=0;L=0;O=0
AF6H6C06NB:S=0;M=0;L=0;O=0,AF6H6C06N8:S=0;M=0;L=0;O=0,AF6H6C06QE:S=0;M=0;L=0;O=0,AF6H6C06SR:S=0;M=0;L=0;O=0,AF6H6C06P3:S=0;M=0;L=0;O=0,AF6H6C06QX:S=0;M=0;L=0;O=0,AF6H6C06KS:S=0;M=0;L=0;O=0,AF6H6C06QT:S=0;M=0;L=0;O=0
AF0UTC005J:S=0;M=0;L=0;O=0,AF0UTC005Y:S=0;M=0;L=0;O=0,AF0UTC005Z:S=0;M=0;L=0;O=0,AF0UTC00BB:S=0;M=0;L=0;O=0,AF0UTC00BG:S=0;M=0;L=0;O=0,AF0UTC008N:S=0;M=0;L=0;O=0,AF0UTC008R:S=0;M=0;L=0;O=0,AF0UTC00DJ:S=0;M=0;L=0;O=0,AF0UTC00DW:S=0;M=0;L=0;O=0,AF0UTC00DG:S=0;M=0;L=0;O=0,AF0UTC008E:S=0;M=0;L=0;O=0,AF0UTC001D:S=0;M=0;L=0;O=0,AF0UTC00DR:S=0;M=0;L=0;O=0,AF0UTC008S:S=0;M=0;L=0;O=0,AF0UTC00DM:S=0;M=0;L=0;O=0,AF0UTC0085:S=0;M=0;L=0;O=0
LV5ACLH9C:S=0;M=0;L=0;O=0,LV5ACLH9B:S=0;M=0;L=0;O=0,LV5ACLH9A:S=0;M=0;L=0;O=0
AF6H6C06G9:S=0;M=0;L=0;O=0
AF6H6C06G6:S=0;M=0;L=0;O=0,AF6H6C06G7:S=0;M=0;L=0;O=0,AF6H6C06G5:S=0;M=0;L=0;O=0
AF0UTC00LP:S=0;M=0;L=0;O=0
AF0UTC00LQ:S=0;M=0;L=0;O=0
AF6H6C06P0:S=0;M=0;L=0;O=0,AF6H6C06S9:S=0;M=0;L=0;O=0,AF6H6C06P1:S=0;M=0;L=0;O=0,AF6H6C06PJ:S=0;M=0;L=0;O=0,AF6H6C06LU:S=0;M=0;L=0;O=0,AF6H6C06N5:S=0;M=0;L=0;O=0,AF6H6C06MD:S=0;M=0;L=0;O=0,AF6H6C06N4:S=0;M=0;L=0;O=0,AF6H6C06UQ:S=0;M=0;L=0;O=0,AF6H6C06QV:S=0;M=0;L=0;O=0,AF6H6C06M1:S=0;M=0;L=0;O=0,AF6H6C06NF:S=0;M=0;L=0;O=0,AF6H6C06N1:S=0;M=0;L=0;O=0,AF6H6C06NE:S=0;M=0;L=0;O=0,AF6H6C06JV:S=0;M=0;L=0;O=0,AF6H6C06UR:S=0;M=0;L=0;O=0,AF6H6C06NA:S=0;M=0;L=0;O=0,AF6H6C06QW:S=0;M=0;L=0;O=0,AF6H6C06ND:S=0;M=0;L=0;O=0,AF6H6C06NC:S=0;M=0;L=0;O=0,AF6H6C06KQ:S=0;M=0;L=0;O=0,AF6H6C06US:S=0;M=0;L=0;O=0,AF6H6C06UP:S=0;M=0;L=0;O=0
AF0UTC00HS:S=0;M=0;L=0;O=0,AF0UTC00GR:S=0;M=0;L=0;O=0,AF0UTC00H3:S=0;M=0;L=0;O=0,AF0UTC00A2:S=0;M=0;L=0;O=0,AF0UTC00A7:S=0;M=0;L=0;O=0,AF0UTC00A6:S=0;M=0;L=0;O=0,AF0UTC00G3:S=0;M=0;L=0;O=0,AF0UTC00D3:S=0;M=0;L=0;O=0,AF0UTC00CZ:S=0;M=0;L=0;O=0,AF0UTC00GN:S=0;M=0;L=0;O=0,AF0UTC00J3:S=0;M=0;L=0;O=0,AF0UTC00GL:S=0;M=0;L=0;O=0,AF0UTC00GP:S=0;M=0;L=0;O=0,AF0UTC00GK:S=0;M=0;L=0;O=0
AF0UTC0057:S=0;M=0;L=0;O=0,AF0UTC0050:S=0;M=0;L=0;O=0,AF0UTC0056:S=0;M=0;L=0;O=0,AF0UTC0055:S=0;M=0;L=0;O=0,AF0UTC0001:S=0;M=0;L=0;O=0,AF0UTC002C:S=0;M=0;L=0;O=0,AF0UTC002B:S=0;M=0;L=0;O=0,AF0UTC000G:S=0;M=0;L=0;O=0,AF0UTC0023:S=0;M=0;L=0;O=0,AF0UTC000N:S=0;M=0;L=0;O=0,AF0UTC00N2:S=0;M=0;L=0;O=0,AF0UTC000V:S=0;M=0;L=0;O=0,AF0UTC002D:S=0;M=0;L=0;O=0,AF0UTC0027:S=0;M=0;L=0;O=0,AF0UTC0024:S=0;M=0;L=0;O=0,AF0UTC0025:S=0;M=0;L=0;O=0,AF0UTC000P:S=0;M=0;L=0;O=0,AF0UTC003Q:S=0;M=0;L=0;O=0,AF0UTC004X:S=0;M=0;L=0;O=0,AF0UTC004V:S=0;M=0;L=0;O=0,AF0UTC00AE:S=0;M=0;L=0;O=0,AF0UTC004Y:S=0;M=0;L=0;O=0,AF0UTC007S:S=0;M=0;L=0;O=0,AF0UTC007M:S=0;M=0;L=0;O=0,AF0UTC001K:S=0;M=0;L=0;O=0,AF0UTC00CJ:S=0;M=0;L=0;O=0,AF0UTC00GC:S=0;M=0;L=0;O=0,AF0UTC00EF:S=0;M=0;L=0;O=0
AF6H6C06SL:S=0;M=0;L=0;O=0,AF6H6C06V1:S=0;M=0;L=0;O=0,AF6H6C06SN:S=0;M=0;L=0;O=0,AF6H6C06SM:S=0;M=0;L=0;O=0,AF6H6C06PW:S=0;M=0;L=0;O=0,AF6H6C06PZ:S=0;M=0;L=0;O=0,AF6H6C06PY:S=0;M=0;L=0;O=0,AF6H6C06Q0:S=0;M=0;L=0;O=0,AF6H6C06LL:S=0;M=0;L=0;O=0,AF6H6C06Q2:S=0;M=0;L=0;O=0,AF6H6C06Q3:S=0;M=0;L=0;O=0,AF6H6C06NH:S=0;M=0;L=0;O=0,AF6H6C06NG:S=0;M=0;L=0;O=0,AF6H6C06NK:S=0;M=0;L=0;O=0,AF6H6C06NJ:S=0;M=0;L=0;O=0,AF6H6C06NM:S=0;M=0;L=0;O=0,AF6H6C06NL:S=0;M=0;L=0;O=0,AF6H6C06NP:S=0;M=0;L=0;O=0,AF6H6C06NN:S=0;M=0;L=0;O=0,AF6H6C06NR:S=0;M=0;L=0;O=0,AF6H6C06R0:S=0;M=0;L=0;O=0,AF6H6C06SF:S=0;M=0;L=0;O=0,AF6H6C06QQ:S=0;M=0;L=0;O=0,AF6H6C06JT:S=0;M=0;L=0;O=0,AF6H6C06S5:S=0;M=0;L=0;O=0,AF6H6C06S4:S=0;M=0;L=0;O=0,AF6H6C06QY:S=0;M=0;L=0;O=0,AF6H6C06LC:S=0;M=0;L=0;O=0,AF6H6C06M6:S=0;M=0;L=0;O=0,AF6H6C06M9:S=0;M=0;L=0;O=0,AF6H6C06M8:S=0;M=0;L=0;O=0,AF6H6C06MB:S=0;M=0;L=0;O=0,AF6H6C06RC:S=0;M=0;L=0;O=0,AF6H6C06RE:S=0;M=0;L=0;O=0,AF6H6C06RH:S=0;M=0;L=0;O=0,AF6H6C06RG:S=0;M=0;L=0;O=0,AF6H6C06RK:S=0;M=0;L=0;O=0,AF6H6C06RJ:S=0;M=0;L=0;O=0,AF6H6C06RM:S=0;M=0;L=0;O=0,AF6H6C06RL:S=0;M=0;L=0;O=0,AF6H6C06RP:S=0;M=0;L=0;O=0,AF6H6C06R8:S=0;M=0;L=0;O=0,AF6H6C06RN:S=0;M=0;L=0;O=0,AF6H6C06RQ:S=0;M=0;L=0;O=0,AF6H6C06RB:S=0;M=0;L=0;O=0,AF6H6C06UU:S=0;M=0;L=0;O=0
AG0UHC01RG:S=0;M=0;L=0;O=0
AF0UTC003T:S=0;M=0;L=0;O=0,AF0UTC0037:S=0;M=0;L=0;O=0,AF0UTC003L:S=0;M=0;L=0;O=0,AF0UTC00FG:S=0;M=0;L=0;O=0,AF0UTC00CB:S=0;M=0;L=0;O=0,AF0UTC00CA:S=0;M=0;L=0;O=0,AF0UTC00AT:S=0;M=0;L=0;O=0,AF0UTC00C4:S=0;M=0;L=0;O=0,AF0UTC00C9:S=0;M=0;L=0;O=0,AF0UTC00C3:S=0;M=0;L=0;O=0,AF0UTC00C0:S=0;M=0;L=0;O=0,AF0UTC00C1:S=0;M=0;L=0;O=0,AF0UTC001T:S=0;M=0;L=0;O=0,AF0UTC00BX:S=0;M=0;L=0;O=0,AF0UTC0010:S=0;M=0;L=0;O=0,AF0UTC00BZ:S=0;M=0;L=0;O=0,AF0UTC00E1:S=0;M=0;L=0;O=0
AG0UHC01LU:S=0;M=0;L=0;O=0,AG0UHC01RY:S=0;M=0;L=0;O=0,AG0UHC01S3:S=0;M=0;L=0;O=0,AG0UHC01MH:S=0;M=0;L=0;O=0,AG0UHC01MW:S=0;M=0;L=0;O=0,AG0UHC01YS:S=0;M=0;L=0;O=0,AG0UHC01UK:S=0;M=0;L=0;O=0,AG0UHC01MZ:S=0;M=0;L=0;O=0,AG0UHC01YU:S=0;M=0;L=0;O=0,AG0UHC01QQ:S=0;M=0;L=0;O=0,AG0UHC01NS:S=0;M=0;L=0;O=0,AG0UHC01M1:S=0;M=0;L=0;O=0,AG0UHC01UC:S=0;M=0;L=0;O=0,AG0UHC01LM:S=0;M=0;L=0;O=0,AG0UHC01Z3:S=0;M=0;L=0;O=0,AG0UHC01Z1:S=0;M=0;L=0;O=0,AG0UHC01Y3:S=0;M=0;L=0;O=0,AG0UHC01RA:S=0;M=0;L=0;O=0,AG0UHC01QV:S=0;M=0;L=0;O=0,AG0UHC01NQ:S=0;M=0;L=0;O=0,AG0UHC01YR:S=0;M=0;L=0;O=0,AG0UHC01P4:S=0;M=0;L=0;O=0
AF0UTC00DV:S=0;M=0;L=0;O=0,AF0UTC000Z:S=0;M=0;L=0;O=0,AF0UTC00E8:S=0;M=0;L=0;O=0,AF0UTC0069:S=0;M=0;L=0;O=0,AF0UTC00FN:S=0;M=0;L=0;O=0,AF0UTC0065:S=0;M=0;L=0;O=0,AF0UTC00E5:S=0;M=0;L=0;O=0,AF0UTC00EA:S=0;M=0;L=0;O=0,AF0UTC00EE:S=0;M=0;L=0;O=0,AF0UTC00DU:S=0;M=0;L=0;O=0,AF0UTC0084:S=0;M=0;L=0;O=0
UC5ABR59A:S=0;M=0;L=0;O=0,UC5ABR59B:S=0;M=0;L=0;O=0,UC5ABR59C:S=0;M=0;L=0;O=0,UC5ABR59D:S=0;M=0;L=0;O=0,UC5ABR59E:S=0;M=0;L=0;O=0,UC5ABR59F:S=0;M=0;L=0;O=0,UC5ABR59G:S=0;M=0;L=0;O=0,UC5ABR59H:S=0;M=0;L=0;O=0,UC5ABR59J:S=0;M=0;L=0;O=0,UC5ABR59K:S=0;M=0;L=0;O=0,UC5ABR59L:S=0;M=0;L=0;O=0,UC5ABR59M:S=0;M=0;L=0;O=0,UC5ABR59N:S=0;M=0;L=0;O=0,UC5ABR59P:S=0;M=0;L=0;O=0,UC5ABR59Q:S=0;M=0;L=0;O=0,UC5ABR59R:S=0;M=0;L=0;O=0,UC5ABR59S:S=0;M=0;L=0;O=0,UC5ABR59T:S=0;M=0;L=0;O=0,UC5ABR59U:S=0;M=0;L=0;O=0,UC5ABR59V:S=0;M=0;L=0;O=0,UC5ABR59W:S=0;M=0;L=0;O=0,UC5ABR59X:S=0;M=0;L=0;O=0,UC5ABR592:S=0;M=0;L=0;O=0,UC5ABR59Y:S=0;M=0;L=0;O=0,UC5ABR59Z:S=0;M=0;L=0;O=0,UC5ABR591:S=0;M=0;L=0;O=0,UC5ABR593:S=0;M=0;L=0;O=0,UC5ABR594:S=0;M=0;L=0;O=0,UC5ABWW3A:S=0;M=0;L=0;O=0,UC5ABWW3B:S=0;M=0;L=0;O=0,UC5ABWW3C:S=0;M=0;L=0;O=0,UC5ABWW3D:S=0;M=0;L=0;O=0,UC5ABWW3E:S=0;M=0;L=0;O=0,UC5ABWW3F:S=0;M=0;L=0;O=0,UC5ABWW3G:S=0;M=0;L=0;O=0,UC5ABWW3H:S=0;M=0;L=0;O=0,UC5ABWW3J:S=0;M=0;L=0;O=0,UC5ABWW3K:S=0;M=0;L=0;O=0,UC5ABWW3L:S=0;M=0;L=0;O=0,UC5ABWW3M:S=0;M=0;L=0;O=0,UC5ABWW3N:S=0;M=0;L=0;O=0,UC5ABWW3P:S=0;M=0;L=0;O=0,UC5ABWW3Q:S=0;M=0;L=0;O=0,UC5ABWW3R:S=0;M=0;L=0;O=0,UC5ABWW3S:S=0;M=0;L=0;O=0,UC5ABWW3T:S=0;M=0;L=0;O=0,UC5ABWW3U:S=0;M=0;L=0;O=0,UC5ABWW3V:S=0;M=0;L=0;O=0,UC5ABWW3W:S=0;M=0;L=0;O=0
AG0UHC01NP:S=0;M=0;L=0;O=0,AG0UHC01NH:S=0;M=0;L=0;O=0,AG0UHC01NM:S=0;M=0;L=0;O=0,AG0UHC01Z4:S=0;M=0;L=0;O=0,AG0UHC01SZ:S=0;M=0;L=0;O=0,AG0UHC01WY:S=0;M=0;L=0;O=0,AG0UHC01T1:S=0;M=0;L=0;O=0,AG0UHC01WC:S=0;M=0;L=0;O=0,AG0UHC01HZ:S=0;M=0;L=0;O=0,AG0UHC01WW:S=0;M=0;L=0;O=0,AG0UHC01X1:S=0;M=0;L=0;O=0,AG0UHC01WK:S=0;M=0;L=0;O=0,AG0UHC01WS:S=0;M=0;L=0;O=0,AG0UHC01WA:S=0;M=0;L=0;O=0,AG0UHC01WX:S=0;M=0;L=0;O=0
AF0UTC0081:S=0;M=0;L=0;O=0,AF0UTC0082:S=0;M=0;L=0;O=0,AF0UTC00MP:S=0;M=0;L=0;O=0,AF0UTC0083:S=0;M=0;L=0;O=0,AF0UTC00AL:S=0;M=0;L=0;O=0,AF0UTC008J:S=0;M=0;L=0;O=0,AF0UTC00L5:S=0;M=0;L=0;O=0,AF0UTC00MA:S=0;M=0;L=0;O=0,AF0UTC00LE:S=0;M=0;L=0;O=0,AF0UTC007C:S=0;M=0;L=0;O=0,AF0UTC0077:S=0;M=0;L=0;O=0,AF0UTC00MK:S=0;M=0;L=0;O=0,AF0UTC0078:S=0;M=0;L=0;O=0,AF0UTC0021:S=0;M=0;L=0;O=0,AF0UTC0036:S=0;M=0;L=0;O=0,AF0UTC0039:S=0;M=0;L=0;O=0,AF0UTC003A:S=0;M=0;L=0;O=0,AF0UTC001U:S=0;M=0;L=0;O=0,AF0UTC00DD:S=0;M=0;L=0;O=0,AF0UTC001P:S=0;M=0;L=0;O=0,AF0UTC00DF:S=0;M=0;L=0;O=0,AF0UTC0014:S=0;M=0;L=0;O=0,AF0UTC000L:S=0;M=0;L=0;O=0,AF0UTC00JZ:S=0;M=0;L=0;O=0,AF0UTC00K2:S=0;M=0;L=0;O=0,AF0UTC0064:S=0;M=0;L=0;O=0,AF0UTC0066:S=0;M=0;L=0;O=0,AF0UTC0068:S=0;M=0;L=0;O=0,AF0UTC007D:S=0;M=0;L=0;O=0,AF0UTC0029:S=0;M=0;L=0;O=0,AF0UTC00CU:S=0;M=0;L=0;O=0,AF0UTC00CT:S=0;M=0;L=0;O=0,AF0UTC00CL:S=0;M=0;L=0;O=0,AF0UTC00CS:S=0;M=0;L=0;O=0,AF0UTC0061:S=0;M=0;L=0;O=0,AF0UTC00C7:S=0;M=0;L=0;O=0,AF0UTC00B6:S=0;M=0;L=0;O=0,AF0UTC001R:S=0;M=0;L=0;O=0,AF0UTC0020:S=0;M=0;L=0;O=0,AF0UTC001Q:S=0;M=0;L=0;O=0,AF0UTC0038:S=0;M=0;L=0;O=0,AF0UTC0033:S=0;M=0;L=0;O=0,AF0UTC00F7:S=0;M=0;L=0;O=0,AF0UTC00F1:S=0;M=0;L=0;O=0,AF0UTC006X:S=0;M=0;L=0;O=0,AF0UTC0016:S=0;M=0;L=0;O=0,AF0UTC00DQ:S=0;M=0;L=0;O=0,AF0UTC00FJ:S=0;M=0;L=0;O=0,AF0UTC00FM:S=0;M=0;L=0;O=0,AF0UTC00E7:S=0;M=0;L=0;O=0,AF0UTC00EK:S=0;M=0;L=0;O=0,AF0UTC00GX:S=0;M=0;L=0;O=0
UC5ABWW3X:S=0;M=0;L=0;O=0,UC5ABWW3Y:S=0;M=0;L=0;O=0,UC5ABWW3Z:S=0;M=0;L=0;O=0,UC5ABWW31:S=0;M=0;L=0;O=0,UC5ABWW32:S=0;M=0;L=0;O=0,UC5ABWW33:S=0;M=0;L=0;O=0,UC5ABWW34:S=0;M=0;L=0;O=0
AG0UHC01SR:S=0;M=0;L=0;O=0,AG0UHC01JS:S=0;M=0;L=0;O=0,AG0UHC01KE:S=0;M=0;L=0;O=0,AG0UHC01HR:S=0;M=0;L=0;O=0,AG0UHC01HP:S=0;M=0;L=0;O=0,AG0UHC01JZ:S=0;M=0;L=0;O=0,AG0UHC01JT:S=0;M=0;L=0;O=0,AG0UHC01SC:S=0;M=0;L=0;O=0,AG0UHC01WM:S=0;M=0;L=0;O=0,AG0UHC01WE:S=0;M=0;L=0;O=0,AG0UHC01WH:S=0;M=0;L=0;O=0,AG0UHC01KA:S=0;M=0;L=0;O=0,AG0UHC01MU:S=0;M=0;L=0;O=0,AG0UHC01MY:S=0;M=0;L=0;O=0,AG0UHC01KD:S=0;M=0;L=0;O=0,AG0UHC01QM:S=0;M=0;L=0;O=0,AG0UHC01NN:S=0;M=0;L=0;O=0
AF0UTC00GY:S=0;M=0;L=0;O=0,AF0UTC00HA:S=0;M=0;L=0;O=0,AF0UTC00GZ:S=0;M=0;L=0;O=0,AF0UTC00H0:S=0;M=0;L=0;O=0,AF0UTC00F9:S=0;M=0;L=0;O=0,AF0UTC00FC:S=0;M=0;L=0;O=0,AF0UTC00ME:S=0;M=0;L=0;O=0,AF0UTC00DS:S=0;M=0;L=0;O=0,AF0UTC00M1:S=0;M=0;L=0;O=0,AF0UTC000Y:S=0;M=0;L=0;O=0,AF0UTC007B:S=0;M=0;L=0;O=0,AF0UTC00K8:S=0;M=0;L=0;O=0,AF0UTC000S:S=0;M=0;L=0;O=0,AF0UTC00KZ:S=0;M=0;L=0;O=0,AF0UTC00D7:S=0;M=0;L=0;O=0,AF0UTC00KW:S=0;M=0;L=0;O=0,AF0UTC00D0:S=0;M=0;L=0;O=0,AF0UTC00BM:S=0;M=0;L=0;O=0,AF0UTC001Y:S=0;M=0;L=0;O=0,AF0UTC00F2:S=0;M=0;L=0;O=0,AF0UTC001E:S=0;M=0;L=0;O=0,AF0UTC003S:S=0;M=0;L=0;O=0
AG0UHC01LT:S=0;M=0;L=0;O=0,AG0UHC01LR:S=0;M=0;L=0;O=0,AG0UHC01LP:S=0;M=0;L=0;O=0,AG0UHC01LQ:S=0;M=0;L=0;O=0,AG0UHC01M5:S=0;M=0;L=0;O=0,AG0UHC01K7:S=0;M=0;L=0;O=0,AG0UHC01K5:S=0;M=0;L=0;O=0,AG0UHC01K2:S=0;M=0;L=0;O=0,AG0UHC01KQ:S=0;M=0;L=0;O=0,AG0UHC01NT:S=0;M=0;L=0;O=0,AG0UHC01QH:S=0;M=0;L=0;O=0,AG0UHC01H9:S=0;M=0;L=0;O=0,AG0UHC01KM:S=0;M=0;L=0;O=0
AF0UTC00KQ:S=0;M=0;L=0;O=0,AF0UTC00J8:S=0;M=0;L=0;O=0,AF0UTC00JV:S=0;M=0;L=0;O=0,AF0UTC00EY:S=0;M=0;L=0;O=0,AF0UTC00GE:S=0;M=0;L=0;O=0,AF0UTC00BJ:S=0;M=0;L=0;O=0,AF0UTC00EN:S=0;M=0;L=0;O=0,AF0UTC0060:S=0;M=0;L=0;O=0,AF0UTC008K:S=0;M=0;L=0;O=0,AF0UTC005U:S=0;M=0;L=0;O=0,AF0UTC005T:S=0;M=0;L=0;O=0,AF0UTC005D:S=0;M=0;L=0;O=0,AF0UTC005V:S=0;M=0;L=0;O=0,AF0UTC005W:S=0;M=0;L=0;O=0,AF0UTC005G:S=0;M=0;L=0;O=0,AF0UTC00BE:S=0;M=0;L=0;O=0
UC5ABWV8A:S=0;M=0;L=0;O=0,UC5ABWV8B:S=0;M=0;L=0;O=0,UC5ABWV8C:S=0;M=0;L=0;O=0,UC5ABWV8D:S=0;M=0;L=0;O=0,UC5ABWV8E:S=0;M=0;L=0;O=0,UC5ABWV8F:S=0;M=0;L=0;O=0,UC5ABWV8G:S=0;M=0;L=0;O=0
AG0UHC01US:S=0;M=0;L=0;O=0,AG0UHC01UP:S=0;M=0;L=0;O=0,AG0UHC01UM:S=0;M=0;L=0;O=0,AG0UHC01W8:S=0;M=0;L=0;O=0,AG0UHC01UQ:S=0;M=0;L=0;O=0
UC5ABWV8M:S=0;M=0;L=0;O=0
AG0UHC01J9:S=0;M=0;L=0;O=0,AG0UHC01JA:S=0;M=0;L=0;O=0,AG0UHC01JD:S=0;M=0;L=0;O=0,AG0UHC01TZ:S=0;M=0;L=0;O=0,AG0UHC01YD:S=0;M=0;L=0;O=0,AG0UHC01YC:S=0;M=0;L=0;O=0,AG0UHC01Y7:S=0;M=0;L=0;O=0,AG0UHC01Z8:S=0;M=0;L=0;O=0,AG0UHC01Y6:S=0;M=0;L=0;O=0,AG0UHC01Y4:S=0;M=0;L=0;O=0,AG0UHC01Y2:S=0;M=0;L=0;O=0,AG0UHC01QK:S=0;M=0;L=0;O=0,AG0UHC01NR:S=0;M=0;L=0;O=0,AG0UHC01VY:S=0;M=0;L=0;O=0,AG0UHC01W4:S=0;M=0;L=0;O=0,AG0UHC01W9:S=0;M=0;L=0;O=0,AG0UHC01W3:S=0;M=0;L=0;O=0,AG0UHC01VW:S=0;M=0;L=0;O=0,AG0UHC01W1:S=0;M=0;L=0;O=0,AG0UHC01W0:S=0;M=0;L=0;O=0,AG0UHC01VU:S=0;M=0;L=0;O=0,AG0UHC01VZ:S=0;M=0;L=0;O=0,AG0UHC01JJ:S=0;M=0;L=0;O=0,AG0UHC01W5:S=0;M=0;L=0;O=0,AG0UHC01VX:S=0;M=0;L=0;O=0,AG0UHC01VS:S=0;M=0;L=0;O=0,AG0UHC01SN:S=0;M=0;L=0;O=0,AG0UHC01VP:S=0;M=0;L=0;O=0,AG0UHC01PF:S=0;M=0;L=0;O=0,AG0UHC01LK:S=0;M=0;L=0;O=0,AG0UHC01LL:S=0;M=0;L=0;O=0,AG0UHC01LH:S=0;M=0;L=0;O=0,AG0UHC01LJ:S=0;M=0;L=0;O=0,AG0UHC01ZF:S=0;M=0;L=0;O=0,AG0UHC01N6:S=0;M=0;L=0;O=0,AG0UHC01T8:S=0;M=0;L=0;O=0,AG0UHC01TM:S=0;M=0;L=0;O=0,AG0UHC01TC:S=0;M=0;L=0;O=0,AG0UHC01ST:S=0;M=0;L=0;O=0,AG0UHC01TJ:S=0;M=0;L=0;O=0,AG0UHC01TE:S=0;M=0;L=0;O=0

In [34]:
tb.head()

,pi_hour,line_id,model,glass_type,maingroup_glass_count,maingroup_defect_count,defect_code_glass_count,small_defect_count,middle_defect_count,large_defect_count,over_defect_count,glass,comment,action,glass_size_detail,Editor,modify_time
0,2025-12-31 23,CAPIC107,B116XAN06,CF,28,18,11,0,8,3,7,"AA1X6C06L6,AA1X6C06L4,AA1X6C06LN,AA1X6C06LD,AA...",,,"AA1X6C06L6:S=0;M=0;L=0;O=2,AA1X6C06L4:S=0;M=1;...",,2026-01-02 09:09:12
1,2025-12-31 23,CAPIC107,B116XAN06,TFT,3,0,0,0,0,0,0,"A25ACPC54,A25ACPC0A,A25ACPC0B",,,"A25ACPC54:S=0;M=0;L=0;O=0,A25ACPC0A:S=0;M=0;L=...",,2026-01-02 09:09:12
2,2025-12-31 23,CAPIC307,B160UAN4A,CF,15,0,0,0,0,0,0,"AG0UAC0E78,AG0UAC0E5U,AG0UAC0EFG,AG0UAC0E5W,AG...",,,"AG0UAC0E78:S=0;M=0;L=0;O=0,AG0UAC0E5U:S=0;M=0;...",,2026-01-02 09:09:12
3,2026-01-01 00,CAPIC107,B116XAN06,CF,1,0,0,0,0,0,0,AA1X6C06LF,,,AA1X6C06LF:S=0;M=0;L=0;O=0,,2026-01-02 09:09:12
4,2026-01-01 00,CAPIC107,B116XAN06,TFT,67,8,7,3,2,0,3,"A25ACPC0C,A25ACPC0D,A25ACPC0E,A25ACPC0F,A25ACP...",,,"A25ACPC0C:S=0;M=0;L=0;O=0,A25ACPC0D:S=0;M=0;L=...",,2026-01-02 09:09:12

In [ ]:
import logging
from typing import List, Any
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy import create_engine, text, inspect

def get_rows_df_in(
        dbhandler,
        table_name: str,
        base_keys: dict,
        in_key: str,
        in_values: List[Any]
    ) -> pd.DataFrame:
    """
    一次撈出某欄位值在 in_values 裡的所有列，回傳 DataFrame。

    參數：
        - table_name: 資料表名稱
        - base_keys: 其他 AND 條件，例如 {'RECIPE_NAME': xxx, 'TOOL_ID': yyy}
        - in_key:    要做 IN 的欄位名稱，例如 'SHEET_ID'
        - in_values: 要篩選的值列表，例如 ['YH5ABVX2A', 'YH5ABVX2B', ...]

    回傳：
        - pandas.DataFrame（可能為空 df）
    """
    if not in_values:
        logging.info(f"[get_rows_df_in] in_values 為空，直接回傳空 DataFrame.")
        return pd.DataFrame()

    try:
        where_parts = []
        params = {}

        # 固定條件 (RECIPE_NAME / TOOL_ID ...) → k = :k
        for k, v in (base_keys or {}).items():
            where_parts.append(f"{k} = :{k}")
            params[k] = v

        # IN 條件：in_key IN (:in_0, :in_1, ...)
        placeholders = []
        for idx, val in enumerate(in_values):
            p_name = f"in_{idx}"
            placeholders.append(f":{p_name}")
            params[p_name] = val
        where_parts.append(f"{in_key} IN ({', '.join(placeholders)})")

        where_clause = " AND ".join(where_parts)
        sql = f"SELECT * FROM `{table_name}` WHERE {where_clause}"

        logging.debug(f"[get_rows_df_in] SQL: {sql}  params: {params}")

        with dbhandler.engine.connect() as conn:
            result = conn.execute(text(sql), params)
            rows = result.mappings().all()

        if not rows:
            logging.info(f"[get_rows_df_in] '{table_name}' 無符合條件資料.")
            return pd.DataFrame()

        df = pd.DataFrame(rows)
        logging.info(f"[get_rows_df_in] 成功取得 '{table_name}' 共 {len(df)} 筆符合條件資料.")
        return df

    except SQLAlchemyError as e:
        logging.error(f"[get_rows_df_in] 查詢 '{table_name}' 發生錯誤: {e}")
        return pd.DataFrame()

In [44]:
from typing import Dict, Any, List, Union
import pandas as pd
import numpy as np

def group_defects_by_glass(
    rows: Union[List[Dict[str, Any]], "pd.DataFrame"]
) -> Dict[str, Dict[str, Any]]:
    """
    將 RAW defect 資料依 SHEET_ID 分組，並輸出：
      - defect_map：該片玻璃所有缺陷點 (x, y, size, img)
      - S/M/L/O/total：各尺寸缺陷數統計

    支援輸入：
      - List[Dict]：例如 SQLAlchemy .mappings().all() 轉成的 row
      - pandas.DataFrame：會自動只取關鍵欄位做清理
    """
    if rows is None:
        return {}

    # 1) 統一轉成 DataFrame
    if isinstance(rows, pd.DataFrame):
        df = rows.copy()
    else:
        if not rows:
            return {}
        df = pd.DataFrame.from_records(rows)

    # 2) 只保留必要欄位，缺少的補上
    needed_cols = ["SHEET_ID", "TOOL_ID", "COORD_X", "COORD_Y", "DEFECT_SIZE_TYPE", "IMG_URL"]
    for col in needed_cols:
        if col not in df.columns:
            # 座標預設 NaN，其他用空字串
            df[col] = np.nan if col in ("COORD_X", "COORD_Y") else ""

    df = df[needed_cols].copy()

    # 3) 型別與清理
    df["SHEET_ID"] = df["SHEET_ID"].astype(str).fillna("")
    df["TOOL_ID"] = df["TOOL_ID"].astype(str).fillna("")

    df["COORD_X"] = pd.to_numeric(df["COORD_X"], errors="coerce")
    df["COORD_Y"] = pd.to_numeric(df["COORD_Y"], errors="coerce")

    # DEFECT_SIZE_TYPE → size (S/M/L/O/None)
    df["size"] = (
        df["DEFECT_SIZE_TYPE"]
        .astype(str)
        .str.strip()
        .str.upper()
        .where(df["DEFECT_SIZE_TYPE"].notna(), None)
    )

    # 4) 座標轉換（依 TOOL_ID）
    df["x"] = df["COORD_X"]
    df["y"] = df["COORD_Y"]

    mask_flip1 = df["TOOL_ID"].isin(["CAPIC207", "CAPIC507", "CAPIC407"])
    mask_flip2 = df["TOOL_ID"].isin(["CAPIC107", "CAPIC307", "CAPIC607", "CAPIC707"])

    # CAPIC207 / 507 / 407
    df.loc[mask_flip1, "x"] = 1850 + df.loc[mask_flip1, "COORD_Y"]
    df.loc[mask_flip1, "y"] = -df.loc[mask_flip1, "COORD_X"]

    # CAPIC107 / 307 / 607 / 707
    df.loc[mask_flip2, "x"] = 1850 - df.loc[mask_flip2, "COORD_Y"]
    df.loc[mask_flip2, "y"] = df.loc[mask_flip2, "COORD_X"]

    # 放大 1000 倍後取整數
    df["x_out"] = (df["x"] * 1000).round().astype("Int64")
    df["y_out"] = (df["y"] * 1000).round().astype("Int64")

    # 如果某些點完全沒有座標，可以選擇丟掉
    df = df.dropna(subset=["x_out", "y_out"])

    # ----（選擇性）Debug：看每片玻璃的缺陷數----
    # print(df.groupby("SHEET_ID").size())

    # 5) 依 SHEET_ID 分組並組裝輸出
    out: Dict[str, Dict[str, Any]] = {}

    for gid, g in df.groupby("SHEET_ID"):
        gid_str = str(gid) if gid is not None else ""

        # 各尺寸計數
        size_counts = g["size"].value_counts()
        s_cnt = int(size_counts.get("S", 0))
        m_cnt = int(size_counts.get("M", 0))
        l_cnt = int(size_counts.get("L", 0))
        o_cnt = int(size_counts.get("O", 0))
        total = s_cnt + m_cnt + l_cnt + o_cnt

        # defect_map list
        defect_map = []
        for x, y, size, img in zip(
            g["x_out"], g["y_out"], g["size"], g["IMG_URL"]
        ):
            defect_map.append(
                {
                    "x": str(int(x)),
                    "y": str(int(y)),
                    "size": size,
                    "img": img if img is not None else "",
                }
            )
        """
        out[gid_str] = {
            "defect_map": defect_map,
            "S": s_cnt,
            "M": m_cnt,
            "L": l_cnt,
            "O": o_cnt,
            "total": total,
        }
        """
        out[gid_str] = defect_map
    return out

In [3]:
row = {
    'line_id': 'line_id'
}
match_dict = row.copy()
match_dict

{'line_id': 'line_id'}

In [4]:
rows=[{'aoi': '', 'pi_hour': '25-12-27 14', 'line_id': 'CAPIC107', 'model': 'B160UAN07', 'glass_type': 'TFT', 'recipe_id': '', 'recipe_comment': '', 'ai_code_1': ''}]
match_s_keys = ['pi_hour', 'line_id', 'model', 'glass_type'] #
SUMMARY_KEYS = ["pi_hour", "line_id", "model", "glass_type"]

for row in rows:
    hourly, line_id, model, glass_type = [row[k] for k in match_s_keys]
    hourly, line_id, model, glass_type = [row[k] if k !='pi_hour' else f'20{row[k]}' for k in SUMMARY_KEYS]
    ym = hourly[:5].replace("-", "")  # '25-12-27 14' -> '25-12' -> '2512'
    reicpe_name = f'{model}-{glass_type}'

    # summary
    summary_tbn = f'inspection_api_summary_20{ym}'
    match_dict = {
        'pi_hour': f'20{hourly}',  # '2025-12-27 14'
        'line_id': line_id,
        'model': model,
        'glass_type': glass_type
    }
    print(summary_tbn, match_dict)

    match_rows = dbhandler.get_rows(summary_tbn, match_dict)
    print('row: ', len(match_rows))
    if len(match_rows) == 0:
        continue

    # raw
    raw_tbn = f'inspection_raw_table_20{ym}'
    base_match = {
        'RECIPE_NAME': reicpe_name,
        'TOOL_ID': line_id
    }

    # 收集所有 glass
    glass_list = []
    for s_row in match_rows:
        glass_list += s_row['glass'].split(",")

    print('glass_list', len(glass_list), glass_list)

    # ★ 一次把所有 SHEET_ID 對應的 defect rows 拉回來（DataFrame）
    """
    defect_df = dbhandler.get_rows_df_in(
        table_name=raw_tbn,
        base_keys=base_match,
        in_key='SHEET_ID',
        in_values=glass_list
    )
    """

    defect_df = get_rows_df_in(
        dbhandler,
        table_name=raw_tbn,
        base_keys=base_match,
        in_key='SHEET_ID',
        in_values=glass_list
    )

    print("defect_df shape:", defect_df.shape)

    if not defect_df.empty:
        defect_df = defect_df[['TOOL_ID', 'SHEET_ID', 'DEFECT_SIZE_TYPE', 'COORD_X', 'COORD_Y', 'IMG_URL']]
        #cnt_by_sheet = defect_df.groupby('SHEET_ID').size()
        out = group_defects_by_glass(defect_df)
        #for gls in glass_list:
        #    print(gls, int(cnt_by_sheet.get(gls, 0)))
    """
    else:
        for gls in glass_list:
            print(gls, 0)
    """

2025-12-30 14:07:29,236 - ERROR - [get_rows] 查詢 'inspection_api_summary_202025' 發生錯誤: (pymysql.err.ProgrammingError) (1146, "Table 'l6a01_project.inspection_api_summary_202025' doesn't exist")
[SQL: SELECT * FROM `inspection_api_summary_202025` WHERE pi_hour = %(pi_hour)s AND line_id = %(line_id)s AND model = %(model)s AND glass_type = %(glass_type)s]
[parameters: {'pi_hour': '202025-12-27 14', 'line_id': 'CAPIC107', 'model': 'B160UAN07', 'glass_type': 'TFT'}]
(Background on this error at: https://sqlalche.me/e/20/f405)

inspection_api_summary_202025 {'pi_hour': '202025-12-27 14', 'line_id': 'CAPIC107', 'model': 'B160UAN07', 'glass_type': 'TFT'}
row:  0

In [46]:
out

{'YH5ABVX22': [{'x': '75684', 'y': '168713', 'size': 'O', 'img': ''},
  {'x': '75684', 'y': '169027', 'size': 'O', 'img': ''}],
 'YH5ABVX23': [{'x': '1309932', 'y': '1333339', 'size': 'M', 'img': ''},
  {'x': '1134391', 'y': '573136', 'size': 'S', 'img': ''}],
 'YH5ABVX2B': [{'x': '423916', 'y': '175407', 'size': 'S', 'img': ''}],
 'YH5ABVX2L': [{'x': '1581563', 'y': '1277737', 'size': 'O', 'img': ''}],
 'YH5ABVX2Y': [{'x': '164213', 'y': '1273796', 'size': 'M', 'img': ''}]}

In [37]:
for tbn , tb in data_dict.items():
    print(tbn)
    print(tb.head())

inspection_api_summary_202511
         pi_hour   line_id      model glass_type  maingroup_glass_count  \
0  2025-11-17 07  CAPIC107  B160UAN04        TFT                      7
1  2025-11-17 08  CAPIC107  B160UAN04         CF                     34
2  2025-11-17 08  CAPIC107  B160UAN04        TFT                     30
3  2025-11-17 08  CAPIC307  B140UAN04        TFT                     59
4  2025-11-17 08  CAPIC607  M270HAN1C         CF                     21

   maingroup_defect_count  defect_code_glass_count  small_defect_count  \
0                       4                        4                   4
1                       4                        4                   4
2                       8                        6                   5
3                       3                        3                   1
4                       5                        5                   2

   middle_defect_count  large_defect_count  over_defect_count  \
0                    0                   0                  0
1                    0                   0                  0
2                    1                   2                  0
3                    1                   0                  1
4                    1                   2                  0

                                               glass comment action  \
0  YD5ABGX5V,YD5ABGX5W,YD5ABGX5X,YD5ABGX5Y,YD5ABG...
1  AG0UAB0DFD,AG0UAB0DFL,AG0UAB0DF8,AG0UAB0DFH,AG...
2  YD5ABGX53,YD5ABGX54,YD5ABGX0A,YD5ABGX0B,YD5ABG...
3  JF5ABJU2Z,JF5ABJU21,JF5ABJU22,JF5ABJU23,JF5ABJ...
4  AR0HJB06V7,AR0HJB07X8,AR0HJB07V2,AR0HJB07WH,AR...

                                   glass_size_detail Editor  \
0  YD5ABGX5V:S=0;M=0;L=0;O=0,YD5ABGX5W:S=1;M=0;L=...
1  AG0UAB0DFD:S=0;M=0;L=0;O=0,AG0UAB0DFL:S=0;M=0;...
2  YD5ABGX53:S=0;M=0;L=0;O=0,YD5ABGX54:S=0;M=0;L=...
3  JF5ABJU2Z:S=0;M=0;L=0;O=0,JF5ABJU21:S=0;M=0;L=...
4  AR0HJB06V7:S=0;M=0;L=0;O=0,AR0HJB07X8:S=0;M=0;...

          modify_time
0 2025-12-26 16:28:18
1 2025-12-26 16:28:18
2 2025-12-26 16:28:18
3 2025-12-26 16:28:18
4 2025-12-26 16:28:18
inspection_api_summary_202512
         pi_hour   line_id      model glass_type  maingroup_glass_count  \
0  2025-11-30 23  CAPIC207  M270DANA0        TFT                      5
1  2025-11-30 23  CAPIC407  B160UAN8A         CF                      1
2  2025-11-30 23  CAPIC407  B160UAN8A        TFT                      3
3  2025-12-01 00  CAPIC207  M270DANA0         CF                     10
4  2025-12-01 00  CAPIC207  M270DANA0        TFT                     50

   maingroup_defect_count  defect_code_glass_count  small_defect_count  \
0                       2                        2                   0
1                      32                        1                   8
2                      20                        3                   6
3                     125                        9                  46
4                      45                       27                  21

   middle_defect_count  large_defect_count  over_defect_count  \
0                    1                   1                  0
1                   10                   6                  8
2                    5                   9                  0
3                   34                  23                 22
4                   12                   6                  6

                                               glass comment action  \
0  VN5AAVV7M,VN5AAVV7N,VN5AAVV7P,VN5AAVV7S,VN5AAVV7U
1                                         AG0UHA00XV
2                      YJ5AAV38B,YJ5AAV38D,YJ5AAV38C
3  AR0D0B01WU,AR0D0B01YG,AR0D0B01YE,AR0D0B01YH,AR...
4  VN5AAVV71,VN5AAVV72,VN5AAVV73,VN5AAVV74,VN5AAV...

                                   glass_size_detail Editor  \
0  VN5AAVV7M:S=0;M=0;L=1;O=0,VN5AAVV7N:S=0;M=0;L=...
1                        AG0UHA00XV:S=8;M=10;L=6;O=8
2  YJ5AAV38B:S=2;M=0;L=4;O=0,YJ5AAV38D:S=4;M=2;L=...
3  AR0D0B01WU:S=0;M=0;L=0;O=0,AR0D0B01YG:S=1;M=2;...
4  VN5AAVV71:S=0;M=0;L=0;O=0,VN5AAVV72:S=2;M=0;L=...

          modify_time
0 2025-12-26 16:29:51
1 2025-12-26 16:29:51
2 2025-12-26 16:29:51
3 2025-12-26 16:29:51
4 2025-12-26 16:29:51
inspection_api_summary_202601
         pi_hour   line_id      model glass_type  maingroup_glass_count  \
0  2025-12-31 23  CAPIC107  B116XAN06         CF                     28
1  2025-12-31 23  CAPIC107  B116XAN06        TFT                      3
2  2025-12-31 23  CAPIC307  B160UAN4A         CF                     15
3  2026-01-01 00  CAPIC107  B116XAN06         CF                      1
4  2026-01-01 00  CAPIC107  B116XAN06        TFT                     67

   maingroup_defect_count  defect_code_glass_count  small_defect_count  \
0                      18                       11                   0
1                       0                        0                   0
2                       0                        0                   0
3                       0                        0                   0
4                       8                        7                   3

   middle_defect_count  large_defect_count  over_defect_count  \
0                    8                   3                  7
1                    0                   0                  0
2                    0                   0                  0
3                    0                   0                  0
4                    2                   0                  3

                                               glass comment action  \
0  AA1X6C06L6,AA1X6C06L4,AA1X6C06LN,AA1X6C06LD,AA...
1                      A25ACPC54,A25ACPC0A,A25ACPC0B
2  AG0UAC0E78,AG0UAC0E5U,AG0UAC0EFG,AG0UAC0E5W,AG...
3                                         AA1X6C06LF
4  A25ACPC0C,A25ACPC0D,A25ACPC0E,A25ACPC0F,A25ACP...

                                   glass_size_detail Editor  \
0  AA1X6C06L6:S=0;M=0;L=0;O=2,AA1X6C06L4:S=0;M=1;...
1
2
3
4  A25ACPC0C:S=0;M=0;L=0;O=0,A25ACPC0D:S=0;M=0;L=...

          modify_time
0 2026-01-02 09:09:12
1 2026-01-02 09:09:12
2 2026-01-02 09:09:12
3 2026-01-02 09:09:12
4 2026-01-02 09:09:12

In [ ]:
#data_dict = {}
for tbn in ['inspection_api_summary_202511',
 'inspection_api_summary_202512',
 'inspection_api_summary_202601']:#[tbn for tbn in tbns if '00_pidensity_202512' in tbn]:
    tb = dbhandler.get_table(tbn)
    #data_dict[tbn] = tb
    print(tbn)
    if tb.empty:
        continue
    #data_dict[tbn] = tb.copy()
    
    tb['glass_size_detail'] = tb.apply(
        lambda row: process1_(row['glass']) if row['glass_size_detail'] == '' else row['glass_size_detail'],
        axis=1  )
    #dbhandler.save_table(tbn,tb)

inspection_api_summary_202511
GD5ABJQ1A:S=0;M=0;L=0;O=0,GD5ABJQ1B:S=0;M=0;L=0;O=0,GD5ABJQ1C:S=0;M=0;L=0;O=0,GD5ABJQ1D:S=0;M=0;L=0;O=0,GD5ABJQ1E:S=0;M=0;L=0;O=0,GD5ABJQ1F:S=0;M=0;L=0;O=0,GD5ABJQ1G:S=0;M=0;L=0;O=0,GD5ABJQ1J:S=0;M=0;L=0;O=0,GD5ABJQ1K:S=0;M=0;L=0;O=0,GD5ABJQ1L:S=0;M=0;L=0;O=0,GD5ABJQ1M:S=0;M=0;L=0;O=0,GD5ABJQ1N:S=0;M=0;L=0;O=0,GD5ABJQ1P:S=0;M=0;L=0;O=0,GD5ABJQ1Q:S=0;M=0;L=0;O=0,GD5ABJQ1R:S=0;M=0;L=0;O=0,GD5ABJQ1S:S=0;M=0;L=0;O=0,GD5ABJQ1T:S=0;M=0;L=0;O=0,GD5ABJQ1U:S=0;M=0;L=0;O=0,GD5ABJQ1V:S=0;M=0;L=0;O=0,GD5ABJQ1W:S=0;M=0;L=0;O=0,GD5ABJQ1X:S=0;M=0;L=0;O=0,GD5ABJQ1Y:S=0;M=0;L=0;O=0,GD5ABJQ1Z:S=0;M=0;L=0;O=0,GD5ABJQ11:S=0;M=0;L=0;O=0,GD5ABJQ12:S=0;M=0;L=0;O=0,GD5ABJQ13:S=0;M=0;L=0;O=0,GD5ABJQ14:S=0;M=0;L=0;O=0
JF5ABKA23:S=0;M=0;L=0;O=0,JF5ABKA24:S=0;M=0;L=0;O=0
GD5ABHY42:S=0;M=0;L=0;O=0,GD5ABHY43:S=0;M=0;L=0;O=0,GD5ABHY44:S=0;M=0;L=0;O=0
AG0UAB0DN4:S=0;M=0;L=0;O=0,AG0UAB0CS8:S=0;M=0;L=0;O=0,AG0UAB0DN2:S=0;M=0;L=0;O=0,AG0UAB0DN1:S=0;M=0;L=0;O=0,AG0UAB0DN0:S=0;M=0;L=0;O=0,AG0UAB0DMZ:S=0;M=0;L=0;O=0,AG0UAB0DMY:S=0;M=0;L=0;O=0
JF5ABJU6Y:S=0;M=0;L=0;O=0,JF5ABJU6Z:S=0;M=0;L=0;O=0,JF5ABJU61:S=0;M=0;L=0;O=0,JF5ABJU62:S=0;M=0;L=0;O=0,JF5ABJU63:S=0;M=0;L=0;O=0,JF5ABJU64:S=0;M=0;L=0;O=0
YD5AAXK7A:S=0;M=0;L=0;O=0,YD5AAXK7B:S=0;M=0;L=0;O=0,YD5AAXK7C:S=0;M=0;L=0;O=0,YD5AAXK7D:S=0;M=0;L=0;O=0,YD5AAXK7E:S=0;M=0;L=0;O=0,YD5AAXK7F:S=0;M=0;L=0;O=0,YD5AAXK7G:S=0;M=0;L=0;O=0,YD5AAXK7H:S=0;M=0;L=0;O=0
AG0UAB0BWJ:S=0;M=0;L=0;O=0,AG0UAB0BWG:S=0;M=0;L=0;O=0,AG0UAB0DE9:S=0;M=0;L=0;O=0,AG0UAB0DK7:S=0;M=0;L=0;O=0,AG0UAB0D0K:S=0;M=0;L=0;O=0,AG0UAB0CXF:S=0;M=0;L=0;O=0
AR0HZB0EDB:S=0;M=0;L=0;O=0,AR0HZB0EDJ:S=0;M=0;L=0;O=0,AR0HZB0DZU:S=0;M=0;L=0;O=0
625ABH28A:S=0;M=0;L=0;O=0,625ABH28B:S=0;M=0;L=0;O=0,625ABH28C:S=0;M=0;L=0;O=0
JF5ABJ95A:S=0;M=0;L=0;O=0,JF5ABJ95B:S=0;M=0;L=0;O=0,JF5ABJ95C:S=0;M=0;L=0;O=0,JF5ABJ95D:S=0;M=0;L=0;O=0,JF5ABJ95E:S=0;M=0;L=0;O=0,JF5ABJ95F:S=0;M=0;L=0;O=0,JF5ABJ95G:S=0;M=0;L=0;O=0,JF5ABJ95H:S=0;M=0;L=0;O=0,JF5ABJ95J:S=0;M=0;L=0;O=0,JF5ABJ95K:S=0;M=0;L=0;O=0,JF5ABJ95L:S=0;M=0;L=0;O=0,JF5ABJ95M:S=0;M=0;L=0;O=0,JF5ABJ95N:S=0;M=0;L=0;O=0,JF5ABJ95P:S=0;M=0;L=0;O=0
AR0HZB0EFL:S=0;M=0;L=0;O=0,AR0HZB0ECU:S=0;M=0;L=0;O=0,AR0HZB0EBS:S=0;M=0;L=0;O=0,AR0HZB0EFN:S=0;M=0;L=0;O=0,AR0HZB0EFT:S=0;M=0;L=0;O=0,AR0HZB0EFP:S=0;M=0;L=0;O=0,AR0HZB0EFJ:S=0;M=0;L=0;O=0,AR0HZB0EFM:S=0;M=0;L=0;O=0,AR0HZB0DT5:S=0;M=0;L=0;O=0,AR0HZB0DDL:S=0;M=0;L=0;O=0,AR0HZB0E1Q:S=0;M=0;L=0;O=0,AR0HZB0E1R:S=0;M=0;L=0;O=0,AR0HZB0E1U:S=0;M=0;L=0;O=0,AR0HZB0E1T:S=0;M=0;L=0;O=0,AR0HZB0E08:S=0;M=0;L=0;O=0,AR0HZB0E5T:S=0;M=0;L=0;O=0,AR0HZB0E4J:S=0;M=0;L=0;O=0,AR0HZB0E4F:S=0;M=0;L=0;O=0,AR0HZB0E4G:S=0;M=0;L=0;O=0,AR0HZB0DX7:S=0;M=0;L=0;O=0,AR0HZB0E4X:S=0;M=0;L=0;O=0,AR0HZB0DVP:S=0;M=0;L=0;O=0,AR0HZB0E4D:S=0;M=0;L=0;O=0,AR0HZB0E4E:S=0;M=0;L=0;O=0,AR0HZB0E4B:S=0;M=0;L=0;O=0,AR0HZB0E4C:S=0;M=0;L=0;O=0,AR0HZB0DXP:S=0;M=0;L=0;O=0,AR0HZB0DXN:S=0;M=0;L=0;O=0,AR0HZB0DXQ:S=0;M=0;L=0;O=0,AR0HZB0DXL:S=0;M=0;L=0;O=0,AR0HZB0DXJ:S=0;M=0;L=0;O=0,AR0HZB0DXE:S=0;M=0;L=0;O=0,AR0HZB0DXK:S=0;M=0;L=0;O=0,AR0HZB0DXG:S=0;M=0;L=0;O=0,AR0HZB0E5Y:S=0;M=0;L=0;O=0,AR0HZB0E1M:S=0;M=0;L=0;O=0,AR0HZB0DXD:S=0;M=0;L=0;O=0,AR0HZB0DXF:S=0;M=0;L=0;O=0,AR0HZB0DGZ:S=0;M=0;L=0;O=0,AR0HZB0DWD:S=0;M=0;L=0;O=0,AR0HZB0DJ2:S=0;M=0;L=0;O=0,AR0HZB0DJ1:S=0;M=0;L=0;O=0,AR0HZB0DJ3:S=0;M=0;L=0;O=0,AR0HZB0DHZ:S=0;M=0;L=0;O=0,AR0HZB0EHA:S=0;M=0;L=0;O=0
AR0HZB0EH7:S=0;M=0;L=0;O=0,AR0HZB0EH8:S=0;M=0;L=0;O=0,AR0HZB0EH5:S=0;M=0;L=0;O=0,AR0HZB0EH6:S=0;M=0;L=0;O=0,AR0HZB0EH1:S=0;M=0;L=0;O=0,AR0HZB0EGZ:S=0;M=0;L=0;O=0,AR0HZB0E3T:S=0;M=0;L=0;O=0,AR0HZB0EGX:S=0;M=0;L=0;O=0,AR0HZB0EH2:S=0;M=0;L=0;O=0,AR0HZB0EGV:S=0;M=0;L=0;O=0,AR0HZB0DJX:S=0;M=0;L=0;O=0,AR0HZB0EDV:S=0;M=0;L=0;O=0,AR0HZB0EH0:S=0;M=0;L=0;O=0,AR0HZB0EGY:S=0;M=0;L=0;O=0,AR0HZB0EGU:S=0;M=0;L=0;O=0,AR0HZB0EGS:S=0;M=0;L=0;O=0,AR0HZB0EGW:S=0;M=0;L=0;O=0,AR0HZB0EGT:S=0;M=0;L=0;O=0,AR0HZB0EG2:S=0;M=0;L=0;O=0,AR0HZB0EE1:S=0;M=0;L=0;O=0,AR0HZB0E1S:S=0;M=0;L=0;O=0
AR0HZB0E7C:S=0;M=0;L=0;O=0,AR0HZB0E9F:S=0;M=0;L=0;O=0,AR0HZB0EAN:S=0;M=0;L=0;O=0
AR0HZB0E7L:S=0;M=0;L=0;O=0,AR0HZB0E60:S=0;M=0;L=0;O=0,AR0HZB0E7J:S=0;M=0;L=0;O=0,AR0HZB0E7G:S=0;M=0;L=0;O=0,AR0HZB0E7H:S=0;M=0;L=0;O=0,AR0HZB0E9P:S=0;M=0;L=0;O=0
AR0HZB0DX2:S=0;M=0;L=0;O=0,AR0HZB0E9X:S=0;M=0;L=0;O=0,AR0HZB0DX1:S=0;M=0;L=0;O=0,AR0HZB0DX4:S=0;M=0;L=0;O=0,AR0HZB0DX3:S=0;M=0;L=0;O=0,AR0HZB0EAA:S=0;M=0;L=0;O=0,AR0HZB0EAC:S=0;M=0;L=0;O=0,AR0HZB0EAE:S=0;M=0;L=0;O=0,AR0HZB0EHC:S=0;M=0;L=0;O=0,AR0HZB0EH3:S=0;M=0;L=0;O=0,AR0HZB0EH9:S=0;M=0;L=0;O=0,AR0HZB0E5U:S=0;M=0;L=0;O=0,AR0HZB0E5P:S=0;M=0;L=0;O=0
AG0UAB0CQ2:S=0;M=0;L=0;O=0,AG0UAB0DPL:S=0;M=0;L=0;O=0
AG0UAB0EWF:S=0;M=0;L=0;O=0,AG0UAB0EWJ:S=0;M=0;L=0;O=0,AG0UAB0EWD:S=0;M=0;L=0;O=0,AG0UAB0E7X:S=0;M=0;L=0;O=0,AG0UAB0EWG:S=0;M=0;L=0;O=0
JF5ABL64A:S=0;M=0;L=0;O=0,JF5ABL64B:S=0;M=0;L=0;O=0,JF5ABL64C:S=0;M=0;L=0;O=0,JF5ABL64D:S=0;M=0;L=0;O=0,JF5ABL64E:S=0;M=0;L=0;O=0,JF5ABL64F:S=0;M=0;L=0;O=0,JF5ABL64G:S=0;M=0;L=0;O=0,JF5ABL64H:S=0;M=0;L=0;O=0,JF5ABL64J:S=0;M=0;L=0;O=0,JF5ABL64K:S=0;M=0;L=0;O=0
AR0HZB0DFE:S=0;M=0;L=0;O=0,AR0HZB0DFK:S=0;M=0;L=0;O=0,AR0HZB0DH6:S=0;M=0;L=0;O=0,AR0HZB0DH9:S=0;M=0;L=0;O=0,AR0HZB0DH8:S=0;M=0;L=0;O=0,AR0HZB0DFG:S=0;M=0;L=0;O=0,AR0HZB0DH4:S=0;M=0;L=0;O=0,AR0HZB0DH5:S=0;M=0;L=0;O=0,AR0HZB0DGX:S=0;M=0;L=0;O=0,AR0HZB0DJH:S=0;M=0;L=0;O=0,AR0HZB0DJF:S=0;M=0;L=0;O=0,AR0HZB0DJG:S=0;M=0;L=0;O=0,AR0HZB0DJC:S=0;M=0;L=0;O=0,AR0HZB0E5A:S=0;M=0;L=0;O=0,AR0HZB0DH2:S=0;M=0;L=0;O=0,AR0HZB0DGF:S=0;M=0;L=0;O=0,AR0HZB0DH0:S=0;M=0;L=0;O=0,AR0HZB0DH3:S=0;M=0;L=0;O=0,AR0HZB0DH1:S=0;M=0;L=0;O=0,AR0HZB0E19:S=0;M=0;L=0;O=0,AR0HZB0DJA:S=0;M=0;L=0;O=0,AR0HZB0DJB:S=0;M=0;L=0;O=0,AR0HZB0DJ8:S=0;M=0;L=0;O=0,AR0HZB0DJ9:S=0;M=0;L=0;O=0,AR0HZB0DJ6:S=0;M=0;L=0;O=0,AR0HZB0DJ4:S=0;M=0;L=0;O=0,AR0HZB0DU6:S=0;M=0;L=0;O=0,AR0HZB0DU4:S=0;M=0;L=0;O=0
JF5ABLL8L:S=0;M=0;L=0;O=0,JF5ABLL8M:S=0;M=0;L=0;O=0,JF5ABLL8N:S=0;M=0;L=0;O=0,JF5ABLL8P:S=0;M=0;L=0;O=0,JF5ABLL8Q:S=0;M=0;L=0;O=0,JF5ABLL8R:S=0;M=0;L=0;O=0,JF5ABLL8S:S=0;M=0;L=0;O=0,JF5ABLL8T:S=0;M=0;L=0;O=0,JF5ABLL8U:S=0;M=0;L=0;O=0,JF5ABLL8V:S=0;M=0;L=0;O=0,JF5ABLL8W:S=0;M=0;L=0;O=0,JF5ABLL8X:S=0;M=0;L=0;O=0,JF5ABLL8Y:S=0;M=0;L=0;O=0,JF5ABLL8Z:S=0;M=0;L=0;O=0,JF5ABLL81:S=0;M=0;L=0;O=0,JF5ABLL82:S=0;M=0;L=0;O=0,JF5ABLL83:S=0;M=0;L=0;O=0,JF5ABLL84:S=0;M=0;L=0;O=0,JF5ABLL0A:S=0;M=0;L=0;O=0,JF5ABLL0B:S=0;M=0;L=0;O=0,JF5ABLL0C:S=0;M=0;L=0;O=0,JF5ABLL0D:S=0;M=0;L=0;O=0,JF5ABLL0E:S=0;M=0;L=0;O=0,JF5ABLL0F:S=0;M=0;L=0;O=0,JF5ABLL0G:S=0;M=0;L=0;O=0,JF5ABLL0H:S=0;M=0;L=0;O=0,JF5ABLL0J:S=0;M=0;L=0;O=0,JF5ABLL0K:S=0;M=0;L=0;O=0,JF5ABLL0L:S=0;M=0;L=0;O=0,JF5ABLL0M:S=0;M=0;L=0;O=0,JF5ABLL0N:S=0;M=0;L=0;O=0,JF5ABLL0P:S=0;M=0;L=0;O=0,JF5ABLL0Q:S=0;M=0;L=0;O=0,JF5ABLL0R:S=0;M=0;L=0;O=0,JF5ABLL0S:S=0;M=0;L=0;O=0,JF5ABLL0T:S=0;M=0;L=0;O=0,JF5ABLL0U:S=0;M=0;L=0;O=0,JF5ABLL0V:S=0;M=0;L=0;O=0,JF5ABLL0W:S=0;M=0;L=0;O=0,JF5ABLL0X:S=0;M=0;L=0;O=0,JF5ABLL0Y:S=0;M=0;L=0;O=0,JF5ABLL0Z:S=0;M=0;L=0;O=0,JF5ABLL01:S=0;M=0;L=0;O=0,JF5ABLL02:S=0;M=0;L=0;O=0,JF5ABLL03:S=0;M=0;L=0;O=0,JF5ABLL04:S=0;M=0;L=0;O=0
625AAX79A:S=0;M=0;L=0;O=0,625AAX79B:S=0;M=0;L=0;O=0,625AAX79C:S=0;M=0;L=0;O=0,625AAX79D:S=0;M=0;L=0;O=0,625AAX79E:S=0;M=0;L=0;O=0,625AAX79F:S=0;M=0;L=0;O=0,625AAX79G:S=0;M=0;L=0;O=0,625AAX79H:S=0;M=0;L=0;O=0,625AAX79J:S=0;M=0;L=0;O=0,625AAX79K:S=0;M=0;L=0;O=0,625AAX79L:S=0;M=0;L=0;O=0,625AAX79M:S=0;M=0;L=0;O=0,625AAX79N:S=0;M=0;L=0;O=0,625AAX79P:S=0;M=0;L=0;O=0,625AAX79Q:S=0;M=0;L=0;O=0,625AAX79R:S=0;M=0;L=0;O=0,625AAX79S:S=0;M=0;L=0;O=0,625AAX79T:S=0;M=0;L=0;O=0,625AAX79U:S=0;M=0;L=0;O=0,625AAX79V:S=0;M=0;L=0;O=0,625AAX79W:S=0;M=0;L=0;O=0,625AAX79X:S=0;M=0;L=0;O=0,625AAX79Y:S=0;M=0;L=0;O=0,625AAX79Z:S=0;M=0;L=0;O=0,625AAX791:S=0;M=0;L=0;O=0,625AAX792:S=0;M=0;L=0;O=0,625AAX793:S=0;M=0;L=0;O=0
AE1U4B09NJ:S=0;M=0;L=0;O=0
5H5ABKD3A:S=0;M=0;L=0;O=0,5H5ABKD3B:S=0;M=0;L=0;O=0,5H5ABKD3C:S=0;M=0;L=0;O=0
AE1U4B06SY:S=0;M=0;L=0;O=0
JF5ABLN53:S=0;M=0;L=0;O=0,JF5ABLN54:S=0;M=0;L=0;O=0,JF5ABKN4A:S=0;M=0;L=0;O=0,JF5ABKN4B:S=0;M=0;L=0;O=0,JF5ABKN4C:S=0;M=0;L=0;O=0,JF5ABKN4D:S=0;M=0;L=0;O=0,JF5ABKN4E:S=0;M=0;L=0;O=0,JF5ABKN4F:S=0;M=0;L=0;O=0,JF5ABKN4G:S=0;M=0;L=0;O=0
JF5ABKN4H:S=0;M=0;L=0;O=0,JF5ABKN4J:S=0;M=0;L=0;O=0,JF5ABKN4K:S=0;M=0;L=0;O=0,JF5ABKN4L:S=0;M=0;L=0;O=0,JF5ABKN4M:S=0;M=0;L=0;O=0,JF5ABKN4N:S=0;M=0;L=0;O=0,JF5ABKN4P:S=0;M=0;L=0;O=0,JF5ABKN4Q:S=0;M=0;L=0;O=0,JF5ABKN4R:S=0;M=0;L=0;O=0,JF5ABKN4S:S=0;M=0;L=0;O=0,JF5ABKN4T:S=0;M=0;L=0;O=0,JF5ABKN4U:S=0;M=0;L=0;O=0,JF5ABKN4V:S=0;M=0;L=0;O=0,JF5ABKN4W:S=0;M=0;L=0;O=0,JF5ABKN4X:S=0;M=0;L=0;O=0,JF5ABKN4Y:S=0;M=0;L=0;O=0,JF5ABKN4Z:S=0;M=0;L=0;O=0,JF5ABKN41:S=0;M=0;L=0;O=0,JF5ABKN42:S=0;M=0;L=0;O=0,JF5ABKN43:S=0;M=0;L=0;O=0,JF5ABKN44:S=0;M=0;L=0;O=0
JF5ABJA2A:S=0;M=0;L=0;O=0,JF5ABJA2B:S=0;M=0;L=0;O=0,JF5ABJA2C:S=0;M=0;L=0;O=0,JF5ABJA2D:S=0;M=0;L=0;O=0,JF5ABJA2E:S=0;M=0;L=0;O=0,JF5ABJA2F:S=0;M=0;L=0;O=0,JF5ABJA2G:S=0;M=0;L=0;O=0,JF5ABJA2H:S=0;M=0;L=0;O=0,JF5ABJA2J:S=0;M=0;L=0;O=0,JF5ABJA2K:S=0;M=0;L=0;O=0,JF5ABJA2L:S=0;M=0;L=0;O=0,JF5ABJA2M:S=0;M=0;L=0;O=0,JF5ABJA2N:S=0;M=0;L=0;O=0,JF5ABJA2P:S=0;M=0;L=0;O=0,JF5ABJA2Q:S=0;M=0;L=0;O=0,JF5ABJA2R:S=0;M=0;L=0;O=0,JF5ABJA2S:S=0;M=0;L=0;O=0,JF5ABJA2T:S=0;M=0;L=0;O=0,JF5ABJA2U:S=0;M=0;L=0;O=0,JF5ABJA2V:S=0;M=0;L=0;O=0,JF5ABJA2W:S=0;M=0;L=0;O=0,JF5ABJA2X:S=0;M=0;L=0;O=0,JF5ABJA2Y:S=0;M=0;L=0;O=0,JF5ABJA2Z:S=0;M=0;L=0;O=0,JF5ABJA21:S=0;M=0;L=0;O=0,JF5ABJA22:S=0;M=0;L=0;O=0,JF5ABJA23:S=0;M=0;L=0;O=0,JF5ABJA24:S=0;M=0;L=0;O=0
AH0EQB06CK:S=0;M=0;L=0;O=0,AH0EQB06CJ:S=0;M=0;L=0;O=0,AH0EQB06AZ:S=0;M=0;L=0;O=0,AH0EQB06CL:S=0;M=0;L=0;O=0,AH0EQB06B2:S=0;M=0;L=0;O=0,AH0EQB05Y0:S=0;M=0;L=0;O=0,AH0EQB06BA:S=0;M=0;L=0;O=0,AH0EQB05VL:S=0;M=0;L=0;O=0,AH0EQB06B9:S=0;M=0;L=0;O=0,AH0EQB06BB:S=0;M=0;L=0;O=0,AH0EQB06LF:S=0;M=0;L=0;O=0,AH0EQB06MK:S=0;M=0;L=0;O=0,AH0EQB06ML:S=0;M=0;L=0;O=0
AG0UAB0EGJ:S=0;M=0;L=0;O=0,AG0UAB0EGG:S=0;M=0;L=0;O=0,AG0UAB0F0V:S=0;M=0;L=0;O=0,AG0UAB0EJG:S=0;M=0;L=0;O=0,AG0UAB0E3V:S=0;M=0;L=0;O=0,AG0UAB0EJF:S=0;M=0;L=0;O=0
AH0EQB06ES:S=0;M=0;L=0;O=0,AH0EQB06EG:S=0;M=0;L=0;O=0,AH0EQB05JZ:S=0;M=0;L=0;O=0,AH0EQB05ZH:S=0;M=0;L=0;O=0,AH0EQB06DW:S=0;M=0;L=0;O=0,AH0EQB05K0:S=0;M=0;L=0;O=0,AH0EQB05K3:S=0;M=0;L=0;O=0,AH0EQB06L4:S=0;M=0;L=0;O=0,AH0EQB06FJ:S=0;M=0;L=0;O=0,AH0EQB06FM:S=0;M=0;L=0;O=0,AH0EQB06FL:S=0;M=0;L=0;O=0,AH0EQB06FN:S=0;M=0;L=0;O=0,AH0EQB05VE:S=0;M=0;L=0;O=0,AH0EQB06FE:S=0;M=0;L=0;O=0,AH0EQB06FQ:S=0;M=0;L=0;O=0,AH0EQB06FP:S=0;M=0;L=0;O=0,AH0EQB068K:S=0;M=0;L=0;O=0,AH0EQB068H:S=0;M=0;L=0;O=0,AH0EQB068N:S=0;M=0;L=0;O=0,AH0EQB0654:S=0;M=0;L=0;O=0,AH0EQB05W5:S=0;M=0;L=0;O=0,AH0EQB0656:S=0;M=0;L=0;O=0,AH0EQB060E:S=0;M=0;L=0;O=0,AH0EQB06FA:S=0;M=0;L=0;O=0,AH0EQB060F:S=0;M=0;L=0;O=0,AH0EQB06FB:S=0;M=0;L=0;O=0,AH0EQB06F6:S=0;M=0;L=0;O=0,AH0EQB0616:S=0;M=0;L=0;O=0
JF5ABM264:S=0;M=0;L=0;O=0,JF5ABLM9A:S=0;M=0;L=0;O=0,JF5ABLM9B:S=0;M=0;L=0;O=0,JF5ABLM9C:S=0;M=0;L=0;O=0,JF5ABLM9D:S=0;M=0;L=0;O=0,JF5ABLM9E:S=0;M=0;L=0;O=0,JF5ABLM9F:S=0;M=0;L=0;O=0,JF5ABLM9G:S=0;M=0;L=0;O=0,JF5ABLM9H:S=0;M=0;L=0;O=0,JF5ABLM9J:S=0;M=0;L=0;O=0
AH0EQB06KK:S=0;M=0;L=0;O=0,AH0EQB06BD:S=0;M=0;L=0;O=0,AH0EQB06BJ:S=0;M=0;L=0;O=0,AH0EQB06BC:S=0;M=0;L=0;O=0,AH0EQB05VH:S=0;M=0;L=0;O=0,AH0EQB06BE:S=0;M=0;L=0;O=0,AH0EQB06BF:S=0;M=0;L=0;O=0,AH0EQB06BL:S=0;M=0;L=0;O=0,AH0EQB05XW:S=0;M=0;L=0;O=0,AH0EQB05JP:S=0;M=0;L=0;O=0,AH0EQB065Q:S=0;M=0;L=0;O=0,AH0EQB065N:S=0;M=0;L=0;O=0,AH0EQB065P:S=0;M=0;L=0;O=0
AH0EQB05KR:S=0;M=0;L=0;O=0,AH0EQB05LD:S=0;M=0;L=0;O=0,AH0EQB05R6:S=0;M=0;L=0;O=0,AH0EQB05SZ:S=0;M=0;L=0;O=0,AH0EQB05KA:S=0;M=0;L=0;O=0,AH0EQB05KV:S=0;M=0;L=0;O=0,AH0EQB05KT:S=0;M=0;L=0;O=0,AH0EQB05SD:S=0;M=0;L=0;O=0,AH0EQB05R4:S=0;M=0;L=0;O=0,AH0EQB05QX:S=0;M=0;L=0;O=0,AH0EQB05SL:S=0;M=0;L=0;O=0,AH0EQB05SH:S=0;M=0;L=0;O=0,AH0EQB05SJ:S=0;M=0;L=0;O=0,AH0EQB063Y:S=0;M=0;L=0;O=0,AH0EQB063W:S=0;M=0;L=0;O=0,AH0EQB063S:S=0;M=0;L=0;O=0,AH0EQB05VK:S=0;M=0;L=0;O=0,AH0EQB063U:S=0;M=0;L=0;O=0,AH0EQB063Q:S=0;M=0;L=0;O=0,AH0EQB063N:S=0;M=0;L=0;O=0,AH0EQB063R:S=0;M=0;L=0;O=0,AH0EQB06FS:S=0;M=0;L=0;O=0,AH0EQB06HU:S=0;M=0;L=0;O=0,AH0EQB063P:S=0;M=0;L=0;O=0,AH0EQB063K:S=0;M=0;L=0;O=0,AH0EQB063L:S=0;M=0;L=0;O=0
AR0T2B001X:S=0;M=0;L=0;O=0,AR0T2B0072:S=0;M=0;L=0;O=0,AR0T2B0013:S=0;M=0;L=0;O=0,AR0T2B001F:S=0;M=0;L=0;O=0,AR0T2B0033:S=0;M=0;L=0;O=0,AR0T2B0045:S=0;M=0;L=0;O=0,AR0T2B004A:S=0;M=0;L=0;O=0,AR0T2B0025:S=0;M=0;L=0;O=0,AR0T2B0059:S=0;M=0;L=0;O=0,AR0T2B006V:S=0;M=0;L=0;O=0,AR0T2B006R:S=0;M=0;L=0;O=0,AR0T2B006E:S=0;M=0;L=0;O=0,AR0T2B000Z:S=0;M=0;L=0;O=0,AR0T2B0011:S=0;M=0;L=0;O=0,AR0T2B002T:S=0;M=0;L=0;O=0,AR0T2B003C:S=0;M=0;L=0;O=0,AR0T2B0028:S=0;M=0;L=0;O=0,AR0T2B002W:S=0;M=0;L=0;O=0,AR0T2B006J:S=0;M=0;L=0;O=0,AR0T2B006G:S=0;M=0;L=0;O=0,AR0T2B006L:S=0;M=0;L=0;O=0,AR0T2B006N:S=0;M=0;L=0;O=0,AR0T2B004E:S=0;M=0;L=0;O=0,AR0T2B000W:S=0;M=0;L=0;O=0,AR0T2B0018:S=0;M=0;L=0;O=0,AR0T2B0049:S=0;M=0;L=0;O=0,AR0T2B004C:S=0;M=0;L=0;O=0,AR0T2B004G:S=0;M=0;L=0;O=0,AR0T2B003W:S=0;M=0;L=0;O=0,AR0T2B006X:S=0;M=0;L=0;O=0,AR0T2B005Z:S=0;M=0;L=0;O=0,AR0T2B004J:S=0;M=0;L=0;O=0,AR0T2B0071:S=0;M=0;L=0;O=0,AR0T2B005B:S=0;M=0;L=0;O=0,AR0T2B002Y:S=0;M=0;L=0;O=0,AR0T2B003U:S=0;M=0;L=0;O=0,AR0T2B0041:S=0;M=0;L=0;O=0,AR0T2B003V:S=0;M=0;L=0;O=0,AR0T2B0043:S=0;M=0;L=0;O=0,AR0T2B0042:S=0;M=0;L=0;O=0,AR0T2B005C:S=0;M=0;L=0;O=0,AR0T2B005A:S=0;M=0;L=0;O=0,AR0T2B005F:S=0;M=0;L=0;O=0,AR0T2B0050:S=0;M=0;L=0;O=0,AR0T2B005E:S=0;M=0;L=0;O=0,AR0T2B001Y:S=0;M=0;L=0;O=0,AR0T2B003J:S=0;M=0;L=0;O=0,AR0T2B004T:S=0;M=0;L=0;O=0,AR0T2B003T:S=0;M=0;L=0;O=0,AR0T2B004Q:S=0;M=0;L=0;O=0
AH0EQB063J:S=0;M=0;L=0;O=0,AH0EQB063G:S=0;M=0;L=0;O=0
AH0EQB06DH:S=0;M=0;L=0;O=0,AH0EQB06DF:S=0;M=0;L=0;O=0,AH0EQB06F2:S=0;M=0;L=0;O=0,AH0EQB06EY:S=0;M=0;L=0;O=0,AH0EQB06EW:S=0;M=0;L=0;O=0,AH0EQB06EX:S=0;M=0;L=0;O=0,AH0EQB06EV:S=0;M=0;L=0;O=0,AH0EQB06F1:S=0;M=0;L=0;O=0,AH0EQB05SF:S=0;M=0;L=0;O=0,AH0EQB05S9:S=0;M=0;L=0;O=0,AH0EQB05S8:S=0;M=0;L=0;O=0,AH0EQB05UG:S=0;M=0;L=0;O=0,AH0EQB05UC:S=0;M=0;L=0;O=0,AH0EQB05UD:S=0;M=0;L=0;O=0,AH0EQB05T8:S=0;M=0;L=0;O=0,AH0EQB05UA:S=0;M=0;L=0;O=0,AH0EQB05U8:S=0;M=0;L=0;O=0,AH0EQB05UB:S=0;M=0;L=0;O=0,AH0EQB05U9:S=0;M=0;L=0;O=0,AH0EQB05NS:S=0;M=0;L=0;O=0,AH0EQB05U6:S=0;M=0;L=0;O=0,AH0EQB05U4:S=0;M=0;L=0;O=0,AH0EQB05U7:S=0;M=0;L=0;O=0,AH0EQB05U2:S=0;M=0;L=0;O=0,AH0EQB05NR:S=0;M=0;L=0;O=0,AH0EQB05KZ:S=0;M=0;L=0;O=0,AH0EQB05PJ:S=0;M=0;L=0;O=0,AH0EQB05TG:S=0;M=0;L=0;O=0
AG0UAB0FA5:S=0;M=0;L=0;O=0
5H5ABL03A:S=0;M=0;L=0;O=0,5H5ABL03B:S=0;M=0;L=0;O=0,5H5ABL03C:S=0;M=0;L=0;O=0
GY5AAQU9M:S=0;M=0;L=0;O=0,GY5AAQU9N:S=0;M=0;L=0;O=0,GY5AAQU9P:S=0;M=0;L=0;O=0,GY5AAQU9R:S=0;M=0;L=0;O=0,GY5AAQU9S:S=0;M=0;L=0;O=0,GY5AAQU9T:S=0;M=0;L=0;O=0,GY5AAQU91:S=0;M=0;L=0;O=0,GY5AAQU92:S=0;M=0;L=0;O=0,GY5AAQU9U:S=0;M=0;L=0;O=0,GY5AAQU9V:S=0;M=0;L=0;O=0,GY5AAQU9W:S=0;M=0;L=0;O=0,GY5AAQU94:S=0;M=0;L=0;O=0,GY5AAQU9X:S=0;M=0;L=0;O=0,GY5AAQU9Y:S=0;M=0;L=0;O=0,GY5AAQU9Z:S=0;M=0;L=0;O=0,GY5AAQV2E:S=0;M=0;L=0;O=0,GY5AAQV2D:S=0;M=0;L=0;O=0,GY5AAQV2C:S=0;M=0;L=0;O=0,GY5AAQV2B:S=0;M=0;L=0;O=0,GY5AAQV2A:S=0;M=0;L=0;O=0,GY5AAQV2J:S=0;M=0;L=0;O=0,GY5AAQV2H:S=0;M=0;L=0;O=0,GY5AAQV2G:S=0;M=0;L=0;O=0,GY5AAQV2F:S=0;M=0;L=0;O=0
5H5ABJB3A:S=0;M=0;L=0;O=0,5H5ABJB3B:S=0;M=0;L=0;O=0,5H5ABJB3C:S=0;M=0;L=0;O=0
AH0EQB05Z6:S=0;M=0;L=0;O=0,AH0EQB05YR:S=0;M=0;L=0;O=0,AH0EQB05Z2:S=0;M=0;L=0;O=0,AH0EQB05Z3:S=0;M=0;L=0;O=0,AH0EQB05Z1:S=0;M=0;L=0;O=0,AH0EQB05YZ:S=0;M=0;L=0;O=0,AH0EQB05Z0:S=0;M=0;L=0;O=0,AH0EQB05YX:S=0;M=0;L=0;O=0,AH0EQB05YY:S=0;M=0;L=0;O=0,AH0EQB05YW:S=0;M=0;L=0;O=0,AH0EQB05YU:S=0;M=0;L=0;O=0,AH0EQB05YV:S=0;M=0;L=0;O=0,AH0EQB06KB:S=0;M=0;L=0;O=0,AH0EQB0640:S=0;M=0;L=0;O=0,AH0EQB06M8:S=0;M=0;L=0;O=0,AH0EQB06M4:S=0;M=0;L=0;O=0,AH0EQB06D3:S=0;M=0;L=0;O=0,AH0EQB06M5:S=0;M=0;L=0;O=0,AH0EQB06M3:S=0;M=0;L=0;O=0,AH0EQB06M1:S=0;M=0;L=0;O=0,AH0EQB06M2:S=0;M=0;L=0;O=0,AH0EQB06LZ:S=0;M=0;L=0;O=0,AH0EQB06LY:S=0;M=0;L=0;O=0,AH0EQB06LA:S=0;M=0;L=0;O=0,AH0EQB06LW:S=0;M=0;L=0;O=0,AH0EQB06LX:S=0;M=0;L=0;O=0,AH0EQB06KC:S=0;M=0;L=0;O=0,AH0EQB06L9:S=0;M=0;L=0;O=0
JF5ABM17A:S=0;M=0;L=0;O=0,JF5ABM17B:S=0;M=0;L=0;O=0,JF5ABM17C:S=0;M=0;L=0;O=0,JF5ABM17D:S=0;M=0;L=0;O=0,JF5ABM17E:S=0;M=0;L=0;O=0
AH0EQB05L7:S=0;M=0;L=0;O=0,AH0EQB05L2:S=0;M=0;L=0;O=0,AH0EQB05L5:S=0;M=0;L=0;O=0,AH0EQB05L0:S=0;M=0;L=0;O=0,AH0EQB05L3:S=0;M=0;L=0;O=0,AH0EQB05UY:S=0;M=0;L=0;O=0,AH0EQB05UV:S=0;M=0;L=0;O=0,AH0EQB05UT:S=0;M=0;L=0;O=0,AH0EQB05UQ:S=0;M=0;L=0;O=0,AH0EQB05UR:S=0;M=0;L=0;O=0,AH0EQB05UM:S=0;M=0;L=0;O=0,AH0EQB05UN:S=0;M=0;L=0;O=0,AH0EQB05UK:S=0;M=0;L=0;O=0,AH0EQB05XH:S=0;M=0;L=0;O=0,AH0EQB05UL:S=0;M=0;L=0;O=0,AH0EQB05UH:S=0;M=0;L=0;O=0,AH0EQB05UJ:S=0;M=0;L=0;O=0,AH0EQB06MA:S=0;M=0;L=0;O=0,AH0EQB05JV:S=0;M=0;L=0;O=0,AH0EQB05K1:S=0;M=0;L=0;O=0,AH0EQB06AN:S=0;M=0;L=0;O=0,AH0EQB06AG:S=0;M=0;L=0;O=0,AH0EQB05JX:S=0;M=0;L=0;O=0,AH0EQB06AH:S=0;M=0;L=0;O=0,AH0EQB06AP:S=0;M=0;L=0;O=0,AH0EQB06AK:S=0;M=0;L=0;O=0,AH0EQB06AM:S=0;M=0;L=0;O=0,AH0EQB06JA:S=0;M=0;L=0;O=0,AH0EQB062F:S=0;M=0;L=0;O=0,AH0EQB066X:S=0;M=0;L=0;O=0,AH0EQB067A:S=0;M=0;L=0;O=0,AH0EQB0677:S=0;M=0;L=0;O=0,AH0EQB067E:S=0;M=0;L=0;O=0,AH0EQB06LM:S=0;M=0;L=0;O=0,AH0EQB06LP:S=0;M=0;L=0;O=0,AH0EQB06LH:S=0;M=0;L=0;O=0,AH0EQB06LL:S=0;M=0;L=0;O=0,AH0EQB063E:S=0;M=0;L=0;O=0,AH0EQB062V:S=0;M=0;L=0;O=0,AH0EQB063F:S=0;M=0;L=0;O=0,AH0EQB063B:S=0;M=0;L=0;O=0,AH0EQB063C:S=0;M=0;L=0;O=0,AH0EQB063A:S=0;M=0;L=0;O=0,AH0EQB0635:S=0;M=0;L=0;O=0
JF5ABM20A:S=0;M=0;L=0;O=0,JF5ABM20B:S=0;M=0;L=0;O=0,JF5ABM20C:S=0;M=0;L=0;O=0,JF5ABM20D:S=0;M=0;L=0;O=0,JF5ABM20E:S=0;M=0;L=0;O=0,JF5ABM20F:S=0;M=0;L=0;O=0,JF5ABM20G:S=0;M=0;L=0;O=0,JF5ABM20H:S=0;M=0;L=0;O=0,JF5ABM20J:S=0;M=0;L=0;O=0,JF5ABM20K:S=0;M=0;L=0;O=0,JF5ABM20L:S=0;M=0;L=0;O=0,JF5ABM20M:S=0;M=0;L=0;O=0,JF5ABM20N:S=0;M=0;L=0;O=0,JF5ABM20P:S=0;M=0;L=0;O=0,JF5ABM20Q:S=0;M=0;L=0;O=0,JF5ABM20R:S=0;M=0;L=0;O=0,JF5ABM20S:S=0;M=0;L=0;O=0,JF5ABM20T:S=0;M=0;L=0;O=0,JF5ABM20U:S=0;M=0;L=0;O=0,JF5ABM20V:S=0;M=0;L=0;O=0,JF5ABM20W:S=0;M=0;L=0;O=0,JF5ABM20X:S=0;M=0;L=0;O=0,JF5ABM20Y:S=0;M=0;L=0;O=0,JF5ABM20Z:S=0;M=0;L=0;O=0,JF5ABM201:S=0;M=0;L=0;O=0,JF5ABM202:S=0;M=0;L=0;O=0,JF5ABM203:S=0;M=0;L=0;O=0,JF5ABM204:S=0;M=0;L=0;O=0
AH0EQB05XL:S=0;M=0;L=0;O=0,AH0EQB05XJ:S=0;M=0;L=0;O=0,AH0EQB0658:S=0;M=0;L=0;O=0,AH0EQB065J:S=0;M=0;L=0;O=0,AH0EQB065G:S=0;M=0;L=0;O=0,AH0EQB065E:S=0;M=0;L=0;O=0,AH0EQB065F:S=0;M=0;L=0;O=0,AH0EQB0659:S=0;M=0;L=0;O=0,AH0EQB066U:S=0;M=0;L=0;O=0,AH0EQB066Q:S=0;M=0;L=0;O=0,AH0EQB066T:S=0;M=0;L=0;O=0,AH0EQB05YE:S=0;M=0;L=0;O=0,AH0EQB066S:S=0;M=0;L=0;O=0,AH0EQB066R:S=0;M=0;L=0;O=0,AH0EQB06KF:S=0;M=0;L=0;O=0,AH0EQB064E:S=0;M=0;L=0;O=0,AH0EQB064G:S=0;M=0;L=0;O=0,AH0EQB06GR:S=0;M=0;L=0;O=0,AH0EQB06KP:S=0;M=0;L=0;O=0,AH0EQB064F:S=0;M=0;L=0;O=0,AH0EQB064H:S=0;M=0;L=0;O=0,AH0EQB05WU:S=0;M=0;L=0;O=0,AH0EQB06GE:S=0;M=0;L=0;O=0,AH0EQB06GS:S=0;M=0;L=0;O=0,AH0EQB06JC:S=0;M=0;L=0;O=0,AH0EQB06GF:S=0;M=0;L=0;O=0,AH0EQB06GH:S=0;M=0;L=0;O=0,AH0EQB06J3:S=0;M=0;L=0;O=0,AH0EQB05QS:S=0;M=0;L=0;O=0,AH0EQB05QK:S=0;M=0;L=0;O=0,AH0EQB05QU:S=0;M=0;L=0;O=0,AH0EQB05TS:S=0;M=0;L=0;O=0,AH0EQB05TR:S=0;M=0;L=0;O=0,AH0EQB05TV:S=0;M=0;L=0;O=0,AH0EQB05TQ:S=0;M=0;L=0;O=0,AH0EQB05TT:S=0;M=0;L=0;O=0,AH0EQB05TM:S=0;M=0;L=0;O=0,AH0EQB05QT:S=0;M=0;L=0;O=0,AH0EQB05QC:S=0;M=0;L=0;O=0,AH0EQB05P5:S=0;M=0;L=0;O=0,AH0EQB069B:S=0;M=0;L=0;O=0,AH0EQB069L:S=0;M=0;L=0;O=0,AH0EQB069J:S=0;M=0;L=0;O=0,AH0EQB069G:S=0;M=0;L=0;O=0,AH0EQB069H:S=0;M=0;L=0;O=0,AH0EQB069E:S=0;M=0;L=0;O=0,AH0EQB069F:S=0;M=0;L=0;O=0,AH0EQB069D:S=0;M=0;L=0;O=0,AH0EQB06BS:S=0;M=0;L=0;O=0,AH0EQB06BQ:S=0;M=0;L=0;O=0,AH0EQB05YP:S=0;M=0;L=0;O=0,AH0EQB05Z7:S=0;M=0;L=0;O=0,AH0EQB05W8:S=0;M=0;L=0;O=0,AH0EQB05Z5:S=0;M=0;L=0;O=0,AH0EQB05Z8:S=0;M=0;L=0;O=0
JF5ABM36Z:S=0;M=0;L=0;O=0,JF5ABM361:S=0;M=0;L=0;O=0,JF5ABM362:S=0;M=0;L=0;O=0,JF5ABM363:S=0;M=0;L=0;O=0,JF5ABM364:S=0;M=0;L=0;O=0

2026-01-05 14:46:48,033 - INFO - [save_table] l6a01_project.inspection_api_summary_202511 已寫入 2080 列（去除 0 重複）

inspection_api_summary_202512
AR0DRB0391:S=0;M=0;L=0;O=0,AR0DRB0390:S=0;M=0;L=0;O=0,AR0DRB037K:S=0;M=0;L=0;O=0,AR0DRB037F:S=0;M=0;L=0;O=0
AR0DRB0316:S=0;M=0;L=0;O=0
VV5ABSH7A:S=0;M=0;L=0;O=0,VV5ABSH7B:S=0;M=0;L=0;O=0,VV5ABSH7C:S=0;M=0;L=0;O=0,VV5ABSH7D:S=0;M=0;L=0;O=0,VV5ABSH7E:S=0;M=0;L=0;O=0,VV5ABSH7F:S=0;M=0;L=0;O=0,VV5ABSH7G:S=0;M=0;L=0;O=0,VV5ABSH7H:S=0;M=0;L=0;O=0,VV5ABSH7J:S=0;M=0;L=0;O=0,VV5ABSH7K:S=0;M=0;L=0;O=0,VV5ABSH7L:S=0;M=0;L=0;O=0,VV5ABSH7M:S=0;M=0;L=0;O=0,VV5ABSH7N:S=0;M=0;L=0;O=0,VV5ABSH7P:S=0;M=0;L=0;O=0,VV5ABSH7Q:S=0;M=0;L=0;O=0,VV5ABSH7R:S=0;M=0;L=0;O=0,VV5ABSH7S:S=0;M=0;L=0;O=0,VV5ABSH7T:S=0;M=0;L=0;O=0,VV5ABSH7U:S=0;M=0;L=0;O=0,VV5ABSH7V:S=0;M=0;L=0;O=0,VV5ABSH7W:S=0;M=0;L=0;O=0,VV5ABSH7X:S=0;M=0;L=0;O=0,VV5ABSH7Y:S=0;M=0;L=0;O=0,VV5ABSH7Z:S=0;M=0;L=0;O=0,VV5ABSH71:S=0;M=0;L=0;O=0,VV5ABSH72:S=0;M=0;L=0;O=0,VV5ABSH73:S=0;M=0;L=0;O=0,VV5ABSH74:S=0;M=0;L=0;O=0,VV5ABSR9A:S=0;M=0;L=0;O=0,VV5ABSR9B:S=0;M=0;L=0;O=0,VV5ABSR9C:S=0;M=0;L=0;O=0,VV5ABSR9D:S=0;M=0;L=0;O=0,VV5ABSR9E:S=0;M=0;L=0;O=0,VV5ABSR9F:S=0;M=0;L=0;O=0,VV5ABSR9G:S=0;M=0;L=0;O=0,VV5ABSR9H:S=0;M=0;L=0;O=0,VV5ABSR9J:S=0;M=0;L=0;O=0,VV5ABSR9K:S=0;M=0;L=0;O=0,VV5ABSR9L:S=0;M=0;L=0;O=0,VV5ABSR9M:S=0;M=0;L=0;O=0
AG0UAB0NPN:S=0;M=0;L=0;O=0
AG0UAB0M17:S=0;M=0;L=0;O=0,AG0UAB0M16:S=0;M=0;L=0;O=0
VV5ABSH8A:S=0;M=0;L=0;O=0,VV5ABSH8B:S=0;M=0;L=0;O=0,VV5ABSH8C:S=0;M=0;L=0;O=0,VV5ABSH8D:S=0;M=0;L=0;O=0,VV5ABSH8E:S=0;M=0;L=0;O=0,VV5ABSH8F:S=0;M=0;L=0;O=0,VV5ABSH8G:S=0;M=0;L=0;O=0,VV5ABSH8H:S=0;M=0;L=0;O=0,VV5ABSH8J:S=0;M=0;L=0;O=0,VV5ABSH8K:S=0;M=0;L=0;O=0,VV5ABSH8L:S=0;M=0;L=0;O=0,VV5ABSH8M:S=0;M=0;L=0;O=0
JT5ABRY0A:S=0;M=0;L=0;O=0,JT5ABRY0B:S=0;M=0;L=0;O=0,JT5ABRY0C:S=0;M=0;L=0;O=0,JT5ABRY0D:S=0;M=0;L=0;O=0,JT5ABRY0E:S=0;M=0;L=0;O=0,JT5ABRY0F:S=0;M=0;L=0;O=0,JT5ABRY0G:S=0;M=0;L=0;O=0,JT5ABRY0H:S=0;M=0;L=0;O=0,JT5ABRY0J:S=0;M=0;L=0;O=0,JT5ABRY0K:S=0;M=0;L=0;O=0,JT5ABRY0L:S=0;M=0;L=0;O=0,JT5ABRY0M:S=0;M=0;L=0;O=0,JT5ABRY0N:S=0;M=0;L=0;O=0,JT5ABRY0P:S=0;M=0;L=0;O=0,JT5ABRY0Q:S=0;M=0;L=0;O=0,JT5ABRY0R:S=0;M=0;L=0;O=0
VV5ABT34Z:S=0;M=0;L=0;O=0,VV5ABT341:S=0;M=0;L=0;O=0,VV5ABT342:S=0;M=0;L=0;O=0,VV5ABT343:S=0;M=0;L=0;O=0,VV5ABT344:S=0;M=0;L=0;O=0,VV5ABSK1A:S=0;M=0;L=0;O=0,VV5ABSK1C:S=0;M=0;L=0;O=0,VV5ABSK1D:S=0;M=0;L=0;O=0,VV5ABSK1E:S=0;M=0;L=0;O=0,VV5ABSK1F:S=0;M=0;L=0;O=0,VV5ABSK1G:S=0;M=0;L=0;O=0,VV5ABSK1H:S=0;M=0;L=0;O=0,VV5ABSK1J:S=0;M=0;L=0;O=0
JT5ABS96B:S=0;M=0;L=0;O=0,JT5ABS96C:S=0;M=0;L=0;O=0,JT5ABS96D:S=0;M=0;L=0;O=0,JT5ABS96E:S=0;M=0;L=0;O=0,JT5ABS96F:S=0;M=0;L=0;O=0,JT5ABS96G:S=0;M=0;L=0;O=0,JT5ABS96H:S=0;M=0;L=0;O=0,JT5ABS96J:S=0;M=0;L=0;O=0,JT5ABS96K:S=0;M=0;L=0;O=0,JT5ABS96L:S=0;M=0;L=0;O=0,JT5ABS96M:S=0;M=0;L=0;O=0,JT5ABS96N:S=0;M=0;L=0;O=0,JT5ABS96P:S=0;M=0;L=0;O=0,JT5ABS96Q:S=0;M=0;L=0;O=0,JT5ABS96R:S=0;M=0;L=0;O=0,JT5ABS96S:S=0;M=0;L=0;O=0,JT5ABS96T:S=0;M=0;L=0;O=0,JT5ABS96U:S=0;M=0;L=0;O=0,JT5ABS96V:S=0;M=0;L=0;O=0,JT5ABS96W:S=0;M=0;L=0;O=0,JT5ABS96X:S=0;M=0;L=0;O=0,JT5ABS96Y:S=0;M=0;L=0;O=0,JT5ABS96Z:S=0;M=0;L=0;O=0,JT5ABS961:S=0;M=0;L=0;O=0,JT5ABS962:S=0;M=0;L=0;O=0,JT5ABS963:S=0;M=0;L=0;O=0,JT5ABS964:S=0;M=0;L=0;O=0
AG0UAB0NKG:S=0;M=0;L=0;O=0
YD5ABR10A:S=0;M=0;L=0;O=0,YD5ABR10B:S=0;M=0;L=0;O=0,YD5ABR10C:S=0;M=0;L=0;O=0
AG0UAB0NDC:S=0;M=0;L=0;O=0,AG0UAB0NDA:S=0;M=0;L=0;O=0,AG0UAB0MKN:S=0;M=0;L=0;O=0,AG0UAB0N0Q:S=0;M=0;L=0;O=0,AG0UAB0MKF:S=0;M=0;L=0;O=0
JT5ABRY21:S=0;M=0;L=0;O=0,JT5ABRY22:S=0;M=0;L=0;O=0,JT5ABRY23:S=0;M=0;L=0;O=0,JT5ABRY24:S=0;M=0;L=0;O=0
AE1U8B023U:S=0;M=0;L=0;O=0,AE1U8B01UW:S=0;M=0;L=0;O=0,AE1U8B023T:S=0;M=0;L=0;O=0
AE1U8B026Q:S=0;M=0;L=0;O=0,AE1U8B026S:S=0;M=0;L=0;O=0,AE1U8B026G:S=0;M=0;L=0;O=0,AE1U8B026P:S=0;M=0;L=0;O=0,AE1U8B01GP:S=0;M=0;L=0;O=0,AE1U8B01R4:S=0;M=0;L=0;O=0,AE1U8B0206:S=0;M=0;L=0;O=0,AE1U8B01T7:S=0;M=0;L=0;O=0
AG0UAB0MZD:S=0;M=0;L=0;O=0,AG0UAB0NC4:S=0;M=0;L=0;O=0,AG0UAB0N2Q:S=0;M=0;L=0;O=0,AG0UAB0NC1:S=0;M=0;L=0;O=0,AG0UAB0NC3:S=0;M=0;L=0;O=0,AG0UAB0MN0:S=0;M=0;L=0;O=0
AG0UAB0MYK:S=0;M=0;L=0;O=0
AG0UAB0MBH:S=0;M=0;L=0;O=0,AG0UAB0M93:S=0;M=0;L=0;O=0,AG0UAB0MBJ:S=0;M=0;L=0;O=0,AG0UAB0MBF:S=0;M=0;L=0;O=0,AG0UAB0MBG:S=0;M=0;L=0;O=0,AG0UAB0NMA:S=0;M=0;L=0;O=0,AG0UAB0NA0:S=0;M=0;L=0;O=0,AG0UAB0MBB:S=0;M=0;L=0;O=0,AG0UAB0MB9:S=0;M=0;L=0;O=0,AG0UAB0MBC:S=0;M=0;L=0;O=0,AG0UAB0M9H:S=0;M=0;L=0;O=0,AG0UAB0MB7:S=0;M=0;L=0;O=0,AG0UAB0MBA:S=0;M=0;L=0;O=0,AG0UAB0NA2:S=0;M=0;L=0;O=0,AG0UAB0NDL:S=0;M=0;L=0;O=0,AG0UAB0MFX:S=0;M=0;L=0;O=0,AG0UAB0MG0:S=0;M=0;L=0;O=0,AG0UAB0MRS:S=0;M=0;L=0;O=0,AG0UAB0MRW:S=0;M=0;L=0;O=0
YD5ABQG0A:S=0;M=0;L=0;O=0,YD5ABQG0B:S=0;M=0;L=0;O=0,YD5ABQG0C:S=0;M=0;L=0;O=0,YD5ABQG0D:S=0;M=0;L=0;O=0,YD5ABQG0E:S=0;M=0;L=0;O=0,YD5ABQG0F:S=0;M=0;L=0;O=0,YD5ABQG0G:S=0;M=0;L=0;O=0,YD5ABQG0H:S=0;M=0;L=0;O=0,YD5ABQG0J:S=0;M=0;L=0;O=0,YD5ABQG0K:S=0;M=0;L=0;O=0,YD5ABQG0L:S=0;M=0;L=0;O=0,YD5ABQG0M:S=0;M=0;L=0;O=0,YD5ABQG0N:S=0;M=0;L=0;O=0,YD5ABQG0P:S=0;M=0;L=0;O=0,YD5ABQG0Q:S=0;M=0;L=0;O=0,YD5ABQG0R:S=0;M=0;L=0;O=0,YD5ABQG0S:S=0;M=0;L=0;O=0,YD5ABQG0T:S=0;M=0;L=0;O=0,YD5ABQG0U:S=0;M=0;L=0;O=0,YD5ABQG0V:S=0;M=0;L=0;O=0,YD5ABQG0W:S=0;M=0;L=0;O=0,YD5ABQG0X:S=0;M=0;L=0;O=0,YD5ABQG0Y:S=0;M=0;L=0;O=0,YD5ABQG0Z:S=0;M=0;L=0;O=0,YD5ABQG01:S=0;M=0;L=0;O=0,YD5ABQG02:S=0;M=0;L=0;O=0,YD5ABQG03:S=0;M=0;L=0;O=0,YD5ABQG04:S=0;M=0;L=0;O=0
AE1U8B02S4:S=0;M=0;L=0;O=0,AE1U8B02SB:S=0;M=0;L=0;O=0,AE1U8B03M1:S=0;M=0;L=0;O=0,AE1U8B03RS:S=0;M=0;L=0;O=0,AE1U8B03RT:S=0;M=0;L=0;O=0,AE1U8B03RQ:S=0;M=0;L=0;O=0,AE1U8B03RR:S=0;M=0;L=0;O=0
JT5ABRF1B:S=0;M=0;L=0;O=0,JT5ABRF1C:S=0;M=0;L=0;O=0,JT5ABRF1D:S=0;M=0;L=0;O=0,JT5ABRF1E:S=0;M=0;L=0;O=0,JT5ABRF1F:S=0;M=0;L=0;O=0,JT5ABRF1G:S=0;M=0;L=0;O=0,JT5ABRF1H:S=0;M=0;L=0;O=0,JT5ABRF1J:S=0;M=0;L=0;O=0,JT5ABRF1K:S=0;M=0;L=0;O=0,JT5ABRF1L:S=0;M=0;L=0;O=0,JT5ABRF1M:S=0;M=0;L=0;O=0,JT5ABRF1N:S=0;M=0;L=0;O=0,JT5ABRF1P:S=0;M=0;L=0;O=0,JT5ABRF1Q:S=0;M=0;L=0;O=0,JT5ABRF1R:S=0;M=0;L=0;O=0,JT5ABRF1S:S=0;M=0;L=0;O=0,JT5ABRF1T:S=0;M=0;L=0;O=0,JT5ABRF1U:S=0;M=0;L=0;O=0,JT5ABRF1V:S=0;M=0;L=0;O=0,JT5ABRF1W:S=0;M=0;L=0;O=0,JT5ABRF1X:S=0;M=0;L=0;O=0,JT5ABRF1Y:S=0;M=0;L=0;O=0,JT5ABRF1Z:S=0;M=0;L=0;O=0,JT5ABRF11:S=0;M=0;L=0;O=0,JT5ABRF12:S=0;M=0;L=0;O=0,JT5ABRF13:S=0;M=0;L=0;O=0,JT5ABRF14:S=0;M=0;L=0;O=0,465ABRX4A:S=0;M=0;L=0;O=0,465ABRX4B:S=0;M=0;L=0;O=0,465ABRX4C:S=0;M=0;L=0;O=0,465ABRX4D:S=0;M=0;L=0;O=0,465ABRX4E:S=0;M=0;L=0;O=0,465ABRX4F:S=0;M=0;L=0;O=0,465ABRX4H:S=0;M=0;L=0;O=0,465ABRX4J:S=0;M=0;L=0;O=0,465ABRX4K:S=0;M=0;L=0;O=0,465ABRX4L:S=0;M=0;L=0;O=0
465ABRX4M:S=0;M=0;L=0;O=0,465ABRX4N:S=0;M=0;L=0;O=0,465ABRX4P:S=0;M=0;L=0;O=0,465ABRX4Q:S=0;M=0;L=0;O=0,465ABRX4R:S=0;M=0;L=0;O=0,465ABRX4S:S=0;M=0;L=0;O=0,465ABRX4T:S=0;M=0;L=0;O=0,465ABRX4U:S=0;M=0;L=0;O=0,465ABRX4V:S=0;M=0;L=0;O=0,465ABRX4W:S=0;M=0;L=0;O=0,465ABRX4X:S=0;M=0;L=0;O=0,465ABRX4Y:S=0;M=0;L=0;O=0,465ABRX4Z:S=0;M=0;L=0;O=0,465ABRX41:S=0;M=0;L=0;O=0,465ABRX42:S=0;M=0;L=0;O=0,465ABRX43:S=0;M=0;L=0;O=0,465ABRX44:S=0;M=0;L=0;O=0
AE1U4B0A4H:S=0;M=0;L=0;O=0,AE1U8B039B:S=0;M=0;L=0;O=0,AE1U8B039G:S=0;M=0;L=0;O=0,AE1U8B039J:S=0;M=0;L=0;O=0,AE1U8B039D:S=0;M=0;L=0;O=0,AE1U8B02ZD:S=0;M=0;L=0;O=0,AE1U8B039F:S=0;M=0;L=0;O=0,AE1U8B02VX:S=0;M=0;L=0;O=0,AE1U8B039H:S=0;M=0;L=0;O=0,AE1U8B039L:S=0;M=0;L=0;O=0
YD5ABR11A:S=0;M=0;L=0;O=0,YD5ABR11B:S=0;M=0;L=0;O=0,YD5ABR11C:S=0;M=0;L=0;O=0,YD5ABR11D:S=0;M=0;L=0;O=0,YD5ABR11E:S=0;M=0;L=0;O=0,YD5ABR11F:S=0;M=0;L=0;O=0,YD5ABR11G:S=0;M=0;L=0;O=0,YD5ABR11H:S=0;M=0;L=0;O=0,YD5ABR11J:S=0;M=0;L=0;O=0,YD5ABR11K:S=0;M=0;L=0;O=0,YD5ABR11L:S=0;M=0;L=0;O=0,YD5ABR11M:S=0;M=0;L=0;O=0,YD5ABR11N:S=0;M=0;L=0;O=0,YD5ABR11P:S=0;M=0;L=0;O=0,YD5ABR11Q:S=0;M=0;L=0;O=0,YD5ABR11R:S=0;M=0;L=0;O=0,YD5ABR11S:S=0;M=0;L=0;O=0,YD5ABR11T:S=0;M=0;L=0;O=0
AG0UAB0NDV:S=0;M=0;L=0;O=0,AG0UAB0NDS:S=0;M=0;L=0;O=0,AG0UAB0NDX:S=0;M=0;L=0;O=0,AG0UAB0NDU:S=0;M=0;L=0;O=0,AG0UAB0MNZ:S=0;M=0;L=0;O=0,AG0UAB0MSE:S=0;M=0;L=0;O=0,AG0UAB0MSG:S=0;M=0;L=0;O=0,AG0UAB0MSD:S=0;M=0;L=0;O=0,AG0UAB0MSJ:S=0;M=0;L=0;O=0,AG0UAB0MSF:S=0;M=0;L=0;O=0,AG0UAB0MSL:S=0;M=0;L=0;O=0,AG0UAB0MVR:S=0;M=0;L=0;O=0,AG0UAB0MVS:S=0;M=0;L=0;O=0,AG0UAB0MVU:S=0;M=0;L=0;O=0
465ABRX6D:S=0;M=0;L=0;O=0,465ABRX6E:S=0;M=0;L=0;O=0,465ABRX6F:S=0;M=0;L=0;O=0,465ABRX6G:S=0;M=0;L=0;O=0,465ABRX6H:S=0;M=0;L=0;O=0,465ABRX6J:S=0;M=0;L=0;O=0,465ABRX6K:S=0;M=0;L=0;O=0,465ABRX6L:S=0;M=0;L=0;O=0,465ABRX6M:S=0;M=0;L=0;O=0,465ABRX6N:S=0;M=0;L=0;O=0,465ABRX6Q:S=0;M=0;L=0;O=0,465ABRX6R:S=0;M=0;L=0;O=0,465ABRX6S:S=0;M=0;L=0;O=0,465ABRX6T:S=0;M=0;L=0;O=0,465ABRX6U:S=0;M=0;L=0;O=0,465ABRX6V:S=0;M=0;L=0;O=0,465ABRX6W:S=0;M=0;L=0;O=0,465ABRX6X:S=0;M=0;L=0;O=0,465ABRX6Y:S=0;M=0;L=0;O=0,465ABRX6Z:S=0;M=0;L=0;O=0,465ABRX61:S=0;M=0;L=0;O=0,465ABRX62:S=0;M=0;L=0;O=0,465ABRX63:S=0;M=0;L=0;O=0,465ABRX64:S=0;M=0;L=0;O=0,JT5ABRE5A:S=0;M=0;L=0;O=0,JT5ABRE5B:S=0;M=0;L=0;O=0,JT5ABRE5C:S=0;M=0;L=0;O=0,JT5ABRE5D:S=0;M=0;L=0;O=0,JT5ABRE5E:S=0;M=0;L=0;O=0,JT5ABRE5F:S=0;M=0;L=0;O=0,JT5ABRE5G:S=0;M=0;L=0;O=0,JT5ABRE5H:S=0;M=0;L=0;O=0
JT5ABSA04:S=0;M=0;L=0;O=0,JT5AAM31J:S=0;M=0;L=0;O=0,JT5AAM31H:S=0;M=0;L=0;O=0
AR0T2B005J:S=0;M=0;L=0;O=0,AR0T2B005X:S=0;M=0;L=0;O=0,AR0T2B000L:S=0;M=0;L=0;O=0,20251203215551:S=0;M=0;L=0;O=0,AR0T2B005W:S=0;M=0;L=0;O=0,AR0T2B005G:S=0;M=0;L=0;O=0,AR0T2B0039:S=0;M=0;L=0;O=0,20251203215930:S=0;M=0;L=0;O=0
AR0T2B000D:S=0;M=0;L=0;O=0,AR0T2B0035:S=0;M=0;L=0;O=0,AR0T2B000B:S=0;M=0;L=0;O=0,20251203220316:S=0;M=0;L=0;O=0,AR0T2B003K:S=0;M=0;L=0;O=0,AR0T2B0034:S=0;M=0;L=0;O=0,AR0T2B003A:S=0;M=0;L=0;O=0,20251203220656:S=0;M=0;L=0;O=0,AR0T2B0007:S=0;M=0;L=0;O=0,AR0T2B005R:S=0;M=0;L=0;O=0,AR0T2B003B:S=0;M=0;L=0;O=0,20251203221039:S=0;M=0;L=0;O=0,AR0T2B002C:S=0;M=0;L=0;O=0,AR0T2B002X:S=0;M=0;L=0;O=0,AR0T2B0002:S=0;M=0;L=0;O=0,AR0T2B004Y:S=0;M=0;L=0;O=0,AR0T2B0051:S=0;M=0;L=0;O=0,AR0T2B003R:S=0;M=0;L=0;O=0,AR0T2B001W:S=0;M=0;L=0;O=0,AR0T2B002E:S=0;M=0;L=0;O=0,20251203221853:S=0;M=0;L=0;O=0,AR0T2B0004:S=0;M=0;L=0;O=0,AR0T2B002Q:S=0;M=0;L=0;O=0,20251203222138:S=0;M=0;L=0;O=0,AR0T2B002U:S=0;M=0;L=0;O=0,AR0T2B002P:S=0;M=0;L=0;O=0,AR0T2B002S:S=0;M=0;L=0;O=0,20251203222518:S=0;M=0;L=0;O=0,AR0T2B002N:S=0;M=0;L=0;O=0,AR0T2B0009:S=0;M=0;L=0;O=0,AR0T2B002G:S=0;M=0;L=0;O=0,20251203222859:S=0;M=0;L=0;O=0,AR0T2B002L:S=0;M=0;L=0;O=0,AR0T2B0027:S=0;M=0;L=0;O=0,AR0T2B002J:S=0;M=0;L=0;O=0,20251203223239:S=0;M=0;L=0;O=0,AR0T2B000E:S=0;M=0;L=0;O=0,AR0T2B001D:S=0;M=0;L=0;O=0,AR0T2B000S:S=0;M=0;L=0;O=0,20251203223624:S=0;M=0;L=0;O=0,AR0T2B0030:S=0;M=0;L=0;O=0,AR0T2B0032:S=0;M=0;L=0;O=0,AR0T2B005D:S=0;M=0;L=0;O=0,20251203224006:S=0;M=0;L=0;O=0,AR0T2B003Y:S=0;M=0;L=0;O=0,AR0T2B004B:S=0;M=0;L=0;O=0,AR0T2B004M:S=0;M=0;L=0;O=0,20251203224346:S=0;M=0;L=0;O=0,GY5AAQV0B:S=0;M=0;L=0;O=0,GY5AAQV0C:S=0;M=0;L=0;O=0,GY5AAQV0D:S=0;M=0;L=0;O=0,20251203224731:S=0;M=0;L=0;O=0,GY5AAQV0F:S=0;M=0;L=0;O=0,GY5AAQV0G:S=0;M=0;L=0;O=0,GY5AAQV0H:S=0;M=0;L=0;O=0,GY5AAQV0J:S=0;M=0;L=0;O=0,GY5AAQV0K:S=0;M=0;L=0;O=0,GY5AAQV0L:S=0;M=0;L=0;O=0,20251203225414:S=0;M=0;L=0;O=0,GY5AAQV0N:S=0;M=0;L=0;O=0,20251203225555:S=0;M=0;L=0;O=0,20251203225657:S=0;M=0;L=0;O=0,GY5AAQV0R:S=0;M=0;L=0;O=0,GY5AAQV0S:S=0;M=0;L=0;O=0,20251203225940:S=0;M=0;L=0;O=0
AG0UAC0498:S=0;M=0;L=0;O=0,AG0UAC049M:S=0;M=0;L=0;O=0,AG0UAC049R:S=0;M=0;L=0;O=0,AG0UAC04JG:S=0;M=0;L=0;O=0,AG0UAC048F:S=0;M=0;L=0;O=0,AG0UAC048G:S=0;M=0;L=0;O=0,AG0UAC0480:S=0;M=0;L=0;O=0,AG0UAC048U:S=0;M=0;L=0;O=0,AG0UAC0463:S=0;M=0;L=0;O=0,AG0UAC0466:S=0;M=0;L=0;O=0,AG0UAC0468:S=0;M=0;L=0;O=0,AG0UAC04W5:S=0;M=0;L=0;O=0,AG0UAC04DF:S=0;M=0;L=0;O=0,AG0UAC0495:S=0;M=0;L=0;O=0
GY5AAQV0U:S=0;M=0;L=0;O=0,GY5AAQV0V:S=0;M=0;L=0;O=0,20251203230219:S=0;M=0;L=0;O=0,GY5AAQV0X:S=0;M=0;L=0;O=0,GY5AAQV0Y:S=0;M=0;L=0;O=0,GY5AAQV0Z:S=0;M=0;L=0;O=0,20251203230605:S=0;M=0;L=0;O=0,GY5AAQV02:S=0;M=0;L=0;O=0,GY5AAQV03:S=0;M=0;L=0;O=0,GY5AAQV04:S=0;M=0;L=0;O=0,20251203230941:S=0;M=0;L=0;O=0,GY5AAQD9B:S=0;M=0;L=0;O=0,GY5AAQD9C:S=0;M=0;L=0;O=0,GY5AAQD9D:S=0;M=0;L=0;O=0,20251203231322:S=0;M=0;L=0;O=0,GY5AAQD9F:S=0;M=0;L=0;O=0,GY5AAQD9G:S=0;M=0;L=0;O=0,GY5AAQD9H:S=0;M=0;L=0;O=0,20251203231701:S=0;M=0;L=0;O=0,GY5AAQD9K:S=0;M=0;L=0;O=0,GY5AAQD9L:S=0;M=0;L=0;O=0,GY5AAQD9N:S=0;M=0;L=0;O=0,GY5AAQD9P:S=0;M=0;L=0;O=0,20251203232421:S=0;M=0;L=0;O=0,GY5AAQD9R:S=0;M=0;L=0;O=0
AF0U3C02H7:S=0;M=0;L=0;O=0
AG0UAC046R:S=0;M=0;L=0;O=0,AG0UAC046Y:S=0;M=0;L=0;O=0,AG0UAC0470:S=0;M=0;L=0;O=0,AG0UAC0479:S=0;M=0;L=0;O=0,AG0UAC04H7:S=0;M=0;L=0;O=0,AG0UAC04HG:S=0;M=0;L=0;O=0,AG0UAC04HQ:S=0;M=0;L=0;O=0,AG0UAC04JP:S=0;M=0;L=0;O=0,AG0UAC04BU:S=0;M=0;L=0;O=0,AG0UAC04V9:S=0;M=0;L=0;O=0,AG0UAC04JQ:S=0;M=0;L=0;O=0,AG0UAC04JM:S=0;M=0;L=0;O=0,AG0UAC04V3:S=0;M=0;L=0;O=0,AG0UAC04JL:S=0;M=0;L=0;O=0
YD5ABTJ2A:S=0;M=0;L=0;O=0,YD5ABTJ2B:S=0;M=0;L=0;O=0,YD5ABTJ2C:S=0;M=0;L=0;O=0,YD5ABTJ2D:S=0;M=0;L=0;O=0,YD5ABTJ2E:S=0;M=0;L=0;O=0,YD5ABTJ2F:S=0;M=0;L=0;O=0,YD5ABTJ2G:S=0;M=0;L=0;O=0,YD5ABTJ2H:S=0;M=0;L=0;O=0,YD5ABTJ2J:S=0;M=0;L=0;O=0,YD5ABTJ2K:S=0;M=0;L=0;O=0,YD5ABTJ2L:S=0;M=0;L=0;O=0,YD5ABTJ2M:S=0;M=0;L=0;O=0,YD5ABTJ2N:S=0;M=0;L=0;O=0,YD5ABTJ2P:S=0;M=0;L=0;O=0,YD5ABTJ2Q:S=0;M=0;L=0;O=0,YD5ABTJ2R:S=0;M=0;L=0;O=0,YD5ABTJ2S:S=0;M=0;L=0;O=0,YD5ABTJ2T:S=0;M=0;L=0;O=0,YD5ABTJ2U:S=0;M=0;L=0;O=0,YD5ABTJ2V:S=0;M=0;L=0;O=0,YD5ABTJ2W:S=0;M=0;L=0;O=0,YD5ABTJ2X:S=0;M=0;L=0;O=0,YD5ABTJ2Y:S=0;M=0;L=0;O=0,YD5ABTJ2Z:S=0;M=0;L=0;O=0,YD5ABTJ21:S=0;M=0;L=0;O=0,YD5ABTJ22:S=0;M=0;L=0;O=0,YD5ABTJ23:S=0;M=0;L=0;O=0,YD5ABTJ24:S=0;M=0;L=0;O=0,YD5ABPM6A:S=0;M=0;L=0;O=0,YD5ABPM6B:S=0;M=0;L=0;O=0,YD5ABPM6C:S=0;M=0;L=0;O=0,YD5ABPM6D:S=0;M=0;L=0;O=0,YD5ABPM6E:S=0;M=0;L=0;O=0,YD5ABPM6F:S=0;M=0;L=0;O=0,YD5ABPM6G:S=0;M=0;L=0;O=0,YD5ABPM6H:S=0;M=0;L=0;O=0,YD5ABPM6J:S=0;M=0;L=0;O=0,YD5ABPM6K:S=0;M=0;L=0;O=0,YD5ABPM6L:S=0;M=0;L=0;O=0,YD5ABPM6M:S=0;M=0;L=0;O=0,YD5ABPM6N:S=0;M=0;L=0;O=0,YD5ABPM6P:S=0;M=0;L=0;O=0,YD5ABPM6Q:S=0;M=0;L=0;O=0,YD5ABPM6R:S=0;M=0;L=0;O=0,YD5ABPM6S:S=0;M=0;L=0;O=0,YD5ABPM6T:S=0;M=0;L=0;O=0,YD5ABPM6U:S=0;M=0;L=0;O=0,YD5ABPM6V:S=0;M=0;L=0;O=0,YD5ABPM6W:S=0;M=0;L=0;O=0,YD5ABPM6X:S=0;M=0;L=0;O=0,YD5ABPM6Y:S=0;M=0;L=0;O=0,YD5ABPM6Z:S=0;M=0;L=0;O=0,YD5ABPM61:S=0;M=0;L=0;O=0,YD5ABPM62:S=0;M=0;L=0;O=0
AR0T2B000P:S=0;M=0;L=0;O=0,20251204011619:S=0;M=0;L=0;O=0,20251204011723:S=0;M=0;L=0;O=0,AR0T2B005M:S=0;M=0;L=0;O=0,20251204011903:S=0;M=0;L=0;O=0,AR0T2B0056:S=0;M=0;L=0;O=0,AR0T2B003N:S=0;M=0;L=0;O=0,20251204012148:S=0;M=0;L=0;O=0,AR0T2B002H:S=0;M=0;L=0;O=0,AR0T2B003F:S=0;M=0;L=0;O=0,AR0T2B000N:S=0;M=0;L=0;O=0,20251204012527:S=0;M=0;L=0;O=0,AR0T2B0038:S=0;M=0;L=0;O=0,AR0T2B001T:S=0;M=0;L=0;O=0,AR0T2B000A:S=0;M=0;L=0;O=0,20251204012908:S=0;M=0;L=0;O=0,AR0T2B003D:S=0;M=0;L=0;O=0,AR0T2B002A:S=0;M=0;L=0;O=0,AR0T2B0047:S=0;M=0;L=0;O=0,20251204013254:S=0;M=0;L=0;O=0,AR0T2B0048:S=0;M=0;L=0;O=0,AR0T2B001R:S=0;M=0;L=0;O=0,AR0T2B000X:S=0;M=0;L=0;O=0,20251204013630:S=0;M=0;L=0;O=0,AR0T2B001P:S=0;M=0;L=0;O=0,AR0T2B005H:S=0;M=0;L=0;O=0,AR0T2B000R:S=0;M=0;L=0;O=0,AR0T2B005T:S=0;M=0;L=0;O=0,GY5AAQD94:S=0;M=0;L=0;O=0,GY5AAQD8A:S=0;M=0;L=0;O=0,GY5AAQD8B:S=0;M=0;L=0;O=0,20251204014348:S=0;M=0;L=0;O=0,GY5AAQD8D:S=0;M=0;L=0;O=0,GY5AAQD8E:S=0;M=0;L=0;O=0,GY5AAQD8F:S=0;M=0;L=0;O=0,20251204014722:S=0;M=0;L=0;O=0,GY5AAQD8H:S=0;M=0;L=0;O=0,GY5AAQD8J:S=0;M=0;L=0;O=0,GY5AAQD8K:S=0;M=0;L=0;O=0,20251204015057:S=0;M=0;L=0;O=0,GY5AAQD8M:S=0;M=0;L=0;O=0,GY5AAQD8N:S=0;M=0;L=0;O=0,GY5AAQD8P:S=0;M=0;L=0;O=0,20251204015431:S=0;M=0;L=0;O=0,GY5AAQD93:S=0;M=0;L=0;O=0,GY5AAQD92:S=0;M=0;L=0;O=0,GY5AAQD8R:S=0;M=0;L=0;O=0,20251204015805:S=0;M=0;L=0;O=0,GY5AAQD8T:S=0;M=0;L=0;O=0
GY5AAQD8U:S=0;M=0;L=0;O=0,GY5AAQD8V:S=0;M=0;L=0;O=0,20251204020139:S=0;M=0;L=0;O=0,GY5AAQD8X:S=0;M=0;L=0;O=0,GY5AAQD8Y:S=0;M=0;L=0;O=0,GY5AAQD8Z:S=0;M=0;L=0;O=0,20251204020513:S=0;M=0;L=0;O=0,GY5AAQD82:S=0;M=0;L=0;O=0,GY5AAQD83:S=0;M=0;L=0;O=0,GY5AAQD84:S=0;M=0;L=0;O=0,20251204020851:S=0;M=0;L=0;O=0,GY5AAQD9Z:S=0;M=0;L=0;O=0,GY5AAQD9Y:S=0;M=0;L=0;O=0,GY5AAQD9X:S=0;M=0;L=0;O=0,20251204021222:S=0;M=0;L=0;O=0,GY5AAQD9V:S=0;M=0;L=0;O=0,GY5AAQD9U:S=0;M=0;L=0;O=0,GY5AAQD9T:S=0;M=0;L=0;O=0,20251204021556:S=0;M=0;L=0;O=0
AF0U3C025N:S=0;M=0;L=0;O=0,AF0U3C025D:S=0;M=0;L=0;O=0,AF0U3C025F:S=0;M=0;L=0;O=0,AF0U3C02GV:S=0;M=0;L=0;O=0,AF0U3C02GW:S=0;M=0;L=0;O=0,AF0U3C02GX:S=0;M=0;L=0;O=0,AF0U3C02H1:S=0;M=0;L=0;O=0,AF0U3C02GU:S=0;M=0;L=0;O=0,AF0U3C02H0:S=0;M=0;L=0;O=0,AF0U3C02GY:S=0;M=0;L=0;O=0,AF0U3C0219:S=0;M=0;L=0;O=0,AF0U3C02QZ:S=0;M=0;L=0;O=0,AF0U3C01UU:S=0;M=0;L=0;O=0,AF0U3C01UN:S=0;M=0;L=0;O=0,AF0U3C01UV:S=0;M=0;L=0;O=0,AF0U3C01VR:S=0;M=0;L=0;O=0,AF0U3C02AC:S=0;M=0;L=0;O=0,AF0U3C02A4:S=0;M=0;L=0;O=0,AF0U3C02AJ:S=0;M=0;L=0;O=0,AF0U3C02AD:S=0;M=0;L=0;O=0,AF0U3C02A6:S=0;M=0;L=0;O=0,AF0U3C02AB:S=0;M=0;L=0;O=0,AF0U3C02A0:S=0;M=0;L=0;O=0,AF0U3C02A7:S=0;M=0;L=0;O=0,AF0U3C025J:S=0;M=0;L=0;O=0,AF0U3C02A1:S=0;M=0;L=0;O=0,AF0U3C02A2:S=0;M=0;L=0;O=0
AF0U3C01K7:S=0;M=0;L=0;O=0,AF0U3B0385:S=0;M=0;L=0;O=0,AF0U3C01YA:S=0;M=0;L=0;O=0
AA1X69016U:S=0;M=0;L=0;O=0
Y25AATG4A:S=0;M=0;L=0;O=0,Y25AATG4B:S=0;M=0;L=0;O=0,Y25AATG4C:S=0;M=0;L=0;O=0,Y25AATG4D:S=0;M=0;L=0;O=0,Y25AATG4E:S=0;M=0;L=0;O=0,Y25AATG4F:S=0;M=0;L=0;O=0
AG0UAC04LR:S=0;M=0;L=0;O=0,AG0UAC04LK:S=0;M=0;L=0;O=0,AG0UAC04G8:S=0;M=0;L=0;O=0,AG0UAC04LL:S=0;M=0;L=0;O=0,AG0UAC04W7:S=0;M=0;L=0;O=0,AG0UAC04N3:S=0;M=0;L=0;O=0,AG0UAC04MM:S=0;M=0;L=0;O=0,AG0UAC04MB:S=0;M=0;L=0;O=0,AG0UAC04N9:S=0;M=0;L=0;O=0,AG0UAC04NU:S=0;M=0;L=0;O=0,AG0UAC0494:S=0;M=0;L=0;O=0,AG0UAC0492:S=0;M=0;L=0;O=0,AG0UAC0493:S=0;M=0;L=0;O=0,AG0UAC0490:S=0;M=0;L=0;O=0,AG0UAC04PN:S=0;M=0;L=0;O=0,AG0UAC0491:S=0;M=0;L=0;O=0,AG0UAC048Y:S=0;M=0;L=0;O=0,AG0UAC04SM:S=0;M=0;L=0;O=0,AG0UAC04S3:S=0;M=0;L=0;O=0,AG0UAC04SN:S=0;M=0;L=0;O=0,AG0UAC0505:S=0;M=0;L=0;O=0,AG0UAC04WR:S=0;M=0;L=0;O=0,AG0UAC04U3:S=0;M=0;L=0;O=0,AG0UAC04WJ:S=0;M=0;L=0;O=0,AG0UAC04TY:S=0;M=0;L=0;O=0,AG0UAC04UD:S=0;M=0;L=0;O=0,AG0UAC04U6:S=0;M=0;L=0;O=0,AG0UAC04GE:S=0;M=0;L=0;O=0
AG0UAC04BC:S=0;M=0;L=0;O=0,AG0UAC04B8:S=0;M=0;L=0;O=0,AG0UAC04B9:S=0;M=0;L=0;O=0,AG0UAC04BB:S=0;M=0;L=0;O=0,AG0UAC04BD:S=0;M=0;L=0;O=0,AG0UAC04CA:S=0;M=0;L=0;O=0,AG0UAC04CB:S=0;M=0;L=0;O=0,AG0UAC04J9:S=0;M=0;L=0;O=0,AG0UAC04J6:S=0;M=0;L=0;O=0,AG0UAC0482:S=0;M=0;L=0;O=0,AG0UAC047W:S=0;M=0;L=0;O=0,AG0UAC047L:S=0;M=0;L=0;O=0,AG0UAC047G:S=0;M=0;L=0;O=0,AG0UAC04W8:S=0;M=0;L=0;O=0,AG0UAC04M7:S=0;M=0;L=0;O=0,AG0UAC04V8:S=0;M=0;L=0;O=0,AG0UAC04LX:S=0;M=0;L=0;O=0,AG0UAC04LV:S=0;M=0;L=0;O=0
AA1X6900SF:S=0;M=0;L=0;O=0,AA1X6900SH:S=0;M=0;L=0;O=0,AA1X6900SG:S=0;M=0;L=0;O=0,AA1X6900SD:S=0;M=0;L=0;O=0,AA1X6900SE:S=0;M=0;L=0;O=0,AA1X6900U0:S=0;M=0;L=0;O=0,AA1X6900K6:S=0;M=0;L=0;O=0,AA1X69019W:S=0;M=0;L=0;O=0,AA1X6900K4:S=0;M=0;L=0;O=0,AA1X6900K2:S=0;M=0;L=0;O=0,AA1X6900K7:S=0;M=0;L=0;O=0,AA1X6900LJ:S=0;M=0;L=0;O=0,AA1X6900K5:S=0;M=0;L=0;O=0,AA1X6900K0:S=0;M=0;L=0;O=0,AA1X6900K3:S=0;M=0;L=0;O=0,AA1X6900LG:S=0;M=0;L=0;O=0,AA1X6900JZ:S=0;M=0;L=0;O=0,AA1X6801KR:S=0;M=0;L=0;O=0,AA1X6801KN:S=0;M=0;L=0;O=0,AA1X6801KS:S=0;M=0;L=0;O=0,AA1X6801KT:S=0;M=0;L=0;O=0,AA1X6801KX:S=0;M=0;L=0;O=0,AA1X6801KU:S=0;M=0;L=0;O=0,AA1X680206:S=0;M=0;L=0;O=0,AA1X680205:S=0;M=0;L=0;O=0,AA1X680208:S=0;M=0;L=0;O=0,AA1X680207:S=0;M=0;L=0;O=0,AA1X680222:S=0;M=0;L=0;O=0,AA1X680209:S=0;M=0;L=0;O=0,AA1X6800SG:S=0;M=0;L=0;O=0,AA1X6800SM:S=0;M=0;L=0;O=0,AA1X6800SS:S=0;M=0;L=0;O=0,AA1X6800SP:S=0;M=0;L=0;O=0,AA1X680086:S=0;M=0;L=0;O=0,AA1X6800SV:S=0;M=0;L=0;O=0,AA1X6800BL:S=0;M=0;L=0;O=0,AA1X680082:S=0;M=0;L=0;O=0,AA1X68006F:S=0;M=0;L=0;O=0,AA1X68006H:S=0;M=0;L=0;O=0,AA1X680083:S=0;M=0;L=0;O=0,AA1X6800BN:S=0;M=0;L=0;O=0
AF0U3C01UW:S=0;M=0;L=0;O=0,AF0U3C01VX:S=0;M=0;L=0;O=0,AF0U3C01W0:S=0;M=0;L=0;O=0,AF0U3C02RU:S=0;M=0;L=0;O=0,AF0U3C02RW:S=0;M=0;L=0;O=0,AF0U3C02GP:S=0;M=0;L=0;O=0,AF0U3C01XA:S=0;M=0;L=0;O=0,AF0U3C02GN:S=0;M=0;L=0;O=0
AG0UAC058J:S=0;M=0;L=0;O=0,AG0UAC055R:S=0;M=0;L=0;O=0,AG0UAC054Q:S=0;M=0;L=0;O=0,AG0UAC054M:S=0;M=0;L=0;O=0,AG0UAC055Z:S=0;M=0;L=0;O=0,AG0UAC054L:S=0;M=0;L=0;O=0,AG0UAC055S:S=0;M=0;L=0;O=0,AG0UAC0539:S=0;M=0;L=0;O=0,AG0UAC055W:S=0;M=0;L=0;O=0,AG0UAC055U:S=0;M=0;L=0;O=0,AG0UAC055H:S=0;M=0;L=0;O=0,AG0UAC057V:S=0;M=0;L=0;O=0,AG0UAC055G:S=0;M=0;L=0;O=0,AG0UAC05CP:S=0;M=0;L=0;O=0,AG0UAC05CJ:S=0;M=0;L=0;O=0,AG0UAC0538:S=0;M=0;L=0;O=0

2026-01-05 14:46:53,066 - INFO - [save_table] l6a01_project.inspection_api_summary_202512 已寫入 4366 列（去除 0 重複）

inspection_api_summary_202601
A25ACPC54:S=0;M=0;L=0;O=0,A25ACPC0A:S=0;M=0;L=0;O=0,A25ACPC0B:S=0;M=0;L=0;O=0
AG0UAC0E78:S=0;M=0;L=0;O=0,AG0UAC0E5U:S=0;M=0;L=0;O=0,AG0UAC0EFG:S=0;M=0;L=0;O=0,AG0UAC0E5W:S=0;M=0;L=0;O=0,AG0UAC0EFJ:S=0;M=0;L=0;O=0,AG0UAC0E5Y:S=0;M=0;L=0;O=0,AG0UAC0EJR:S=0;M=0;L=0;O=0,AG0UAC0EJS:S=0;M=0;L=0;O=0,AG0UAC0EJT:S=0;M=0;L=0;O=0,AG0UAC0EN5:S=0;M=0;L=0;O=0,AG0UAC0ENA:S=0;M=0;L=0;O=0,AG0UAC0EJU:S=0;M=0;L=0;O=0,AG0UAC0EH4:S=0;M=0;L=0;O=0,AG0UAC0EFU:S=0;M=0;L=0;O=0,AG0UAC0EH2:S=0;M=0;L=0;O=0
AA1X6C06LF:S=0;M=0;L=0;O=0
AG0UAC0EHC:S=0;M=0;L=0;O=0,AG0UAC0EHD:S=0;M=0;L=0;O=0,AG0UAC0EH5:S=0;M=0;L=0;O=0,AG0UAC0EH8:S=0;M=0;L=0;O=0,AG0UAC0EJW:S=0;M=0;L=0;O=0,AG0UAC0EH9:S=0;M=0;L=0;O=0,AG0UAC0ENS:S=0;M=0;L=0;O=0,AG0UAC0ENJ:S=0;M=0;L=0;O=0,AG0UAC0ENG:S=0;M=0;L=0;O=0,AG0UAC0ENH:S=0;M=0;L=0;O=0,AG0UAC0ENK:S=0;M=0;L=0;O=0,AG0UAC0ENL:S=0;M=0;L=0;O=0,AG0UAC0EPQ:S=0;M=0;L=0;O=0,AG0UAC0ENP:S=0;M=0;L=0;O=0,AG0UAC0EPR:S=0;M=0;L=0;O=0,AG0UAC0ENR:S=0;M=0;L=0;O=0,AG0UAC0EPN:S=0;M=0;L=0;O=0,AG0UAC0EPP:S=0;M=0;L=0;O=0,AG0UAC0EG8:S=0;M=0;L=0;O=0,AG0UAC0E7J:S=0;M=0;L=0;O=0,AG0UAC0E8R:S=0;M=0;L=0;O=0,AG0UAC0E8S:S=0;M=0;L=0;O=0,AG0UAC0E8P:S=0;M=0;L=0;O=0,AG0UAC0E8Q:S=0;M=0;L=0;O=0,AG0UAC0E8M:S=0;M=0;L=0;O=0,AG0UAC0ECT:S=0;M=0;L=0;O=0,AG0UAC0ELS:S=0;M=0;L=0;O=0,AG0UAC0ELU:S=0;M=0;L=0;O=0,AG0UAC0ELT:S=0;M=0;L=0;O=0,AG0UAC0ELW:S=0;M=0;L=0;O=0,AG0UAC0ELV:S=0;M=0;L=0;O=0,AG0UAC0ELX:S=0;M=0;L=0;O=0,AG0UAC0ELY:S=0;M=0;L=0;O=0,AG0UAC0EN8:S=0;M=0;L=0;O=0,AG0UAC0ELZ:S=0;M=0;L=0;O=0,AG0UAC0EM2:S=0;M=0;L=0;O=0,AG0UAC0EH7:S=0;M=0;L=0;O=0,AG0UAC0EHB:S=0;M=0;L=0;O=0,AG0UAC0EF8:S=0;M=0;L=0;O=0,AG0UAC0EDR:S=0;M=0;L=0;O=0,AG0UAC0ER8:S=0;M=0;L=0;O=0,AG0UAC0EFA:S=0;M=0;L=0;O=0,AG0UAC0EJQ:S=0;M=0;L=0;O=0,AG0UAC0EDT:S=0;M=0;L=0;O=0,AG0UAC0EPH:S=0;M=0;L=0;O=0,AG0UAC0EN7:S=0;M=0;L=0;O=0,AG0UAC0EPJ:S=0;M=0;L=0;O=0,AG0UAC0EHT:S=0;M=0;L=0;O=0,AG0UAC0EHS:S=0;M=0;L=0;O=0,AG0UAC0EHN:S=0;M=0;L=0;O=0,AG0UAC0EHP:S=0;M=0;L=0;O=0,AG0UAC0EHM:S=0;M=0;L=0;O=0,AG0UAC0EHL:S=0;M=0;L=0;O=0,AG0UAC0EHJ:S=0;M=0;L=0;O=0,AG0UAC0EHA:S=0;M=0;L=0;O=0,AG0UAC0EHF:S=0;M=0;L=0;O=0,AG0UAC0EHG:S=0;M=0;L=0;O=0,AG0UAC0E6Y:S=0;M=0;L=0;O=0,AG0UAC0E75:S=0;M=0;L=0;O=0,AG0UAC0E76:S=0;M=0;L=0;O=0,AG0UAC0EHY:S=0;M=0;L=0;O=0,AG0UAC0EJ0:S=0;M=0;L=0;O=0,AG0UAC0F3M:S=0;M=0;L=0;O=0,AG0UAC0F3P:S=0;M=0;L=0;O=0,AG0UAC0F3R:S=0;M=0;L=0;O=0,AG0UAC0F3S:S=0;M=0;L=0;O=0,AG0UAC0EN3:S=0;M=0;L=0;O=0
A25ACPC3Y:S=0;M=0;L=0;O=0,A25ACPC3Z:S=0;M=0;L=0;O=0,A25ACPC31:S=0;M=0;L=0;O=0,A25ACPC32:S=0;M=0;L=0;O=0,A25ACPC33:S=0;M=0;L=0;O=0,A25ACPC34:S=0;M=0;L=0;O=0
AL5HZC08NZ:S=0;M=0;L=0;O=0,AL5HZC092Y:S=0;M=0;L=0;O=0,AL5HZC08QB:S=0;M=0;L=0;O=0,AL5HZC08P0:S=0;M=0;L=0;O=0,MQ5ACWS5U:S=0;M=0;L=0;O=0,MQ5ACWR94:S=0;M=0;L=0;O=0,AL5HZC08W3:S=0;M=0;L=0;O=0
Y25ACQS24:S=0;M=0;L=0;O=0,AF0U3C03BR:S=0;M=0;L=0;O=0
AF0U3C04Y1:S=0;M=0;L=0;O=0,AF0U3C04Y5:S=0;M=0;L=0;O=0,AF0U3C04W9:S=0;M=0;L=0;O=0,AF0U3C04Y9:S=0;M=0;L=0;O=0,AF0U3C04Y3:S=0;M=0;L=0;O=0,AF0U3C04Y7:S=0;M=0;L=0;O=0,AF0U3C04XZ:S=0;M=0;L=0;O=0,AF0U3C03PK:S=0;M=0;L=0;O=0,AF0U3C03QG:S=0;M=0;L=0;O=0,AF0U3C03QB:S=0;M=0;L=0;O=0,AF0U3C03PL:S=0;M=0;L=0;O=0,AF0U3C03PJ:S=0;M=0;L=0;O=0,AF0U3C051P:S=0;M=0;L=0;O=0,AF0U3C04EW:S=0;M=0;L=0;O=0,AF0U3C051E:S=0;M=0;L=0;O=0,AF0U3C051K:S=0;M=0;L=0;O=0,AF0U3C04F1:S=0;M=0;L=0;O=0,AF0U3C04DW:S=0;M=0;L=0;O=0,AF0U3C04FS:S=0;M=0;L=0;O=0,AF0U3C04FR:S=0;M=0;L=0;O=0,AF0U3C04FL:S=0;M=0;L=0;O=0,AF0U3C04F8:S=0;M=0;L=0;O=0,AF0U3C04FK:S=0;M=0;L=0;O=0,AF0U3C04FF:S=0;M=0;L=0;O=0,AF0U3C04F9:S=0;M=0;L=0;O=0,AF0U3C04FC:S=0;M=0;L=0;O=0,AF0U3C04FB:S=0;M=0;L=0;O=0,AF0U3C04FG:S=0;M=0;L=0;O=0,AF0U3C04FA:S=0;M=0;L=0;O=0,AF0U3C04FD:S=0;M=0;L=0;O=0,AF0U3C04FE:S=0;M=0;L=0;O=0,AF0U3C04EZ:S=0;M=0;L=0;O=0,AF0U3C04FH:S=0;M=0;L=0;O=0,AF0U3C04FJ:S=0;M=0;L=0;O=0,AF0U3C04F4:S=0;M=0;L=0;O=0,AF0U3C04MB:S=0;M=0;L=0;O=0,AF0U3C04ER:S=0;M=0;L=0;O=0,AF0U3C04QF:S=0;M=0;L=0;O=0,AF0U3C04ET:S=0;M=0;L=0;O=0,AF0U3C04EQ:S=0;M=0;L=0;O=0
Y25ACQR2A:S=0;M=0;L=0;O=0,Y25ACQR2B:S=0;M=0;L=0;O=0,Y25ACQR2C:S=0;M=0;L=0;O=0,Y25ACQR2D:S=0;M=0;L=0;O=0,Y25ACQR2E:S=0;M=0;L=0;O=0,Y25ACQR2F:S=0;M=0;L=0;O=0,Y25ACQR2G:S=0;M=0;L=0;O=0,Y25ACQR2H:S=0;M=0;L=0;O=0,Y25ACQR2J:S=0;M=0;L=0;O=0,Y25ACQR2K:S=0;M=0;L=0;O=0,Y25ACQR2L:S=0;M=0;L=0;O=0,Y25ACQR2M:S=0;M=0;L=0;O=0
AF0U3C04JD:S=0;M=0;L=0;O=0,AF0U3C04J7:S=0;M=0;L=0;O=0,AF0U3C04J8:S=0;M=0;L=0;O=0,AF0U3C04JA:S=0;M=0;L=0;O=0,AF0U3C04SG:S=0;M=0;L=0;O=0,AF0U3C04SD:S=0;M=0;L=0;O=0,AF0U3C04S7:S=0;M=0;L=0;O=0,AF0U3C03G6:S=0;M=0;L=0;O=0,AF0U3C03EW:S=0;M=0;L=0;O=0,AF0U3C03F0:S=0;M=0;L=0;O=0,AF0U3C03E9:S=0;M=0;L=0;O=0,AF0U3C03F3:S=0;M=0;L=0;O=0,AF0U3C03FA:S=0;M=0;L=0;O=0,AF0U3C03BX:S=0;M=0;L=0;O=0,AF0U3C03BW:S=0;M=0;L=0;O=0,AF0U3C04UX:S=0;M=0;L=0;O=0,AF0U3C03BU:S=0;M=0;L=0;O=0,AF0U3C04HT:S=0;M=0;L=0;O=0,AF0U3C04HS:S=0;M=0;L=0;O=0,AF0U3C04JZ:S=0;M=0;L=0;O=0,AF0U3C04HR:S=0;M=0;L=0;O=0,AF0U3C04HV:S=0;M=0;L=0;O=0,AF0U3C04HX:S=0;M=0;L=0;O=0,AF0U3C04HY:S=0;M=0;L=0;O=0,AF0U3C04JT:S=0;M=0;L=0;O=0,AF0U3C04HZ:S=0;M=0;L=0;O=0,AF0U3C04HN:S=0;M=0;L=0;O=0,AF0U3C04K8:S=0;M=0;L=0;O=0,AF0U3C04JN:S=0;M=0;L=0;O=0,AF0U3C04K7:S=0;M=0;L=0;O=0,AF0U3C04K5:S=0;M=0;L=0;O=0,AF0U3C04K2:S=0;M=0;L=0;O=0,AF0U3C04K3:S=0;M=0;L=0;O=0,AF0U3C04JV:S=0;M=0;L=0;O=0,AF0U3C04K0:S=0;M=0;L=0;O=0,AF0U3C04JY:S=0;M=0;L=0;O=0
AF0U3C04JU:S=0;M=0;L=0;O=0,AF0U3C04JX:S=0;M=0;L=0;O=0,AF0U3C04JQ:S=0;M=0;L=0;O=0,AF0U3C04JR:S=0;M=0;L=0;O=0
Y25ACRB6A:S=0;M=0;L=0;O=0,Y25ACRB6B:S=0;M=0;L=0;O=0,Y25ACRB6C:S=0;M=0;L=0;O=0,Y25ACRB6D:S=0;M=0;L=0;O=0
AF0U3C03BY:S=0;M=0;L=0;O=0
LV5ACLH9A:S=0;M=0;L=0;O=0,LV5ACLH9B:S=0;M=0;L=0;O=0,LV5ACLH9C:S=0;M=0;L=0;O=0
AL5HZC08X2:S=0;M=0;L=0;O=0,AL5HZC08X3:S=0;M=0;L=0;O=0,AL5HZC08VY:S=0;M=0;L=0;O=0,AL5HZC08X0:S=0;M=0;L=0;O=0,AL5HZC08X1:S=0;M=0;L=0;O=0,AL5HZC08WZ:S=0;M=0;L=0;O=0,AL5HZC08WY:S=0;M=0;L=0;O=0,AL5HZC08W2:S=0;M=0;L=0;O=0,AL5HZC08VZ:S=0;M=0;L=0;O=0
Q65ABLS34:S=0;M=0;L=0;O=0,LV5ACLH9E:S=0;M=0;L=0;O=0,LV5ACLH9F:S=0;M=0;L=0;O=0
LV5ACRE1A:S=0;M=0;L=0;O=0,LV5ACRE1B:S=0;M=0;L=0;O=0,LV5ACRE1C:S=0;M=0;L=0;O=0,LV5ACRE1D:S=0;M=0;L=0;O=0,LV5ACRE1E:S=0;M=0;L=0;O=0,LV5ACRE1F:S=0;M=0;L=0;O=0,LV5ACRE1G:S=0;M=0;L=0;O=0,LV5ACRE1H:S=0;M=0;L=0;O=0,LV5ACRE1J:S=0;M=0;L=0;O=0,LV5ACRE1K:S=0;M=0;L=0;O=0,LV5ACRE1L:S=0;M=0;L=0;O=0,LV5ACRE1M:S=0;M=0;L=0;O=0,LV5ACRE1N:S=0;M=0;L=0;O=0,LV5ACRE1P:S=0;M=0;L=0;O=0,LV5ACRE1Q:S=0;M=0;L=0;O=0,LV5ACRE1R:S=0;M=0;L=0;O=0,LV5ACRE1S:S=0;M=0;L=0;O=0,LV5ACRE1T:S=0;M=0;L=0;O=0,LV5ACRE1U:S=0;M=0;L=0;O=0,LV5ACRE1V:S=0;M=0;L=0;O=0,LV5ACRE1W:S=0;M=0;L=0;O=0,LV5ACRE1X:S=0;M=0;L=0;O=0,LV5ACRE1Y:S=0;M=0;L=0;O=0
AL5HZC094X:S=0;M=0;L=0;O=0,AL5HZC094U:S=0;M=0;L=0;O=0,AL5HZC094V:S=0;M=0;L=0;O=0,AL5HZC094S:S=0;M=0;L=0;O=0,AL5HZC094T:S=0;M=0;L=0;O=0,AL5HZC094Q:S=0;M=0;L=0;O=0,AL5HZC094R:S=0;M=0;L=0;O=0,AL5HZC094N:S=0;M=0;L=0;O=0,AL5HZC094K:S=0;M=0;L=0;O=0,AL5HZC094P:S=0;M=0;L=0;O=0,AL5HZC094L:S=0;M=0;L=0;O=0,AL5HZC095V:S=0;M=0;L=0;O=0,AL5HZC095S:S=0;M=0;L=0;O=0,AL5HZC095T:S=0;M=0;L=0;O=0,AL5HZC092H:S=0;M=0;L=0;O=0,AL5HZC08M0:S=0;M=0;L=0;O=0,AL5HZC095Q:S=0;M=0;L=0;O=0,AL5HZC092F:S=0;M=0;L=0;O=0,AL5HZC092E:S=0;M=0;L=0;O=0,AL5HZC092C:S=0;M=0;L=0;O=0,AL5HZC08WC:S=0;M=0;L=0;O=0
AF0U3C03RE:S=0;M=0;L=0;O=0,AF0U3C03FK:S=0;M=0;L=0;O=0,AF0U3C03FM:S=0;M=0;L=0;O=0,AF0U3C03FP:S=0;M=0;L=0;O=0,AF0U3C04LU:S=0;M=0;L=0;O=0,AF0U3C04KA:S=0;M=0;L=0;O=0,AF0U3C04LT:S=0;M=0;L=0;O=0,AF0U3C04LW:S=0;M=0;L=0;O=0,AF0U3C04LS:S=0;M=0;L=0;O=0,AF0U3C03TQ:S=0;M=0;L=0;O=0,AF0U3C03FF:S=0;M=0;L=0;O=0,AF0U3C03GD:S=0;M=0;L=0;O=0,AF0U3C04QL:S=0;M=0;L=0;O=0
AL5HZC08FH:S=0;M=0;L=0;O=0,AL5HZC08FF:S=0;M=0;L=0;O=0,AL5HZC08FG:S=0;M=0;L=0;O=0,AL5HZC08LV:S=0;M=0;L=0;O=0,AL5HZC08LU:S=0;M=0;L=0;O=0,AL5HZC08LT:S=0;M=0;L=0;O=0,AL5HZC08LS:S=0;M=0;L=0;O=0,AL5HZC08LR:S=0;M=0;L=0;O=0,AL5HZC08FX:S=0;M=0;L=0;O=0,AL5HZC08JT:S=0;M=0;L=0;O=0,AL5HZC08HB:S=0;M=0;L=0;O=0,AL5HZC08S1:S=0;M=0;L=0;O=0,AL5HZC08S4:S=0;M=0;L=0;O=0,AL5HZC08S6:S=0;M=0;L=0;O=0,AL5HZC093G:S=0;M=0;L=0;O=0,AL5HZC0933:S=0;M=0;L=0;O=0,AL5HZC0934:S=0;M=0;L=0;O=0,AL5HZC096C:S=0;M=0;L=0;O=0
AF6H6C05YA:S=0;M=0;L=0;O=0,AF6H6C05Y9:S=0;M=0;L=0;O=0,AF6H6C05VW:S=0;M=0;L=0;O=0,AF6H6C05Y8:S=0;M=0;L=0;O=0,AF6H6C05UM:S=0;M=0;L=0;O=0,AF6H6C05JW:S=0;M=0;L=0;O=0,AF6H6C06RT:S=0;M=0;L=0;O=0,AF6H6C06RW:S=0;M=0;L=0;O=0,AF6H6C06T9:S=0;M=0;L=0;O=0,AF6H6C06KK:S=0;M=0;L=0;O=0,AF6H6C06KF:S=0;M=0;L=0;O=0
AF0U3C03R5:S=0;M=0;L=0;O=0,AF0U3C03R4:S=0;M=0;L=0;O=0,AF0U3C03QY:S=0;M=0;L=0;O=0,AF0U3C03QZ:S=0;M=0;L=0;O=0
AF6H6C06NB:S=0;M=0;L=0;O=0,AF6H6C06N8:S=0;M=0;L=0;O=0,AF6H6C06QE:S=0;M=0;L=0;O=0,AF6H6C06SR:S=0;M=0;L=0;O=0,AF6H6C06P3:S=0;M=0;L=0;O=0,AF6H6C06QX:S=0;M=0;L=0;O=0,AF6H6C06KS:S=0;M=0;L=0;O=0,AF6H6C06QT:S=0;M=0;L=0;O=0
AF0UTC005J:S=0;M=0;L=0;O=0,AF0UTC005Y:S=0;M=0;L=0;O=0,AF0UTC005Z:S=0;M=0;L=0;O=0,AF0UTC00BB:S=0;M=0;L=0;O=0,AF0UTC00BG:S=0;M=0;L=0;O=0,AF0UTC008N:S=0;M=0;L=0;O=0,AF0UTC008R:S=0;M=0;L=0;O=0,AF0UTC00DJ:S=0;M=0;L=0;O=0,AF0UTC00DW:S=0;M=0;L=0;O=0,AF0UTC00DG:S=0;M=0;L=0;O=0,AF0UTC008E:S=0;M=0;L=0;O=0,AF0UTC001D:S=0;M=0;L=0;O=0,AF0UTC00DR:S=0;M=0;L=0;O=0,AF0UTC008S:S=0;M=0;L=0;O=0,AF0UTC00DM:S=0;M=0;L=0;O=0,AF0UTC0085:S=0;M=0;L=0;O=0
LV5ACLH9C:S=0;M=0;L=0;O=0,LV5ACLH9B:S=0;M=0;L=0;O=0,LV5ACLH9A:S=0;M=0;L=0;O=0
AF6H6C06G9:S=0;M=0;L=0;O=0
AF6H6C06G6:S=0;M=0;L=0;O=0,AF6H6C06G7:S=0;M=0;L=0;O=0,AF6H6C06G5:S=0;M=0;L=0;O=0
AF0UTC00LP:S=0;M=0;L=0;O=0
AF0UTC00LQ:S=0;M=0;L=0;O=0
AF6H6C06P0:S=0;M=0;L=0;O=0,AF6H6C06S9:S=0;M=0;L=0;O=0,AF6H6C06P1:S=0;M=0;L=0;O=0,AF6H6C06PJ:S=0;M=0;L=0;O=0,AF6H6C06LU:S=0;M=0;L=0;O=0,AF6H6C06N5:S=0;M=0;L=0;O=0,AF6H6C06MD:S=0;M=0;L=0;O=0,AF6H6C06N4:S=0;M=0;L=0;O=0,AF6H6C06UQ:S=0;M=0;L=0;O=0,AF6H6C06QV:S=0;M=0;L=0;O=0,AF6H6C06M1:S=0;M=0;L=0;O=0,AF6H6C06NF:S=0;M=0;L=0;O=0,AF6H6C06N1:S=0;M=0;L=0;O=0,AF6H6C06NE:S=0;M=0;L=0;O=0,AF6H6C06JV:S=0;M=0;L=0;O=0,AF6H6C06UR:S=0;M=0;L=0;O=0,AF6H6C06NA:S=0;M=0;L=0;O=0,AF6H6C06QW:S=0;M=0;L=0;O=0,AF6H6C06ND:S=0;M=0;L=0;O=0,AF6H6C06NC:S=0;M=0;L=0;O=0,AF6H6C06KQ:S=0;M=0;L=0;O=0,AF6H6C06US:S=0;M=0;L=0;O=0,AF6H6C06UP:S=0;M=0;L=0;O=0
AF0UTC00HS:S=0;M=0;L=0;O=0,AF0UTC00GR:S=0;M=0;L=0;O=0,AF0UTC00H3:S=0;M=0;L=0;O=0,AF0UTC00A2:S=0;M=0;L=0;O=0,AF0UTC00A7:S=0;M=0;L=0;O=0,AF0UTC00A6:S=0;M=0;L=0;O=0,AF0UTC00G3:S=0;M=0;L=0;O=0,AF0UTC00D3:S=0;M=0;L=0;O=0,AF0UTC00CZ:S=0;M=0;L=0;O=0,AF0UTC00GN:S=0;M=0;L=0;O=0,AF0UTC00J3:S=0;M=0;L=0;O=0,AF0UTC00GL:S=0;M=0;L=0;O=0,AF0UTC00GP:S=0;M=0;L=0;O=0,AF0UTC00GK:S=0;M=0;L=0;O=0
AF0UTC0057:S=0;M=0;L=0;O=0,AF0UTC0050:S=0;M=0;L=0;O=0,AF0UTC0056:S=0;M=0;L=0;O=0,AF0UTC0055:S=0;M=0;L=0;O=0,AF0UTC0001:S=0;M=0;L=0;O=0,AF0UTC002C:S=0;M=0;L=0;O=0,AF0UTC002B:S=0;M=0;L=0;O=0,AF0UTC000G:S=0;M=0;L=0;O=0,AF0UTC0023:S=0;M=0;L=0;O=0,AF0UTC000N:S=0;M=0;L=0;O=0,AF0UTC00N2:S=0;M=0;L=0;O=0,AF0UTC000V:S=0;M=0;L=0;O=0,AF0UTC002D:S=0;M=0;L=0;O=0,AF0UTC0027:S=0;M=0;L=0;O=0,AF0UTC0024:S=0;M=0;L=0;O=0,AF0UTC0025:S=0;M=0;L=0;O=0,AF0UTC000P:S=0;M=0;L=0;O=0,AF0UTC003Q:S=0;M=0;L=0;O=0,AF0UTC004X:S=0;M=0;L=0;O=0,AF0UTC004V:S=0;M=0;L=0;O=0,AF0UTC00AE:S=0;M=0;L=0;O=0,AF0UTC004Y:S=0;M=0;L=0;O=0,AF0UTC007S:S=0;M=0;L=0;O=0,AF0UTC007M:S=0;M=0;L=0;O=0,AF0UTC001K:S=0;M=0;L=0;O=0,AF0UTC00CJ:S=0;M=0;L=0;O=0,AF0UTC00GC:S=0;M=0;L=0;O=0,AF0UTC00EF:S=0;M=0;L=0;O=0
AF6H6C06SL:S=0;M=0;L=0;O=0,AF6H6C06V1:S=0;M=0;L=0;O=0,AF6H6C06SN:S=0;M=0;L=0;O=0,AF6H6C06SM:S=0;M=0;L=0;O=0,AF6H6C06PW:S=0;M=0;L=0;O=0,AF6H6C06PZ:S=0;M=0;L=0;O=0,AF6H6C06PY:S=0;M=0;L=0;O=0,AF6H6C06Q0:S=0;M=0;L=0;O=0,AF6H6C06LL:S=0;M=0;L=0;O=0,AF6H6C06Q2:S=0;M=0;L=0;O=0,AF6H6C06Q3:S=0;M=0;L=0;O=0,AF6H6C06NH:S=0;M=0;L=0;O=0,AF6H6C06NG:S=0;M=0;L=0;O=0,AF6H6C06NK:S=0;M=0;L=0;O=0,AF6H6C06NJ:S=0;M=0;L=0;O=0,AF6H6C06NM:S=0;M=0;L=0;O=0,AF6H6C06NL:S=0;M=0;L=0;O=0,AF6H6C06NP:S=0;M=0;L=0;O=0,AF6H6C06NN:S=0;M=0;L=0;O=0,AF6H6C06NR:S=0;M=0;L=0;O=0,AF6H6C06R0:S=0;M=0;L=0;O=0,AF6H6C06SF:S=0;M=0;L=0;O=0,AF6H6C06QQ:S=0;M=0;L=0;O=0,AF6H6C06JT:S=0;M=0;L=0;O=0,AF6H6C06S5:S=0;M=0;L=0;O=0,AF6H6C06S4:S=0;M=0;L=0;O=0,AF6H6C06QY:S=0;M=0;L=0;O=0,AF6H6C06LC:S=0;M=0;L=0;O=0,AF6H6C06M6:S=0;M=0;L=0;O=0,AF6H6C06M9:S=0;M=0;L=0;O=0,AF6H6C06M8:S=0;M=0;L=0;O=0,AF6H6C06MB:S=0;M=0;L=0;O=0,AF6H6C06RC:S=0;M=0;L=0;O=0,AF6H6C06RE:S=0;M=0;L=0;O=0,AF6H6C06RH:S=0;M=0;L=0;O=0,AF6H6C06RG:S=0;M=0;L=0;O=0,AF6H6C06RK:S=0;M=0;L=0;O=0,AF6H6C06RJ:S=0;M=0;L=0;O=0,AF6H6C06RM:S=0;M=0;L=0;O=0,AF6H6C06RL:S=0;M=0;L=0;O=0,AF6H6C06RP:S=0;M=0;L=0;O=0,AF6H6C06R8:S=0;M=0;L=0;O=0,AF6H6C06RN:S=0;M=0;L=0;O=0,AF6H6C06RQ:S=0;M=0;L=0;O=0,AF6H6C06RB:S=0;M=0;L=0;O=0,AF6H6C06UU:S=0;M=0;L=0;O=0
AG0UHC01RG:S=0;M=0;L=0;O=0
AF0UTC003T:S=0;M=0;L=0;O=0,AF0UTC0037:S=0;M=0;L=0;O=0,AF0UTC003L:S=0;M=0;L=0;O=0,AF0UTC00FG:S=0;M=0;L=0;O=0,AF0UTC00CB:S=0;M=0;L=0;O=0,AF0UTC00CA:S=0;M=0;L=0;O=0,AF0UTC00AT:S=0;M=0;L=0;O=0,AF0UTC00C4:S=0;M=0;L=0;O=0,AF0UTC00C9:S=0;M=0;L=0;O=0,AF0UTC00C3:S=0;M=0;L=0;O=0,AF0UTC00C0:S=0;M=0;L=0;O=0,AF0UTC00C1:S=0;M=0;L=0;O=0,AF0UTC001T:S=0;M=0;L=0;O=0,AF0UTC00BX:S=0;M=0;L=0;O=0,AF0UTC0010:S=0;M=0;L=0;O=0,AF0UTC00BZ:S=0;M=0;L=0;O=0,AF0UTC00E1:S=0;M=0;L=0;O=0
AG0UHC01LU:S=0;M=0;L=0;O=0,AG0UHC01RY:S=0;M=0;L=0;O=0,AG0UHC01S3:S=0;M=0;L=0;O=0,AG0UHC01MH:S=0;M=0;L=0;O=0,AG0UHC01MW:S=0;M=0;L=0;O=0,AG0UHC01YS:S=0;M=0;L=0;O=0,AG0UHC01UK:S=0;M=0;L=0;O=0,AG0UHC01MZ:S=0;M=0;L=0;O=0,AG0UHC01YU:S=0;M=0;L=0;O=0,AG0UHC01QQ:S=0;M=0;L=0;O=0,AG0UHC01NS:S=0;M=0;L=0;O=0,AG0UHC01M1:S=0;M=0;L=0;O=0,AG0UHC01UC:S=0;M=0;L=0;O=0,AG0UHC01LM:S=0;M=0;L=0;O=0,AG0UHC01Z3:S=0;M=0;L=0;O=0,AG0UHC01Z1:S=0;M=0;L=0;O=0,AG0UHC01Y3:S=0;M=0;L=0;O=0,AG0UHC01RA:S=0;M=0;L=0;O=0,AG0UHC01QV:S=0;M=0;L=0;O=0,AG0UHC01NQ:S=0;M=0;L=0;O=0,AG0UHC01YR:S=0;M=0;L=0;O=0,AG0UHC01P4:S=0;M=0;L=0;O=0
AF0UTC00DV:S=0;M=0;L=0;O=0,AF0UTC000Z:S=0;M=0;L=0;O=0,AF0UTC00E8:S=0;M=0;L=0;O=0,AF0UTC0069:S=0;M=0;L=0;O=0,AF0UTC00FN:S=0;M=0;L=0;O=0,AF0UTC0065:S=0;M=0;L=0;O=0,AF0UTC00E5:S=0;M=0;L=0;O=0,AF0UTC00EA:S=0;M=0;L=0;O=0,AF0UTC00EE:S=0;M=0;L=0;O=0,AF0UTC00DU:S=0;M=0;L=0;O=0,AF0UTC0084:S=0;M=0;L=0;O=0
UC5ABR59A:S=0;M=0;L=0;O=0,UC5ABR59B:S=0;M=0;L=0;O=0,UC5ABR59C:S=0;M=0;L=0;O=0,UC5ABR59D:S=0;M=0;L=0;O=0,UC5ABR59E:S=0;M=0;L=0;O=0,UC5ABR59F:S=0;M=0;L=0;O=0,UC5ABR59G:S=0;M=0;L=0;O=0,UC5ABR59H:S=0;M=0;L=0;O=0,UC5ABR59J:S=0;M=0;L=0;O=0,UC5ABR59K:S=0;M=0;L=0;O=0,UC5ABR59L:S=0;M=0;L=0;O=0,UC5ABR59M:S=0;M=0;L=0;O=0,UC5ABR59N:S=0;M=0;L=0;O=0,UC5ABR59P:S=0;M=0;L=0;O=0,UC5ABR59Q:S=0;M=0;L=0;O=0,UC5ABR59R:S=0;M=0;L=0;O=0,UC5ABR59S:S=0;M=0;L=0;O=0,UC5ABR59T:S=0;M=0;L=0;O=0,UC5ABR59U:S=0;M=0;L=0;O=0,UC5ABR59V:S=0;M=0;L=0;O=0,UC5ABR59W:S=0;M=0;L=0;O=0,UC5ABR59X:S=0;M=0;L=0;O=0,UC5ABR592:S=0;M=0;L=0;O=0,UC5ABR59Y:S=0;M=0;L=0;O=0,UC5ABR59Z:S=0;M=0;L=0;O=0,UC5ABR591:S=0;M=0;L=0;O=0,UC5ABR593:S=0;M=0;L=0;O=0,UC5ABR594:S=0;M=0;L=0;O=0,UC5ABWW3A:S=0;M=0;L=0;O=0,UC5ABWW3B:S=0;M=0;L=0;O=0,UC5ABWW3C:S=0;M=0;L=0;O=0,UC5ABWW3D:S=0;M=0;L=0;O=0,UC5ABWW3E:S=0;M=0;L=0;O=0,UC5ABWW3F:S=0;M=0;L=0;O=0,UC5ABWW3G:S=0;M=0;L=0;O=0,UC5ABWW3H:S=0;M=0;L=0;O=0,UC5ABWW3J:S=0;M=0;L=0;O=0,UC5ABWW3K:S=0;M=0;L=0;O=0,UC5ABWW3L:S=0;M=0;L=0;O=0,UC5ABWW3M:S=0;M=0;L=0;O=0,UC5ABWW3N:S=0;M=0;L=0;O=0,UC5ABWW3P:S=0;M=0;L=0;O=0,UC5ABWW3Q:S=0;M=0;L=0;O=0,UC5ABWW3R:S=0;M=0;L=0;O=0,UC5ABWW3S:S=0;M=0;L=0;O=0,UC5ABWW3T:S=0;M=0;L=0;O=0,UC5ABWW3U:S=0;M=0;L=0;O=0,UC5ABWW3V:S=0;M=0;L=0;O=0,UC5ABWW3W:S=0;M=0;L=0;O=0
AG0UHC01NP:S=0;M=0;L=0;O=0,AG0UHC01NH:S=0;M=0;L=0;O=0,AG0UHC01NM:S=0;M=0;L=0;O=0,AG0UHC01Z4:S=0;M=0;L=0;O=0,AG0UHC01SZ:S=0;M=0;L=0;O=0,AG0UHC01WY:S=0;M=0;L=0;O=0,AG0UHC01T1:S=0;M=0;L=0;O=0,AG0UHC01WC:S=0;M=0;L=0;O=0,AG0UHC01HZ:S=0;M=0;L=0;O=0,AG0UHC01WW:S=0;M=0;L=0;O=0,AG0UHC01X1:S=0;M=0;L=0;O=0,AG0UHC01WK:S=0;M=0;L=0;O=0,AG0UHC01WS:S=0;M=0;L=0;O=0,AG0UHC01WA:S=0;M=0;L=0;O=0,AG0UHC01WX:S=0;M=0;L=0;O=0
AF0UTC0081:S=0;M=0;L=0;O=0,AF0UTC0082:S=0;M=0;L=0;O=0,AF0UTC00MP:S=0;M=0;L=0;O=0,AF0UTC0083:S=0;M=0;L=0;O=0,AF0UTC00AL:S=0;M=0;L=0;O=0,AF0UTC008J:S=0;M=0;L=0;O=0,AF0UTC00L5:S=0;M=0;L=0;O=0,AF0UTC00MA:S=0;M=0;L=0;O=0,AF0UTC00LE:S=0;M=0;L=0;O=0,AF0UTC007C:S=0;M=0;L=0;O=0,AF0UTC0077:S=0;M=0;L=0;O=0,AF0UTC00MK:S=0;M=0;L=0;O=0,AF0UTC0078:S=0;M=0;L=0;O=0,AF0UTC0021:S=0;M=0;L=0;O=0,AF0UTC0036:S=0;M=0;L=0;O=0,AF0UTC0039:S=0;M=0;L=0;O=0,AF0UTC003A:S=0;M=0;L=0;O=0,AF0UTC001U:S=0;M=0;L=0;O=0,AF0UTC00DD:S=0;M=0;L=0;O=0,AF0UTC001P:S=0;M=0;L=0;O=0,AF0UTC00DF:S=0;M=0;L=0;O=0,AF0UTC0014:S=0;M=0;L=0;O=0,AF0UTC000L:S=0;M=0;L=0;O=0,AF0UTC00JZ:S=0;M=0;L=0;O=0,AF0UTC00K2:S=0;M=0;L=0;O=0,AF0UTC0064:S=0;M=0;L=0;O=0,AF0UTC0066:S=0;M=0;L=0;O=0,AF0UTC0068:S=0;M=0;L=0;O=0,AF0UTC007D:S=0;M=0;L=0;O=0,AF0UTC0029:S=0;M=0;L=0;O=0,AF0UTC00CU:S=0;M=0;L=0;O=0,AF0UTC00CT:S=0;M=0;L=0;O=0,AF0UTC00CL:S=0;M=0;L=0;O=0,AF0UTC00CS:S=0;M=0;L=0;O=0,AF0UTC0061:S=0;M=0;L=0;O=0,AF0UTC00C7:S=0;M=0;L=0;O=0,AF0UTC00B6:S=0;M=0;L=0;O=0,AF0UTC001R:S=0;M=0;L=0;O=0,AF0UTC0020:S=0;M=0;L=0;O=0,AF0UTC001Q:S=0;M=0;L=0;O=0,AF0UTC0038:S=0;M=0;L=0;O=0,AF0UTC0033:S=0;M=0;L=0;O=0,AF0UTC00F7:S=0;M=0;L=0;O=0,AF0UTC00F1:S=0;M=0;L=0;O=0,AF0UTC006X:S=0;M=0;L=0;O=0,AF0UTC0016:S=0;M=0;L=0;O=0,AF0UTC00DQ:S=0;M=0;L=0;O=0,AF0UTC00FJ:S=0;M=0;L=0;O=0,AF0UTC00FM:S=0;M=0;L=0;O=0,AF0UTC00E7:S=0;M=0;L=0;O=0,AF0UTC00EK:S=0;M=0;L=0;O=0,AF0UTC00GX:S=0;M=0;L=0;O=0
UC5ABWW3X:S=0;M=0;L=0;O=0,UC5ABWW3Y:S=0;M=0;L=0;O=0,UC5ABWW3Z:S=0;M=0;L=0;O=0,UC5ABWW31:S=0;M=0;L=0;O=0,UC5ABWW32:S=0;M=0;L=0;O=0,UC5ABWW33:S=0;M=0;L=0;O=0,UC5ABWW34:S=0;M=0;L=0;O=0
AG0UHC01SR:S=0;M=0;L=0;O=0,AG0UHC01JS:S=0;M=0;L=0;O=0,AG0UHC01KE:S=0;M=0;L=0;O=0,AG0UHC01HR:S=0;M=0;L=0;O=0,AG0UHC01HP:S=0;M=0;L=0;O=0,AG0UHC01JZ:S=0;M=0;L=0;O=0,AG0UHC01JT:S=0;M=0;L=0;O=0,AG0UHC01SC:S=0;M=0;L=0;O=0,AG0UHC01WM:S=0;M=0;L=0;O=0,AG0UHC01WE:S=0;M=0;L=0;O=0,AG0UHC01WH:S=0;M=0;L=0;O=0,AG0UHC01KA:S=0;M=0;L=0;O=0,AG0UHC01MU:S=0;M=0;L=0;O=0,AG0UHC01MY:S=0;M=0;L=0;O=0,AG0UHC01KD:S=0;M=0;L=0;O=0,AG0UHC01QM:S=0;M=0;L=0;O=0,AG0UHC01NN:S=0;M=0;L=0;O=0
AF0UTC00GY:S=0;M=0;L=0;O=0,AF0UTC00HA:S=0;M=0;L=0;O=0,AF0UTC00GZ:S=0;M=0;L=0;O=0,AF0UTC00H0:S=0;M=0;L=0;O=0,AF0UTC00F9:S=0;M=0;L=0;O=0,AF0UTC00FC:S=0;M=0;L=0;O=0,AF0UTC00ME:S=0;M=0;L=0;O=0,AF0UTC00DS:S=0;M=0;L=0;O=0,AF0UTC00M1:S=0;M=0;L=0;O=0,AF0UTC000Y:S=0;M=0;L=0;O=0,AF0UTC007B:S=0;M=0;L=0;O=0,AF0UTC00K8:S=0;M=0;L=0;O=0,AF0UTC000S:S=0;M=0;L=0;O=0,AF0UTC00KZ:S=0;M=0;L=0;O=0,AF0UTC00D7:S=0;M=0;L=0;O=0,AF0UTC00KW:S=0;M=0;L=0;O=0,AF0UTC00D0:S=0;M=0;L=0;O=0,AF0UTC00BM:S=0;M=0;L=0;O=0,AF0UTC001Y:S=0;M=0;L=0;O=0,AF0UTC00F2:S=0;M=0;L=0;O=0,AF0UTC001E:S=0;M=0;L=0;O=0,AF0UTC003S:S=0;M=0;L=0;O=0
AG0UHC01LT:S=0;M=0;L=0;O=0,AG0UHC01LR:S=0;M=0;L=0;O=0,AG0UHC01LP:S=0;M=0;L=0;O=0,AG0UHC01LQ:S=0;M=0;L=0;O=0,AG0UHC01M5:S=0;M=0;L=0;O=0,AG0UHC01K7:S=0;M=0;L=0;O=0,AG0UHC01K5:S=0;M=0;L=0;O=0,AG0UHC01K2:S=0;M=0;L=0;O=0,AG0UHC01KQ:S=0;M=0;L=0;O=0,AG0UHC01NT:S=0;M=0;L=0;O=0,AG0UHC01QH:S=0;M=0;L=0;O=0,AG0UHC01H9:S=0;M=0;L=0;O=0,AG0UHC01KM:S=0;M=0;L=0;O=0
AF0UTC00KQ:S=0;M=0;L=0;O=0,AF0UTC00J8:S=0;M=0;L=0;O=0,AF0UTC00JV:S=0;M=0;L=0;O=0,AF0UTC00EY:S=0;M=0;L=0;O=0,AF0UTC00GE:S=0;M=0;L=0;O=0,AF0UTC00BJ:S=0;M=0;L=0;O=0,AF0UTC00EN:S=0;M=0;L=0;O=0,AF0UTC0060:S=0;M=0;L=0;O=0,AF0UTC008K:S=0;M=0;L=0;O=0,AF0UTC005U:S=0;M=0;L=0;O=0,AF0UTC005T:S=0;M=0;L=0;O=0,AF0UTC005D:S=0;M=0;L=0;O=0,AF0UTC005V:S=0;M=0;L=0;O=0,AF0UTC005W:S=0;M=0;L=0;O=0,AF0UTC005G:S=0;M=0;L=0;O=0,AF0UTC00BE:S=0;M=0;L=0;O=0
UC5ABWV8A:S=0;M=0;L=0;O=0,UC5ABWV8B:S=0;M=0;L=0;O=0,UC5ABWV8C:S=0;M=0;L=0;O=0,UC5ABWV8D:S=0;M=0;L=0;O=0,UC5ABWV8E:S=0;M=0;L=0;O=0,UC5ABWV8F:S=0;M=0;L=0;O=0,UC5ABWV8G:S=0;M=0;L=0;O=0
AG0UHC01US:S=0;M=0;L=0;O=0,AG0UHC01UP:S=0;M=0;L=0;O=0,AG0UHC01UM:S=0;M=0;L=0;O=0,AG0UHC01W8:S=0;M=0;L=0;O=0,AG0UHC01UQ:S=0;M=0;L=0;O=0
UC5ABWV8M:S=0;M=0;L=0;O=0
AG0UHC01J9:S=0;M=0;L=0;O=0,AG0UHC01JA:S=0;M=0;L=0;O=0,AG0UHC01JD:S=0;M=0;L=0;O=0,AG0UHC01TZ:S=0;M=0;L=0;O=0,AG0UHC01YD:S=0;M=0;L=0;O=0,AG0UHC01YC:S=0;M=0;L=0;O=0,AG0UHC01Y7:S=0;M=0;L=0;O=0,AG0UHC01Z8:S=0;M=0;L=0;O=0,AG0UHC01Y6:S=0;M=0;L=0;O=0,AG0UHC01Y4:S=0;M=0;L=0;O=0,AG0UHC01Y2:S=0;M=0;L=0;O=0,AG0UHC01QK:S=0;M=0;L=0;O=0,AG0UHC01NR:S=0;M=0;L=0;O=0,AG0UHC01VY:S=0;M=0;L=0;O=0,AG0UHC01W4:S=0;M=0;L=0;O=0,AG0UHC01W9:S=0;M=0;L=0;O=0,AG0UHC01W3:S=0;M=0;L=0;O=0,AG0UHC01VW:S=0;M=0;L=0;O=0,AG0UHC01W1:S=0;M=0;L=0;O=0,AG0UHC01W0:S=0;M=0;L=0;O=0,AG0UHC01VU:S=0;M=0;L=0;O=0,AG0UHC01VZ:S=0;M=0;L=0;O=0,AG0UHC01JJ:S=0;M=0;L=0;O=0,AG0UHC01W5:S=0;M=0;L=0;O=0,AG0UHC01VX:S=0;M=0;L=0;O=0,AG0UHC01VS:S=0;M=0;L=0;O=0,AG0UHC01SN:S=0;M=0;L=0;O=0,AG0UHC01VP:S=0;M=0;L=0;O=0,AG0UHC01PF:S=0;M=0;L=0;O=0,AG0UHC01LK:S=0;M=0;L=0;O=0,AG0UHC01LL:S=0;M=0;L=0;O=0,AG0UHC01LH:S=0;M=0;L=0;O=0,AG0UHC01LJ:S=0;M=0;L=0;O=0,AG0UHC01ZF:S=0;M=0;L=0;O=0,AG0UHC01N6:S=0;M=0;L=0;O=0,AG0UHC01T8:S=0;M=0;L=0;O=0,AG0UHC01TM:S=0;M=0;L=0;O=0,AG0UHC01TC:S=0;M=0;L=0;O=0,AG0UHC01ST:S=0;M=0;L=0;O=0,AG0UHC01TJ:S=0;M=0;L=0;O=0,AG0UHC01TE:S=0;M=0;L=0;O=0

2026-01-05 14:46:58,052 - INFO - [save_table] l6a01_project.inspection_api_summary_202601 已寫入 683 列（去除 0 重複）

In [22]:
type(tb['pi_hour'][1388])

str

In [13]:
tb = data_dict['aoi100_pidensity_202512_pi700']
tb['defect_seq' ].unique()
#
tb[tb['defect_seq' ] == '57'].iloc[0,:].to_dict()

{'scan_time': Timestamp('2025-12-17 07:32:46'),
 'line_id': 'CAPIC700',
 'model': 'M270QAN06',
 'glass_type': 'CF',
 'recipe_id': '605',
 'glass_id': 'AR0QZC0CQM',
 'pic_name': 'CaptureImage/CAPIT203_AR0QZC0CQM_57_49_2512170732.JPG',
 'x': '168460',
 'y': '74715',
 'predict_code': '!',
 'judge_code': '!',
 'mark': '',
 'hour': '',
 'dayhour': '',
 'day': Timestamp('2025-12-17 07:32:46'),
 'year': '',
 'month': '',
 'season': '',
 'week': '',
 'yearmonth': '',
 'defect_count': '139',
 'defect_size': '205',
 'open_status': '',
 'ai_code_1': 'OP_Defect',
 'ai_code_2': '2025-12-17 01:06:31',
 'ai_code_3': '',
 'ai_code_4': '',
 'ai_code_5': '',
 'gray_name': 'CCDImage\\IP01\\0013',
 'ip_num': '',
 'first_code': '',
 'chip_name': 'AR0QZC0CQME',
 'defect_seq': '57',
 'pi_time': '2025-12-17 02:01:11',
 'pi_hour': '2025-12-17 02',
 'pic_path': 'http://10.97.139.98:1454//CAPIT203/CA0327/AR0QZC0CQM/CAPIC700/20251217073246/',
 'recipe_comment': ''}

In [15]:
tb.columns

Index(['pi_hour', 'line_id', 'model', 'glass_type', 'maingroup_glass_count',
       'maingroup_defect_count', 'defect_code_glass_count',
       'small_defect_count', 'middle_defect_count', 'large_defect_count',
       'over_defect_count', 'glass', 'comment', 'glass_size_detail', 'Editor',
       'modify_time'],
      dtype='object')

In [7]:
size_types = ['S','M','L','O','SM','SL','SO','ML','MO','LO','SML','SMO','SLO','MLO','SMLO']
len(size_types)

15

In [6]:
tbn= 'aoi_density_spec_for_aoimonitor'
tb = dbhandler.get_table(tbn)
tb.head()

,MODEL_ID,MODEL_TYPE,DEFECT_CODE,PROCESS_TYPE,SIZE_TYPE,OOC,OOS,Editor,modify_time,drop
0,B070AAN01,Normal,PI_Spot_NP,BIG,OL,0.33,0.57,預設,2025-12-09 08:00:00,F
1,B070AAN01,Normal,PI_Spot_NP,BIG,OLMS,300,300,預設,2025-12-09 08:00:00,F
2,B070AAN01,Normal,PIS With Particle,BIG,OL,0.28,0.33,預設,2025-12-24 15:56:23,F
3,B070AAN01,Normal,PIS With Particle,BIG,OLMS,2,3,預設,2025-12-09 08:00:00,F
4,B070AAN01,Normal,Polymer,BIG,OLMS,5,10,預設,2025-12-09 08:00:00,F

In [14]:
size_types = ['S','M','L','O','SM','SL','SO','ML','MO','SML','SMO','SLO','MLO']
tb = dbhandler.get_table(tbn)
print(len(tb))
df = pd.DataFrame()
tb['line_id'] = ''
tb['SIZE_TYPE'] = ''
for line in [f'CAPIC{i}00' for i in range(1,8,1)]:
    #for size in size_types:
        #print(line, size)
    new = tb.copy()
    new['line_id'] = line
    #new['SIZE_TYPE'] = size
    df = pd.concat([df, new])

print(len(df))
df.head()

1063
7441

,MODEL_ID,MODEL_TYPE,DEFECT_CODE,PROCESS_TYPE,SIZE_TYPE,OOC,OOS,Editor,modify_time,drop,line_id
0,B070AAN01,Normal,PI_Spot_NP,BIG,,0.33,0.57,預設,2025-12-09 08:00:00,F,CAPIC100
1,B070AAN01,Normal,PI_Spot_NP,BIG,,300,300,預設,2025-12-09 08:00:00,F,CAPIC100
2,B070AAN01,Normal,PIS With Particle,BIG,,0.28,0.33,預設,2025-12-24 15:56:23,F,CAPIC100
3,B070AAN01,Normal,PIS With Particle,BIG,,2,3,預設,2025-12-09 08:00:00,F,CAPIC100
4,B070AAN01,Normal,Polymer,BIG,,5,10,預設,2025-12-09 08:00:00,F,CAPIC100

In [13]:
len(tb)*len(range(1,8,1))*len(size_types)

96733

In [3]:
tbn= 'aoi_inspection_default_spectable'
tb = dbhandler.get_table(tbn)
tb.head()

,pi,model,glass_type,line_id,OOC,OOS,Editor,modify_time,drop
0,PI100,A101EAN01,TFT,CAPIC107,0.5,0.8,預設,2025-12-24 09:00:00,F
1,PI100,B070AAN01,TFT,CAPIC107,0.5,0.8,預設,2025-12-24 09:00:00,F
2,PI100,B070AAN1Y,TFT,CAPIC107,0.5,0.8,預設,2025-12-24 09:00:00,F
3,PI100,B080EAN05,TFT,CAPIC107,0.5,0.8,預設,2025-12-24 09:00:00,F
4,PI100,B101EAN02,TFT,CAPIC107,0.5,0.8,預設,2025-12-24 09:00:00,F

In [5]:
tb[tb['glass_type'] != 'TFT']

Empty DataFrame
Columns: [pi, model, glass_type, line_id, OOC, OOS, Editor, modify_time, drop]
Index: []

In [ ]:

#for cl, val in (['Editor', 'modify_time', 'drop'],['', '2025-12-24 09:00:00', 'F']):
#    tb[cl] = val
#tb['size_type'] = ''
"""
df = pd.DataFrame()
for size in size_types:
    new_df = tb.copy()
    new_df['size_type'] = size
    df = pd.concat([df, new_df])
"""
for cl, val in zip(['Editor', 'modify_time', 'drop'],['預設', '2025-12-24 09:00:00', 'F']):
    tb[cl] = val
#dbhandler.save_table(tbn, tb)
tb.head()

2025-12-24 13:26:48,827 - INFO - [save_table] l6a01_project.aoi_inspection_default_spectable 已寫入 720 列（去除 0 重複）

,pi,model,glass_type,line_id,OOC,OOS,Editor,modify_time,drop
0,PI100,A101EAN01,TFT,CAPIC107,0.5,0.8,預設,2025-12-24 09:00:00,F
1,PI100,B070AAN01,TFT,CAPIC107,0.5,0.8,預設,2025-12-24 09:00:00,F
2,PI100,B070AAN1Y,TFT,CAPIC107,0.5,0.8,預設,2025-12-24 09:00:00,F
3,PI100,B080EAN05,TFT,CAPIC107,0.5,0.8,預設,2025-12-24 09:00:00,F
4,PI100,B101EAN02,TFT,CAPIC107,0.5,0.8,預設,2025-12-24 09:00:00,F

In [4]:
tbn = 'inspection_summary_table_202511'
tbn = 'aoi_inspection_default_spectable'
tbn = 'aoi_spec_for_aoimonitor'
tbn = 'aoi100_rawdata_202512'
df = dbhandler.get_table(tbn)
print(len(df))
#df['day'] = df['SCAN_ENDTIME'].apply(lambda x: str(x).split(" ")[0])
df.head()

308061

,scantime,line_id,model,glass_type,recipe_id,glass_id,pic_name,x,y,predict_code,...,ip_num,first_code,chip_name,defect_seq,image_path,over_defect_count,large_defect_count,middle_defect_count,small_defect_count,indexid
0,2025-12-01 09:40:00,CAPIT203,M215HAN01-C-A7UM,M215HAN01-C-A7UM,117,AL5HZB0KVW,CaptureImage/CAPIT203_AL5HZB0KVW_2_354_2512010...,1776165,298476,!,...,,,AL5HZB0KVWA,1,/CAPIT203/CA0320/AL5HZB0KVW/A/20251201094000/,0,0,50,431,57437b8082374029b593ba1a8a520ade
1,2025-12-01 09:40:00,CAPIT203,M215HAN01-C-A7UM,M215HAN01-C-A7UM,117,AL5HZB0KVW,CaptureImage/CAPIT203_AL5HZB0KVW_13_97_2512010...,1646879,278510,!,...,,,AL5HZB0KVWA,10,/CAPIT203/CA0320/AL5HZB0KVW/A/20251201094000/,0,0,50,431,fc013c22f5ee4a9994a4d9e4116577aa
2,2025-12-01 09:40:00,CAPIT203,M215HAN01-C-A7UM,M215HAN01-C-A7UM,117,AL5HZB0KVW,CaptureImage/CAPIT203_AL5HZB0KVW_22_218_251201...,1637966,67039,!,...,,,AL5HZB0KVWA,100,/CAPIT203/CA0320/AL5HZB0KVW/A/20251201094000/,0,0,50,431,133777b099f941b4a44f8b7f11b36082
3,2025-12-01 09:40:00,CAPIT203,M215HAN01-C-A7UM,M215HAN01-C-A7UM,117,AL5HZB0KVW,CaptureImage/CAPIT203_AL5HZB0KVW_21_242_251201...,1787829,25605,!,...,,,AL5HZB0KVWA,101,/CAPIT203/CA0320/AL5HZB0KVW/A/20251201094000/,0,0,50,431,ac3a69dabf954a3ca8c473b3c71d00e8
4,2025-12-01 09:40:00,CAPIT203,M215HAN01-C-A7UM,M215HAN01-C-A7UM,117,AL5HZB0KVW,CaptureImage/CAPIT203_AL5HZB0KVW_73_350_251201...,1778433,279178,!,...,,,AL5HZB0KVWA,102,/CAPIT203/CA0320/AL5HZB0KVW/A/20251201094000/,0,0,50,431,9b016ac24ac84a08a19698ff71199d93

In [7]:
df['model'].unique()

array(['M215HAN01-C-A7UM', 'B140UAN08-C-A7UM', 'M270DANA0-C-A7UM',
       'B160UAN04-T-A7UM', 'M270QAN07-C-A7UM', 'M270QAN07-T-A7UM',
       'B116XAN06-C-A7UM', 'B140UAN04-C-A7UM', 'M270QAN06-C-A7UM',
       'G215HVN01-C-A7UM'], dtype=object)

In [6]:
df[df['model'].str.contains('M215HAN01-')]['model'].unique()

array(['M215HAN01-C-A7UM'], dtype=object)

In [3]:
5201-4514

687

In [17]:
import pandas as pd

def build_pi_trend_tables(df_hour: pd.DataFrame):
    """
    df_hour 欄位需求：
    - 'pi_hour' (str or datetime): 'YYYY-MM-DD HH'
    - 'line_id', 'model', 'glass_type'
    - 'maingroup_glass_count'
    - 'maingroup_defect_count'
    - 'defect_code_glass_count'
    - 'small_defect_count', 'middle_defect_count',
      'large_defect_count', 'over_defect_count'
    """

    df = df_hour.copy()

    # 1) 時間欄位處理
    # -------------------------------------------------
    # 若 pi_hour 還是字串，先轉成 datetime (到小時)
    if not pd.api.types.is_datetime64_any_dtype(df['pi_hour']):
        df['pi_hour'] = pd.to_datetime(df['pi_hour'], format='%Y-%m-%d %H')

    # 日 key
    df['pi_date'] = df['pi_hour'].dt.date  # date 物件

    # 月 key（取該月第一天 00:00）
    df['month'] = df['pi_hour'].dt.to_period('M').dt.to_timestamp()

    # 週 key（你可以改成 W-SAT / W-SUN，看你週別定義）
    # 這裡先用 ISO week，另建 label 給前端用
    iso = df['pi_hour'].dt.isocalendar()
    df['week_year']  = iso['year']
    df['week_num']   = iso['week']
    # 週開始日，用「該週的星期一」當 key
    df['week_start'] = df['pi_hour'] - pd.to_timedelta(df['pi_hour'].dt.weekday, unit='D')
    df['week_start'] = df['week_start'].dt.normalize()
    # 週顯示用 label：2025-W48
    df['week_label'] = df['week_year'].astype(str) + '-W' + df['week_num'].astype(str).str.zfill(2)

    # 2) 聚合欄位列表
    # -------------------------------------------------
    agg_cols = [
        'maingroup_glass_count',
        'maingroup_defect_count',
        'defect_code_glass_count',
        'small_defect_count',
        'middle_defect_count',
        'large_defect_count',
        'over_defect_count',
    ]

    agg_dict = {c: 'sum' for c in agg_cols}

    # 3) 建日表 pi_day
    # -------------------------------------------------
    day_keys = ['pi_date', 'line_id', 'model', 'glass_type']
    g_day = df.groupby(day_keys, as_index=False).agg(agg_dict)

    # 算 density
    g_day['density_all']    = g_day['maingroup_defect_count'] / g_day['maingroup_glass_count']
    g_day['density_small']  = g_day['small_defect_count']    / g_day['maingroup_glass_count']
    g_day['density_middle'] = g_day['middle_defect_count']   / g_day['maingroup_glass_count']
    g_day['density_large']  = g_day['large_defect_count']    / g_day['maingroup_glass_count']
    g_day['density_over']   = g_day['over_defect_count']     / g_day['maingroup_glass_count']

    # 4) 建週表 pi_week
    # -------------------------------------------------
    week_keys = ['week_start', 'week_label', 'line_id', 'model', 'glass_type']
    g_week = df.groupby(week_keys, as_index=False).agg(agg_dict)

    g_week['density_all']    = g_week['maingroup_defect_count'] / g_week['maingroup_glass_count']
    g_week['density_small']  = g_week['small_defect_count']    / g_week['maingroup_glass_count']
    g_week['density_middle'] = g_week['middle_defect_count']   / g_week['maingroup_glass_count']
    g_week['density_large']  = g_week['large_defect_count']    / g_week['maingroup_glass_count']
    g_week['density_over']   = g_week['over_defect_count']     / g_week['maingroup_glass_count']

    # 5) 建月表 pi_month
    # -------------------------------------------------
    month_keys = ['month', 'line_id', 'model', 'glass_type']
    g_month = df.groupby(month_keys, as_index=False).agg(agg_dict)

    g_month['density_all']    = g_month['maingroup_defect_count'] / g_month['maingroup_glass_count']
    g_month['density_small']  = g_month['small_defect_count']    / g_month['maingroup_glass_count']
    g_month['density_middle'] = g_month['middle_defect_count']   / g_month['maingroup_glass_count']
    g_month['density_large']  = g_month['large_defect_count']    / g_month['maingroup_glass_count']
    g_month['density_over']   = g_month['over_defect_count']     / g_month['maingroup_glass_count']

    return {
        'pi_day': g_day,
        'pi_week': g_week,
        'pi_month': g_month,
    }




trend_tables = build_pi_trend_tables(all_data)

df_day   = trend_tables['pi_day']
df_week  = trend_tables['pi_week']
df_month = trend_tables['pi_month']

In [ ]:
"""
前端回傳格式改正如下:
{
    'day':{ 'date':['starDate', 'endDate'], #e.g. ['2025-11-17', '2025-12-11']
            'line_id': [],
            'model': [],
            'glass_type': ['TFT', 'CF'],
            'defect_size':['S', 'M', 'L', 'O']
        },
    'week':{
            'date':['starWeek', 'endWeek'], #e.g. ['W40', 'W49']
            'line_id': ['CAPIC207'],
            'model': [],
            'glass_type': ['TFT'],
            'defect_size':['L', 'O']
        },
    'month':{
            'date':['starMon', 'endMon'],  #e.g.[202503, 202512]
            'line_id': ['CAPIC107', 'CAPIC407', 'CAPIC607', 'CAPIC707'],
            'model': ['B160UAN03', 'M270DAN08'],
            'glass_type': [],
            'defect_size':['S', 'O']
        }
}

後端撈取資料庫資料表名稱格式'inspection_api_summary_' + yyyymm , e.g. inspection_api_summary_202511
根據要求時間'date'撈取時間符合的資料及每個篩選器對應的資料欄位的特定值(或全選)
初始觸發前端會傳遞
{
    'day':{},
    'week':{},
    'month':{}
}
則預設取7天,7週及7個月的資料


"""

,month,line_id,model,glass_type,maingroup_glass_count,maingroup_defect_count,defect_code_glass_count,small_defect_count,middle_defect_count,large_defect_count,over_defect_count,density_all,density_small,density_middle,density_large,density_over
0,2025-11-01,CAPIC107,B160UAN03,CF,418,150,106,97,23,17,13,0.358852,0.232057,0.055024,0.040670,0.031100
1,2025-11-01,CAPIC107,B160UAN03,TFT,406,405,221,119,160,86,40,0.997537,0.293103,0.394089,0.211823,0.098522
2,2025-11-01,CAPIC107,B160UAN04,CF,4899,773,620,592,72,57,52,0.157787,0.120841,0.014697,0.011635,0.010614
3,2025-11-01,CAPIC107,B160UAN04,TFT,5245,1533,1242,1240,146,80,67,0.292278,0.236416,0.027836,0.015253,0.012774
4,2025-11-01,CAPIC107,B160UAN4H,CF,370,107,40,50,12,21,24,0.289189,0.135135,0.032432,0.056757,0.064865
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,2025-12-01,CAPIC607,B153UAN02,TFT,151,96,75,65,9,16,6,0.635762,0.430464,0.059603,0.105960,0.039735
137,2025-12-01,CAPIC607,B160UAN04,CF,2103,411,291,229,66,17,99,0.195435,0.108892,0.031384,0.008084,0.047076
138,2025-12-01,CAPIC607,B160UAN04,TFT,1991,251,192,113,35,23,80,0.126067,0.056755,0.017579,0.011552,0.040181
139,2025-12-01,CAPIC607,M270DAN08,CF,687,141,109,44,24,29,44,0.205240,0.064047,0.034934,0.042213,0.064047
140,2025-12-01,CAPIC607,M270DAN08,TFT,630,50,35,15,11,3,21,0.079365,0.023810,0.017460,0.004762,0.033333

In [16]:
all_data = pd.DataFrame()
for tbn in [v for v in tbns if 'inspection_api_summary' in v ]:
    tb = dbhandler.get_table(tbn)
    print(tbn, len(tb))
    print(tb.iloc[-1,:].to_dict())
    all_data = pd.concat([all_data, tb])
    """
    if 'comment' not in tb.columns:
        tb['comment'] = ''
    if 'noteText' in tb.columns:
        tb = tb[['pi_hour', 'line_id', 'model', 'glass_type', 'maingroup_glass_count', 'maingroup_defect_count', 'defect_code_glass_count', 'small_defect_count', 'middle_defect_count', 'large_defect_count', 'over_defect_count', 'glass', 'comment']]
        #dbhandler.save_df(tb, tbn)
    """

inspection_api_summary_202511 2076
{'pi_hour': '2025-11-30 23', 'line_id': 'CAPIC207', 'model': 'M270DANA0', 'glass_type': 'TFT', 'maingroup_glass_count': 62, 'maingroup_defect_count': 84, 'defect_code_glass_count': 40, 'small_defect_count': 34, 'middle_defect_count': 25, 'large_defect_count': 13, 'over_defect_count': 12, 'glass': 'VN5AAVV3P,VN5AAVV3Q,VN5AAVV3R,VN5AAVV3F,VN5AAVV3G,VN5AAVV3L,VN5AAVV3K,VN5AAVV3J,VN5AAVV3H,VN5AAVV3S,VN5AAVV3T,VN5AAVV3N,VN5AAVV3M,VN5AAVV3U,VN5AAVV3V,VN5A9U80A,VN5A9U80B,VN5AAVV31,VN5AAVV32,VN5A9U80C,VN5A9U80D,VN5AAVV3W,VN5AAVV3X,VN5AAVV3Y,VN5AAVV3Z,VN5AAVV33,VN5AAVV34,VN5A9U80E,VN5A9U80F,VN5A9U80G,VN5A9U80H,VN5A9U80J,VN5A9U80K,VN5A9U80L,VN5A9U80M,VN5A9U80N,VN5A9U80P,VN5A9U80Q,VN5A9U80R,VN5A9U801,VN5A9U802,VN5A9U80S,VN5A9U80T,VN5A9U80U,VN5A9U803,VN5A9U80V,VN5A9U80W,VN5A9U80X,VN5A9U80Y,VN5A9U80Z,VN5A9U804,VN5AAVV7A,VN5AAVV7B,VN5AAVV7C,VN5AAVV7D,VN5AAVV7E,VN5AAVV7F,VN5AAVV7G,VN5AAVV7H,VN5AAVV7J,VN5AAVV7K,VN5AAVV7L', 'comment': ''}
inspection_api_summary_202512 1499
{'pi_hour': '2025-12-11 09', 'line_id': 'CAPIC507', 'model': 'M270DAN7F', 'glass_type': 'CF', 'maingroup_glass_count': 23, 'maingroup_defect_count': 190, 'defect_code_glass_count': 22, 'small_defect_count': 51, 'middle_defect_count': 46, 'large_defect_count': 60, 'over_defect_count': 33, 'glass': 'AR0DFC01VT,AR0DFC02UW,AR0DFC01YN,AR0DFC01YQ,AR0DFC022Y,AR0DFC02E7,AR0DFC02UG,AR0DFC01YB,AR0DFB04WW,AR0DFB053E,AR0DFC01YK,AR0DFB04XF,AR0DFB04XK,AR0DFB04XJ,AR0DFC01VQ,AR0DFB04XA,AR0DFB04XL,AR0DFB04XN,AR0DFB04XQ,AR0DFC01YG,AR0DFB050Y,AR0DFB050W,AR0DFC01VS', 'comment': ''}

In [ ]:
for tbn, tb in all_data.items():
    tb['pi_day']

2025-12-11 08:22:33,020 - INFO - [list_tables] 成功取得資料表名稱，共 130 張表。

['aoi_inspection_default_spectable',
 'inspection_api_summary_202511',
 'inspection_api_summary_202512',
 'inspection_raw_table_202511',
 'inspection_raw_table_202512',
 'inspection_summary_table_202511',
 'inspection_summary_table_202512']

In [3]:
class Config:
    def __init__(self):
        # ================================================= datetime =================================================
        now = datetime.now()
        ym = now.strftime("%Y%m")
        print(f"連線時間: {now}({ym})")
        #one_mon_ago = now - timedelta(days=30)
        # ================================================= 資料設定  =================================================
        # === PI Line ====
        self.uni_pi_names = [f'CAPIC{i}07' for i in range(1,8,1)]

        # ==== defect size config  ===
        self.uni_defect_sizes = ['S', 'M', 'L', 'O']
        self.defect_size_col = 'DEFECT_SIZE_TYPE'
        self.size_group_keys = ['S','M','L','O','SM','SL','SO','ML','MO','LO','SML','SMO','SLO','MLO','SMLO']
        self.table_size_cols =['small_defect_count', 'middle_defect_count', 'large_defect_count', 'over_defect_count']
        # === Glass side  ===
        self.glass_sides = ['CF', 'TFT']
        # ==================================== MySQL AOI Inspection datamall 資料表設定 ==========================================
        self.summary_table_name = f'inspection_summary_table_{ym}'
        self.raw_table_name = f'inspection_raw_table_{ym}'

        self.summary_sql_cols = ['CHIP_COUNT', 'CHIP_JUDGE', 'CHIP_OK_COUNT', 'DEFECT', 'FAB',
       'MODEL_NO', 'RECIPE_NAME', 'RUN_ID', 'SCAN_ENDTIME', 'SCAN_STARTTIME',
       'SHEET_ID', 'STAGE', 'TOOL_ID', 'TOTAL_DEFECT_COUNT', 'TYPE']
        self.rawdata_sql_cols = ['COORD_X', 'COORD_Y', 'DEFECT', 'DEFECT_AREA', 'DEFECT_ID',
       'DEFECT_SIZE_TYPE', 'FAB', 'FRONT_REVERSE', 'IMG_URL', 'RECIPE_NAME',
       'RUN_ID', 'SCAN_ENDTIME', 'SCAN_STARTTIME', 'SHEET_ID', 'SP', 'STAGE',
       'TOOL_ID', 'TOTAL_DEFECT_COUNT']
        
        # ==================================== API SUMMARY 資料設定 ==========================================
        self.group_keys = ["HOURLY", "TOOL_ID", "MODEL_NO", "TYPE"]
        self.calculate_keys = ['hourly_run_glass_count', 'hourly_defect_count','hourly_defect_glass_couunt']
        self.sub_table_keys = self.uni_defect_sizes + ['glass']
        self.group_table_keys = self.group_keys + self.calculate_keys + self.sub_table_keys 
        
        ## 片數唯一值
        self. uni_glass_keys = ['SHEET_ID','SCAN_ENDTIME']
       
        self.PRIMARY_GROUP_COLS = self.group_keys
        # =================================================  UPI/SPOT Default config  =================================================
        self.filter_config = {
            "TOOL_ID": [],
            "MODEL_NO": [],
            "TYPE": [],
        }

         # ================================================= 前端網頁CONFIG =================================================
        self.chart_table_coldict = {
            'TOOL_ID': 'line_id',
            'MODEL_NO': 'model',
            'TYPE': 'side',
            'HOURLY': 'HOURLY',
            'hourly_run_glass_count': 'total gld',
            'hourly_defect_count': 'def count', 
            'glass':'glass' ,
            'glass_defect_count': 'size'
            }
        

        self.table_group_key_dict = {
            'main_group': ["HOURLY", "TOOL_ID", "MODEL_NO", "TYPE", 'hourly_run_glass_count', 'hourly_defect_count'],
                           #'maingroup_glass_count', 'maingroup_defect_count'],
            'uni_col': ['glass', 'glass_defect_count']
            # glass 依照現有邏輯分割後單獨對應 uni_col 中的其他欄位資訊
        }

        self.chart_group_dict = {
            'left': ['line_id','model','maingroup_glass_count', 'defect_code_glass_count'],
            'up':   [ ],
            'down': ["HOURLY"],
            'right':['density'],
        }

        self.uni_glass_row_info_dict = {
            'glass_id': 'glass',
            'glass_defect_count':'glass_defect_count',
            'small_defect_count': 'S',
            'middle_defect_count': 'M',
            'large_defect_count': 'L',
            'over_defect_count':  'O'
        }

        self.defect_group_coldict = {'COORD_X': 'x', 'COORD_Y': 'y',  'IMG_URL':'img'}

        self.filter_item_coldict = {
            'TOOL_ID': 'Line',
            'MODEL_NO': 'Model',
            'TYPE': 'glass_side',
            'DEFECT_SIZE_TYPE': 'defect size'
        }

        self.front_config = {
            'chartKeyDict': self.chart_group_dict,
            'filtetItemKeyDict': self.filter_item_coldict,
            'hourlyTable': self.chart_table_coldict,
            'hourlyTable_key_group': self.table_group_key_dict,
            'uniGlassInfo': self.uni_glass_row_info_dict,
            'uniGlassDefectTable': self.defect_group_coldict,
            'SubTabsFilterDefaultDict': self.filter_config
        }
        
cfg = Config()

連線時間: 2025-11-24 10:46:33.491414(202511)

In [6]:
def _add_hourly_col(df: pd.DataFrame, time_col: str = "SCAN_ENDTIME") -> pd.DataFrame:
    """
    由 time_col 產生 'HOURLY' 欄位，格式為整點時間。
    若 time_col 不存在則原樣回傳。
    """
    if time_col not in df.columns:
        print(f"[WARN] 欄位 {time_col} 不存在，無法產生 HOURLY")
        return df

    df = df.copy()
    dt = pd.to_datetime(df[time_col], errors="coerce")
    # 依需求可選擇用 floor('H') 或字串格式，這裡用 floor:
    #df["HOURLY"] = dt.dt.floor("H")
    df["HOURLY"] = dt.dt.floor("H").dt.strftime("%Y-%m-%d %H")
    return df


def _split_recipe_to_model_type(df: pd.DataFrame, col: str = "RECIPE_NAME") -> pd.DataFrame:
    """
    將 RECIPE_NAME 切割成 MODEL_NO 與 TYPE 兩欄。
    假設格式類似 'MODEL_NO_TYPE'，用第一次 '_' 分割。
    若沒有 '_'，MODEL_NO = 原字串，TYPE = 空字串。
    """
    if col not in df.columns:
        print(f"[WARN] 欄位 {col} 不存在，無法切割 MODEL_NO / TYPE")
        return df

    df = df.copy()
    # 確保是字串
    s = df[col].astype(str)
    parts = s.str.split("-", n=1, expand=True)

    df["MODEL_NO"] = parts[0]
    if parts.shape[1] > 1:
        df["TYPE"] = parts[1]
    else:
        df["TYPE"] = ""

    return df


def get_tables(dbhandler, cfg):
    # 取得 summary、raw
    summary_df = dbhandler.get_table(cfg.summary_table_name)
    print("summary_df 原始筆數:", len(summary_df))

    raw_df = dbhandler.get_table(cfg.raw_table_name)
    print("raw_df 原始筆數:", len(raw_df))

    # ===== 清理 summary：SCAN_ENDTIME → HOURLY =====
    summary_df = _add_hourly_col(summary_df, time_col="SCAN_ENDTIME")
    #print("summary_df 加 HOURLY 後欄位:", summary_df.columns.tolist())

    # ===== 清理 raw：RECIPE_NAME 切 MODEL_NO / TYPE, SCAN_ENDTIME → HOURLY =====
    raw_df = _split_recipe_to_model_type(raw_df, col="RECIPE_NAME")
    raw_df = _add_hourly_col(raw_df, time_col="SCAN_ENDTIME")
    #print("raw_df 加 MODEL_NO / TYPE / HOURLY 後欄位:", raw_df.columns.tolist())

    return summary_df, raw_df

In [61]:
df = dbhandler.get_table('pidenisty_pihour_202511')
df.head()

,pi_hour,aoi,line_id,model,glass_type,recipe_id,ai_code_1,maingroup_glass_count,maingroup_defect_count,defect_code_glass_count,defect_code_count,small_defect_count,middle_defect_count,large_defect_count,over_defect_count,glass,pic_paths,noteText
0,2025-11-03 07:00:00,aoi200,CAPIC500,M270DAN8S,TFT,0286,Not_Found,4,421,4,17,8,9,0,0,"VQ5AANS8C,VQ5AANS8D,VQ5AANS8E,VQ5AANS8F",http://10.97.139.98:1454/CAAOI202/CA007001/JF5...,None
1,2025-11-03 07:00:00,aoi200,CAPIC500,M270DAN8S,TFT,0286,NPI_TFT,4,421,3,5,0,4,1,0,"VQ5AANS8C,VQ5AANS8D,VQ5AANS8E",http://10.97.139.98:1454/CAAOI202/CA007001/JF5...,None
2,2025-11-03 07:00:00,aoi200,CAPIC500,M270DAN8S,TFT,0286,PI_Gel,4,421,2,2,0,2,0,0,"VQ5AANS8C,VQ5AANS8D",http://10.97.139.98:1454/CAAOI202/CA007001/JF5...,None
3,2025-11-03 07:00:00,aoi200,CAPIC500,M270DAN8S,TFT,0286,PI_Spot_NP,4,421,4,358,33,319,6,0,"VQ5AANS8C,VQ5AANS8D,VQ5AANS8E,VQ5AANS8F",http://10.97.139.98:1454/CAAOI202/CA007001/JF5...,None
4,2025-11-03 07:00:00,aoi200,CAPIC500,M270DAN8S,TFT,0286,Polymer,4,421,3,4,0,4,0,0,"VQ5AANS8C,VQ5AANS8E,VQ5AANS8F",http://10.97.139.98:1454/CAAOI202/CA007001/JF5...,None

In [ ]:
group_keys = ["HOURLY", "TOOL_ID", "MODEL_NO", "TYPE"]
group_table_keys = group_keys + ['hourly_run_glass_count', 'hourly_defect_count','hourly_defect_glass_couunt']+ cfg.uni_defect_sizes + ['glass', 'noteText' ]
uni_glass_keys = ['SHEET_ID','SCAN_ENDTIME']
defect_size_col = 'DEFECT_SIZE_TYPE'
uni_defect_sizes = ['S', 'M', 'L', 'O']


summary_df, raw_df = get_tables(dbhandler, cfg)
summary_groups = summary_df.groupby(group_keys)
raw_groups = raw_df.groupby(group_keys)

## 
new_coldict = {'HOURLY': 'pi_hour',
 'TOOL_ID': 'line_id',
 'MODEL_NO': 'model',
 'TYPE': 'glass_type',
 'hourly_run_glass_count': 'maingroup_glass_count',
 'hourly_defect_count': 'maingroup_defect_count',
 'hourly_defect_glass_couunt': 'defect_code_glass_count',
 'S': 'small_defect_count',
 'M': 'middle_defect_count',
 'L': 'large_defect_count',
 'O': 'over_defect_count',
 'glass':'glass',
 'noteText': 'noteText'}

summary_df 原始筆數: 822
raw_df 原始筆數: 699

C:\Users\Ray\AppData\Local\Temp\ipykernel_16552\3239562941.py:14: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df["HOURLY"] = dt.dt.floor("H").dt.strftime("%Y-%m-%d %H")
C:\Users\Ray\AppData\Local\Temp\ipykernel_16552\3239562941.py:14: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df["HOURLY"] = dt.dt.floor("H").dt.strftime("%Y-%m-%d %H")

In [24]:
api_summary_df = pd.DataFrame(columns=group_table_keys)
for main_keys, summary_rows in summary_groups:
    hour, tool_id, model_no, type_ = main_keys
    hourly_run_glass_count = len(summary_rows)

    print(f"[Summary] HOURLT={hour}, TOOL_ID={tool_id}, MODEL_NO={model_no}, TYPE={type_}, rows={len(summary_rows)}")
    
    # 嘗試從 raw_groups 取出對應 group
    size_group_data = {}
    try:
        raw_rows = raw_groups.get_group(main_keys)
        hourly_defect_count = len(raw_rows)
        hourly_defect_glass_couunt = len(raw_rows.groupby(uni_glass_keys))
        print(f"[Raw] defect rows: {len(raw_rows)}, glass_couunt :{hourly_defect_glass_couunt}")
        size_group_data = [len(raw_rows[raw_rows[cfg.defect_size_col] == size]) for size in cfg.uni_defect_sizes]
    except KeyError:
        # 沒有對應 raw 資料時
        raw_rows = raw_df.iloc[0:0].copy()  # 空 df
        hourly_defect_count = hourly_defect_glass_couunt = 0
        size_group_data = [0 for size in cfg.uni_defect_sizes]
        #size_group_data = {cl: len(raw_rows['DEFECT_SIZE_TYPE'].unique()) for cl, size in zip(cfg.table_size_cols, cfg.uni_defect_sizes) }
        print("[Raw]無對應資料 (0 rows)")
    
    glass_str = ",".join(summary_rows['SHEET_ID'].unique())
    api_summary_df.loc[len(api_summary_df)] = [hour, tool_id, model_no, type_, \
        hourly_run_glass_count, hourly_defect_count, hourly_defect_glass_couunt] + size_group_data + [glass_str, '']
api_summary_df = api_summary_df.rename(columns = new_coldict)

[Summary] HOURLT=2025-11-17 07, TOOL_ID=CAPIC107, MODEL_NO=B160UAN04, TYPE=TFT, rows=7
[Raw] defect rows: 4, glass_couunt :4
[Summary] HOURLT=2025-11-17 08, TOOL_ID=CAPIC107, MODEL_NO=B160UAN04, TYPE=CF, rows=34
[Raw] defect rows: 4, glass_couunt :4
[Summary] HOURLT=2025-11-17 08, TOOL_ID=CAPIC107, MODEL_NO=B160UAN04, TYPE=TFT, rows=30
[Raw] defect rows: 8, glass_couunt :6
[Summary] HOURLT=2025-11-17 08, TOOL_ID=CAPIC307, MODEL_NO=B140UAN04, TYPE=TFT, rows=59
[Raw] defect rows: 3, glass_couunt :3
[Summary] HOURLT=2025-11-17 08, TOOL_ID=CAPIC607, MODEL_NO=M270HAN1C, TYPE=CF, rows=21
[Raw] defect rows: 5, glass_couunt :5
[Summary] HOURLT=2025-11-17 08, TOOL_ID=CAPIC607, MODEL_NO=M270HAN1C, TYPE=TFT, rows=43
[Raw] defect rows: 6, glass_couunt :6
[Summary] HOURLT=2025-11-17 09, TOOL_ID=CAPIC107, MODEL_NO=B160UAN04, TYPE=CF, rows=65
[Raw] defect rows: 16, glass_couunt :13
[Summary] HOURLT=2025-11-17 09, TOOL_ID=CAPIC307, MODEL_NO=B140UAN04, TYPE=CF, rows=54
[Raw] defect rows: 22, glass_couunt :13
[Summary] HOURLT=2025-11-17 09, TOOL_ID=CAPIC307, MODEL_NO=B140UAN04, TYPE=TFT, rows=10
[Raw] defect rows: 4, glass_couunt :1
[Summary] HOURLT=2025-11-17 09, TOOL_ID=CAPIC607, MODEL_NO=M270HAN1C, TYPE=CF, rows=44
[Raw] defect rows: 7, glass_couunt :6
[Summary] HOURLT=2025-11-17 09, TOOL_ID=CAPIC607, MODEL_NO=M270HAN1C, TYPE=TFT, rows=27
[Raw]無對應資料 (0 rows)
[Summary] HOURLT=2025-11-17 10, TOOL_ID=CAPIC107, MODEL_NO=B160UAN04, TYPE=CF, rows=15
[Raw] defect rows: 1, glass_couunt :1
[Summary] HOURLT=2025-11-17 10, TOOL_ID=CAPIC307, MODEL_NO=B140UAN04, TYPE=CF, rows=9
[Raw] defect rows: 4, glass_couunt :2
[Summary] HOURLT=2025-11-17 10, TOOL_ID=CAPIC307, MODEL_NO=B140UAN04, TYPE=TFT, rows=19
[Raw] defect rows: 1, glass_couunt :1
[Summary] HOURLT=2025-11-17 10, TOOL_ID=CAPIC607, MODEL_NO=M270HAN1C, TYPE=CF, rows=19
[Raw] defect rows: 9, glass_couunt :4
[Summary] HOURLT=2025-11-17 10, TOOL_ID=CAPIC607, MODEL_NO=M270HAN1C, TYPE=TFT, rows=14
[Raw] defect rows: 7, glass_couunt :5
[Summary] HOURLT=2025-11-17 12, TOOL_ID=CAPIC107, MODEL_NO=B160UAN04, TYPE=CF, rows=23
[Raw] defect rows: 7, glass_couunt :5
[Summary] HOURLT=2025-11-17 12, TOOL_ID=CAPIC107, MODEL_NO=B160UAN04, TYPE=TFT, rows=6
[Raw] defect rows: 1, glass_couunt :1
[Summary] HOURLT=2025-11-17 12, TOOL_ID=CAPIC307, MODEL_NO=B140UAN04, TYPE=CF, rows=14
[Raw] defect rows: 5, glass_couunt :5
[Summary] HOURLT=2025-11-17 12, TOOL_ID=CAPIC307, MODEL_NO=B140UAN04, TYPE=TFT, rows=2
[Raw]無對應資料 (0 rows)
[Summary] HOURLT=2025-11-17 12, TOOL_ID=CAPIC607, MODEL_NO=M270HAN1C, TYPE=CF, rows=12
[Raw] defect rows: 2, glass_couunt :2
[Summary] HOURLT=2025-11-17 12, TOOL_ID=CAPIC607, MODEL_NO=M270HAN1C, TYPE=TFT, rows=3
[Raw]無對應資料 (0 rows)
[Summary] HOURLT=2025-11-17 13, TOOL_ID=CAPIC107, MODEL_NO=B160UAN04, TYPE=CF, rows=36
[Raw] defect rows: 4, glass_couunt :4
[Summary] HOURLT=2025-11-17 13, TOOL_ID=CAPIC307, MODEL_NO=B140UAN04, TYPE=CF, rows=42
[Raw] defect rows: 15, glass_couunt :10
[Summary] HOURLT=2025-11-17 13, TOOL_ID=CAPIC307, MODEL_NO=B140UAN04, TYPE=TFT, rows=6
[Raw] defect rows: 1, glass_couunt :1
[Summary] HOURLT=2025-11-17 13, TOOL_ID=CAPIC507, MODEL_NO=M270DAN7F, TYPE=CF, rows=52
[Raw] defect rows: 495, glass_couunt :51
[Summary] HOURLT=2025-11-17 13, TOOL_ID=CAPIC507, MODEL_NO=M270DAN7F, TYPE=TFT, rows=2
[Raw] defect rows: 1, glass_couunt :1
[Summary] HOURLT=2025-11-17 13, TOOL_ID=CAPIC607, MODEL_NO=M270HAN1C, TYPE=CF, rows=44
[Raw] defect rows: 11, glass_couunt :7
[Summary] HOURLT=2025-11-17 13, TOOL_ID=CAPIC607, MODEL_NO=M270HAN1C, TYPE=TFT, rows=10
[Raw] defect rows: 2, glass_couunt :2
[Summary] HOURLT=2025-11-17 14, TOOL_ID=CAPIC507, MODEL_NO=M270DAN7F, TYPE=TFT, rows=11
[Raw] defect rows: 10, glass_couunt :7

In [25]:
df = dbhandler.get_table('inspection_api_summary_202511')
df

,pi_hour,line_id,model,glass_type,maingroup_glass_count,maingroup_defect_count,defect_code_glass_count,small_defect_count,middle_defect_count,large_defect_count,over_defect_count,glass,noteText
0,2025-11-17 07,CAPIC107,B160UAN04,TFT,7,4,4,4,0,0,0,"YD5ABGX5V,YD5ABGX5W,YD5ABGX5X,YD5ABGX5Y,YD5ABG...",
1,2025-11-17 08,CAPIC107,B160UAN04,CF,34,4,4,4,0,0,0,"AG0UAB0DFD,AG0UAB0DFL,AG0UAB0DF8,AG0UAB0DFH,AG...",
2,2025-11-17 08,CAPIC107,B160UAN04,TFT,30,8,6,5,1,2,0,"YD5ABGX53,YD5ABGX54,YD5ABGX0A,YD5ABGX0B,YD5ABG...",
3,2025-11-17 08,CAPIC307,B140UAN04,TFT,59,3,3,1,1,0,1,"JF5ABJU2Z,JF5ABJU21,JF5ABJU22,JF5ABJU23,JF5ABJ...",
4,2025-11-17 08,CAPIC607,M270HAN1C,CF,21,5,5,2,1,2,0,"AR0HJB06V7,AR0HJB07X8,AR0HJB07V2,AR0HJB07WH,AR...",
...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,2025-11-18 14,CAPIC607,M270HAN03,TFT,31,6,5,4,0,0,2,"625AAXE0A,625AAXE0B,625AAXE0C,625AAXE0D,625AAX...",
199,2025-11-18 15,CAPIC307,B140UAN04,TFT,6,0,0,0,0,0,0,"JF5ABJ95Q,JF5ABJ95R,JF5ABJ95S,JF5ABJ95T,JF5ABJ...",
200,2025-11-18 15,CAPIC507,M270DAN7F,CF,4,18,4,4,4,8,2,"AR0DFB04SX,AR0DFB04ST,AR0DFB04SW,AR0DFB0460",
201,2025-11-18 15,CAPIC507,M270DAN7F,TFT,29,28,21,9,10,5,4,"20251118150007,VA5AAWZ12,VA5AAWZ13,20251118150...",
202,2025-11-18 15,CAPIC607,M270HAN03,TFT,8,0,0,0,0,0,0,"625AAXD6D,625AAXD6E,625AAXD6F,625AAXD6G,625AAX...",

In [17]:
df = dbhandler.get_table('inspection_raw_table_202511')
df = df.drop_duplicates()
print(len(df))
df.head()

30227

,COORD_X,COORD_Y,DEFECT,DEFECT_AREA,DEFECT_ID,DEFECT_SIZE_TYPE,FAB,FRONT_REVERSE,IMG_URL,RECIPE_NAME,RUN_ID,SCAN_ENDTIME,SCAN_STARTTIME,SHEET_ID,SP,STAGE,TOOL_ID,TOTAL_DEFECT_COUNT
0,837.2795,486.413,True,2.0,1.0,S,L6A,1N,,B160UAN04-TFT,-2117333627.0,2025-11-14T15:07:12,2025-11-14T15:06:50,YD5AAVQ1Z,,CELL,CAPIC107,1.0
1,844.904236,300.480316,True,2.0,1.0,S,L6A,1P,,B160UAN04-TFT,-2117333626.0,2025-11-14T15:07:59,2025-11-14T15:07:37,YD5AAVQ11,,CELL,CAPIC107,1.0
2,840.084351,1786.102,True,2.0,1.0,S,L6A,1P,,B160UAN04-TFT,-2117333623.0,2025-11-14T15:10:52,2025-11-14T15:10:30,YD5AAVQ14,,CELL,CAPIC107,2.0
3,838.892,128.396057,True,2.0,2.0,S,L6A,1N,,B160UAN04-TFT,-2117333623.0,2025-11-14T15:10:52,2025-11-14T15:10:30,YD5AAVQ14,,CELL,CAPIC107,2.0
4,1080.82617,1750.23218,True,13.0,1.0,O,L6A,1N,,B140UAN04-CF,-2117333638.0,2025-11-14T15:16:40,2025-11-14T15:16:18,AE1U4B05WW,,CELL,CAPIC307,1.0

In [24]:
for cl in ['COORD_X', 'COORD_Y']:
    df[cl] = df[cl].astype(float)
df[(df['COORD_X']<0) & (df['COORD_Y']<0)]

,COORD_X,COORD_Y,DEFECT,DEFECT_AREA,DEFECT_ID,DEFECT_SIZE_TYPE,FAB,FRONT_REVERSE,IMG_URL,RECIPE_NAME,RUN_ID,SCAN_ENDTIME,SCAN_STARTTIME,SHEET_ID,SP,STAGE,TOOL_ID,TOTAL_DEFECT_COUNT
119,-352.731,-1503.317,True,,5.0,M,L6A,1N,http://10.97.138.17/20251117/20251117131422/5.jpg,M270DAN7F-CF,-2117319364.0,2025-11-17T13:14:46,2025-11-17T13:14:22,20251117131422,N,CELL,CAPIC507,5.0
120,-1347.924,-1282.580,True,,1.0,S,L6A,1N,http://10.97.138.17/20251117/AR0DFB04DJ/1.jpg,M270DAN7F-CF,-2117319363.0,2025-11-17T13:15:32,2025-11-17T13:15:08,AR0DFB04DJ,N,CELL,CAPIC507,1.0
121,-51.242,-1810.625,True,,1.0,S,L6A,1P,http://10.97.138.17/20251117/AR0DFB049J/1.jpg,M270DAN7F-CF,-2117319362.0,2025-11-17T13:16:28,2025-11-17T13:16:05,AR0DFB049J,N,CELL,CAPIC507,12.0
122,-1389.545,-344.356,True,,2.0,L,L6A,1P,http://10.97.138.17/20251117/AR0DFB049J/2.jpg,M270DAN7F-CF,-2117319362.0,2025-11-17T13:16:28,2025-11-17T13:16:05,AR0DFB049J,N,CELL,CAPIC507,12.0
123,-962.796,-292.211,True,,3.0,L,L6A,1P,http://10.97.138.17/20251117/AR0DFB049J/3.jpg,M270DAN7F-CF,-2117319362.0,2025-11-17T13:16:28,2025-11-17T13:16:05,AR0DFB049J,N,CELL,CAPIC507,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30222,-888.034,-406.227,True,,5.0,S,L6A,1P,http://10.97.138.17/20251118/AR0DFB04HJ/5.jpg,M270DAN7F-CF,-2117313624.0,2025-11-18T14:20:04,2025-11-18T14:19:40,AR0DFB04HJ,N,CELL,CAPIC507,10.0
30223,-931.842,-319.639,True,,4.0,L,L6A,1P,http://10.97.138.17/20251118/AR0DFB04HJ/4.jpg,M270DAN7F-CF,-2117313624.0,2025-11-18T14:20:04,2025-11-18T14:19:40,AR0DFB04HJ,N,CELL,CAPIC507,10.0
30224,-956.218,-296.567,True,,3.0,O,L6A,1P,http://10.97.138.17/20251118/AR0DFB04HJ/3.jpg,M270DAN7F-CF,-2117313624.0,2025-11-18T14:20:04,2025-11-18T14:19:40,AR0DFB04HJ,N,CELL,CAPIC507,10.0
30225,-506.805,-793.002,True,,2.0,O,L6A,1N,http://10.97.138.17/20251118/AR0DFB04HJ/2.jpg,M270DAN7F-CF,-2117313624.0,2025-11-18T14:20:04,2025-11-18T14:19:40,AR0DFB04HJ,N,CELL,CAPIC507,10.0
30226,-98.901,-413.889,True,,1.0,L,L6A,1P,http://10.97.138.17/20251118/AR0DFB04HJ/1.jpg,M270DAN7F-CF,-2117313624.0,2025-11-18T14:20:04,2025-11-18T14:19:40,AR0DFB04HJ,N,CELL,CAPIC507,10.0

In [7]:
df = dbhandler.get_table('inspection_summary_table_202511')
print(df.iloc[0,:].to_dict())
print(df['TOOL_ID'].unique())
"""
key_dict={'pi_hour': '2025-11-17 07', 'TOOL_ID': 'CAPIC107', 'MODEL_NO':'B160UAN04', 'RECIPE_NAME': 'B160UAN04-TFT'}
for key, val in key_dict.items():
    if key =='pi_hour':
        df = df[df['SCAN_ENDTIME'].str.contains(val)]
    else:
        df = df[df[key]==val]
print(df)
"""

{'CHIP_COUNT': '32.0', 'CHIP_JUDGE': 'OK', 'CHIP_OK_COUNT': '32.0', 'DEFECT': 'True', 'FAB': 'L6A', 'MODEL_NO': 'B160UAN04', 'RECIPE_NAME': 'B160UAN04-TFT', 'RUN_ID': '-2117320325.0', 'SCAN_ENDTIME': '2025-11-17 07:53:56.000', 'SCAN_STARTTIME': '2025-11-17 07:53:34.000', 'SHEET_ID': 'YD5ABGX5V', 'STAGE': 'CELL', 'TOOL_ID': 'CAPIC107', 'TOTAL_DEFECT_COUNT': '0.0', 'TYPE': 'TFT'}
['CAPIC107' 'CAPIC307' 'CAPIC607' 'CAPIC507' 'CAPIC407' 'CAPIC207']

"\nkey_dict={'pi_hour': '2025-11-17 07', 'TOOL_ID': 'CAPIC107', 'MODEL_NO':'B160UAN04', 'RECIPE_NAME': 'B160UAN04-TFT'}\nfor key, val in key_dict.items():\n    if key =='pi_hour':\n        df = df[df['SCAN_ENDTIME'].str.contains(val)]\n    else:\n        df = df[df[key]==val]\nprint(df)\n"

In [6]:
abs(-1500 + 961.937)-750

-211.937

In [26]:
df = dbhandler.get_table('inspection_raw_table_202511')
key_dict={'pi_hour': '2025-11-17 07', 'TOOL_ID': 'CAPIC107', 'RECIPE_NAME': 'B160UAN04-TFT'}
for key, val in key_dict.items():
    if key =='pi_hour':
        df = df[df['SCAN_ENDTIME'].str.contains(val.replace(" ","T"))]
    else:
        df = df[df[key]==val]
print(df)

       COORD_X     COORD_Y DEFECT DEFECT_AREA DEFECT_ID DEFECT_SIZE_TYPE  FAB  \
12    852.3279  1454.34656   True         2.0       1.0                S  L6A
13    832.0453    936.6382   True         2.0       1.0                S  L6A
17  849.001953     359.048   True         3.0       1.0                S  L6A
18  849.085632  67.8875656   True         2.0       1.0                S  L6A

   FRONT_REVERSE IMG_URL    RECIPE_NAME         RUN_ID         SCAN_ENDTIME  \
12            1P          B160UAN04-TFT  -2117320344.0  2025-11-17T07:52:58
13            1P          B160UAN04-TFT  -2117320356.0  2025-11-17T07:45:39
17            1P          B160UAN04-TFT  -2117320324.0  2025-11-17T07:54:53
18            1N          B160UAN04-TFT  -2117320320.0  2025-11-17T07:58:33

         SCAN_STARTTIME   SHEET_ID SP STAGE   TOOL_ID TOTAL_DEFECT_COUNT
12  2025-11-17T07:52:36  YD5ABGX5U     CELL  CAPIC107                1.0
13  2025-11-17T07:45:17  YD5ABGX5L     CELL  CAPIC107                1.0
17  2025-11-17T07:54:30  YD5ABGX5W     CELL  CAPIC107                1.0
18  2025-11-17T07:58:11  YD5ABGX51     CELL  CAPIC107                1.0